### ISSUE TITLE
Binance buy order lot size (LOT_SIZE) issue in Python

### ISSUE THREAD

**Issue by speggos** [ccxt/ccxt#799] opened 2017-12-09 06:35 UTC
Hello, I'm attempting to make buy orders on binance using amount_to_lots. The amount_to_lots function usually (4/5 times) returns the correct amount and the buy order is placed correctly. However, eventually I will have an invalid quantity returned, causing an invalidOrder error to be raised.

Here is a copy of the terminal output:

```
Buying coins. Buying: LTC with BTC on exchange binance
Cancelling all binance binance orders for LTCBTC
All binance binance orders for LTCBTC cancelled
2.04098903462 //Before amount_to_lots
2.04 //Correctly formatted, buy order placed
Buy order placed at rate 0.00920898 for 2.04 in market LTC/BTC
Cancelling all binance binance orders for LTCBTC
All binance binance orders for LTCBTC cancelled
2.05324293502 //before amount_to_lots
2.049999 //Invalid return value, error raised

Traceback (most recent call last):
...
  File "main.py", line 885, in makeBinanceBuyOrder
    response = globalVariables.binanceCcxt.createLimitBuyOrder(market, quantity, rate)
  File "/Library/Python/2.7/site-packages/ccxt/base/exchange.py", line 937, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/Library/Python/2.7/site-packages/ccxt/binance.py", line 449, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "/Library/Python/2.7/site-packages/ccxt/binance.py", line 592, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Python/2.7/site-packages/ccxt/base/exchange.py", line 269, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Python/2.7/site-packages/ccxt/base/exchange.py", line 325, in fetch
    self.handle_errors(e.code, e.reason, url, method, None, message if message else text)
  File "/Library/Python/2.7/site-packages/ccxt/binance.py", line 587, in handle_errors
    raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) {"code":-1013,"msg":"Filter failure: LOT_SIZE"}
$ 
```

Here is the code:

```
print(quantity)
quantity = globalVariables.binanceCcxt.amount_to_lots(market, quantity)

print(quantity)
response = globalVariables.binanceCcxt.createLimitBuyOrder(market, quantity, rate)
```

Is this a known issue?

**Comment by kroitor** [comment] 2017-12-09 06:42
Hi, @speggos ! Thanks for reporting this issue! We will look into it, the `amount_to_lots()` should've returned a value that would pass the LOT_SIZE filter, need some time to debug it. In general, this may be related to a different known request for arbitrary precision with decimal.Decimal for Python: https://github.com/ccxt/ccxt/issues/522. We will get back to you shortly on this with a fix. In the meantime, you can round the value to `market['lot']` size before submitting it further.

**Comment by kroitor** [comment] 2017-12-09 07:08
Does this test raise an Exception for you?

```Python
import ccxt
import sys
import random
binance = ccxt.binance()
binance.load_markets()

# test 1

value1 = 2.04098903462
value2 = 2.05324293502

for i in range(0,1000):
    result1 = str(binance.amount_to_lots('LTC/BTC', value1))
    result2 = str(binance.amount_to_lots('LTC/BTC', value2))
    print(str(value1) + ' > ' + result1)
    print(str(value2) + ' > ' + result2)
    if result1 != '2.04':
        raise Exception(str(value1) + ' ' + result1)
    if result2 != '2.04':
        raise Exception(str(value2) + ' ' + result2)

# test 2

value1 = 2.04098903462
value2 = 2.05324293502

while value1 < value2:
    value1 += random.random () * 0.00012345671
    result1 = str(binance.amount_to_lots('LTC/BTC', value1))
    print(str(value1) + ' > ' + result1)
    if str(result1) != '2.04':
        raise Exception(str(value1) + ' > ' + result1)

print('no errors')
```

**Comment by speggos** [comment] 2017-12-09 07:11
It does indeed:

$ python stuff.py 
2.04098903462 > 2.04
2.05324293502 > 2.049999
Traceback (most recent call last):
  File "stuff.py", line 20, in <module>
    raise Exception(str(value2) + ' ' + result2)
Exception: 2.05324293502 2.049999


However, this seems to work as a solution:

lot = (1 / globalVariables.binanceCcxt.markets[market]['lot'])
		quantity = math.floor(quantity * lot)/lot

**Comment by kroitor** [comment] 2017-12-09 07:20
I guess, you're on MacOS? Can you tell us your OS and Python versions exactly?

**Comment by kroitor** [comment] 2017-12-09 07:23
Also, what's your version of ccxt?

**Comment by speggos** [comment] 2017-12-10 00:37
ccxt version 1.10.337, Python 2.7.10, max OS X El Captain 10.11.16

**Comment by kroitor** [comment] 2017-12-10 05:34
This is strange, I can't repeat it with Mac OS X High Sierra 10.13.1, Python 2.7.13, ccxt 1.10.337...

**Comment by kroitor** [comment] 2017-12-10 05:38
I'd close this for now if you don't mind, until we have a followup on this. I'd suggest to continue further discussion here: https://github.com/ccxt/ccxt/issues/522 as these two issues are related. We will fix this issue anyway, hopefully soon. In the meantime, let me know if you have any other questions. Thx!

**Closed by kroitor** 2017-12-10 05:38 UTC

**Comment by davzucky** [comment] 2017-12-27 14:35
@kroitor, I got exactly the same problem with Binance. However I'm running on Linux with Python 3.6 using ccxt (1.10.495)
I'm trying to create 4 orders, 3 are passing one is failing with this error. I cannot explain why as this is looking good. It is happening for other pair as well
```
 Dec 27 22:09:42 binance-NAVBTC ExchangeWrapper INFO [MainThread  ] [INFO ]  buy 10.59 of NAV from BTC at 0.0002526057656106141. Order Id : 16749
Dec 27 22:09:43 binance-NAVBTC ExchangeWrapper INFO [MainThread  ] [INFO ]  buy 11.15 of NAV from BTC at 0.0002399754773300834. Order Id : 16750
Dec 27 22:09:43 binance-NAVBTC ExchangeWrapper INFO [MainThread  ] [INFO ]  sell 9.58 of NAV from BTC at 0.0002791958462012051. Order Id : 16751
Dec 27 22:09:44 binance-NAVBTC ExchangeWrapper ERROR [MainThread  ] [ERROR]  CANNOT EXCUTE ORDER sell 9.12 of NAV from BTC at 0.00029315563851126537. binance order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) {"code":-1013,"msg":"Filter failure: LOT_SIZE"} 
```
I'm using as well amount_to_lots as per your information from another request that I opened last month with you [#663](https://github.com/ccxt/ccxt/issues/663) 
Any idea ?

**Comment by kroitor** [comment] 2017-12-27 14:51
> I'm trying to create 4 orders, 3 are passing one is failing with this error. I cannot explain why as this is looking good. It is happening for other pair as well

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#lot_size

If you could show your code to reproduce the problem and **verbose** output, like described here, it would be much easier for us to help you: 

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Set `.verbose = True` on your exchange instance. Then copy a minimal snippet of code to reproduce the problem + the output of it here.

```shell
mbp:python igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
```Python
>>> import ccxt
>>> ccxt.__version__
'1.10.495'
>>> exchange = ccxt.binance()
>>> markets = exchange.load_markets()
>>> exchange.markets['NAV/BTC']['lot']
0.01
```

NAV lot size is 0.01. And your amount should be evenly divisible by lot size. Your amount **looks like** if it is 9.12, which **looks like** evenly divisible by lot size of 0.01, however, from your output it is hard to tell, whether the amount **actually is** 9.12. If you paste more details, we will see that from your verbose output and from your code.

**Comment by allenfrostline** [comment] 2018-01-12 19:16
Confirm that this issue still exists in the most up-to-date version. Also... no idea how it happens. It happens really rarely.

**Comment by kroitor** [comment] 2018-01-12 19:22
@allenfrostline this is [answered here](https://github.com/ccxt/ccxt/issues/663#issuecomment-357278220) (read from the linked comment to the end, please).

**Comment by allenfrostline** [comment] 2018-01-12 19:31
@kroitor Thanks for the reference. That should answer my question. However, actually I've been using `.market(symbol)['limit']['amount']['min']` to control my minimum order size, not `.market(symbol)['limit']['cost']['min']`. Therefore, it seems that using only the minimum amounts is not enough to guarantee a valid order without further checking the minimum costs. Is that right?

**Comment by kroitor** [comment] 2018-01-12 19:39
@allenfrostline that's right, exactly. The full set of Binance's filers is described in their official docs:

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters

- PRICE_FILTER (min / max / precision) – this one is to filter invalid prices
- LOT_SIZE (min, max, precision) – this one is to filter invalid amounts
- MIN_NOTIONAL (min, max) – this one is for filtering invalid costs

The above three filters work simultaneously. See their docs for more details.

**Comment by allenfrostline** [comment] 2018-01-12 19:50
I see. So I guess the true minimum amount should be something like `max(limit['amount']['min'], limit['cost']['min'] / ticker(symbol)['last'])`? Sounds I'm making things more complicated...

**Comment by kroitor** [comment] 2018-01-13 02:35
> So I guess the true minimum amount should be something like max(limit['amount']['min'], limit['cost']['min'] / ticker(symbol)['last'])?

Nope, not really. It is close, but not exact. The correct ruleset is as follows:

- the true minimum amount is: `['limits']['amount']['min']`
- the true minimum price is `['limits']['price']['min']`
- the true minimum cost is `['limits']['cost']['min']`

Your goal is not to guess it with some error by dividing it over the last price. Instead, your goal is to be precise, therefore you have to copy the entire logic of their limits + a dozen of checks into your code if you really want to work effectively with this exchange.
