### ISSUE TITLE
quadrigacx fetchBalance error

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#957] opened 2017-12-25 07:01 UTC
quadrigacx fetchBalance method error

- OS: MacOS
- Programming Language: Node 8.4.0
- CCXT version: 1.10.456
- Exchange: quadrigacx
- Method: fetchBalance

```

await quadrigacx.fetchBalance()


(node:59361) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of undefined
(node:59361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by kroitor** [comment] 2017-12-25 07:10
How do you initialize it? Can you show the full snippet of your code to reproduce the problem, please?

```JavaScript
> let ccxt = require('./ccxt.js')
undefined
> let quadrigacx = new ccxt.quadrigacx ({'uid':'MY_UID', 'apiKey':'MY_API_KEY', 'secret': 'MY_SECRET_KEY'})
undefined
> ;(async () => { console.log (await quadrigacx.fetchBalance ()); }) ()
> { info: 
   { btc_available: '0.00000000',
     btc_reserved: '0.00000000',
     btc_balance: '0.00000000',
     bch_available: '0.00000000',
     bch_reserved: '0.00000000',
     bch_balance: '0.00000000',
     btg_available: '0.00000000',
     btg_reserved: '0.00000000',
     btg_balance: '0.00000000',
     eth_available: '0.00000000',
     eth_reserved: '0.00000000',
     eth_balance: '0.00000000',
     ltc_available: '0.00000000',
     ltc_reserved: '0.00000000',
     ltc_balance: '0.00000000',
     etc_available: '0.00000000',
     etc_reserved: '0.00000000',
     etc_balance: '0.00000000',
     cad_available: '0.00',
     cad_reserved: '0.00',
     cad_balance: '0.00',
     usd_available: '0.00',
     usd_reserved: '0.00',
     usd_balance: '0.00',
     xau_available: '0.000000',
     xau_reserved: '0.000000',
     xau_balance: '0.000000',
     fee: '0.5000',
     fees: 
      { btc_cad: '0.5000',
        btc_usd: '0.5000',
        eth_btc: '0.2000',
        eth_cad: '0.5000',
        ltc_cad: '0.5000',
        bch_cad: '0.5000',
        btg_cad: '0.5000' } },
  BCH: { free: 0, used: 0, total: 0 },
  BTC: { free: 0, used: 0, total: 0 },
  BTG: { free: 0, used: 0, total: 0 },
  CAD: { free: 0, used: 0, total: 0 },
  ETH: { free: 0, used: 0, total: 0 },
  LTC: { free: 0, used: 0, total: 0 },
  USD: { free: 0, used: 0, total: 0 },
  free: { BCH: 0, BTC: 0, BTG: 0, CAD: 0, ETH: 0, LTC: 0, USD: 0 },
  used: { BCH: 0, BTC: 0, BTG: 0, CAD: 0, ETH: 0, LTC: 0, USD: 0 },
  total: { BCH: 0, BTC: 0, BTG: 0, CAD: 0, ETH: 0, LTC: 0, USD: 0 } }
```

**Comment by kroitor** [comment] 2017-12-25 12:48
Let us know if we can help with anything else. I'm closing this for now, if you don't mind.

**Closed by kroitor** 2017-12-25 12:48 UTC
Labels: question

**Comment by ChenLi0830** [comment] 2017-12-25 16:13
Hi there, you solved my problem, thank you! I missed the `uid` param when initiating `quadrigacx`. Is there an easy way to tell what is required when initiating the exchanges?

**Comment by kroitor** [comment] 2017-12-25 16:32
> Is there an easy way to tell what is required when initiating the exchanges?

Yes. There's a `.requiredCredentials` property on each exchange, you can see what is required and what is not. 

But, in fact, there's also the `.checkRequiredCredentials()` function. Those two things are parts of a mechanism that was implemented as a layer of protection against signing with empty credentials or against forgetting to set them properly, so, I don't really understand, how you managed to get around that protection...

That `.checkRequiredCredentials()` function gets called internally and it throws an exception when you forget to set any of required credentials. The commands and the results are shown on the screenshot below:

<img width="908" alt="screen shot 2017-12-25 at 19 20 48" src="https://user-images.githubusercontent.com/1294454/34341472-51076296-e9a9-11e7-922d-ac303dbfd638.png">

As you can see from the above screenshot, it literally throws an exception, if you forget to set the `uid`. But because you did not paste the entire code to reproduce the problem, it's hard to tell, why the above protection layer didn't work for you as designed.

Please, never paste one line of code. And don't paste more than 20. You should paste the minimal snippet that I can copy and launch without wasting too much time to recreate your setup. If you put a snippet of 5-10 lines, a full short program, that demonstrates your problem from the very instantiation, up to the breaking point, and if it can be launched right away – you will get your help and answers 10x faster, believe me. If you do that, most often you will find the problem yourself very quickly and will not need any help. The code snippet should only reproduce the problem and should not have anything unnecessary. However, it should be complete. So, if you want somebody to help you, make it easy for them to help you ;) 

Merry Christmas!

**Comment by ChenLi0830** [comment] 2017-12-25 16:55
Hi @kroitor Thank you for the detailed answer! It turns out the error message I saw came from not handling a caught error properly as shown below. 

```
const handleError = (e, exchange) => {
  console.error(e, exchange.id) <--- trying to access id of this string...
    ...
}

(async () => {
  try {
//    await fetchAll()
    let exchange = 'quadrigacx'
    await fetchBalance(exchange)
  } catch (e) {
    api.handleError(e)
  }
}) ()
```

I wasn't even thinking about this part, that's why I totally missed it and didn't paste it into the snippet. Anyway, I am really glad for your help. Merry Christmas!
