### ISSUE TITLE
 install error under linux os

### ISSUE THREAD

**Issue by jyj545** [ccxt/ccxt#6257] opened 2019-12-12 12:16 UTC
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:mint
- Programming Language version:js
- CCXT version:latest
- Exchange:
- Method:npm install -g ccxt

error below:
npm install -g ccxt
npm WARN tarball tarball data for ccxt@latest (sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for ccxt@latest (sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting ccxt@latest:
npm ERR! Verification failed while extracting ccxt@latest:
npm ERR! sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= integrity checksum failed when using sha1: wanted sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= but got sha512-IiAeK9VNI4mN5pXm3upTn4gNJLDTbHc6q4lr3p1A8DlT7B3jY2rJxsMABnfBq0PS2fT6OrUTqNYpYZ+qPgvppw== sha1-+3wXef7UBmVpxYZ74mHig0k7SpE=. (30126 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jyj/.npm/_logs/2019-12-12T12_11_07_676Z-debug.log

**Comment by kroitor** [comment] 2019-12-12 12:18
What's your version of npm?

**Comment by jyj545** [comment] 2019-12-12 12:18
npm -v
6.12.1

**Comment by kroitor** [comment] 2019-12-12 12:22
@jyj545 try this and let me know if that helps or not: https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0

**Comment by jyj545** [comment] 2019-12-12 12:43
still not work for me.
logs below
--------------------------------------------------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/home/jyj/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/jyj/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ccxt',
1 verbose cli   '--save' ]
2 info using npm@6.13.4
3 info using node@v10.16.0
4 verbose npm-session 3f151e6ea4a1608b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npm.taobao.org/ccxt 986ms
8 silly pacote tag manifest for ccxt@latest fetched in 1063ms
9 timing stage:loadCurrentTree Completed in 1081ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule ccxt@1.20.70 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4ms
18 timing stage:loadIdealTree Completed in 6ms
19 silly currentTree lib
20 silly idealTree lib
20 silly idealTree └── ccxt@1.20.70
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 3ms
23 silly diffTrees action count 1
24 silly diffTrees add ccxt@1.20.70
25 silly decomposeActions action count 8
26 silly decomposeActions fetch ccxt@1.20.70
27 silly decomposeActions extract ccxt@1.20.70
28 silly decomposeActions preinstall ccxt@1.20.70
29 silly decomposeActions build ccxt@1.20.70
30 silly decomposeActions install ccxt@1.20.70
31 silly decomposeActions postinstall ccxt@1.20.70
32 silly decomposeActions finalize ccxt@1.20.70
33 silly decomposeActions refresh-package-json ccxt@1.20.70
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /home/jyj/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /home/jyj/.npm/_locks/staging-3985669dea7156cd.lock for /home/jyj/.nvm/versions/node/v10.16.0/lib/node_modules/.staging
38 silly doParallel extract 1
39 silly extract ccxt@1.20.70
40 silly tarball trying ccxt@latest by hash: sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI=
41 silly tarball no local data for ccxt@latest. Extracting by manifest.
42 warn tarball tarball data for ccxt@latest (sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI=) seems to be corrupted. Trying one more time.
43 warn tarball tarball data for ccxt@latest (sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI=) seems to be corrupted. Trying one more time.
44 timing action:extract Completed in 118782ms
45 verbose unlock done using /home/jyj/.npm/_locks/staging-3985669dea7156cd.lock for /home/jyj/.nvm/versions/node/v10.16.0/lib/node_modules/.staging
46 timing stage:rollbackFailedOptional Completed in 0ms
47 timing stage:runTopLevelLifecycles Completed in 119886ms
48 verbose stack Error: sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= integrity checksum failed when using sha1: wanted sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= but got sha512-9WPB/rS6Fb9k74lSOMV6TdLFISwyqI1SGQ0s6aEGnIxxRXKVLVVAu+913wYRwk+jUcGO2G3KJQ20v/8ydBM+8g== sha1-BQc2lqfuOZymW6we/YQ+ZC5qnDw=. (203865 bytes)
48 verbose stack     at Transform.on (/home/jyj/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
48 verbose stack     at Transform.emit (events.js:203:15)
48 verbose stack     at endReadableNT (_stream_readable.js:1129:12)
48 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
49 verbose cwd /home/jyj/work/hb_jt
50 verbose Linux 4.15.0-72-generic
51 verbose argv "/home/jyj/.nvm/versions/node/v10.16.0/bin/node" "/home/jyj/.nvm/versions/node/v10.16.0/bin/npm" "install" "-g" "ccxt" "--save"
52 verbose node v10.16.0
53 verbose npm  v6.13.4
54 error code EINTEGRITY
55 error Verification failed while extracting ccxt@latest:
55 error Verification failed while extracting ccxt@latest:
55 error sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= integrity checksum failed when using sha1: wanted sha1-uXJ7nog0hFTsTxI9MqZr/SAUKYI= but got sha512-9WPB/rS6Fb9k74lSOMV6TdLFISwyqI1SGQ0s6aEGnIxxRXKVLVVAu+913wYRwk+jUcGO2G3KJQ20v/8ydBM+8g== sha1-BQc2lqfuOZymW6we/YQ+ZC5qnDw=. (203865 bytes)
56 verbose exit [ 1, true ]

**Comment by kroitor** [comment] 2019-12-12 12:46
Does it work for you with a local install?

```shell
mkdir test-local-ccxt-install
cd test-local-ccxt-install
npm init
npm install ccxt
```

?

**Comment by jyj545** [comment] 2019-12-12 12:59
not work.
 system:Linux Mint 19.1 Tessa \n \l
 node -v:v10.16.0
 npm -v:6.13.4

**Comment by kroitor** [comment] 2019-12-12 13:03
@jyj545 unfortunately, i cannot reproduce it with ubuntu... and to be honest, it's hard to tell from the above what would be the reason for this. I suggest that we rule out environment/os/configuration issues, do you have an alternative system (preferably a different breed of linux) to try and test there, for comparison?

**Comment by jyj545** [comment] 2019-12-12 14:48
thanks for your help,it seems to be that my computer operation has somthing wrong with ccxt,ccxt install commands works in windows10 os

**Comment by kroitor** [comment] 2019-12-12 14:58
@jyj545 yep, it appears as an os-specific or a config-specific issue with that particular machine. Can you check the `npmrc` and other configuration settings that might force it to use sha-1 instead of sha-512 in this case? Unfortunately, it's hard to help you in this without having the access to your machine. So, I suggest that you try this: https://github.com/nodejs/node/issues/13635. Closing this for now as this is not really an issue with the CCXT, but an issue with your NPM/Node installation. Feel free to reopen it if needed or just ask further questions if any.

**Closed by kroitor** 2019-12-12 14:58 UTC
Labels: question

**Comment by jyj545** [comment] 2019-12-12 15:05
my npm setting:npm config ls -l
; cli configs
long = true
metrics-registry = "https://registry.npm.taobao.org/"
scope = ""
user-agent = "npm/6.13.4 node/v10.16.0 linux x64"

; userconfig /home/jyj/.npmrc
home = "https://npm.taobao.org"
registry = "https://registry.npm.taobao.org/"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
audit = true
audit-level = "low"
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "/home/jyj/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/home/jyj/.nvm/versions/node/v10.16.0/etc/npmrc"
globalignorefile = "/home/jyj/.nvm/versions/node/v10.16.0/etc/npmignore"
group = 1000
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/home/jyj/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-options = null
node-version = "10.16.0"
noproxy = null
offline = false
onload-script = null
only = null
optional = true
otp = null
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/home/jyj/.nvm/versions/node/v10.16.0"
preid = ""
production = false
progress = true
proxy = null
read-only = false
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "/bin/bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 18
unicode = true
unsafe-perm = true
update-notifier = true
usage = false
user = 1000
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} {ci}" (overridden)
userconfig = "/home/jyj/.npmrc"
version = false
versions = false
viewer = "man"

**Comment by kroitor** [comment] 2019-12-12 15:14
@jyj545 

> registry = "https://registry.npm.taobao.org/"

↑ I'm 99.99% sure that those overrides + your cache – are the actual cause of the issue.

- https://www.ludofischer.com/blog/npm-cache-error/
- https://community.appdynamics.com/t5/Dynamic-Languages-Node-JS-Python/NPM-install-integrity-check-failure-on-Linux/td-p/29166
- https://dnasir.com/2018/02/12/solving-the-package-lock-json-integrity-discrepancy/
- https://www.google.com/search?q=npm+install+ignore+integrity
- https://www.google.com/search?q=npm+install+integrity
- etc...

**Comment by jyj545** [comment] 2019-12-13 02:50
thanks for your help,i changed the npm registry to its original source:  npm -------- https://registry.npmjs.org/,
then my problem resolved.
