### ISSUE TITLE
Binance don't give the "Average price" of order

### ISSUE THREAD

**Issue by vitoo** [ccxt/ccxt#1011] opened 2017-12-30 16:44 UTC
Hi,

When using fetch order, binance don't give us the average (real) price, but only the limit price requested.

So in binance.php the : 'cost' => $price * $amount, is wrong because the $price is not the average price.

Binance don't give us enough info about order

**Comment by kroitor** [comment] 2017-12-30 16:49
Hello! Thanks for reporting! What would you suggest as a solution to this?

**Comment by vitoo** [comment] 2017-12-30 17:00
Well, we should ask binance to add the average price in api response maybe

**Comment by kroitor** [comment] 2017-12-30 17:04
Ok, I've sent them a message. Will report here upon getting a follow up on this. I'm closing this for now if you don't mind. Feel free to reopen it, or ask questions, if any. Thx!

**Closed by kroitor** 2017-12-30 17:04 UTC
Labels: question

**Comment by vitoo** [comment] 2017-12-30 17:11
I've asked them too, too add avg price, total cost, and fees

**Comment by kroitor** [comment] 2017-12-31 17:02
An update on this:

```
Igor Kroitor, [30.12.17 20:03]
Hey! Hope you're doing well! Our users ask if you could add average order price to your order APIs, is that possible? ) Do you have any plans for that?

Ninj0r, [31.12.17 12:47]
In a future version we will return the total quote quanity that's been executed. Dividing this value by the executedQty will give the average price. No ETA on it's release date to production at this time.
```

**Comment by holographix** [comment] 2018-01-11 00:05
Hi @kroitor,
Thx for your stellar job on this amazing lib. 
I'm facing the same issue like @vitoo, so I was wondering if you have any workaround to fetch the price of the symbol at the time of the order, when you bought market?
Because atm if I place a market buy, I don't have any way to know what is the real price to which the symbol has been bought.

**Comment by kroitor** [comment] 2018-01-11 00:08
@holographix hi!

> Because atm if I place a market buy, I don't have any way to know what is the real price to which the symbol has been bought.

You should call `fetchMyTrades()` to find the actual filling price for a market order (it can be filled with multiple trades each having its own price due to price/volume distributions in the order book). You can consider this not a *workaround*, but a *generic way* to fetch your historical prices. I hope it answers your question.

**Comment by vitoo** [comment] 2018-01-11 00:15
As a workaround i use the last price as average price (just after i set my order)

```php
$orderId = $this->exchange->createMarketSellOrder($this->instrument, $this->balance_out)['id'];
$lastPrice = $this->exchange->fetch_ticker($this->instrument)['last'];
$order = $this->exchange->fetchOrder($orderId, $this->instrument);

$subtotal = round($this->balance_out * $lastPrice, 8);
$fees_amount = round($subtotal * $this->fees, 8);
$proceed = $subtotal - $fees_amount;
//i set computed data here :
$order['average'] = $lastPrice;
$order['cost'] = $proceed;
$order['fee'] = ['cost' => $fees_amount];
```

**Comment by holographix** [comment] 2018-01-11 00:18
hey thanks to both of you. I think I'll stick to the fetchMyTrades() solution, since I really need to get the exact price of the transaction, since I gotta make some calculations on top of it, but thank you so much for your superquick reply.

**Comment by kroitor** [comment] 2018-01-11 00:18
@vitoo it's a very risky workaround, you risk getting a foreign order price (not yours).

**Comment by holographix** [comment] 2018-01-11 00:24
I can confirm that this works, and solves my problem. 
Nevertheless it would be way more convenient if Binance could give this data in the callback of the buy method.
Hope they implement it in the near future, until then, this is my way to go!

Thanks again.

**Comment by vitoo** [comment] 2018-01-11 00:25
But if there is many trades for 1 order, you have to filter them with order id so

**Comment by vitoo** [comment] 2018-01-11 12:17
Simple solution to get the average price 
```php
//$order is from fetchOrder()
 public function realPriceOfOrder($order) {
    $trades = $this->exchange->fetchMyTrades($this->instrument);
    $sumUnit=$sumCost=0;
    foreach($trades as $trade){
       if($trade['info']['orderId'] == $order['id']){
         $sumUnit += $trade['amount'];
         $sumCost += $trade['cost'];
       }
    }
    $order['average'] = $sumCost / $sumUnit; 
    $order['cost'] = $sumCost; 
    return $order;
  }
```

**Comment by kroitor** [comment] 2018-01-11 12:18
@vitoo thank you! I'm sure this snippet will be of help to the community!

**Comment by vitoo** [comment] 2018-01-11 22:17
Hi again @kroitor 
Binance doesnt return the volume in fetch_tickers

I used to sort all instrument by volume in one request, look's like its not possible with binance

**Comment by radarxc** [comment] 2018-09-08 23:55
@kroitor, thank you for replying.

Yeah, cost mostly works for me. But I notice cost always equals to
 order limit price multiple volume on binance, so I am looking for the actual average price and find this post. 

In your comment 8 months ago, you mentioned binance replied they will return actual total quote in the future, so I was trying to follow up if binance implement this improvement.

**Comment by kroitor** [comment] 2018-09-09 00:04
> In your comment 8 months ago, you mentioned binance replied they will return actual total quote in the future, so I was trying to follow up if binance implement this improvement.

We've made some progress since then and now the cost returned from the exchange has the precedence. You might also want to check this:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L273
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L623
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L717

;)

**Comment by radarxc** [comment] 2018-09-09 00:13
Thank you so much😁

I will check those.

**Comment by mklosi** [comment] 2020-11-12 18:31
hi all. @kroitor   I'm still a bit confused on what I am actually looking for :)     I see orders now (end of 2020) return "price" and "average". which is the actual price I paid for ?   
In the [order structure docs](https://ccxt.readthedocs.io/en/latest/manual.html#order-structure), I see that "cost" (which I assume is how much quote currency I actually spent on this order) is equal to 'filled' * 'price', which is not what I get in my orders. I get "cost = filled * average". Also I see no "average" in the docs. Docs are possibly outdated?

**Comment by kroitor** [comment] 2020-11-17 14:51
Hi @mklosi ! Do you still have this question after https://github.com/ccxt/ccxt/issues/7979 ? Let me know if you need more clarifications.

**Comment by mklosi** [comment] 2020-11-17 18:05
no, all understood now :) thank you.
