### ISSUE TITLE
Bybit ccxt.pro watch_positions does not work properly, returns error

### ISSUE THREAD

**Issue by IskanderMufteev** [ccxt/ccxt#20527] opened 2023-12-23 16:19 UTC
### Operating System

Wndows 10

### Programming Languages

Python

### CCXT Version

4.1.97

### Description

This example returns error:
"<class 'ccxt.base.errors.BadSymbol'> bybit does not have market symbol I"

All other  WS watch_ function work well with this symbol 'ICP/USDT:USDT'.
In the error message the symbol is truncated to 1 character.

### Code

```
import ccxt.pro
import asyncio
from pprint import pprint

async def observe_positions(exchange, symbol):
    try:
        positions = await exchange.watch_positions(symbol)
        pprint(positions)
    except ccxt.BaseError as e:
        print(type(e), e)
    except Exception as e:
        print(type(e), e)

async def main():
    exchange = ccxt.pro.bybit({
        "apiKey": "p---------",
        "secret": "WS--------",
    })
    
    await observe_positions(exchange, 'ICP/USDT:USDT')

asyncio.run(main())
```

**Comment by Lilneo786** [comment] 2023-12-23 16:27
The error message you're facing, <class 'ccxt.base.errors.BadSymbol'> bybit does not have market symbol I, implies that the symbol 'ICP/USDT:USDT' is not acknowledged by the Bybit exchange. The error message also suggests that the symbol is being shortened to 'I'.

verify the accurate trading symbol format for Bybit. Each exchange may have distinct symbol formats.

Once you have the correct format, modify the observe_positions function call accordingly.

**Comment by IskanderMufteev** [comment] 2023-12-23 16:36
> The error message you're facing, <class 'ccxt.base.errors.BadSymbol'> bybit does not have market symbol I, implies that the symbol 'ICP/USDT:USDT' is not acknowledged by the Bybit exchange. The error message also suggests that the symbol is being shortened to 'I'.
> 
> verify the accurate trading symbol format for Bybit. Each exchange may have distinct symbol formats.
> 
> Once you have the correct format, modify the observe_positions function call accordingly.

In this case, I am sure that the character format is correct for bybit. I've tried others too.

**Comment by Lilneo786** [comment] 2023-12-23 16:40
```
import ccxt.pro
import asyncio
from pprint import pprint

async def observe_positions(exchange, symbol):
    try:
        positions = await exchange.watch_positions(symbol)
        pprint(positions)
    except ccxt.BaseError as e:
        print(type(e), e)
    except Exception as e:
        print(type(e), e)

async def main():
    exchange = ccxt.pro.bybit({
        "apiKey": "p---------",
        "secret": "WS--------",
    })
    
    await observe_positions(exchange, 'ICPUSDT')  # Use 'ICPUSDT' as the symbol

asyncio.run(main())
```


Verify the exact symbol format for position updates in the Bybit

**Comment by IskanderMufteev** [comment] 2023-12-23 17:41
> Verify the exact symbol format for position updates in the Bybit

Firstly, this contradicts the standards for representing symbols in the CCXT library.
And even if you specify it in this format it does not work.

**Comment by Lilneo786** [comment] 2023-12-23 18:56
Youre right my fault

```
async def main():
    exchange = ccxt.pro.bybit({
        "apiKey": "p---------",
        "secret": "WS--------",
    })

    # Load the markets and print their symbols
    await exchange.load_markets()
    print("Available symbols on Bybit:")
    pprint(exchange.symbols)

    # Use the standard symbol format for the desired trading pair
    symbol = 'ICP/USDT'
    await observe_positions(exchange, symbol)

asyncio.run(main())

```

**Comment by IskanderMufteev** [comment] 2023-12-23 20:28
> Youre right my fault
> 
You'd better explore the symbol format in the CCXT. Simple brout force of symbols will not work here :)

**Comment by pcriadoperez** [comment] 2023-12-23 23:38
Hi @IskanderMufteev , the issue is `watch_positions` takes in an array of symbols, that is why it's giving a Bad Symbol error for I. Please try changing your code to `positions = await exchange.watch_positions([ symbol ])`

I'll close this issue for now but feel free to reopen or reach out with any other questions.

**Closed by pcriadoperez** 2023-12-23 23:38 UTC
