### ISSUE TITLE
huobi create_market_buy_order()  error 

### ISSUE THREAD

**Issue by runrun88** [ccxt/ccxt#5197] opened 2019-05-26 12:14 UTC
- OS: window10
- Programming Language version: py
- CCXT version 1.18.562
- Exchange: huobipro
- Method: create_market_buy_order()

the code ::

```Python
         market_price_buy = float(ticker_base['bid'])
        order_result = self.huobi.create_market_buy_order('EOS/BTC', market_buy_size, market_price_buy)
```

I have add the param: price 

But when I use create_market_buy_order()  it  says error:
InvalidOrder(self.id + " market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the

**Comment by runrun88** [comment] 2019-05-26 13:08
How to  use fetch_trade_limt () in  py ?

**Comment by Tezeug** [comment] 2019-05-26 13:53
I think you should have not added the price when you are executing an market order because the price is automated.

**Comment by runrun88** [comment] 2019-05-26 23:17
But  I really  have added the price : market_price_buy.
It still has error.

**Comment by runrun88** [comment] 2019-05-27 02:50
when I use:
 order_result = self.huobi.create_order('EOS/BTC', 'market', 'buy', market_buy_size, market_price_buy) .
It still has error::
ccxt.base.errors.InvalidOrder: huobipro {"status":"error","err-code":"order-marketorder-amount-min-error","err-msg":"market order amount error, min: `0.0001`","data":null}

How can I sovle it ?
Help me!!!

**Comment by Tezeug** [comment] 2019-05-27 05:59
Do not add the price.

**Comment by Tezeug** [comment] 2019-05-27 08:39
When you execute an market order you shall not add the price. It will cause an error because the price variable is calculated automatically. You execute an market order so you do not set the price. The price is being set automatically.

**Comment by kroitor** [comment] 2019-05-27 17:21
> ccxt.base.errors.InvalidOrder: huobipro {"status":"error","err-code":"order-marketorder-amount-min-error","err-msg":"market order amount error, min: 0.0001","data":null}

@runrun88 see the answer here: 

- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits ← pay attention, especially here

Basically the exchange is telling you what's wrong, but the message isn't very clear:

> market order amount error, min: 0.0001

↑ that refers either to the `amount` or to the total `cost` of the order, but it's impossible to tell from the code you've copypasted above. So we need you to follow precisely [these guides](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) and paste your **verbose request** and **verbose response**:

```Python
self.huobi.load_markets()

# ...

market_price_buy = float(ticker_base['bid'])

self.huobi.verbose = True  # ←----------- ADD THIS

order_result = self.huobi.create_market_buy_order('EOS/BTC', market_buy_size, market_price_buy)
```

↑ Paste the output (both the request and the response) here, plz.

**Comment by kroitor** [comment] 2019-05-27 17:24
@Tezeug 

> Do not add the price.

> When you execute an market order you shall not add the price. It will cause an error because the price variable is calculated automatically. You execute an market order so you do not set the price. The price is being set automatically.

It has to be added in this specific case, so your comments are a bit wrong. The `price` is required for a market buy on Huobi, because of how the exchange API works. The price is needed to calculate the total cost of the order. See the explanation here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/huobipro.py#L756

**Comment by Tezeug** [comment] 2019-05-27 21:17
Did not know that, wow. Looks like every exchange is absolutely different in some aspects but in the most cases you do not need to add it :/. Sorry, man.

**Comment by kroitor** [comment] 2019-05-27 21:21
@Tezeug no worries... there are other such cases, CEX, CoinTiger and probably a dozen others. It's common to place a market buy for total cost in quote currency, instead of market buying the amount in base currency.

**Comment by runrun88** [comment] 2019-05-28 02:48
> > ccxt.base.errors.InvalidOrder: huobipro {"status":"error","err-code":"order-marketorder-amount-min-error","err-msg":"market order amount error, min: 0.0001","data":null}
> 
> @runrun88 see the answer here:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#markets
> * https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits ← pay attention, especially here
> 
> And, also check this:
> 
> * https://github.com/ccxt/ccxt/blob/master/python/ccxt/huobipro.py#L756
> 
> Basically the exchange is telling you what's wrong, but the message isn't very clear:
> 
> > market order amount error, min: 0.0001
> 
> ↑ that refers either to the `amount` or to the total `cost = amount * price` of the order. Either the `amount` or `amount * price` is too low (below exchange limits). But it's impossible to tell from the code you've copypasted above.
> 
> So, we need you to follow precisely [these guides](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) and paste your **verbose request** and **verbose response**:
> 
> ```python
> self.huobi.load_markets()
> 
> # ...
> 
> market_price_buy = float(ticker_base['bid'])
> 
> self.huobi.verbose = True  # ←----------- ADD THIS
> 
> order_result = self.huobi.create_market_buy_order('EOS/BTC', market_buy_size, market_price_buy)
> ```
> 
> ↑ Paste the output (both the request and the response) here, plz.

thanks very much.
I got it.

**Comment by runrun88** [comment] 2019-05-28 02:50
> Did not know that, wow. Looks like every exchange is absolutely different in some aspects but in the most cases you do not need to add it :/. Sorry, man.

also  thanks

**Comment by kroitor** [comment] 2019-05-28 02:50
@runrun88 you mean, the issue is now resolved and we can close this? )

**Comment by runrun88** [comment] 2019-05-28 02:50
> @runrun88 you mean, the issue is now resolved and we can close this? )

Yes， yes. thanks

**Closed** 2019-05-28 02:51 UTC
Labels: question

**Comment by amal348** [comment] 2022-02-23 09:59
bitmart createOrder failed due to exchange error: bitmart {"message":"Header X-BM-SIGN is wrong","code":30005,"trace":"cfc3d749-f21e-4fe3-8b70-d5ac129a9b97","data":{}}                                                                                                                                       

when request using bitmart showing this error, where this X-BM-SIGN is given? please help
