### ISSUE TITLE
precisionMode returned int instead of type + precisions implementation

### ISSUE THREAD

**Issue by Eriz11** [ccxt/ccxt#6707] opened 2020-03-30 17:10 UTC
- OS: Linux (Ubuntu 18.04)
- Programming Language version: Python 3.7
- CCXT version: 1.25.41

Hey all, 

I have some questions related to precisions, limits and related things when order sending in different exchanges.

**1)** When calling exchange.precisionMode, I don't get the string related (TICK_SIZE, DECIMAL_DIGITS or SIGNIFICANT DIGITS); instead I get an integer.

Just using the code from the **Manual** in the case of **Binance** or **Okex** (happens with many others).
```
exchange = ccxt.binance ({
    'rateLimit': 10000,  # unified exchange property
    'headers': {
        'YOUR_CUSTOM_HTTP_HEADER': 'YOUR_CUSTOM_VALUE',
    },
    'options': {
        'adjustForTimeDifference': True,  # exchange-specific option
    }
})
print(exchange.precisionMode)

## Result: 2
```

```
exchange = ccxt.okex ({
    'rateLimit': 10000,  # unified exchange property
    'headers': {
        'YOUR_CUSTOM_HTTP_HEADER': 'YOUR_CUSTOM_VALUE',
    },
    'options': {
        'adjustForTimeDifference': True,  # exchange-specific option
    }
})
print(exchange.precisionMode)

## Result: 4
```
Why is this happening? Am I misunderstading what should be returned? As I recall from the **Manual**, the ```exchange.precisionMode``` holds the type of precision that should be returned, not an int.

**2)** This might have been asked before but I don't find to see a clear explanation or clarity about it to confirm my thoughts.

I have noted that some (if not most) of the exchanges have built-in functionality to handle any order quantity and round/truncate/pad or anything that has to be done to success in the sending (how I know that? If I seach for the ```create_order``` method in the exchange modules, I see that inside the method there is some use of the ```amount_to_precision``` utils and others).

I have noted also that checking the limits in terms of the max and min order quantities has to be done instead. So, my question is:

**¿Can I assume that precision limits are handled in each exchange class BUT checks for order quantity limits (and orders) has to be developed in my program?**

Many thanks in advance for the work and help,

**Comment by kroitor** [comment] 2020-03-30 17:21
Hi!

1. 

> Why is this happening?

It is happening by design / expected to behave like that.

> Am I misunderstading what should be returned?

Yes, because the type is actually a constant. It's not a string. You can access it by it's numeric value (an integer in our case) or by a constant literal, for example `ccxt.TICK_SIZE`, `ccxt.DECIMAL_PLACES`. But you cannot access it as a string `'TICK_SIZE'` ← it won't work. 

Those constants are defined in such a way, because that is the native default way of defining constants in each supported language (as opposed to arbitrary user-defined strings):

- https://github.com/ccxt/ccxt/blob/master/js/base/functions/number.js#L21
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/decimal_to_precision.py#L26
- https://github.com/ccxt/ccxt/blob/master/php/base/Exchange.php#L47

> As I recall from the Manual, the exchange.precisionMode holds the type of precision that should be returned, not an int.

That is correct. But, to be precise, we never said that it should be a string in the Manual. No  _"string"_ word there.

> ¿Can I assume that precision limits are handled in each exchange class BUT checks for order quantity limits (and orders) has to be developed in my program?

That is correct. Precision is handled by CCXT in most cases (there may be some exceptions). Limits should be handled in the userland.

Let me know if that does not answer the questions. Feel free to reopen this if needed or just ask if you have more. Closing this for now if you don't mind.

**Closed by kroitor** 2020-03-30 17:21 UTC
Labels: question

**Comment by Eriz11** [comment] 2020-03-30 18:31
Hi Kroitor,

Many thanks for the fast response.

> Yes, because the type is actually a constant. It's not a string. You can access it by it's numeric value (an integer in our case) or by a constant literal, for example ccxt.TICK_SIZE, ccxt.DECIMAL_PLACES. But you cannot access it as a string 'TICK_SIZE' ← it won't work.

Understood. Thanks for clarifying it.

> That is correct. But, to be precise, we never said that it should be a string in the Manual. No "string" word there.

You are correct; it was assumed on my side that it was a string. Checked and understood.

> That is correct. Precision is handled by CCXT in most cases (there may be some exceptions). Limits should be handled in the userland.

One more question here. In the cases in which the exchange needs the order quantity in the quote currency, I guess that it is also handled by CCXT but we need to provide the price (via fetchTickers or just getting the saved price previously). Am I assuming right here? What happens on those exchanges that don't have the `createMarketBuyOrderRequiresPrice` key to check it?

Also, just to give my two cents to new comers, it would be awesome if you could add a note to the Wiki about the idea that precision is handled internally by CCXT (except some cases; it would be perfect also if it could be highlighted which of them don't handle it) to avoid getting trapped in building the back-end for it (yes, new comer trapped during some hours today;)).

Thanks for the work!

**Comment by kroitor** [comment] 2020-03-30 18:49
>  I guess that it is also handled by CCXT but we need to provide the price (via fetchTickers or just getting the saved price previously). Am I assuming right here?

Yes. You either provide the `price`, and then the CCXT can calculate the total quote `cost = amount * price` internally. Or you set `createMarketBuyOrderRequiresPrice = false` and specify the `amount` in quote currency (which is in base for all orders by default).

> What happens on those exchanges that don't have the createMarketBuyOrderRequiresPrice key to check it?

Those exchanges either have the capability `createMarketOrder = false` in their `has` metainfo, or they accept an amount in base currency for market buys.
