### ISSUE TITLE
I got "amount is invalid" error when i try to withdraw

### ISSUE THREAD

**Issue by Nicour** [ccxt/ccxt#6550] opened 2020-03-02 15:36 UTC
- OS: Mac OS Catalina
- Programming Language version: Node.js
- CCXT version: 1.23.1
- Exchange: Bitmex
- Method: withdraw

This is my route:

```
router.post('/withdraw', async (req, res, next) => {
  const {code, address, amount, otpToken, currency } = req.body;

  const exchange = await new ccxt.bitmex();
  exchange.apiKey = "MY - KEY";
  exchange.secret = "MY - SECRET";

  await exchange.withdraw (code, amount, address, tag = undefined, params = {}, otpToken)
  .then((response) => console.log(res))
  .catch(ex => console.log(ex))

});
```

And this is what i am trying to post:

{
    "address": "THE ADRESS",
    "amount": 0.0022,
    "code": "BTC",
    "otpToken": "MY TOKEN"
}

When i execute this route, i get this error:
BadRequest: bitmex {"error":{"message":"amount is invalid","name":"HTTPError"}}

The key and the secret are OK. The otpToken too. I can fetch everything.
I´m new on this, and i can´t figure it out where is the error on my code.

Thank you!!

**Comment by kroitor** [comment] 2020-03-02 19:31
Hi! 

I think BitMEX requires the amount in satoshis (an integer, not a floating point decimal). So, instead of `"amount": 0.0022` it should be `"amount": 220000`.

Let me know if that does not help.

**Comment by kroitor** [comment] 2020-03-02 22:14
Closing this for now, feel free to reopen it or just ask further questions if any. We will be happy if you report back whether the issue is resolved on your side or not.

**Closed by kroitor** 2020-03-02 22:14 UTC
Labels: question

**Comment by Nicour** [comment] 2020-03-03 08:24
Hello.
Thank you very much for your help. 
I've just try with the amount in satoshis an it works.

Thank you again!
