### ISSUE TITLE
fetchdepositaddress js

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#2147] opened 2018-03-06 21:02 UTC
Hello, i have a problem, actually im not 100% sure that its ccxt problem but however
async function candep(stock,id){
    let market = eval(stock)
    let info = await market.fetchDepositAddress(id)
    if(info.info.success == true){
        return 1
    }
    else{
        return 0
    }
}
Thats my code, stock and id are strings.Js says that market.fetch... is not a function BUT i have already used this strategy to work with stocks and everything goes great expect this function. Thanks for help

**Comment by kroitor** [comment] 2018-03-06 21:37
Can you reduce the error case to a minimal but a complete snippet of code that I can copypaste to reproduce your problem?

The lines that you've copied don't really tell me anything.

It's really hard to help you without seeing the code and your verbose output as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue 

Can you, please, provide more info and remove everything that isn't absolutely necessary to reproduce the case? Please follow the steps from the above doc literally. Standing by for more info from you. Thx!

**Comment by artbred** [comment] 2018-03-07 09:26
Sorry, will do it little bit later, i have a problem with ccxt.sleep(), you use it in your code examples but it seems to be not working, can you help with that please

**Comment by kroitor** [comment] 2018-03-07 09:32
@artbred sure, I can, but my answer remains the same: need to see a minimal code snippet to reproduce the problem (now with `sleep`) and verbose output of it... So whatever the problem is, I need at least some info from you.

**Comment by kroitor** [comment] 2018-03-10 03:56
@artbred hey ) Do you have a follow-up on this? I'd close this for now if you don't mind ) Feel free to reopen it if needed or just ask questions if any, we will be happy to help. Thx!

**Closed by kroitor** 2018-03-10 03:56 UTC
Labels: question
