### ISSUE TITLE
Bitget WatchBalance does not return a result. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22014] opened 2024-04-01 20:51 UTC
### Operating System

Windows 10

### CCXT Version

4.2.87

### Description

WatchBalance with params does not return the result

### Code

```
var exchange = new ccxt.pro.Bitget();
exchange.apiKey = "xxx";
exchange.secret = "xxx";
exchange.password = "xxx";

Dictionary<string, object> _balanceParams = new Dictionary<string, object>();
_balanceParams.Add("type", "MARGIN");
_balanceParams.Add("marginMode", "isolated");
var balanceMarginIsolated = await exchange.WatchBalance(_balanceParams);
Console.WriteLine("isolated margin received");
```

```
var exchange = new ccxt.pro.Bitget();
exchange.apiKey = "xxx";
exchange.secret = "xxx";
exchange.password = "xxx";

Dictionary<string, object> _balanceParams = new Dictionary<string, object>();
_balanceParams.Add("type", "MARGIN");
_balanceParams.Add("marginMode", "cross");
var balanceMarginCross= await exchange.WatchBalance(_balanceParams);
Console.WriteLine("cross margin received");
```

**Comment by skuvv** [comment] 2024-04-01 20:58
I see the trace, but the result is not returned:
```
On message: {"event":"subscribe","arg":{"instType":"MARGIN","channel":"account-crossed","coin":"default"}}
On message: {"action":"snapshot","arg":{"instType":"MARGIN","channel":"account-crossed","coin":"default"},"data":[{"uTime":"1712004971030","id":"zzz","coin":"USDT","available":"0.13000000","borrow":"0.00000000","frozen":"0.00000000","interest":"0.00000000","coupon":"0.00000000"}],"ts":1712004971030}
```

**Comment by samgermain** [comment] 2024-04-02 21:48
Duplicate of #21973

**Comment by skuvv** [comment] 2024-04-03 06:34
@samgermain 
This is not a duplicate for #21973
This issue does not finish request at all.

**Comment by skuvv** [comment] 2024-04-03 09:13
I made debug, problem in processing handleMessage for bitget.
**Args**:
{[instType, MARGIN]}
{[channel, account-isolated]}
{[coin, default]}
**topic** is account-isolated
object Methods does not contains **account-isolated** nor **account-crossed**
Request stays unprocessed

**Comment by carlosmiei** [comment] 2024-04-03 15:43
Hello @skuvv thanks, I'm going to take a look

**Closed** 2024-04-03 16:43 UTC

**Comment by skuvv** [comment] 2024-04-04 19:29
Tested on 4.2.89, fixed now. Both margin return the result.
Thanks!
