### ISSUE TITLE
Bibox withdraw apikey error

### ISSUE THREAD

**Issue by rjruigrok** [ccxt/ccxt#3643] opened 2018-08-13 18:47 UTC
Dear @kroitor

I'm having an issue with the api implementation for bibox, see details below:
- OS: Centos 7
- Programming Language version: PHP 7
- CCXT version: master
- Exchange: bibox
- Method: withdraw

```$bibox->withdraw('LTC', 1.0, 'litecoin address', null, array('totp_code' => '123456', 'trade_pwd' => '123456'));```

results always in the following error: 

```{"error":{"code":"3011","msg":"接口不支持apikey请求方式"}}```

And of course I'm using the correct totp_code and trading password parameters. 
All other trading functions (placing orders, cancels, trade history, etc) work fine, so it looks like it has something to do with the signing.

**Comment by kroitor** [comment] 2018-08-13 19:07
@rjruigrok have you checked if your key has a withdraw permission? 

<img width="469" alt="screen shot 2018-08-13 at 22 07 06" src="https://user-images.githubusercontent.com/1294454/44052451-49d3d0a2-9f45-11e8-945c-afabdfb9ff01.png">

**Comment by rjruigrok** [comment] 2018-08-13 20:47
@kroitor Sure.. all 3 checkboxes checked, and all necessary 2fa, trading pwd etc enabled (manual withdrawal via website also works fine)

Tried various things to get the method working, unfortunately without success.

* looks like the addr_remark contains a typo (address_remark in ccxt, but in official api refered as addr_remark). Can't confirm whether this is really the case, or a fault in their docs.
* also checked out whether it is because of missing any required params (like addr_remark), but looks like its not the case.
* thought it might be the order of parameters, but even in the order from the documentation it doesnt work
* tried it with and without surrounding array around the cmds, read something about that on a chinese forum, but the way it currently is seems to be the right way
* Strangest thing: the cancel function (also a POST, private and with arguments) works without issues. 

See a dump below. You see anything strange? 

```
POST https://api.bibox.com/v1/transfer
{
  "cmds": "[{\"cmd\":\"transfer\\/transferOut\",\"body\":{\"totp_code\":\"123456\",\"trade_pwd\":\"123456789\",\"coin_symbol\":\"LTC\",\"amount\":\"3.2\",\"addr\":\"Lh711111111111111...\",\"addr_remark\":\"\"}}]",
  "apikey": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "sign": "aaaaaaaaaaaaaaaaaaa"
}
```

**Comment by kroitor** [comment] 2018-08-13 21:05
Can you try the following?

```PHP
//  try undefined here instead of a defined null ↓ value
$bibox->withdraw('LTC', 1.0, 'litecoin address', null, array('totp_code' => '123456', 'trade_pwd' => '123456'));
// ↓
$bibox->withdraw('LTC', 1.0, 'litecoin address', undefined, array('totp_code' => '123456', 'trade_pwd' => '123456'));
```

**Comment by rjruigrok** [comment] 2018-08-13 21:07
undefined does not exist in php :)

I tried by altering the body array itself, with and without various parts. Also without the tag (which was the default).

**Comment by kroitor** [comment] 2018-08-13 21:07
The thing is that `addr_remark` should not be there as far as I get, so a null value for it should not yield `\"addr_remark\":\"\"` in the request...

**Comment by rjruigrok** [comment] 2018-08-13 21:08
never mind, the addr_remark was added by myself because I called it with an empty string as the param. But even when it's not there (and thus not in body, verified this), problem persists.

**Comment by kroitor** [comment] 2018-08-13 21:17
@rjruigrok one more quick check: do you have sms confimations upon withdrawals enabled?

**Comment by rjruigrok** [comment] 2018-08-13 21:25
@kroitor Nope, but have 2fa via totp enabled. When i do a withdrawal using the website, I have to enter the trading pwd and authenticator totp code, and then able to do succesful withdrawals

![image](https://user-images.githubusercontent.com/3985534/44058848-d06819c0-9f4f-11e8-957a-f4a8092b65bf.png)


I'm going to try your shortest possible snippet now. Brb!

**Comment by kroitor** [comment] 2018-08-13 21:27
I've edited the above script, added a line to the beginning of it, `date_default_timezone_set ('UTC');`, just to rule out irrelevant causes.

**Comment by rjruigrok** [comment] 2018-08-13 21:39
@kroitor see the output below. With the exact snippet, including the date setting. 
Btw, the script fires 3 api calls in total. First getting all market information, then coin info, then the actual withdraw. Below is output of the last call:

```
Request:
Array
(
    [0] => POST
    [1] => https://api.bibox.com/v1/transfer
    [2] => Array
        (
            [0] => Content-Type: application/json
        )

    [3] => {"cmds":"[{\"cmd\":\"transfer\\\/transferOut\",\"body\":{\"trade_pwd\":\"............\",\"coin_symbol\":\"LTC\",\"amount\":1,\"addr\":\".........\",\"totp_code\":\"568231\"}}]","apikey":"............","sign":"..............."}
)

Response:
Array
(
    [0] => POST
    [1] => https://api.bibox.com/v1/transfer
    [2] => 200
    [3] => 
    [4] => Array
        (
            [server] => Array
                (
                    [0] => Tengine
                )

            [date] => Array
                (
                    [0] => Mon, 13 Aug 2018 21:31:06 GMT
                )

            [content-type] => Array
                (
                    [0] => application/json; charset=utf-8
                )

            [content-length] => Array
                (
                    [0] => 67
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [access-control-allow-origin] => Array
                (
                    [0] => undefined
                )

            [access-control-allow-methods] => Array
                (
                    [0] => POST, GET, OPTIONS
                )

            [access-control-allow-headers] => Array
                (
                    [0] => Content-Type, Accept, x-access-token, X-Requested-With
                )

            [access-control-max-age] => Array
                (
                    [0] => 172800
                )

            [x-ca-request-id] => Array
                (
                    [0] => 4C30CB98-D78F-4C2C-9027-7ED70F586691
                )

            [x-powered-by] => Array
                (
                    [0] => Express
                )

            [access-control-allow-credentials] => Array
                (
                    [0] => true
                )

            [etag] => Array
                (
                    [0] => W/"43-ZqeOEf4ZLo+6gjGn1D3me1vXNco"
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

        )

    [5] => {"error":{"code":"3011","msg":"接口不支持apikey请求方式"}}
)
PHP Fatal error:  Uncaught ccxt\ExchangeError: bibox {"error":{"code":"3011","msg":"接口不支持apikey请求方式"}} in /sites/development/subversion-checkout/ccxt/php/bibox.php:699
Stack trace:
#0 /sites/development/subversion-checkout/ccxt/php/Exchange.php(1094): ccxt\bibox->handle_errors('3011', '', 'https://api.bib...', 'POST', Array, '{"error":{"code...')
#1 /sites/development/subversion-checkout/ccxt/php/Exchange.php(939): ccxt\Exchange->fetch('https://api.bib...', 'POST', Array, '{"cmds":"[{\\"cm...')
#2 /sites/development/subversion-checkout/ccxt/php/bibox.php(711): ccxt\Exchange->fetch2('transfer', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\bibox->request('transfer', 'private', 'POST', Array)
#4 /sites/development/subversion-checkout/ccxt/php/Exchange.php(868): call_user_func(Array, 'transfer', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 /sites/development/subversion-checkout/ccxt/php/Exchange.php(1962): call_user_func_array(Object(Closure), Arr in /sites/development/subversion-checkout/ccxt/php/bibox.php on line 699
```

**Comment by kroitor** [comment] 2018-08-13 21:40
Yep, I've managed to reproduce it on my side with the above snippet, will debug this and will get back to you shortly.

**Comment by rjruigrok** [comment] 2018-08-13 21:41
Thanks! If you need any help, possibly it's related to bibox api itself, if you suspect this then we can both try to push their support to fix this.

**Comment by kroitor** [comment] 2018-08-13 21:42
@rjruigrok need to make sure it's not an error in our implementation first, but I definitely will. Thx for your responsiveness as well!

**Comment by kroitor** [comment] 2018-08-13 22:03
@rjruigrok does this work for you, have you tried it btw? https://github.com/MaxPovver/biboxDemo The README there says it will solve the 3011 error issue, but I'm not sure yet (didn't have time to test it on my side yet). Would be great if you could help testing with that package as well. )

**Comment by kroitor** [comment] 2018-08-14 08:03
I'd close this for now as it seems to be answered at this points. Feel free to reopen it if needed or just ask further questions, if any.

**Closed by kroitor** 2018-08-14 08:03 UTC
Labels: question

**Comment by rjruigrok** [comment] 2018-08-14 11:42
Thanks @kroitor for researching this! 

And if I see the method suddenly starts working in the future (our bot will notice this :) I'll give an update here.

**Comment by coding8282** [comment] 2018-08-23 08:48
I spent a lot of time so much... Finally, Bibox does NOT support withdraw.

**Comment by calbertuk** [comment] 2018-10-03 09:05
After checking with Bibox team on telegram, it would appear that their API does support withdrawals.
The only thing they answered for now is below but I will dig further. @kroitor 
```
data = {
     cmds: string,   // json object serialization into string
     apikey: string, // your apikey
     sign: string    // sign cmds with your secret
 };
 url = 'https://api.bibox.com/v1/xxx';
 post(url, data); // post request

string after formatting：
"cmds": "[{\"cmd\":\"api/ticker\",\"body\":{\"pair\":\"BIX_BTC\"}}]"
```

**Comment by rjruigrok** [comment] 2018-11-28 21:07
@kroitor and others: 
Withdrawals via bibox api are fixed! It suddenly started to work since the end of october. 
But be careful, it looks like its still buggy. I did multiple withdrawals after each other (with 30 secs delay between them, due to 2fa) to different addresses, but the withdrawals all ended up in the first address. You're all warned. ;)

**Comment by kroitor** [comment] 2018-11-28 21:08
@rjruigrok thx for the update, we really appreciate the feedback! Will test on our side as well!
