### ISSUE TITLE
BTCex unable to fetch open positions

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17622] opened 2023-04-21 07:30 UTC
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.59

### Description

I am unable to fetch the open positions from this exchange, it returns an empty list. 

### Code

```
  
import ccxt
public = ""
private = ""
            
client = ccxt.btcex({'apiKey': public, 'secret': private})

client.fetch_positions()

```
[]

**Comment by Dan-krm** [comment] 2023-04-21 08:19
The title of this issue says Btcex and your code is using ccxt.huobi, is that a typo? can you change that to ccxt.btcex and let me know if the issue is still there?

**Comment by Tomas-MP** [comment] 2023-04-21 08:24
Hi @Dan-krm that is indeed the case, my mistake. I am currently working on multiple exchanges.

**Comment by Dan-krm** [comment] 2023-04-22 07:05
I'm not sure how to recreate your issue, fetchPositions is working properly for me, what trading pair and market type are you trying to fetchPositions for?
```
python3 examples/py/cli.py btcex fetchPositions

[{'collateral': 5.481503006012024,
  'contractSize': 1.0,
  'contracts': 0.001,
  'datetime': None,
  'entryPrice': 27340.0,
  'id': None,
  'info': {'adlLevel': '1',
           'autoIncreaseMargin': False,
           'available_withdraw_funds': '0.0135',
           'average_price': '27340',
           'currency': 'PERPETUAL',
           'direction': 'buy',
           'floating_profit_loss': '0.0127',
           'initial_margin': '5.468',
           'instrId': '3315',
           'instrument_name': 'BTC-USDT-PERPETUAL',
           'kind': 'perpetual',
           'leverage': '5',
           'liquid_price': '21926.01503759',
           'maintenance_margin': '0.06838175',
           'margin': '5.4688',
           'margin_balance': '5.4815',
           'margin_type': 'isolate',
           'mark_price': '27352.7',
           'order_id': '395591381819154432',
           'pos_id': '1',
           'position_side': 'LONG',
           'realized_profit_loss': '0',
           'risk_level': '0.012475',
           'roe': '0.002322',
           'show_name': 'BTCUSDT',
           'size': '0.001',
           'stopLossAmount': '0',
           'stopLossRecord': '0',
           'takeProfitAmount': '0',
           'takeProfitRecord': '0',
           'traceType': '0',
           'version': '3020'},
  'initialMargin': 5.468,
  'initialMarginPercentage': 0.19990713896617152,
  'lastPrice': None,
  'lastUpdateTimestamp': None,
  'leverage': 5.0,
  'liquidationPrice': 21926.01503759,
  'maintenanceMargin': 0.06838175,
  'maintenanceMarginPercentage': 0.0025,
  'marginRatio': 0.012475,
  'marginType': 'isolate',
  'markPrice': 27352.7,
  'notional': 27.3527,
  'percentage': None,
  'side': 'long',
  'symbol': 'BTC/USDT:USDT',
  'timestamp': None,
  'unrealizedPnl': 0.0127}]
```

**Comment by Tomas-MP** [comment] 2023-04-22 08:02
Might it be that since I am using client.options['defaultType'] = 'swap', it does not return anything properly?

**Comment by Tomas-MP** [comment] 2023-04-22 08:09
@Dan-krm as the client.fetch_balance() endpoint does not give uPnL, I am trying to fetch my uPnL by fetching all open positions and then adding up the uPnL, which unfortunately does not work.

**Comment by Dan-krm** [comment] 2023-04-22 18:13
Thanks for investigating further and letting us know, closing this issue now

**Closed by Dan-krm** 2023-04-22 18:13 UTC
