### ISSUE TITLE
NetworkError fetch failed

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17253] opened 2023-03-18 22:07 UTC
### Operating System

Ubuntu

### Programming Languages

JS

### CCXT Version

3.0.20

### Description

This exception doesn't get handled properly :

NetworkError: binance GET https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT fetch failed
    at binance.fetch (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:18402:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:20144:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:36737:26)
    at async binance.fetchTicker (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:32051:26)
    at async _0x264545 (/var/opt/balance-botv2/bb/bot.js:1:12815)

### Code

```
await exchange.fetchTicker(symbol); 

```

**Comment by carlosmiei** [comment] 2023-03-18 23:47
Hello @hodlerhacks,
Can you elaborate a bit more? What "doesn't get handled properly" means here?

**Comment by hodlerhacks** [comment] 2023-03-19 00:09
It seems similar to this one: https://github.com/ccxt/ccxt/issues/17241#event-8783319737. I would expect such exception to be mapped to one of the documented network exceptions. I'm handling those documented exceptions in my code, but since v3.x unhandled exceptions are slipping through, causing problems on my side. Of course, I can try to catch those myself, but don't know what exceptions to expect from the various exchanges.

Hope this makes sense.

**Comment by carlosmiei** [comment] 2023-03-19 22:22
> 

@hodlerhacks I will take a look.

**Comment by hodlerhacks** [comment] 2023-03-20 07:03
Thanks @carlosmiei!

**Comment by carlosmiei** [comment] 2023-03-20 09:56
Hum @hodlerhacks I can't reproduce this issue, can you update to the latest version pls?

**Comment by hodlerhacks** [comment] 2023-03-20 10:04
I'm seeing this issue on a regular basis with v3.0.20, but I'll update to the latest and see if it still appears.

**Comment by hodlerhacks** [comment] 2023-03-20 21:11
Just got the exception again, twice in two different processes:

2023/03/20 22:07:10: Bot 001 > [DEBUG] Uncaught NetworkError:
NetworkError: binance GET https://api.binance.com/api/v3/account?timestamp=1679346430317&recvWindow=10000&signature=523c9b2172bc0ddf3b83c3e3ccdb856be65760a3efd5bd010112bf3e96ea447e fetch failed
    at binance.fetch (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:715:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2457:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:7522:26)
    at async binance.fetchBalance (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:2365:26)
    at async getCoins (/var/opt/balance-botv2/bb/bot.js:1:45960)
    at async watchTransactions (/var/opt/balance-botv2/bb/bot.js:1:13493)
2023/03/20 22:07:10: Bot 001 > Binance connection problem | Pausing for 5 minutes
2023/03/20 22:07:21: Bot 002 > [DEBUG] Uncaught NetworkError:
NetworkError: binance GET https://api.binance.com/api/v3/ticker/24hr?symbol=BTCEUR fetch failed
    at binance.fetch (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:715:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2457:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:7522:26)
    at async binance.fetchTicker (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:2828:26)
    at async _0x26edcc (/var/opt/balance-botv2/bb/bot.js:1:12575)
2023/03/20 22:07:21: Bot 002 > Binance connection problem | Pausing for 5 minutes

This is with v3.0.23.

**Comment by hodlerhacks** [comment] 2023-03-21 12:29
Just to give you an idea of how often this occurs, see the timestamps below. I didn't have so many Network Errors in the past. I'm wondering if this is related to Binance, or could there be another cause?

bbv2_bot, [2023-03-21 02:16]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 04:00]
Bot 002 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 04:00]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 04:24]
Bot 002 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 04:24]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 05:05]
Bot 002 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 05:05]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 05:36]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 06:42]
Bot 001 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 12:51]
Bot 002 > Binance connection problem | Pausing for 5 minutes
bbv2_bot, [2023-03-21 13:21]
Bot 002 > Binance connection problem | Pausing for 5 minutes

**Comment by carlosmiei** [comment] 2023-03-21 12:44
@hodlerhacks

> I'm wondering if this is related to Binance

I'm not sure yet

But my main question is, are you able to catch those using the `ccxt.NetworkError` exception?

**Comment by hodlerhacks** [comment] 2023-03-21 14:01
Perhaps my understanding is incorrect. Yes, I can catch these using NetworkError. But I thought all these exceptions would be mapped to underlying, more precise issues, like so:

+---+ NetworkError (recoverable)
    |
    +---+ InvalidNonce
    |
    +---+ RequestTimeout
    |
    +---+ ExchangeNotAvailable
    |   |
    |   +---+ OnMaintenance
    |
    +---+ DDoSProtection
        |
        +---+ RateLimitExceeded

So I was catching the lower-level exceptions. From your question I get that it is intentional that some exceptions don't go beyond just NetworkError. Correct?

**Comment by carlosmiei** [comment] 2023-03-21 14:10
@hodlerhacks Yes our exceptions follow a hierarchy (you can check it here: https://github.com/ccxt/ccxt/blob/master/ts/src/base/errorHierarchy.ts) And yes, `InvalidNonce/RequestTimeout/etc` are more specific than `NetworkError,` and we try to throw them when we are sure about the error being thrown but yes if the exception is raised by `node-fetch` we might not able to be as specific as we wanted to.

**Comment by hodlerhacks** [comment] 2023-03-21 14:13
Ok, clear. So I'm catching them now on the top level. Still, I never saw those Fetch Failed exceptions before. And now that I'm getting so many, it would still be good to know what the root cause is.

**Comment by carlosmiei** [comment] 2023-03-21 14:14
> Ok, clear. So I'm catching them now on the top level. Still, I never saw those Fetch Failed exceptions before. And now that I'm getting so many, it would still be good to know what the root cause is.

@hodlerhacks Do you get them on every method call?

**Comment by frosty00** [comment] 2023-03-22 08:53
@hodlerhacks which version are you using, you shouldn't be able to catch fetch errors at the top level anymore since #cd8e8af9fbaabdcca649ae22c9d6d33f05951b20

**Comment by frosty00** [comment] 2023-03-22 08:55
actually it looks like you are just getting a network error from your stack trace, you should handle those: https://docs.ccxt.com/#/README?id=error-handling

**Comment by hodlerhacks** [comment] 2023-03-22 08:59
Indeed, I'm doing that now. The thing is, those fetch errors seem new, never had those in the past two years, and I'm getting them frequently.

**Comment by hodlerhacks** [comment] 2023-03-25 08:52
Update: using the example from the documentation

`if (e instanceof ccxt.NetworkError) {`

I'm getting the following error:

TypeError: Right-hand side of 'instanceof' is not an object

**Comment by xd94533844** [comment] 2023-03-28 06:46
Big guys are amazing

**Comment by carlosmiei** [comment] 2023-03-28 08:04
> Update: using the example from the documentation
> 
> `if (e instanceof ccxt.NetworkError) {`
> 
> I'm getting the following error:
> 
> TypeError: Right-hand side of 'instanceof' is not an object

Hello @hodlerhacks, that is related to the way you're importing `ccxt`. Are you using cjs or esm?

**Comment by hodlerhacks** [comment] 2023-03-28 08:15
I'm using cjs.

**Comment by carlosmiei** [comment] 2023-03-28 08:20
> I'm using cjs.

@hodlerhacks It should work then, can you try to update to the latest version?

**Comment by hodlerhacks** [comment] 2023-03-28 12:10
Will do. I'm currently on 3.0.34 in production, and haven't seen any network errors over the past days. So things seem pretty stable. Will report back here when I have further insights.

**Comment by hodlerhacks** [comment] 2023-03-31 11:54
I've been waiting several days for this 'fetch failed' error to appear. Nothing so far. Have you changed anything on your end to avoid this from happening? Or could it have been a temporary issue on the Binance side?

In any case, to test if this now works properly:

`if (e instanceof ccxt.NetworkError) {`

I just threw an error in  my code, but I got the same error as before:

TypeError: Right-hand side of 'instanceof' is not an object

So this problem had not been resolved, even with the latest v3.0.46.

**Comment by frosty00** [comment] 2023-03-31 15:05
@hodlerhacks can you download the latest ccxt.bundle.cjs, you should be able to use instanceof to check errors in javascript

**Comment by frosty00** [comment] 2023-03-31 15:05
```
> e = new ccxt.NetworkError()
> e instanceof ccxt.NetworkError

true
```

using the latest cjs bundle

**Comment by hodlerhacks** [comment] 2023-03-31 15:17
That's interesting. I checked node_modules, and under ccxt/dist, I don't see ccxt.bundle.cjs at all. I only see ccxt.cjs. And in ccxt/dist/cjs I have ccxt.js. Am I doing something wrong?

I'm importing ccxt using npm. That should pull in everything I need, right?

**Comment by carlosmiei** [comment] 2023-03-31 15:47
> That's interesting. I checked node_modules, and under ccxt/dist, I don't see ccxt.bundle.cjs at all. I only see ccxt.cjs. And in ccxt/dist/cjs I have ccxt.js. Am I doing something wrong?
> 
> I'm importing ccxt using npm. That should pull in everything I need, right?

@hodlerhacks No you're not doing anything wrong, right after the TS merge, we were shipping a cjs bundle to nom users, but now we ship the code following the same structure 1:1 with the usual folders and file so it's a bit more readable when an error happens and/or you want to add a custom change.

**Comment by hodlerhacks** [comment] 2023-03-31 16:20
Ok, so since `e instance of cctt.NetworkError` is still causing issues, does this make sense (at least as a short-term fix):

I assume that I can just do instead:

if (e.toString().includes('NetworkError'))

Will this catch all NetworkErrors? And the same for ExchangeErrors?

**Comment by frosty00** [comment] 2023-03-31 18:18
`e instanceof ccxt.NetworkError` that should work, can you post a sample of your code?

**Comment by hodlerhacks** [comment] 2023-03-31 19:08
I think I found the problem. I'm doing this:

const ccxt = require('ccxt').pro;

If I remove `.pro`, then `e instanceof ccxt.NetworkError` works. But I'm using the websocket APIs, so I need the pro version.

**Comment by hodlerhacks** [comment] 2023-03-31 19:24
I found the problem. I was doing this:

const ccxt = require('ccxt').pro

Removed the `.pro` and and adjusted the relevant parts of my code accordingly. Now it's working. My mistake, apologies for that. Case closed.

**Comment by carlosmiei** [comment] 2023-04-01 08:55
@hodlerhacks Good to know, I will close this issue then, feel free to re open it if anything 🙂

**Closed by carlosmiei** 2023-04-01 08:55 UTC
