### ISSUE TITLE
[gemini] - Move away from parsing html pages

### ISSUE THREAD

**Issue by drothroc** [ccxt/ccxt#7875] opened 2020-10-28 16:07 UTC
Gemini has created the API to provide the minimums and other information, therefore parsing of the HTML page will be no more!

The API documentation is currently being created, however, below is the format and response.

Public API Example:

Format
https://api.gemini.com/v1/symbols/details/:symbol - where :symbol is any of the supported symbols

e.g.
https://api.gemini.com/v1/symbols/details/BTCUSD
response:
```
{
  "symbol": "BTCUSD",
  "base_currency": "BTC",
  "quote_currency": "USD",
  "tick_size": 2,
  "quote_increment": 8,
  "min_order_size": "0.00001",
  "status": "open"
}
```

**Comment by kroitor** [comment] 2020-10-28 16:15
The problem is – it's insane to fetch each symbol one by one, that's too many requests...

**Comment by kroitor** [comment] 2020-10-28 16:16
It would be great if they could add https://api.gemini.com/v1/symbols/details, but that one doesn't work.

**Comment by drothroc** [comment] 2020-10-28 16:18
This is very true, I will try to push for that as well.

**Comment by kroitor** [comment] 2020-10-28 16:21
@drothroc let me know if anything, in the meantime, the [parser bug](#7874) is fixed in 1.36.95+

**Comment by drothroc** [comment] 2020-10-28 16:50
Looks like they are not planning to do a list API, the goal would be to call the specific ones and update systems when new assets are added. Maybe we can configure fetch_markets, to exclude this information for this exchange and just have it as a separate call, as the information should very seldom change, particularly only when new assets are added.

**Comment by kroitor** [comment] 2020-10-28 16:52
@drothroc without that info it's impossible to properly format amounts and prices in `createOrder`, which is a showstopper... They are not really in line with the majority of the exchanges. I think we'd proceed with the parsed html for now since it does the job, what do you say?

**Comment by drothroc** [comment] 2020-10-28 16:58
@kroitor Yea, I'm for leaving it as is, using the parser, and will continue to drive for the list API. Can probably close this issue until we can get it.

**Comment by kroitor** [comment] 2020-10-28 16:58
@drothroc thx for your feedback, appreciate it!

**Closed by kroitor** 2020-10-28 16:58 UTC
Labels: enhancement
