### ISSUE TITLE
[Huobi] 403 Forbidden 

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#11873] opened 2022-02-07 15:16 UTC
Hi fellows,
since today I can't get huobi endpoints, maybe they changed something.

- CCXT version: ccxt@1.72.37

Here is a sample request, that I am able to execute successfully in chrome. I suppose there is some header problem.
```
fetch Request:
 huobi GET https://api.huobi.pro/v2/reference/currencies 
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'
} 
RequestBody:
 undefined 

handleRestResponse:
 huobi GET https://api.huobi.pro/v2/reference/currencies 403 Forbidden 
ResponseHeaders:
 {
  'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
  'Cf-Chl-Bypass': '1',
  'Cf-Ray': '6d9d78e85aea410d-PRG',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Type': 'text/html; charset=UTF-8',
  Date: 'Mon, 07 Feb 2022 14:57:43 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
  'Permissions-Policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'SAMEORIGIN'
} 
ResponseBody:
 <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Attention Required! | Cloudflare</title>

<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
...
```
Could you please check from your side?
Thanks

**Comment by kroitor** [comment] 2022-02-07 16:26
This issue is confirmed on Huobi side, it's not with your code nor with CCXT's code. We can't really do much about it, the Huobi team is working to resolve it as soon as possible.

**Comment by kroitor** [comment] 2022-02-07 16:28
@krychla1 if it's not a secret, you can paste your Huobi UID here, we will forward it to Huobi and it will be unblocked asap.

**Comment by wxy122221** [comment] 2022-02-07 16:49
I have the same issue.
Maybe it's not one UID's problem, because I have tried many Huobi's accounts, the issue is the same.

**Comment by krychla1** [comment] 2022-02-07 17:25
> @krychla1 if it's not a secret, you can paste your Huobi UID here, we will forward it to Huobi and it will be unblocked with cloudflare asap.

Have you reproduced this issue? I've got it on every endpoint I tried, most of them do not contain UUID, so unblocking it will have no effect.

**Comment by kroitor** [comment] 2022-02-08 06:05
>  I've got it on every endpoint I tried, most of them do not contain UUID, so unblocking it will have no effect.

It was caused by the Cloudflare blocking specific users, they needed the user ids (from the website in the account section) to whitelist those users and fix the issue for at least some people faster. At this point it is not relevant anymore, cause they have fixed the issue on the exchange side. Closing it if you don't mind.

**Closed by kroitor** 2022-02-08 06:05 UTC

**Comment by krychla1** [comment] 2022-02-08 08:28
I confirm, they fixed it. Thanks for your support

**Comment by wanderer120** [comment] 2022-02-08 14:18
Hi all, i'm having the same issue still on my heroku, got the same error when i fetchOHLCV to get the candles without login in to Huobi (It was working previously for a week+). Do they have any API call limit? As my app will call fetchOHLCV every 5 minutes to get the latest candles.

**Comment by kroitor** [comment] 2022-02-08 14:20
@wanderer120 one call to fetchOHLCV in 5 minutes – is way below their limits, so it's not a rate limiting question. I would suggest reaching out to their tech support – it's been resolved for most of the users already.

**Comment by wanderer120** [comment] 2022-02-17 12:20
Yup, issue have been resolved. Thanks all.

**Comment by chxmberland** [comment] 2023-06-30 14:36
Hello, I've been making a request to the following endpoint to get all of the available symbol pairs supported by the exchange: https://api.huobi.com/v1/common/symbols. 

This request works on my local machine (M1 MacBook) from the terminal and in the browser as well. However, in production, I get a 403 error. I am using an Azure Container App located in Canada central. However, I've tried deploying to several locations with the same result. Does anyone have any ideas why this may be happening?
