### ISSUE TITLE
Binance YOYO fetchOpenOrders fail

### ISSUE THREAD

**Issue by 86chenjie** [ccxt/ccxt#479] opened 2017-11-07 02:17 UTC
``` javascript
const exchange = 'binance'
const base = 'YOYO'
const quote = 'BTC'
const symbol = `${base}/${quote}`;

(async () => {
  var ex = util.getExchange(exchange, {verbose: true})
  // const openOrders = await ex.fetchOpenOrders(symbol, { status: 'open' })
  const openOrders = await ex.fetchOpenOrders(symbol)
})()
```

```
(node:725) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: binance does not have market symbol YOYO/BTC
(node:725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment] 2017-11-07 09:35
We will have to add the fetchMarkets () from Binance web API, otherwise it will be increasingly difficult to maintain their market list (if we keep it hardcoded). I'll fix this very soon and will let you know.

**Closed** 2017-11-07 18:10 UTC

**Comment by 86chenjie** [comment] 2017-11-08 02:29
@kroitor  i still got error
```
[root@izj6ca6225p45ds02ug6lpz current]# ./node_modules/.bin/babel-node test.js
binance GET https://www.binance.com/api/v1/openOrders?timestamp=1510108005296&signature=cc5a8ef445f6417ba3e00ac591a33127220647b28c6e2882dff976d4d3c2198c 
Request:
 { 'X-MBX-APIKEY': 'WeslFVVCyquP6Jr73zYbGnd0ZX56itpwto5IBADcfR7k5pSjVvGDykr2xiVmHJkK' } undefined
binance GET https://www.binance.com/api/v1/openOrders?timestamp=1510108005296&signature=cc5a8ef445f6417ba3e00ac591a33127220647b28c6e2882dff976d4d3c2198c 
Response:
{"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
(node:11582) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: binance GET https://www.binance.com/api/v1/openOrders?timestamp=1510108005296&signature=cc5a8ef445f6417ba3e00ac591a33127220647b28c6e2882dff976d4d3c2198c 400 Bad Request {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
(node:11582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment] 2017-11-08 07:59
@86chenjie looking into it to see the cause...

**Comment by kroitor** [comment] 2017-11-08 08:23
@86chenjie ok, found the problem, forgot to preload markets automatically, as now they are not hardcoded, so, this is fixed as of version 1.10.19, thx for your involvement!

**Comment by 86chenjie** [comment] 2017-11-08 09:28
works. 👍

**Comment by kroitor** [comment] 2017-11-08 09:28
@86chenjie thanks for your feedback!

**Comment by kroitor** [comment] 2017-11-08 09:28
@86chenjie you might also want to look at this: https://github.com/ccxt/ccxt/issues/485

**Comment by 86chenjie** [comment] 2017-11-08 09:54
@kroitor  just curious, what's the status of the websocket support?  Websocket is much better to get market data and order status notification.

**Comment by kroitor** [comment] 2017-11-08 09:58
@86chenjie we have WS for ok*, bitfinex, bittrex, poloniex, gdax and several other exchanges implemented, and we are working on it intensively now, hope to deliver the first version of ccxt supporting WS this month... 

Ref: https://github.com/ccxt/ccxt/issues/56#issuecomment-342715498

**Comment by 86chenjie** [comment] 2017-11-08 09:59
@kroitor  good to hear that! 👍
