### ISSUE TITLE
fetch_open_order method not implemented yet in some exchanges

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#935] opened 2017-12-22 11:53 UTC
Hey, @kroitor,

In order to manage my open orders, I tried to call the fetch_open_orders method in some exchanges I work, but in the most, this method was not implemented yet. I suppose you will implement it in each one of it, as a task in your Unified API. So, I would like to know when you plan to implement to Bitfinex, Mercado Bitcoin, BitBay and QuadrigaCX. Please, I know you have many requests to handle from your ccxt users, but if you could to spend some time with my request, I would be more thankful than I already am, because without it, it becomes hard managing open orders.

- OS: Windows 10
- Language: English
- CCXT version: 1.10.437
- Exchange: Bitfinex, Mercado Bitcoin, Bitbay, QuadrigaCX
- Method: fetch_open_orders

Thank you again!!

**Comment by kroitor** [comment] 2017-12-22 12:45
Hi! Did you consider contributing those implementations to ccxt? If you [follow this](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code) literally you could do them all in one day, and, having some practice, you could do them all in one hour. I guess, this would be much more effective, than waiting for me to do it ) What do you think about it?

**Comment by Felipe-Mangueira** [comment] 2017-12-22 13:10
Agreed, it would be much more effective and I thinked about, but I suppose I'll take much more than one day to implement it, considering my programming skills. Anyway, I'll read the "How To Contribute Code" topic and see if I can do it by myself. Thanks!!

**Comment by snowboardinsteve** [comment] 2017-12-23 09:35
Duplicate of #71 I think

**Comment by kroitor** [comment] 2017-12-23 18:15
@snowboardinsteve 

I agree, Id suggest to move this discussion to #71.

@Felipe-Mangueira will let you know there, when this is available (hopefully, very soon).

**Closed by kroitor** 2017-12-23 18:15 UTC
Labels: question

**Comment by Felipe-Mangueira** [comment] 2017-12-23 20:18
Ok, thanks!
