### ISSUE TITLE
Correct way to re-load markets ?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9514] opened 2021-07-05 20:56 UTC
I have observed that when pair has been added recently somewhere, the "create_order" function returns "bad symbol" , because depending `load_markets()` it thinks that the pair is not on exchange, and the order doesn't even reach to exchange, instead within CCXT the exception is returned, saying  "BadSymbol..".  I tried even to use `true` flag: `load_markets(true)` but neither that help. the orders doesn't reach to exchange, instead "BadSymbol" returns.
What is best way to avoid that?
I see that "create_order" function dont just fires order, but in logic it calculates/refers many things from "loaded market"  and then making api-call in last place. So, how we can force to reload markets freshly ?

**Comment by ttodua** [comment] 2021-07-06 14:05
Kroitor, I very much respect you and appreciate all of these, but today we still lost quite a bit much amount due to this bug.
You might remember (a month ago or so) I've mailed (with my name) to ccxt support where I described the issue/consequences of this.
Today the same happened. The newly added symbols seems not be loading and when firing order, it cant fire order, even though on exchange the Pair is being traded. I assume that the issue came from load-markets function (but not sure), however, before you fixed the issue, i've "implemented" (i thought so) my custom function where I manually added the pair name (like "BTC/USDT") , and then I achieved that CCXT passed the internal checkings and orders were being sent to exchange the the actual response from exchange returned. However, today (this happened on second exchange) I have tried again my "dumb fix" and while thinking the trade would have gone ok, shortly later (while watching in live chart on exchange UI) that trade didnt go through, i've checked and found that, even though the trade-order (from "createOrder" function) was sent to exchange for that newly-added PAIR, the prices were miscalculated and exchange executed quite different price. To break down in parts, the "createOrder" function gets the current pair's market-object (from cached/aggegarted object "this.markets", where I had manually added the new pair name) but after that turned out that a bit below in the function, there was command that re-calculated our inputed price using command  `request['price'] = parseFloat (this.priceToPrecision (symbol, price));`    and as we had sell limit order at i.e. ` 1.234`, that command made its own digestion of input price, and (because `priceToPrecision` uses some other variable  `this.market[pairname]-->precision.price` ) it couldnt find that property of the PAIR (as there was not registered full info about PAIR, instead I had only added "pair-name" added, and I didn't know if i had to manually input other properties too).  So, that function returned incorrect price (rounded to zero, because of the absense of the pair-information) and sent the empty-price order to the exchange.  we had lost quite much again (as in previous month), and we are very disappointed.  I don't understand why createOrder function touched our inputed  limit price (using `..parseFloat (this.priceToPrecision ...` ).  How can we do that, just fire order as is, without giving any permission to CCXT to check anything internal, and just execute our `createOrder` as is, without looking if there is pair in the cache or not, and execute that price/amount whatever we inputed.  
As said, I am very disappointed. I know, there is no obligations, but if you can and have willing, please let us know if you will address the issue.  I think, that in the base there should be another  separate method `createOrderForced` (or smth named) , which should be fired from 'createOrder' itself, in the last line, where now  it is written "const response = await this[method] (this.extend (request, params));" as the last line.

So, that `createOrderForced` will be a method that executes everything as is:
- when called from  `createOrder` function, all parameters will be corrected inside `createOrder` function and so, then corrected params will be passed toward `createOrderForced` method. So, everything will stay same in CCXT and there will be no break
- when called by developers,  it will execute everything as is, without checking/correcting things -- "just send the order to exchange whatever we input".

I see this as a solution to the problem.

**Comment by ttodua** [comment] 2021-07-06 14:15
Another thing to add  on top of this, that is also easy to implement, is, when executing `createOrder` (or any other method, that has interaction with `this.markets` object) and ccxt finds that the commanded pair/symbol is not found, before returning error/exception, it should make a "fresh" request to exchange to get the fresh data about pairs. Maybe, there can be some flag when initializing CCXT exchange class (like there is "rate-limit" or "apiKey" argument passed to exchange class) alike that, there might be "Force_Refresh_Info_If_Inexistent_pair_requested" (yeah, this variable name is long just to express what I say, however, you can name it shorter name), so, when firing "createOrder" (I critically refer to that function, though it might be implemented for others method, but I care about `createOrder`) and it doesn't find the requested pair, it should re-query the exchange to get fresh info, albeit there is new pair which is being requested by user, and ccxt cache (or whatever is behind this problem) yet didnt knew that). so, it ONCE (will be there some static flag, if that if the first case) will re-request pairs info, and if it confirms that that pair doesnt exist, only after then return "BadSymbol....etc..".

**Comment by ttodua** [comment] 2021-07-06 14:24
here code that I used to add that to register pair manually https://pastebin.com/QApDE6Kx

**Comment by kroitor** [comment] 2021-07-06 14:24
>  it couldnt find that property of the PAIR (as there was not registered full info about PAIR, instead I had only added "pair-name" added, and I didn't know if i had to manually input other properties too).

I assumed it was obvious that if you want that "synthetic" market to work with createOrder – you have to add the properties of that market, that are used in createOrder.

We cannot avoid formatting entirely without breaking the lib for the majority of users. The core idea is to keep it unified across the exchanges. Some exchanges will require floats, others will require strings. Therefore formatting cannot be avoided for all exchanges universally. It's either all or nothing.

However, if you want to avoid automatic formatting, you can override priceToPrecision / amountToPrecision / costToPrecision on the user-level for a specific exchange:

```PHP
class MyBinance extends \ccxt\binance {

    public function cost_to_precision($symbol, $cost) {
        // return self::decimal_to_precision($cost, TRUNCATE, $this->markets[$symbol]['precision']['price'], $this->precisionMode, $this->paddingMode);
        return $this->number_to_string($cost); // string as is
    }

    public function price_to_precision($symbol, $price) {
        // return self::decimal_to_precision($price, ROUND, $this->markets[$symbol]['precision']['price'], $this->precisionMode, $this->paddingMode);
        return $this->number_to_string($price); // string as is
    }

    public function amount_to_precision($symbol, $amount) {
        // return self::decimal_to_precision($amount, TRUNCATE, $this->markets[$symbol]['precision']['amount'], $this->precisionMode, $this->paddingMode);
        return $this->number_to_string($amount); // string as is
    }
}

$exchange = new MyBinance();

// ...
```

**Comment by ttodua** [comment] 2021-07-06 14:32
I understand, i dont say to avoid formatting, I suggested to do two things (neither of that breaks lib):

A) in the bottom of `createOrder` function, instead of directly executing `const response = await this[method] (this.extend (request, params));`, move that part to new method, i.e. `createOrderForced` so, for noone nothing will break, like:
```

craeteOrder(){
    ....
    ...
    //const response = await this[method] (this.extend (request, params)); 
    const response = await createOrderForce(this[method], request, params);
}

createOrderForce(methodName, request, params){
    return await methodName(this.extend (request, params));
}
```

so, as you see, this change is only in background ccxt codes, and for no user in million will see any break. The advantage is that, it will be unified function which can be called by us too, so instead of calling  `createOrder`  now we can call `createOrderForce` as our preference.

**Comment by ttodua** [comment] 2021-07-06 14:34
B) what I said about "re-fetching fresh data" if the pair is not found in "markets". there should be flag (passed in Exchange object initialization when doing new ccxt\myBinance(... Force_Refetch_if_not_found...=>true) to turn this on.

**Comment by kroitor** [comment] 2021-07-06 14:42
- **A** cannot be done universally for all exchanges – you will understand if you attempt it. Some orders need a price, others don't. Therefore, you will have to add all sorts of checks to the "wrapping" createOrder function. And you will have to do those checks one more time in createOrderForced to properly fill up the order. So, the solution to properly change that behaviour will boil down to changing the methods i've posted [above](https://github.com/ccxt/ccxt/issues/9514#issuecomment-874807297).

- **B** has to live in the userland:

```
try:
    exchange.createOrder(symbol)
except BadSymbol:
   # the symbol does not exist / not found
   reload / populate your markets how you want
except Exception as e:
   # other exceptions
```

↑ Not all users will want that in the basecode. However, CCXT already gives you all ways of controlling the behaviour how you want.

**Comment by ttodua** [comment] 2021-07-06 15:00
and what about FLAG to force reload pairs-data from exchange freshly?   loadMarkets(true) didnt help

**Comment by kroitor** [comment] 2021-07-06 15:07
@ttodua i will try to paste a snippet to reproduce.

**Comment by ttodua** [comment] 2021-07-10 19:06
Any update?

**Comment by ttodua** [comment] 2021-07-16 17:48
...

**Comment by kroitor** [comment] 2021-07-17 01:58
@ttodua pardon for the delays, will get to it asap!

**Comment by ttodua** [comment] 2021-07-23 12:09
...

**Comment by ttodua** [comment] 2021-07-31 06:54
...

**Comment by ttodua** [comment] 2021-07-31 18:36
Thanks. (to remind, that issue is observable well, when the pair is newly opened (say several minutes even, or even 10-15 minutes before listing too, when the currency is already obtainable from exchange api-link), but ccxt cant see it and returns "badSymbol" error, even after pair is opened, during next few mins (i havent counted how many minutes, but quite enough, more than 5 mins I think) no change happens, even if you do "load_markets(true)";

**Comment by ttodua** [comment] 2021-08-05 12:36
Kroitor, let's say directly. this is no-go now. So, please don't spend any more time about planning this. Just as a last thing, mention a "theoretical" steps how this should be done and I will take it on my own. Just tell how CCXT should do that correctly.

**Comment by frosty00** [comment] 2023-11-02 19:35
closing because `loadMarket(true)` should reload markets, unable to reproduce

**Closed by frosty00** 2023-11-02 19:35 UTC
Labels: question
