### ISSUE TITLE
Binance withdraw()

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#320] opened 2017-10-15 03:23 UTC
Hello!

I have an issue with withdraw function. Is it not supported for all the exchanges? For example, binance:

```
import ccxt
exch = ccxt.binance({
'apiKey': key,
'secret': secret,
})

order = exch.withdraw('USDT', 105, exch_withdraw_to.usdt_wallet)
```

result:

> Traceback (most recent call last):
>   File "withdraw.py", line 87, in <module>
>     order = exch_withdraw_from.private_exch.withdraw('USDT', 105, exch_withdraw_to.usdt_wallet)
> AttributeError: 'binance' object has no attribute 'withdraw'

**Comment by kroitor** [comment] 2017-10-15 03:31
@Fcl69 hi! 

First, on Binance they don't have such an option, there is no such endpoint. They don't have withdrawals in their API on Binance. So, you have to do it manually until they implement a programmatic withdrawal endpoint. We can't workaround that, unfortunately.

Second, yes, it's not completely unified in ccxt yet, so we don't have all withdraw() methods implemented yet for some of those exchanges that do offer such an endpoint for algorithmic withdrawals and rebalancing.

Let us know if the above answers your question. Thx!

**Comment by Fcl69** [comment] 2017-10-15 04:29
Yeah... I guess it does. A bit disappointing though, that the process can't be fully automated, but I get you, it's not the ccxt problem. Thanks for clarifying though!

**Comment by kroitor** [comment] 2017-10-15 04:34
@Fcl69 hey, but what if we organize a usermass large enough and push on Binance a little by sending a massive amount of requests of the same withdraw feature so that they finally implement that endpoint? )

**Comment by Fcl69** [comment] 2017-10-15 04:36
I'm all for it! ;) Tell where to sign or when to send a ticket request!

**Comment by kroitor** [comment] 2017-10-15 04:39
@Fcl also, this process still can be automated, if you hold a buffer of money there, large enough to sustain your trading operation for a week or a month...
I suggest, let's plan it thoroughly, we need a statement text first, that we will be sending, I'll write one and I will post it here. And then we will open a new issue for other users to read and join us )

**Comment by Fcl69** [comment] 2017-10-15 04:51
>@Fcl69, also, this process still can be automated if you hold a buffer of money there large enough to sustain your trading operation for a week or a month...
I didn't get you, could you please be more specific?

#2 - sounds good!

**Comment by kroitor** [comment] 2017-10-15 04:55
> I didn't get you, could you please be more specific?

Well, you hold a balance there. And when it gets low, you send a notification to refill it ← this part of funding can be automated by simply sending to Binance deposit address. When it gets too high, you send a notification to withdraw ← that can be automated by simulating user activity on their website and doing a few "clicks".

**Comment by kroitor** [comment] 2017-10-21 17:04
Good news for you! Binance is implementing the `withdraw()` method in their API and we will unify it in ccxt as well, very soon! Cheers!

**Comment by Fcl69** [comment] 2017-10-22 04:04
It's a good news indeed. Thank you so much for the update!!

**Comment by Fcl69** [comment] 2017-10-26 02:17
Please let me know if it's been implemented yet.
Or where I could check the status, so I don't poke you in vain.
Thanks,

**Comment by kroitor** [comment] 2017-10-26 02:44
@Fcl69 It has been implemented in 1.9.268. Let us know if you have any difficulties with it. Thx!

**Comment by Fcl69** [comment] 2017-10-26 03:34
Will do! Thank you!

**Comment by Fcl69** [comment] 2017-10-26 05:55
Looks like it's not perfect yet:

>exch.withdraw(currency, balance, wallet_withdraw_to)

Result:
{'info': {'msg': '{"code":-1105,"msg":"Parameter \'payload\' was was empty."}', 'success': False}, 'id': None}

**Comment by kroitor** [comment] 2017-10-26 12:44
@Fcl69 ok, but, can you please paste **verbose** output? Need it for debugging (hope you understand). Remove your keys from it if you want.

```
exch.verbose = True  # add this line before doing the call
exch.withdraw (...
```

**Comment by kroitor** [comment] 2017-10-26 12:55
Nope, never mind, don't the verbose output.

<img width="717" alt="screen shot 2017-10-26 at 15 52 09" src="https://user-images.githubusercontent.com/1294454/32054028-b93894de-ba65-11e7-8dc7-b81f4fc3186d.png">

.
.
.

<img width="717" alt="screen shot 2017-10-26 at 15 52 39" src="https://user-images.githubusercontent.com/1294454/32054041-c182bc3c-ba65-11e7-8eee-4e2c139751e2.png">

As you see, other users are having same symptoms (without ccxt). Looks like their withdraw API is still not working, but without proper docs it would be very hard to implement. Let's wait a little more until Binance is ready to provide a documented `withdraw`. I'm closing it for now, standing by for further updates from them.

**Comment by Fcl69** [comment] 2017-10-29 15:27
>ccc 333, [29.10.17 02:06]
>OK, I think I fixed the withdraw api issue in my scenario.
>One thing is not so intuitive about the with api that the api is parameter order senstive
>If you post /wapi/v1/getDepositHistory.html?asset=ETH&recvWindow=6000000&timestamp=1509267785850&signature=1617846782e2a36907977d56d150107845a680dd5a6d9d21c85b1a30c10e10ac, it will be fine
>Cyril, [29.10.17 02:08]
@Ninj0r the binance login slider gives me "Net Err. Please refresh, or feedback" very often
is there something i can do about that?
>ccc 333, [29.10.17 02:08]
>But if you post /wapi/v1/getDepositHistory.html?asset=ETH&recvWindow=6000000&signature=1617846782e2a36907977d56d150107845a680dd5a6d9d21c85b1a30c10e10ac&timestamp=1509267785850, it will say signature is not valid 😅
>the signature request paramter has always to be the last one
>Sylvain Ribes, [29.10.17 02:21]
>@gosucymp the channel is meant for API issues think you should address support directly, or MB binance's reddit.
>Jam Trader, [29.10.17 02:32]
>Think I've finally cracked the withdraw endpoint. Thanks for all the help 🙂
>See https://github.com/sammchardy/python-binance and documentation around withdrawals for assumptions on the Binance side that you need to know about. http://python-binance.readthedocs.io/en/latest/withdraw.html

https://github.com/sammchardy/python-binance

**Comment by kroitor** [comment] 2017-10-29 15:47
@Fcl69 thx! We will fix for that in ccxt as well (asap).

**Comment by kroitor** [comment] 2017-11-02 11:35
@Fcl69 hi again! Can you please try 1.9.338? I uploaded the fixes and tested locally, worked for me. Let us know if it works for you or not, please. Thx!

**Comment by Ninj0r** [comment] 2017-11-02 12:02
That should work. I pinned a post in the API chat a while back:
```
3) You can't send /wapi parameters in the request body. They have to be query parameters.
If you get:
{"msg":"{\"code\":-1105,\"msg\":\"Parameter 'payload' was was empty.\"}","success":false}

That means you sent things in the request body.
For /api endpoints, you can use the request body freely but you cannot for the /wapi endpoints.
```

(The @ from the comment a few days ago put me on the thread.)

**Comment by Fcl69** [comment] 2017-11-02 16:50
Thank you for implementing it!
I'll be able to give a try in a day or so. Will comment here soon.

**Comment by kroitor** [comment] 2017-11-02 22:01
@Fcl69 I am closing this issue if you don't mind, will stand by to hear from you. We will be happy if you report back, whether it does work normally for you or not. Feel free to reopen it if needed. Thx!

**Comment by Fcl69** [comment] 2017-11-02 22:01
Hm... I got this reply:
 {'id': None, 'info': {'success': False, 'msg': '{"code":-1022,"msg":"Signature for this request is not valid."}'}}

**Comment by kroitor** [comment] 2017-11-02 22:02
@Fcl69 can you please show verbose output?

**Comment by Fcl69** [comment] 2017-11-02 22:08
https://www.binance.com/api/v1/account?timestamp=1509660410464&signature=xxx GET https://ww
w.binance.com/api/v1/account?timestamp=1509660410464&signature=xxxx
Request: {'Accept-Encoding': 'gzip, deflate', 'X-MBX-APIKEY': 'key', 'User-Agent': 'ccxt/1.9.346 (+https://github.com/ccxt-dev/
ccxt) Python/3.5.2'} None
GET https://www.binance.com/api/v1/account?timestamp=1509660410464&signature=xxxx
Response: Date: Thu, 02 Nov 2017 22:06:50 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: close
Server: nginx
Content-Encoding: gzip

**Comment by kroitor** [comment] 2017-11-02 22:10
@Fcl69 no, it's not the withdraw call. Can you show your actual code and output (you can delete the keys if you want)?

**Comment by Fcl69** [comment] 2017-11-02 22:14
Excuse me, I copy-pasted the wrong peace of the log. Here is a correct one. [I still can provide code if needed]:

>  https://www.binance.com/wapi/v1/withdraw.html?timestamp=1509660365636&address=xxx&amount=501.0&asset=USDT&signature=yyysigantureyyy
> POST https://www.binance.com/wapi/v1/withdraw.html?timestamp=1509660365636&address=xxx&amount=501.0&asset=USDT&signature=yyysigantureyyy
> Request: {'Accept-Encoding': 'gzip, deflate', 'X-MBX-APIKEY': 'key', 'User-Agent': 'ccxt/1.9.346 (+https://github.com/ccxt-dev/
> ccxt) Python/3.5.2'} None
> POST https://www.binance.com/wapi/v1/withdraw.html?timestamp=1509660365636&address=xxx&amount=16501.0&asset=USDT&signature=yyysigantureyyy
> Response: Date: Thu, 02 Nov 2017 22:06:06 GMT
> Content-Type: application/json;charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Server: nginx
> Set-Cookie: JSESSIONID=cookie_id; Path=/; HttpOnly
> 
>  {"msg":"{\"code\":-1022,\"msg\":\"Signature for this request is not valid.\"}","success":false}
> https://www.binance.com/api/v1/account?timestamp=1509660381628&signature=yyysigantureyyy GET https://www.binance.com/api/v1/account?timestamp=1509660381628&signature=yyysigantureyyy
> Request: {'Accept-Encoding': 'gzip, deflate', 'X-MBX-APIKEY': 'key', 'User-Agent': 'ccxt/1.9.346 (+https://github.com/ccxt-dev/ccxt) Python/3.5.2'} None
> GET https://www.binance.com/api/v1/account?timestamp=1509660381628&signature=yyysigantureyyy
> Response: Date: Thu, 02 Nov 2017 22:06:22 GMT
> Content-Type: text/html;charset=utf-8
> Transfer-Encoding: chunked
> Connection: close
> Server: nginx
> Content-Encoding: gzip

**Comment by kroitor** [comment] 2017-11-02 22:26
Ok, I see, will get back to you shortly with another fix. Thx for your responses!

**Comment by Fcl69** [comment] 2017-11-03 17:54
Should I give it a try yet?

**Comment by kroitor** [comment] 2017-11-03 17:57
@Fcl69 not yet, I'll let you know soon. Still have to test it on our side. Thx for your patience!

**Comment by Fcl69** [comment] 2017-11-03 17:58
no problem! thanks

**Closed** 2017-11-03 23:46 UTC
Labels: enhancement

**Comment by kroitor** [comment] 2017-11-04 00:34
@Fcl69 it was added in 1.9.359. Please let us know if it works for you or not (it should, we tested it locally). Thx!

**Comment by Fcl69** [comment] 2017-11-04 05:34
I've installed .359, but it fucks up my current code in some other place: ;)

> 2017-11-03 22:28:43,106 : ERROR. GetBalance() cannot get balance for binance (attempt #1)
> Traceback (most recent call last):
>   File "ccwd.py", line 72, in __init__
>     balance = exch.fetch_balance()
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/binance.py", line 203, in fetch_balance
>     response = self.privateGetAccount(params)
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/binance.py", line 496, in request
>     response = self.fetch2(path, api, method, params, headers, body)
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 237, in fetch2
>     request = self.sign(path, api, method, params, headers, body)
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/binance.py", line 480, in sign
>     signature = self.hash(self.encode(auth), hashlib.sha256)  # v1
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 580, in hash
>     h = hashlib.new(algorithm, request)
>   File "/usr/lib/python3.5/hashlib.py", line 122, in __hash_new
>     return _hashlib.new(name, data)

I'll try to work on it later. Will keep you posted. If you know what's up with fetch_balance() let me know, please.

**Comment by kroitor** [comment] 2017-11-04 05:36
@Fcl69 try 1.9.360. Need to see your code / verbose output to be able to tell the cause.

**Comment by kroitor** [comment] 2017-11-04 05:37
@Fcl69 does your original example from the initial post work with 1.9.360 ?

**Comment by Fcl69** [comment] 2017-11-04 05:53
Hm....

Current code:
```
import ccxt 
exch = ccxt.binance({
    'apiKey': 'key',
    'secret': 'secret',
    'enableRateLimit': True,
    'verbose': True,
    })
order = exch.fetch_balance()
print(order)


```
Result:

> Traceback (most recent call last):
>   File "ob_small.py", line 26, in <module>
>     order = exch.fetch_balance()
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 203, in fetch_balance
>     response = self.privateGetAccount(params)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 496, in request
>     response = self.fetch2(path, api, method, params, headers, body)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 237, in fetch2
>     request = self.sign(path, api, method, params, headers, body)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 480, in sign
>     signature = self.hash(self.encode(auth), hashlib.sha256)  # v1
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 580, in hash
>     h = hashlib.new(algorithm, request)
>   File "/usr/lib/python3.5/hashlib.py", line 122, in __hash_new
>     return _hashlib.new(name, data)
> TypeError: name must be a string


PS Will check withdraw() in a bit.

**Comment by Fcl69** [comment] 2017-11-04 06:12
...had to revert back to (1.9.338) to make it work as previously.

**Comment by kroitor** [comment] 2017-11-04 06:39
Ok, it was a minor left over. Can you please update once again to 1.9.361 and retry? Both methods (`fetch_balance` and `withdraw`) should work now. Standing by to hear from you. Thx!

**Comment by Ninj0r** [comment] 2017-11-04 07:08
I would recommend you remove all the `/api/v1` signing logic. `/wapi/v1` signed endpoints use the `/api/v3` signing logic so you can remove the need the for both signing methodologies if you switch your signed calls from `/api/v1` to `/api/v3`.

Signed `/api/v1` endpoints should be considered deprecated and will be removed at some (yet to be determined) time in the future so please always use the `/api/v3` endpoints for signed requests. 100% of the `v1` signed endpoints are available in `v3` and the only difference is the signing logic. Note that `/api/v1` and `/wapi/v1` are not the same system and `/wapi/v1` endpoints are not deprecated.

**Comment by kroitor** [comment] 2017-11-04 07:10
@Ninj0r thx, will migrate to v3!

**Comment by Fcl69** [comment] 2017-11-04 15:07
updated to .361, both method works. Withdraw successfully submitted. Thank you!

**Comment by kroitor** [comment] 2017-11-04 16:46
@Fcl69 woohooo! )

**Comment by sumiti** [comment] 2019-04-17 13:00
Hello everyone,
I am facing an issue while calling the withdraw API for Binance.
Here is my request: 
https://www.binance.com/wapi/v3/withdraw.html?asset=BTC&address=bc1qm0rc9dvm63v8d2ehayzcem7th82z8je0qe66km&amount=1&recvWindow=5000&name=addressName&timestamp=1510903211000&signature=CqTEOjSQS6GCqXzGXypP54Onb9ayic0OvE1DdZGEBlfzUAPea3jb4UAizmSxxZQz'

The result response is:
{
    "msg": "You don't have permission.",
    "success": false
}

I am passing the X-MBX-APIKEY in the headers.
Please help.

**Comment by kroitor** [comment] 2019-04-17 13:03
@sumiti can you show your CCXT code to reproduce it or your verbose request/response? If it says that you don't have a permission, then it means that your `apiKey` doesn't have the necessary withdrawal permission enabled.

**Comment by sumiti** [comment] 2019-04-17 13:17
@kroitor I got your point the setting is not enabled.
Thanks!!

**Comment by sumiti** [comment] 2019-04-18 11:00
Hi,
I added my system ip and have provided the withdrawal permissions on my API key also.
Even though If I am hitting the withdrawal API it is giving me "Invalid IP address" error.
Please help!

**Comment by kroitor** [comment] 2019-04-18 11:09
@sumiti 

> it is giving me "Invalid IP address" error.

If it says "Invalid IP Address", then you should make sure that your address entered in the apiKey settings on Binance website is correct. Google for `what is my ip address` to find it.

**Comment by sumiti** [comment] 2019-04-23 08:55
I did that I entered the same shown by the google and my system ip only.
Even though it is showing me the same error.

**Comment by hsh4269** [comment] 2023-12-19 05:36
I used the Binance withdrawal function.
The withdrawal was made normally, but all return values have None stamped.

{'info': {'id': '9b16ffa5ffad4becb12346c90eed5'}, 'id': '9b16ffa5ffad4becb12346c90eed5', 'txid': None, 'timestamp': None, 'datetime': None, 'network': None, 'address': None, 'addressTo': None, 'addressFrom': None, 'tag': None, 'tagTo': None, 'tagFrom': None, 'type': 'withdrawal', 'amount': None, 'currency': 'DOGE', 'status': None, 'updated': None, 'internal': None, 'fee': None}

What is the problem?
How do I solve this?
