### ISSUE TITLE
Bitmex contract naming unification questions

### ISSUE THREAD

**Issue by orikalinski** [ccxt/ccxt#3540] opened 2018-08-01 13:38 UTC
In the latest version of ccxt (python - 1.17.60).
The symbols in Bitmex exchanges are not unified except XBTUSD (BTC/USD)
I guess it wasn't unified due to the fact that except XBTUSD all the others are futures and their symbol ends with U18 (current expiration date - September 2018)

In my use case I need them to be unified, and I can also make a pull request if needed. that's a very small change in order to make them unified (for example ADAU18 will become ADA/BTC)

Just wonder if that what people desire

**Comment by kroitor** [comment] 2018-08-01 13:44
> (for example ADAU18 will become ADA/BTC)

How would you unify the following two active contracts? ) Both are BTC/USD, U for September, Z for December? 

```
          |            | 0.00075 | -0.00025 | XBTU18      | XBTU18      | BTC  | USD   | true   | future | false | false | true   | false
          |            | 0.00075 | -0.00025 | XBTZ18      | XBTZ18      | BTC  | USD   | true   | future | false | false | true   | false
```

**Comment by orikalinski** [comment] 2018-08-01 13:51
But that's the same right here, as ccxt didn't unified XBTU18 and XBTZ18 and yet unified XBTUSD.
I'm not offering to unify those symbols but at least we can unify all the alt pairs which have only 1 pair each.

What do you think?

**Comment by kroitor** [comment] 2018-08-01 13:54
I don't mind unifying the rest of them, but there's one possible side effect with this. If there a second contract is delisted and then relisted, this will cause "flickering" – the market will be renamed between consequent launches which is not what you want. Because I don't trade too often with BitMEX, I can't really say how frequently the above can happen and whether it happens at all or not. Can you shed some light on this?

**Comment by orikalinski** [comment] 2018-08-01 13:57
That doesn't really matter because the ccxt_symbol_data["info"]["quoteCurrency"] is always XBT for those symbols no matter if the symbol were replaced with a new date identity

**Comment by kroitor** [comment] 2018-08-01 13:59
> That doesn't really matter because the ccxt_symbol_data["info"]["quoteCurrency"] is always XBT for those symbols no matter if the symbol were replaced with a new date identity

Yep, but this doesn't really add to unification, if you have to look up in the `info`...

In general I would rather keep them with their fixed names, because if you suddenly start trading a different contract under the same name without any distinct notion of it, financially this might lead to very bad consequences for the trader. I'd rather keep the trader aware of what he is actually trading. Do you agree?

**Comment by orikalinski** [comment] 2018-08-01 14:02
def fetch_markets(self):
        markets = self.publicGetInstrumentActiveAndIndices()
        result = []
        for p in range(0, len(markets)):
            market = markets[p]
            active = (market['state'] != 'Unlisted')
            id = market['symbol']
            base = market['underlying']
            quote = market['quoteCurrency']
            type = None
            future = False
            prediction = False
            basequote = base + quote
            base = self.common_currency_code(base)
            quote = self.common_currency_code(quote)
            swap = (id == basequote)
            symbol = id
            if swap:
                type = 'swap'
                symbol = base + '/' + quote
            elif id.find('B_') >= 0:
                prediction = True
                type = 'prediction'
            else:
                future = True
                type = 'future'



that's the begging of the fetch_markets in bitmex.
correct me if I'm wrong but the quoteCurrency is used in here and the way that XBTUSD replaced to XBT/USD is using those values.
I'm not seeing any issue to use those in order to turn ADAU18 into ADA/XBT for example.

**Comment by kroitor** [comment] 2018-08-01 14:08
> I'm not seeing any issue to use those in order to turn ADAU18 into ADA/XBT for example.

I tried to explain the issue above with the example of XBTU and XBTZ. If you don't parse those two, then imagine what will happen in this scenario:

A user happily trades his ADA/BTC for a while (which is actually ADAU), and then BitMEX launches ADAZ. Now there's two of them, so ADA is not unique anymore. So the parser in fetchMarkets won't touch it (same behavior as was proposed by you above with XBTZ vs ZBTU – it doesn't touch them). 
So, in the end, we have a a user that was trading ADA/BTC, then, all of a sudden, after a normal restart, there's no ADA/BTC there anymore and there's ADAU and ADAZ (call them whatever). 

Alternative example of a problem case: The user looks up the price for ADAU (ADA/BTC), and takes some time to come with a trading decision. During that time, the ADAU→ADAZ replacement happens. The user goes back to BitMEX without knowing that, and makes a mistake with a wrong market, being convinced that this is the same ADA/BTC contract.

To me both of the above examples are unacceptable to a trader, how about you? )

**Comment by orikalinski** [comment] 2018-08-01 14:17
Well I agree with the above,
I think the first issue is fixable by taking the closest date if there is no permanent symbol exists, like in XBTUSD (which we can ignore the two others). so If we'll let's say have ADAU and ADAZ (we need to verify that but I think that these date identifiers - U,Z are fixed) we can take here the ADAU in this case.

About the second point I agree that this is an issue that the trader will have a gap that he needs to understand whether is ADAU or ADAZ. I need to think about a solution. anything you can think of?

**Comment by kroitor** [comment] 2018-08-01 14:20
I'd keep this issue open for a while to see what other users might add to the above. And will think about a proper way of doing this on my own as well. If nobody except two of us shows any interest to the question you raised, then I guess, this isn't really an issue for an average user and I'd close it then. How does that sound to you?

**Comment by orikalinski** [comment] 2018-08-01 14:21
That sounds great,
Thanks for the quick response

**Comment by kroitor** [comment] 2018-08-01 14:26
Your help and contributions are welcome and appreciated anyways. We'll be happy to receive PRs from you, there's a ton of things inside the library that can be implemented / fixed or unified, and a lot of work in progress, read more about the approach to it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code.

**Comment by orikalinski** [comment] 2018-08-01 14:28
Will do +1

**Comment by orikalinski** [comment] 2018-08-01 15:09
Just tried to read a bit about what happen when the contract ends and I figured out that on Bitmex when the contract expires then the positions close automatically with market order.
So if i'm going back to the second point you mentioned, I as a trader, would prefer to be able to put immediately another position in case the old one closes without be needed to change the code.
What I'm trying to say that anyway all my positions will be closed in the expiration date and in addition I know it's not the goal of ccxt but the ccxt user can always check out the <expiry> attribute in order to figure out how much time left for the current contract. I'm going to use that attribute in order to get notification X amount of time before expired.

Your thoughts?

**Comment by orikalinski** [comment] 2018-08-01 15:39
By saying needed, I meant prettier I guess. That feels hacky to try and build your next valid symbol. for example if  we try to fetch ADAU18 we need to iterate over the symbols and years and to create each symbol like ADAQ18 and search for it and then ADAU18 and search for it until you find a valid key. which feels it isn't the best practice in this case (more over if you work with another exchanges in your project then this adds complexity to your code.)

about the `info` section that has to be checked now it's problematic I agree. In my case this isn't an issue.
Well I guess we'll let people say what they think and in the meantime I'll patch the code to my case.

**Comment by joncinque** [comment] 2018-09-03 19:47
Hey everyone, I'd like provide my 2 cents on this one.  Having worked in the commodities sector for some time, where we had to deal with these sorts of contracts all the time (along with their derivatives), I don't think it's up to ccxt to unify the contracts.  If someone is buying ADAU18, it's very different from buying ADA with BTC, so they should be maintained as different entities, and I would even be careful about unifying their perpetual contract XBT/USD since it's also not the same thing.  It should be up to application developers to do whatever unifying and caching they need as contracts roll over.
Mercantile exchanges usually offer an "active contract" which maps to the currently most traded contract, but BitMEX doesn't (yet?) unfortunately.  Once they offer an active or front contract, then some unification might make sense.
There is something else we could unify, and I'd be curious about what others think of this.  BitMEX publishes their reference indices used for settling contracts, calculated from other exchanges, e.g. `.XBT` comes from the average of GDAX and Bitstamp.  The problem is that these are untradable, which makes them unusable with `create_order`.  What are your thoughts?

**Comment by kroitor** [comment] 2018-09-04 04:43
@joncinque thx! I agree, we better not try unifying perpetual contract names.

> The problem is that these are untradable, which makes them unusable with create_order. What are your thoughts?

However, I'm not sure if I got that last issue description properly, can you elaborate a bit more plz? I do understand that those prices are indexed from other exchanges, yet still, don't really see what we can do in the lib about it.

**Comment by kroitor** [comment] 2018-09-04 04:45
@orikalinski , @joncinque btw, just got this email:

<img width="598" alt="screen shot 2018-09-04 at 07 40 22" src="https://user-images.githubusercontent.com/1294454/45010470-667c6e80-b016-11e8-9d1d-7abdb2af2685.png">

;)

**Comment by joncinque** [comment] 2018-09-04 11:55
> However, I'm not sure if I got that last issue description properly, can you elaborate a bit more plz? I do understand that those prices are indexed from other exchanges, yet still, don't really see what we can do in the lib about it. Can you explain this further plz?
I was proposing another way forward with unifying, where the conventional ticker maps to its BitMEX index.  For example, mapping `ADA/BTC` to `.ADAXBT Index`.  My issue with doing that is that it's impossible to trade on the index price, so if someone calls `create_order` on `ADA/BTC` thinking that they're buying ADA with BTC, it would fail.  On the flip side, it does give BitMEX's view on the price of `ADA/BTC`.   What do people think about that?

**Comment by joncinque** [comment] 2018-09-04 11:57
And seeing how they change the definition of the index, it would definitely be useful to be able to fetch it :smile:

**Comment by fonzmeister** [comment] 2019-05-28 08:18
Maybe I should have openend a new issue for this. But why not unify the period for the contract?
e.g. for BTC you will get
BTC1W
BTC2W
BTC1M
BTC3M
BTC6M

The above will work for okex, bitmex and deribit if I am correct. You can do the same for altcoins.

It will require some logic to map the contracts, but I think it will be nice with more and more exchanges offering futures

**Comment by kroitor** [comment] 2019-05-29 03:06
@fonzmeister that may be a good way to go, but then you also have to invent a standard for other derivatives and swap markets and other types of instruments.

Also, because it could be an ETH to USD future market or an ETH to BTC future market, the second currency will probably have to be included in the symbolic name, so ETH/USD:1W, ETH/BTC:3M, ETH/BTC:SWAP, ...

See [okex3](https://github.com/ccxt/ccxt/blob/master/js/okex3.js) markets for example:

<img width="1252" alt="Screen Shot 2019-05-29 at 06 04 12" src="https://user-images.githubusercontent.com/1294454/58526432-9d636780-81d7-11e9-9e4b-2ffe8c4b7d5c.png">

So, we might need some more bits in this, but yes, the general direction is correct – we're currently gathering and consolidating our research info to approach the unification for futures and derivatives.

**Comment by fonzmeister** [comment] 2019-05-29 06:25
I never have looked into the option markets as for example deribit offers.

I think your proposal will work, did not think about all the other markets. I am more thinking about the user. How will ccxt handle symbol changes close to the settlement date? Symbols won't match, or you trade the wrong market. Users need the be aware to refresh the symbol data every now and then (should be good practice anyway, to do a exhange.load_markets(true)

I think the names are quite clear for. You'll need some code to map it though. I wrote something for it for my bot, it uses bitmex and deribit. So it is not complete, but can work as a basis.

below code is for bitmex
```
#returns a list of all the active symbols. Inactive symbolshave a "." before it. 
#the symbols with a "_" are the indexes, which you cannot trade
def find_bitmex_tickers(exchange):
    exchange.loadMarkets()
    symbols = exchange.symbols
    tickers=[]
    for symbol in symbols:
        if not '.' in symbol:
            if 'BTC/USD'in symbol:
                tickers.append(symbol)
            if 'XBT' in symbol and '_' not in symbol:
                tickers.append(symbol)
    
    return tickers

#returns the 3M and 6M tickers.

def find_bitmex_symbols(tickers):
    mapping = {'F' : datetime.strptime('Jan', '%b'),
               'G' : datetime.strptime('Feb', '%b'),
               'H' : datetime.strptime('Mar', '%b'),
               'J' : datetime.strptime('Apr', '%b'),
               'K' : datetime.strptime('May', '%b'),
               'M' : datetime.strptime('Jun', '%b'),
               'N' : datetime.strptime('Jul', '%b'),
               'Q' : datetime.strptime('Aug', '%b'),
               'U' : datetime.strptime('Sep', '%b'),
               'V' : datetime.strptime('Oct', '%b'),
               'X' : datetime.strptime('Nov', '%b'),
               'Z' : datetime.strptime('Dec', '%b'),
            }
    
#close to the settlement date bitmex has 3 future markets. 
#this code discards the one that will close earliest, my bot doesn't need to
# can probalby become a 2W markets or something like that
    if len(tickers) == 3:
        x = tickers[0][3]
        y = tickers[1][3]
        z = tickers[2][3]  
        t = [x,y,z]
        
        index = t.index(min(t))
        
        tickers.pop(index)
        
    if len(tickers) == 2:
        x = tickers[0][3]
        y = tickers[1][3]
    
        if mapping[x] < mapping[y]:
            bitmex3MTicker = tickers[0]
            bitmex6MTicker = tickers[1]
        else:
            bitmex3MTicker = tickers[1]
            bitmex6MTicker = tickers[0]
    
        return bitmex3MTicker, bitmex6MTicker
    else:
        logger.error("more than 3 or less than 1 ticker")
        return
```

**Comment by kroitor** [comment] 2019-05-29 14:57
> How will ccxt handle symbol changes close to the settlement date?

@fonzmeister that's a very good question. Currently, in okex3, the set of market ids and symbols contains the closing date, similar to `ETH/USD:2019-06-01` – that implies, that there's no `1W`/`2W` in the symbol. Instead, there's just the closing date (which may be a week ahead, two weeks ahead). So when the closing date arrives – old markets stop working, and new markets appear. There's a rolling window of history that keeps a few outdated markets available for historical purposes.

**Comment by fonzmeister** [comment] 2019-05-29 15:56
> > How will ccxt handle symbol changes close to the settlement date?
> 
> @fonzmeister that's a very good question. Currently, in okex3, the set of market ids and symbols contains the closing date, similar to `ETH/USD:2019-06-01` – that implies, that there's no `1W`/`2W` in the symbol. Instead, there's just the closing date (which may be a week ahead, two weeks ahead). So when the closing date arrives – old markets stop working, and new markets appear. There's a rolling window of history that keeps a few outdated markets available for historical purposes. This is not unified yet, however.

Yeah that is basically what I do in my code.

So on a loadMarkets(true) (think it should be here, not sure), you should probably map the symbols

So in case of Okex, you sort the symbol names on datetime and then the one with the closest closing date will become 1W, the next 2W etc

It is very exchange dependent and requires hardcoding, so might not be ideal

**Comment by kroitor** [comment] 2019-05-30 07:56
> It is very exchange dependent and requires hardcoding, so might not be ideal

Right, it's exchange-specific now, but we're actually going to unify this behaviour or something similar to that, in other words, the symbolic standard for futures-markets will be the same across the exchanges, that should make it a lot easier to handle futures-expiration in userland. We'll add expiration dates to market structures as well.

**Closed** 2022-05-11 05:02 UTC
Labels: enhancement, question
