### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH while updating tickers with bittrex

### ISSUE THREAD

**Issue by Burtonium** [ccxt/ccxt#2034] opened 2018-02-23 22:59 UTC
I got ERR_CONTENT_LENGTH_MISMATCH while trying to fetch tickers for the second time using bittrex. Anyone know what's causing it and how to fix it?

- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.10.1021
- Exchange: Bittrex
- Method:

**Comment by kroitor** [comment] 2018-02-23 23:02
> Anyone know what's causing it and how to fix it?

Hard to tell without your code and verbose output. Can show a minimal (but a complete) snippet of code to reproduce the problem? Remove everything that is not absolutely necessary, to rule out other causes, and please copypaste your code and verbose output following these steps: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Standing by for more info from you.

**Comment by Burtonium** [comment] 2018-02-23 23:28
Here's an example I was able to reproduce using VueJS

`import { bittrex } from 'ccxt';

const b = new bittrex();
b.proxy = process.env.CORS_PROXY_URL;

export default {
  data() {
    return {
      interval: null,
      index: 1
    };
  },
  mounted() {
    this.interval = setInterval(async () => {
      console.log(`Calling API ${this.index++} time`);
      await b.fetchTickers();
    }, 5000);
  },
  beforeDestroy() {
    clearInterval(this.interval);
  }
};`

The error surfaces intermittently, from my testing.

**Comment by Burtonium** [comment] 2018-02-23 23:35
Here is the verbose output, as requested
```
fetch:
 bittrex GET https://arb-bot-burtonium.c9users.io:8082/https://bittrex.com/api/v1.1/public/getmarketsummaries 
Request:
 {} 
 undefined 

Exchange.js?3c9e:274 GET https://arb-bot-burtonium.c9users.io:8082/https://bittrex.com/api/v1.1/public/getmarketsummaries net::ERR_CONTENT_LENGTH_MISMATCH
executeRestRequest @ Exchange.js?3c9e:274
fetch @ Exchange.js?3c9e:359
fetch2 @ Exchange.js?3c9e:368
request @ bittrex.js?0930:728
partial @ Exchange.js?3c9e:321
fetchTickers @ bittrex.js?0930:321
async function (async)
fetchTickers @ bittrex.js?0930:338
_callee$ @ History.vue?0caa:22
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
setInterval (async)
mounted @ History.vue?0caa:20
callHook @ vue.esm.js?efeb:2895
insert @ vue.esm.js?efeb:4090
invokeInsertHook @ vue.esm.js?efeb:5864
patch @ vue.esm.js?efeb:6083
Vue._update @ vue.esm.js?efeb:2637
updateComponent @ vue.esm.js?efeb:2765
get @ vue.esm.js?efeb:3115
Watcher @ vue.esm.js?efeb:3104
mountComponent @ vue.esm.js?efeb:2772
Vue$3.$mount @ vue.esm.js?efeb:8429
Vue$3.$mount @ vue.esm.js?efeb:10790
Vue._init @ vue.esm.js?efeb:4570
Vue$3 @ vue.esm.js?efeb:4659
(anonymous) @ main.js?1c90:11
./src/main.js @ app.js:3170
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:3291
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
asyncToGenerator.js?7b11:20 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by kroitor** [comment] 2018-02-23 23:38
```JavaScript
const b = new bittrex();
b.proxy = process.env.CORS_PROXY_URL;
b.enableRateLimit = true; // ←--------------------------  ADD THIS

export default {
  data() {
    return {
      running: false,  // ←--------------------------  CHANGE THIS
      index: 1
    };
  },

  //  ↓↓↓ TRY THIS ↓↓↓

  mounted() { 
    this.running = true;
    setTimeout(async () => {
        while (this.running) {  
            console.log(`Calling API ${this.index++} time`);
            const result = await b.fetchTickers();  // ←--------------------------  CHANGE THIS
            console.log ('Fetched:', Object.keys (result))  // ←------------------  ADD THIS
        }
    }, 0);
  },

  beforeDestroy() {
    this.running = false; // ←---------------- CHANGE THIS
  }
};
```

↑ Does it work this way?

**Comment by Burtonium** [comment] 2018-02-23 23:45
It doesn't. It failed on the 19th fetch. It seems rather intermittent. 
Here's a sample of the 18th and 19th calls.

```
Calling API 18 time
History.vue?0caa:24 Fetched: 1ST/BTC,2GIVE/BTC,ABY/BTC,ADA/BTC,ADT/BTC,ADX/BTC,AEON/BTC,AGRS/BTC,AMP/BTC,ANT/BTC,ARDR/BTC,ARK/BTC,AUR/BTC,BAT/BTC,BAY/BTC,BCH/BTC,BCPT/BTC,BCY/BTC,BITB/BTC,BLITZ/BTC,BLK/BTC,BLOCK/BTC,BNT/BTC,BRK/BTC,BRX/BTC,BSD/BTC,BTG/BTC,BURST/BTC,BYC/BTC,CANN/BTC,CFI/BTC,CLAM/BTC,CLOAK/BTC,CLUB/BTC,COVAL/BTC,CPC/BTC,CRB/BTC,CRW/BTC,CURE/BTC,CVC/BTC,DASH/BTC,DCR/BTC,DCT/BTC,DGB/BTC,DMD/BTC,DNT/BTC,DOGE/BTC,DOPE/BTC,DTB/BTC,DYN/BTC,EBST/BTC,EDG/BTC,EFL/BTC,EGC/BTC,EMC/BTC,EMC2/BTC,ENG/BTC,ENRG/BTC,ERC/BTC,ETC/BTC,ETH/BTC,EXCL/BTC,EXP/BTC,FAIR/BTC,FCT/BTC,FLDC/BTC,FLO/BTC,FTC/BTC,GAM/BTC,GAME/BTC,GBG/BTC,GBYTE/BTC,GCR/BTC,GEO/BTC,GLD/BTC,GNO/BTC,GNT/BTC,GOLOS/BTC,GRC/BTC,GRS/BTC,GUP/BTC,HMQ/BTC,IGNIS/BTC,INCNT/BTC,INFX/BTC,IOC/BTC,ION/BTC,IOP/BTC,KMD/BTC,KORE/BTC,LBC/BTC,LGD/BTC,LMC/BTC,LSK/BTC,LTC/BTC,LUN/BTC,MAID/BTC,MANA/BTC,MCO/BTC,MEME/BTC,MER/BTC,MLN/BTC,MONA/BTC,MUE/BTC,MUSIC/BTC,NAV/BTC,NBT/BTC,NEO/BTC,NEOS/BTC,NLG/BTC,NMR/BTC,NXC/BTC,NXS/BTC,NXT/BTC,OK/BTC,OMG/BTC,OMNI/BTC,PART/BTC,PAY/BTC,PDC/BTC,PINK/BTC,PIVX/BTC,PKB/BTC,POT/BTC,POWR/BTC,PPC/BTC,PTC/BTC,PTOY/BTC,QRL/BTC,QTUM/BTC,QWARK/BTC,RADS/BTC,RBY/BTC,RCN/BTC,RDD/BTC,REP/BTC,RLC/BTC,SALT/BTC,SBD/BTC,SC/BTC,SEQ/BTC,SHIFT/BTC,SIB/BTC,SLR/BTC,SLS/BTC,SNRG/BTC,SNT/BTC,SPHR/BTC,SPR/BTC,SRN/BTC,START/BTC,STEEM/BTC,STORJ/BTC,STRAT/BTC,SWIFT/BTC,SWT/BTC,SYNX/BTC,SYS/BTC,THC/BTC,TIX/BTC,TKS/BTC,TRST/BTC,TRUST/BTC,TX/BTC,UBQ/BTC,UKG/BTC,UNB/BTC,VEE/BTC,VIA/BTC,VIB/BTC,VOX/BTC,VRC/BTC,VRM/BTC,VTC/BTC,VTR/BTC,WAVES/BTC,WAX/BTC,WINGS/BTC,XCP/BTC,XDN/BTC,XEL/BTC,XEM/BTC,XLM/BTC,XMG/BTC,XMR/BTC,XMY/BTC,XRP/BTC,XST/BTC,XVC/BTC,XVG/BTC,XWC/BTC,XZC/BTC,ZCL/BTC,ZEC/BTC,ZEN/BTC,ZRX/BTC,1ST/ETH,ADA/ETH,ADT/ETH,ADX/ETH,ANT/ETH,BAT/ETH,BCH/ETH,BCPT/ETH,BNT/ETH,BTG/ETH,CFI/ETH,CRB/ETH,CVC/ETH,DASH/ETH,DGB/ETH,DNT/ETH,ENG/ETH,ETC/ETH,FCT/ETH,GNO/ETH,GNT/ETH,GUP/ETH,HMQ/ETH,LGD/ETH,LTC/ETH,LUN/ETH,MANA/ETH,MCO/ETH,NEO/ETH,NMR/ETH,OMG/ETH,PAY/ETH,POWR/ETH,PTOY/ETH,QRL/ETH,QTUM/ETH,RCN/ETH,REP/ETH,RLC/ETH,SALT/ETH,SC/ETH,SNT/ETH,SRN/ETH,STORJ/ETH,STRAT/ETH,TIX/ETH,TRST/ETH,UKG/ETH,VEE/ETH,VIB/ETH,WAVES/ETH,WAX/ETH,WINGS/ETH,XEM/ETH,XLM/ETH,XMR/ETH,XRP/ETH,ZEC/ETH,ZRX/ETH,ADA/USDT,BCH/USDT,BTC/USDT,BTG/USDT,DASH/USDT,ETC/USDT,ETH/USDT,LTC/USDT,NEO/USDT,NXT/USDT,OMG/USDT,XMR/USDT,XRP/USDT,XVG/USDT,ZEC/USDT
History.vue?0caa:22 Calling API 19 time
Exchange.js?3c9e:274 GET https://arb-bot-burtonium.c9users.io:8082/https://bittrex.com/api/v1.1/public/getmarketsummaries net::ERR_CONTENT_LENGTH_MISMATCH
executeRestRequest @ Exchange.js?3c9e:274
fetch @ Exchange.js?3c9e:359
fetch2 @ Exchange.js?3c9e:368
async function (async)
fetch2 @ Exchange.js?3c9e:369
request @ bittrex.js?0930:728
partial @ Exchange.js?3c9e:321
fetchTickers @ bittrex.js?0930:321
async function (async)
fetchTickers @ bittrex.js?0930:338
_callee$ @ History.vue?0caa:23
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
setInterval (async)
mounted @ History.vue?0caa:20
callHook @ vue.esm.js?efeb:2895
insert @ vue.esm.js?efeb:4090
invokeInsertHook @ vue.esm.js?efeb:5864
patch @ vue.esm.js?efeb:6083
Vue._update @ vue.esm.js?efeb:2637
updateComponent @ vue.esm.js?efeb:2765
get @ vue.esm.js?efeb:3115
Watcher @ vue.esm.js?efeb:3104
mountComponent @ vue.esm.js?efeb:2772
Vue$3.$mount @ vue.esm.js?efeb:8429
Vue$3.$mount @ vue.esm.js?efeb:10790
Vue._init @ vue.esm.js?efeb:4570
Vue$3 @ vue.esm.js?efeb:4659
(anonymous) @ main.js?1c90:11
./src/main.js @ app.js:3170
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:3291
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
asyncToGenerator.js?7b11:20 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by kroitor** [comment] 2018-02-24 00:22
@Burtonium in fact, it should not have failed at all, I mean, it should resume after a failure, did it continue polling?

**Comment by kroitor** [comment] 2018-02-24 00:24
Also, what does the proxy say?

**Comment by Burtonium** [comment] 2018-02-24 00:50
It continued polling, yes, sorry for the misunderstanding. I was just curious about the error and how to stop it from happening.

**Comment by Burtonium** [comment] 2018-02-24 00:51
Digging in the proxy atm to find more info. No errors are shown. I'm using cors-anywhere@0.4.1

**Comment by Burtonium** [comment] 2018-02-24 00:52
It's quite interesting that this seems to be limited to bittrex, also, if your initial suspicions are true.

**Comment by kroitor** [comment] 2018-02-24 01:09
> I was just curious about the error and how to stop it from happening.

First, you can't really stop it from happening, as sooner or later another error of a different type will happen, and in general, you don't "avoid" errors, you are prepared to "handle" them, namely, have some to handle the errors...

To me it now looks like Bittrex has a lower rate limit on fetchTickers. The higher the rateLimit, the more requests go through until you hit the exchange's limit. So, if you increase the delays between your poll-requests, you should eventually be able to find a rate that satisfies Bittrex. Also, you need to do some debugging on the proxy side to see the reason of failure.

**Comment by kroitor** [comment] 2018-03-17 01:58
@Burtonium i'd close this for now if you don't mind. The solution to this issue in general is to add the error handling code that would catch a network error and issue a new request / retry / attempt again... You can't totally eliminate all networking errors, and for exact reasons (be it request collisions on the proxy side, or whatever), you need to debug your HTTP messaging with verbose mode and excessive logging. Unfortunately, we can't really do this for you without having full access to all your systems. Feel free to reopen it if needed or just ask questions if any, we will be happy to help where possible.

**Closed by kroitor** 2018-03-17 01:58 UTC
Labels: question
