### ISSUE TITLE
Coinbase Pro, Coinbase Prime: fetchDepositAddress errors with 403 with correct keys

### ISSUE THREAD

**Issue by hrharder** [ccxt/ccxt#5843] opened 2019-09-20 18:52 UTC
## Overview

Unable to fetch a deposit address with JS `ccxt.coinbaseprime.prototype.fetchDepositAddress` (the ticker used is `"ETH"`).

Withdrawals work, as well as balance fetching, so the API keys are correct and authenticated.

## Details

- OS: `darwin` (MacOS v10.13)
- Programming Language version: `Node.js LTS` (v10.15)
- CCXT version: `v1.18.1166`
- Exchange: `Coinbase Prime`
- Method: `.fetchDepositAddress` (param: `"ETH"`)

## Error output
_The below output was generated after successfully performing a balance check, as well as a withdrawal of Ether, so the API keys are authenticated._

```
(node:26588) UnhandledPromiseRejectionWarning: ExchangeNotAvailable: coinbaseprime GET https://api.prime.coinbase.com/coinbase-accounts/b6ff3406-a066-5308-a6c4-0f429a30aa23/addresses 403 Forbidden {"message":"Forbidden"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at coinbaseprime.defaultErrorHandler (/Users/hen/GitHub/zaidan-liquidity/node_modules/ccxt/js/base/Exchange.js:586:19)
    at response.text.then (/Users/hen/GitHub/zaidan-liquidity/node_modules/ccxt/js/base/Exchange.js:629:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kroitor** [comment] 2019-09-20 19:44
@hrharder hi! Have you tried reaching out to their tech support on this issue? The endpoint in question is not documented, however, it is mentioned in their [official github repo](https://github.com/coinbase/coinbase-pro-node) (which points to pro for both pro and prime). Since it's not mentioned in the docs, it is not guaranteed to work. Unfortunately, Coinbase Prime restrictions are such that it does not allow me to sign up with their system to test on my side...

**Comment by hrharder** [comment] 2019-09-23 16:11
Hi @kroitor, thanks for the response! 

Thanks for checking that out, and it seems you're right, that endpoint is not documented for the prime API. We'll reach out to their support today and see if there is a new endpoint, or if fetching crypto deposit addresses is even possible with prime.

I can keep you updated here, if it is of interest.

**Comment by kroitor** [comment] 2019-09-23 16:50
@hrharder 

> I can keep you updated here, if it is of interest.

That would be awesome! Thx so much!

**Comment by karlandoh** [comment] 2019-11-06 13:34
This error has also been reproduced for me as well. I'll also be reaching out to support for any updates.

**Comment by ttodua** [comment] 2022-07-16 11:09
As last reference link (above) suggests, the issue was handled in that topic. Closing this topic for now. (btw, coinbase api might need rewrite in upcoming period)

**Closed by ttodua** 2022-07-16 11:09 UTC
