### ISSUE TITLE
Binance: amount_to_lots() overly precise

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1483] opened 2018-01-25 02:18 UTC
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.10.837
- Exchange: Binance
- Method: amount_to_lots()

I'm trying to buy 1.01 `ETH/USDT`. To avoid the `order amount should be evenly divisible by lot` error, I convert the order amount using `amount_to_lots()` before placing the order.

I've been trying to follow this issue: https://github.com/ccxt/ccxt/issues/663, but I'm not sure to understand the conclusion. Should I even call `amount_to_lots()` before my order, or should I just make sure that the order amount is not below the lot size?

In this case, CCXT tells me that the lot size for `ETH/USDT` is 1e-05 (which is suspiciously small). As a result, the output of `amount_to_lots()` is 1.0099. Ordering 1.0099 `ETH/USDT` works but it only fills 1.0098 without any errors or warning.
![screenshot 2018-01-24 21 12 00](https://user-images.githubusercontent.com/1474114/35367375-fefea490-014b-11e8-9823-2434f546bcf7.png)

When I skip `amount_to_lots()` and directly order 1.01 ETH/USDT, it works. This confirms my assumption that the lot size is incorrect.
![screenshot 2018-01-24 21 16 01](https://user-images.githubusercontent.com/1474114/35367389-06684cc2-014c-11e8-87e9-3f7e792e1c59.png)

**Comment by fredfortier** [comment] 2018-01-25 02:51
According to this: https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule, the minimum order amount is 0.00001 which explains the `lots` value. These min amount numbers seem disproportionally low for USDT markets. It does not say anything about being an actual lot so I'll change my business logic to remove `amount_to_lots()` and treat the lot value as a min amount. Do I understand this correctly? Is this going to be an issue with other exchanges?

**Comment by kroitor** [comment] 2018-01-25 03:02
Hi!

> According to this: https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule, the minimum order amount is 0.00001 which explains the lots value. 

That link is outdated! The actual logic of their filters is described here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters

> It does not say anything about being an actual lot so I'll change my business logic to remove amount_to_lots() and treat the lot value as a min amount. Do I understand this correctly?

It isn't a min amount, it is the **lot size**.

- When dealing with min amount: your amount should be greater than the minimum and that's it. So, the rule is `amount > min == true`.
- When dealing with lot sizes, the amount should be evenly divisible by lot size, which makes it equal to or greater than the lot size automatically. So, the rule is `amount % lot = 0` ("modulo" remainder)

> Is this going to be an issue with other exchanges?

The same is natural with most of exchanges. The difference with them is that they just have very small lot sizes (equal to the minimal noticeable step). You may want to check HitBTC as well.

> In this case, CCXT tells me that the lot size for ETH/USDT is 1e-05 (which is suspiciously small). As a result, the output of amount_to_lots() is 1.0099. When I skip amount_to_lots() and directly order 1.01 ETH/USDT, it works. This confirms my assumption that the lot size is incorrect.

This indicates a bug in the amount_to_lots, but the lot size should be correct. Will look into it and will get back to you.

**Comment by fredfortier** [comment] 2018-01-25 03:05
Okay I see it now, thanks for the link.

**Comment by mkutny** [comment] 2018-01-26 12:29
```
> Math.floor(1.01 / 0.0001) * 0.0001
1.01
> Math.floor(1.01 / 0.00001) * 0.00001
1.0099900000000002
```

**Comment by fredfortier** [comment] 2018-01-27 21:25
Did you guys have a chance to look into this? Please let me know if I can do anything to help.

**Comment by kroitor** [comment] 2018-01-28 03:43
@fredfortier yep, fixing it now. The problem is decoupling the truncation logic, fixing it and making it work seamlessly and universally for all exchanges, but we are almost there... Thanks for your patience!

**Comment by mkutny** [comment] 2018-01-28 05:40
Wonder, how it will be fixed. Made several attempts with floats but had no luck until switched to arbitrary precision math.

**Comment by kroitor** [comment] 2018-01-28 06:23
@mkutny we are making an all-in-one prototype function for this, and will add modules (in C, precompiled for speed) for Node.js and Python later.

```JavaScript
// /*  ------------------------------------------------------------------------ */

// const toPrecision = (x, { round = true, digits = 8, fixed = true })
//        => round ? roundNumber (x, { digits, fixed })
//                 : truncNumber (x, { digits, fixed })

```

https://github.com/ccxt/ccxt/blob/master/js/base/functions/number.js

**Comment by kroitor** [comment] 2018-01-28 11:00
@fredfortier a quick workaround would be to not apply amount_to_lots with Binance, as it has a proper implementation inside it, that does .amount_to_string ('ETH/USDT', 1.01) and returns a fixed-point result, which is perfectly fine for Binance API.

```Python
import ccxt
b = ccxt.binance()
b.load_markets()
b.amount_to_string('ETH/USDT', 1.01)
```

So, if you are doing this:

```
binance.create_order('ETH/USDT', 'limit', 'buy', binance.amount_to_lots ('ETH/USDT', 1.01), price, params)
```

Then do this instead with Binance:

```
binance.create_order('ETH/USDT', 'limit', 'buy', 1.01, price, params)
```

Should work normally like that. That is, until we fix the amount_to_lots, or offer a better alternative with arbitrary precision as discussed on this issue. Let me know if the above workaround helps you or not. Thx!

**Comment by kroitor** [comment] 2018-01-31 11:28
Related work: #1635

**Comment by fredfortier** [comment] 2018-02-01 02:42
Thanks for the workaround. This is a bit of an issue for me because I need to know about any amount adjustment before placing an order for tracking purposes. If one tries to order 1.001ETH, and `create_order` automatically adjusts it `ETH`, that's not an issue but I need to know synchronously. That's why I called `amount_to_lots()` before `create_order()`. That being said, I'll push the workaround a bit further to solve my problem. Do you have a sense of when you might release the #1635 branch?

**Comment by kroitor** [comment] 2018-02-01 07:24
> Do you have a sense of when you might release the #1635 branch?

A few days.

>  Is it safe to assume that the amount attribute will always be in this dict and correspond to the actual order amount on the exchange?

Currently, no. It is safe to assume that fields described in the Manual for the createOrder response will be there (namely, the order id), but we are going to extend the return to give back a full order structure (so, more fields will be added). More about it here: 
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- related: https://github.com/ccxt/ccxt/issues/1445
- related: https://github.com/ccxt/ccxt/issues/1518

**Comment by kroitor** [comment] 2018-02-01 08:32
@fredfortier however, as you may have noticed, we always return the `info` field that contains the reply from the exchange **as is, untouched**, so you can use it to extract all necessary info from all unified calls. The `info` field is present in all structures returned by the exchange. That is, until we unify them all completely. Also, some exchanges already implement the logic of returning a full order structure from createOrder (like, HitBTC, for example, and some others). So, this is, again, a work in progress.

**Comment by vlad-tokarev** [comment] 2018-05-14 11:01
It seems that my problem is similar. But I not found in ccxt source code tools to solve that problem.
Bithumb exchange require that price be multiple of some integer number. For example: 100, 500 (!!!), 1000 and so on.
As I can understand methods **price_to_precision** and **amount_to_precision** can not be helpful there.
It be nice if someone could give me advice in terms of ccxt architecture...

**Closed** 2018-08-05 18:25 UTC
