### ISSUE TITLE
[New exchange] Binance TR

### ISSUE THREAD

**Issue by kerimSD** [ccxt/ccxt#17183] opened 2023-03-15 07:07 UTC
### Exchange Name

Binance TR

### URL of the Exchange

https://www.trbinance.com/

### URL of the Exchange's API docs

https://www.trbinance.com/apidocs/

### Why should this exchange be implemented?

ccxt already implemented Binance, Binance US and Binance Futures. But there is also thousand of users on Binance TR which is the Binance in Turkey. I think It would be nice to have Binance TR on ccxt too.

**Comment by ttodua** [comment] 2024-06-10 14:48
duplicate of https://github.com/ccxt/ccxt/issues/8122

**Closed by ttodua** 2024-06-10 14:48 UTC
Labels: new exchange
