### ISSUE TITLE
Binance: Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#936] opened 2017-12-22 13:20 UTC
I modified returned responses in Exchange.php to get more information. This is what i get:

> Error when loading details: binance GET https://api.binance.com/api/v3/account?timestamp=1513948454747&signature=xxxxxxxxxxxx 
> 
> 400 not accessible from this location at the moment
> 
> {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

**Comment by kroitor** [comment] 2017-12-22 23:48
Hi! Do you have internet time synchronization enabled in your system clock settings?

**Comment by paroxysm** [comment] 2017-12-23 01:06
I'm also seeing this error on my end. I'm running on an ubuntu VM and yes, time sync is enabled.

**Comment by shprink** [comment] 2017-12-23 07:54
MacOS here and I have the same problem. My time is sync as well

**Comment by janeCMD** [comment] 2017-12-23 09:56
Yes, my time is sync as well.

**Comment by kroitor** [comment] 2017-12-23 18:21
Does this work for you, guys:

```Javascript
// JavaScript
;(async () => {
    balance = await binance.fetchBalance ({'recvWindow': 1000000})
    console.log (balance)
}) ();
```

```Python
# Python
balance = binance.fetch_balance({'recvWindow': 1000000})
print(balance)
```

```PHP
// PHP
$binance->verbose = true;
$balance = $binance->fetch_balance ({'recvWindow': 10000000});
var_dump ($balance);
```

?

**Comment by paroxysm** [comment] 2017-12-23 18:57
Yes this works. It's strange that you need such a huge window for their API. Something's strange going on there...

**Comment by kroitor** [comment] 2017-12-23 19:04
@paroxysm apparently, they have time synch issues with their server themselves. The code for Binance hasn't changed recently, so if they stopped working suddenly because of timing issues, it means their service is experiencing trouble. 

I notified their team, they usually respond quickly. I guess, they are aware and are working on this already. If you don't mind, I would close this issue for now, because the reason is now mostly obvious.

I will update you here, when we have a followup on this from Binance. For now, we can't workaround this issue, if their own time-synch is unstable. Let me know if I can help with anything else.

**Closed by kroitor** 2017-12-23 19:04 UTC
Labels: duplicate, question

**Comment by kroitor** [comment] 2017-12-24 09:22
From Binance:

```
Igor Kroitor, [23.12.17 21:24]
Hi, again! We're receiving reports of multiple timestamp-related errors from users who have time synch enabled, and who didn't have this problem with the same code previously. Most of the time "timestamp more than 1000ms ahead of server time" and "timestamp outside of recvWindow"... the 2nd one can probably be tackled by choosing a greater recvWindow, however, the first one is making us subtract a thousand from an otherwise-synchronized time... Is there a better way to solve these issues?

Ninj0r, [24.12.17 11:59]
Timestamp related issues on are on the users end. Synch your clocks (and keep them in sync) and you'll not have issues. Synching your clock is not a one time thing; clocks drift for a host of reasons and need to be repeatedly synced. This is why the default on ntpd is to sync clocks at least every 1024 s (17mins 4 seconds). If the user can't prove they synced their clock within that timeframe, I'm not going to investigate it.

Ninj0r, [24.12.17 12:01]
I'll look into this.

Igor Kroitor, [24.12.17 12:07]
they mostly set default time synch in windows 10

Igor Kroitor, [24.12.17 12:08]
(always on)

Ninj0r, [24.12.17 12:08]
Yeah, which typically does something like a time synch once a day if even that.
```

- http://www.thewindowsclub.com/change-internet-time-update-interval-windows
- https://technet.microsoft.com/en-us/library/cc773263(WS.10).aspx
- https://www.opentechguides.com/how-to/article/windows-10/121/windows-10-internet-time.html

Guys, from the above, I guess, it follows, that you need to change the frequency of your time synch updates (set smaller intervals for time polling). You can either do this by googling for it or with 3rd party software. Mac users can change their ntpd settings to alter the time synch params. Hope it helps.

**Comment by paroxysm** [comment] 2017-12-24 22:59
ok

**Comment by janeCMD** [comment] 2017-12-26 14:38
This helped me. i set sync to each 12 minutes, it work s now

**Comment by dmeffert** [comment] 2018-02-13 13:45
I added the following to my ntp.conf:
maxpoll 3
minpoll 3

But I still get the same recvWindow error. Is this the right way to increase the syncing frequency on OSX?

**Comment by kroitor** [comment] 2018-02-14 09:19
@dmeffert need to google for it, for example, see if this helps: https://apple.stackexchange.com/questions/117864/how-can-i-tell-if-my-mac-is-keeping-the-clock-updated-properly

**Comment by kamov** [comment] 2018-03-14 17:58
I get the same error.

What can be a correct value for timestamp? I know the format, but not when..

example:

['recvWindow' => 10000000, 'timestamp' => time() + 10000000 ]

right?

**Comment by kroitor** [comment] 2018-03-15 00:42
> What can be a correct value for timestamp?

You don't need to set it by hand at all. All you need is to create a new key and set up proper time synchronization on your machine to sync time once every 10 minutes.

> ['recvWindow' => 10000000, 'timestamp' => time() + 10000000 ]
> right?

Nope. The best solution would be to set up time synch and not override their defaults at all.

```
// JavaScript
;(async () => {
    binance.verbose = true
    balance = await binance.fetchBalance ({'recvWindow': 10000000}) // no override for timestamp
    console.log (balance)
}) ();
```

An alternative way would be to enable adjustments for the time difference:

```JavaScript
// JavaScript
let binance = new ccxt.binance ({
    'options': {
        'adjustForTimeDifference': true,
        'verbose': true, // if needed
    },
})
;(async () => {
    balance = await binance.fetchBalance ()
    console.log (balance)
}) ();
```

Hope it helps.

**Comment by pepsouille** [comment] 2018-09-27 21:16
Hello,

I am experiencing the same error. Can  anyone please explain me how  to synchronize my machine with the  server ? 
Thanks

**Comment by kroitor** [comment] 2018-09-27 21:30
@pepsouille the `nptd` daemon is often included in a Linux distribution, Ubuntu should have it installed by default, you just want to configure and enable it:

https://help.ubuntu.com/lts/serverguide/NTP.html.en

**Comment by joshuar87** [comment] 2019-02-23 11:27
Hi, I'm running linux mint (ubuntu) and after running ntpstat it show time accurate within 87ms. Polling server every 1024 s. Surely this is accurate enough? With reference to "error 1021. Timestamp out of recwindow'

**Comment by kroitor** [comment] 2019-02-23 12:48
> it shows time accurate within 87ms.

Within 87ms from what? From Binance time? ;)

> Surely this is accurate enough?

Accurate enough for what? ) You could have the most precise atomic clock on Earth – having a precise timer, but that doesn't necessarily mean that it's in sync with Binance. They have their own timer which may be different from yours and you have to adjust to it. The adjustment is done like shown here: https://github.com/ccxt/ccxt/issues/936#issuecomment-425247573

**Comment by fibo** [comment] 2019-12-30 18:37
Had the same issue, when running here in Italy it does not work, running the same code on a server in Virginia it works. Using the `adjustForTimeDifference` flag worked everywhere.

**Comment by vvvladimir758** [comment] 2020-08-14 17:32
working decision  is to add parameter  
recvWindow=60000 to the http request

https://api.binance.com/api/v3/account?recvWindow=60000&timestamp=1513948454747&signature=xxxxxxxxxxxx

> I modified returned responses in Exchange.php to get more information. This is what i get:
> 
> > Error when loading details: binance GET https://api.binance.com/api/v3/account?timestamp=1513948454747&signature=xxxxxxxxxxxx
> > 400 not accessible from this location at the moment
> > {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

**Comment by seroberto** [comment] 2020-11-23 07:41
Hello i buyed a website project from codecanyon but owner of project didnt reply me. I have just 1 problem about binance api. When i put my binance key and binance secret i got this error. 

binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

I cant see any balance on my website and I have a meeting 2 hours later about this website. I can give cpanel informations. I cant find where should i put your codes. Please someone help me this is very important meeting for me. Thank you

**Comment by kroitor** [comment] 2020-11-23 07:45
@seroberto hi! Unfortunately, we can't support the code that we don't write or maintain, especially, without the seeing the code itself. CCXT works in that regard and it is free for the users.

**Comment by seroberto** [comment] 2020-11-23 07:51
So just can you tell me which code can fix it and where should i put that code? 

binance-server-time.js
php-binance-api.php
etc.

**Comment by kroitor** [comment] 2020-11-23 07:53
@seroberto we are not the authors of the code you mentioned, so we can't physically guess how to fix it.

**Comment by seroberto** [comment] 2020-11-23 08:02
const binance = new ccxt['binance'] ()
const recvWindow = binance.security.recvWindow
const aheadWindow = 1000

--------------------------------------------------------------

$opt = [
            "symbol" => $symbol,
            "side" => $side,
            "type" => $type,
            "quantity" => $quantity,
            "recvWindow" => 60000,
        ];

------------------------------------------------------------

    'recvWindow' => 5 * 1000, // 5 sec, binance default

-------------------------------------------------------------

  'timestamp' => $this->nonce (),
  'recvWindow' => $this->options['recvWindow'],

-------------------------------------------------------------

Sorry for my questions but its really important for me. Should i fix anything one of the this parts?

**Comment by kroitor** [comment] 2020-11-23 08:08
@seroberto it's hard to help you without seeing the code, and we are not in charge of it, sorry.

Try changing this line:

```JavaScript
const binance = new ccxt['binance'] ()
```

↓

```JavaScript
const binance = new ccxt['binance'] ({ enableRateLimit: true, options: { adjustForTimeDifference: true }})
```

If that does not help – we won't be able to fix it for you, unfortunately.

**Comment by fibo** [comment] 2020-11-23 10:02
@seroberto it can happen if you used the same key on anither timezone, I read it also in the ccxt docs. For example I have two api keys on binance, one is used on the servers and one is used locally during development, otherwise if you use only one key the nonce could s main requirement that is to be an increasing sequence. In particular this happens if the timezones are different.

So probably your code works but the issue is on the api key nonce, you probably should use one key for development and one for production.

good luck!

**Comment by seroberto** [comment] 2020-11-25 10:35
@kroitor 

// PHP
$binance->verbose = true;
$balance = $binance->fetch_balance ({'recvWindow': 10000000});
var_dump ($balance);

when i use this code i got  this error for this line 

$balance = $binance->fetch_balance ({'recvWindow': 10000000});

**Syntax error, uxpected  '{'**

**Comment by seroberto** [comment] 2020-11-25 10:36
> @seroberto it can happen if you used the same key on anither timezone, I read it also in the ccxt docs. For example I have two api keys on binance, one is used on the servers and one is used locally during development, otherwise if you use only one key the nonce could miss its main requirement that is to be an increasing sequence. In particular this happens if the timezones are different.
> 
> So probably your code works but the issue is on the api key nonce, you probably should use one key for development and one for production.
> 
> good luck!

Hello. How did you get 2 api from binance? When i try to create i have only one choose for api on binance.

**Comment by kroitor** [comment] 2020-11-25 10:44
@seroberto Change it like so:

```PHP
$balance = $binance->fetch_balance();
```

However, if you are not familiar with the programming languages, you might run into another problem right away, since using this lib requires programming skills.

**Comment by fibo** [comment] 2020-11-25 10:57
> > @seroberto it can happen if you used the same key on anither timezone, I read it also in the ccxt docs. For example I have two api keys on binance, one is used on the servers and one is used locally during development, otherwise if you use only one key the nonce could miss its main requirement that is to be an increasing sequence. In particular this happens if the timezones are different.
> > So probably your code works but the issue is on the api key nonce, you probably should use one key for development and one for production.
> > good luck!
> 
> Hello. How did you get 2 api from binance? When i try to create i have only one choose for api on binance.

Hi,

for example I have two keys now, to add another one I see something like this, I just need to add a label and click create

<img width="678" alt="Screenshot 2020-11-25 at 11 54 25" src="https://user-images.githubusercontent.com/176730/100218691-59a90580-2f15-11eb-89ba-376db543f5f6.png">

**Comment by AbdullahChaudhry** [comment] 2021-06-02 15:57
I had the same problem on the Mac and turns out my firewall was blocking timed which is Apple's "Time Daemon".

I put it into the whitelist and the requests starting working again.

"Time Daemon" is a macOS system process that maintains system clock accuracy by synchronizing the clock with reference clocks via technologies like NTP.

**Comment by ilearnio** [comment] 2021-06-24 08:14
Force syncing time helped (MacOS)
```
sudo sntp -sS pool.ntp.org
```

**Comment by reason211** [comment] 2021-10-03 02:12
WINDOWS 11 synchronizes every 1 minute, but occasionally reports errors
