### ISSUE TITLE
PHP Binance withdrawable info

### ISSUE THREAD

**Issue by cryptonic203** [ccxt/ccxt#17630] opened 2023-04-21 18:37 UTC
### Operating System

WIndows

### Programming Languages

php

### CCXT Version

3.0.74

### Description

Hi.
It is required to write a cycle about the ability to withdraw for all coins from several exchanges.
At first I used fetchCurrencies(), but some exchanges do not support this array, for example, Binance, Bybit. And each exchange produces a different array structure.
How do I get the array structure by what function? =>[[Currency Structure](https://docs.ccxt.com/#/README?id=currency-structure)]
Maybe there is already a similar task?

Thank you for your help.

### Code

```
  

```

**Comment by cryptonic203** [comment] 2023-04-23 18:39
For Bybit  fetchCurrencies() starts working after adding APIKEYS:
```
$exchange_id = 'bybit';
$exchange_class = "\\ccxt\\$exchange_id";
$exchange = new $exchange_class (array (
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));
```
Another question: Why does the query only show 217 currencies when they claim there are over 300? It seems to me that it reflects only futures, but I could be wrong.
```
echo '<pre>';
var_dump($exchange->fetch_tickers());
echo '</pre>';
```

**Comment by sc0Vu** [comment] 2023-05-02 06:13
Hi @cryptonic203

For some exchange, we used private api for fetchCurrencies & fetchMarkets (it required api credentials).

Do you mean you only see tickers for future markets?

**Comment by cryptonic203** [comment] 2023-05-04 19:17
Hi, [sc0Vu](https://github.com/sc0Vu)
I don't know how to get information on withdrawing coins. The function fetchCurrencies() doesn't work correct. Shows NULL, and discrepancies across chains.
For example, the KUCOIN gives correct data, but GATEIO like this (cut out part).

```
  ["SOUL"]=>
  array(12) {
    ["id"]=>
    string(4) "SOUL"
        ["withdraw"]=>
    bool(true)
    ["fee"]=>
    NULL
```

How is it possible to get the correct data array for this question?

Thank you for your help.

**Comment by ttodua** [comment] 2023-09-11 14:40
duplicate of https://github.com/ccxt/ccxt/issues/19067

**Closed by ttodua** 2023-09-11 14:40 UTC
Labels: question
