### ISSUE TITLE
medatada for exchange to know if trading fee is inclusive (paid upfront) or not

### ISSUE THREAD

**Issue by tuloski** [ccxt/ccxt#9195] opened 2021-05-17 15:35 UTC
From what I saw in the generalized API, there is no information if the fee is paid upfront or not (I don't know if this is the correct term). 
Also the side (currency) in which the fee are paid is nowere (but less relevant maybe).
Also if the fee is/can be paid in a third currency, for example BNB in Binance.

Example: Balance: 100DAI. Order is: buy 100 USD from DAI @1. Symbol is DAI/USD. Fee is 0.1%.

-If the fee is paid upfront then 0.1 DAI are paid as fees and 99.9 USD are received.
-If the fee is not paid upfront, then the order will fail, because the account needs 100.1001001... DAI to receive the full 100 USD.

Even worst there are exchanges that this behavior depends on the side and the currency.
Maybe I'm missing it from the code and documentation, but the orders are recalculated inside ccxt to consider the fee always upfront or always not upfront.

**Comment by busbykt** [comment] 2021-08-15 20:50
The docs may help answer your question here:
https://ccxt.readthedocs.io/en/latest/manual.html#my-trades

They state:  
"The ``cost`` of the trade is a *"gross"* value. That is the value pre-fee, and the fee has to be applied afterwards."  

Can you use the trade information from `fetchMyTrades()` to perform the result net of fees that you are looking for?

**Comment by ttodua** [comment] 2024-10-28 19:57
duplicate of https://github.com/ccxt/ccxt/issues/5644

**Closed by ttodua** 2024-10-28 19:57 UTC
Labels: enhancement
