### ISSUE TITLE
HitBTCv2 ETC/BTC pair discrepancy

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#709] opened 2017-11-29 11:29 UTC
https://i.imgur.com/5kx53JM.png  <-- current status. (price around ~0.0027)
From ccxt:
```
             'ticker': {'ask': 0.003153,
                        'average': None,
                        'baseVolume': 5559.721,
                        'bid': 0.003152,
                        'change': None,
                        'close': None,
                        'datetime': '2017-11-28T12:16:07.300Z',
                        'first': None,
                        'high': 0.0033,
                        'info': {'ask': '0.003153',
                                 'bid': '0.003152',
                                 'high': '0.003300',
                                 'last': '0.003153',
                                 'low': '0.003014',
                                 'open': '0.003061',
                                 'symbol': 'ETCBTC',
                                 'timestamp': '2017-11-28T12:16:07.300Z',
                                 'volume': '5559.721',
                                 'volumeQuote': '17.189768819'},
                        'last': 0.003153,
                        'low': 0.003014,
                        'open': 0.003061,
                        'percentage': None,
                        'quoteVolume': 17.189768819,
                        'symbol': 'ETC/BTC',
                        'timestamp': 1511871367300,
                        'vwap': None}},
```

Something is fetching wrong with this thing.

**Comment by kroitor** [comment] 2017-11-29 11:53
Well, their reply is there, as is, unparsed (`info` field), ETCBTC is there, and the values are incorrect. Looks like they report it that way... I fetched it now and it says 
```
mbp:ccxt igorkroitor$ node examples/js/tickers.js hitbtc2 ETC/BTC
Instantiating hitbtc2 exchange exchange
hitbtc2 ETC/BTC ticker 2017-11-29T11:51:32.220Z high: 0.00345 low: 0.002648 bid: 0.002726 ask: 0.002736 volume: 122776.666
mbp:ccxt igorkroitor$ 
```

Is it repeatable on your side?

**Comment by nmiculinic** [comment] 2017-11-29 15:16
Yes, it's repeatable on my side.

**Comment by kroitor** [comment] 2017-11-29 15:17
@nmiculinic can you post a minimal code to reproduce it?

**Comment by nmiculinic** [comment] 2017-11-29 15:20
hmm, now numbers look alright...will keep an eye on this one and check again tomorrow.

**Comment by kroitor** [comment] 2017-11-29 15:28
@nmiculinic from your output it looks like they indeed replied with some weird prices, but that is not something we change inside ccxt, I mean the `info` field there is copied entirely as is, and it cannot get mixed with another ticker (no room for that anywhere inside the library), as you see, the symbol of ETCBTC is also there, indicating an erroneous return from HitBTC.

**Comment by nmiculinic** [comment] 2017-12-01 09:46
Yeah, I guess so...

I was busy lately; will check again sometime in the future what's the status of this one.

**Comment by kroitor** [comment] 2017-12-01 12:40
Ok, I'll close this for now if you don't mind, feel free to reopen it if needed. Thx!

**Closed by kroitor** 2017-12-01 12:40 UTC
