### ISSUE TITLE
Bitfinex watch_order_books() yields empty ask / empty bid randomly

### ISSUE THREAD

**Issue by Ricardus312** [ccxt/ccxt#8205] opened 2021-01-03 19:20 UTC
- OS: Windows
- Programming Language version: python 3.8.5
- CCXT version: 1.40.14
- CCXT pro version: 0.5.17

```
async def watch_book(exchange, symbol, limit):
    
        try: orderbook = await exchange.watch_order_book(symbol, limit)
        except asyncio.CancelledError: raise
        
        return orderbook['asks'], orderbook['bids']


async def ticks(exchange, symbol, limit=None):
        
        while True:
            try: book = await self.watch_book(exchange, symbol, limit)
            except asyncio.CancelledError: break
            except Exception as e: 
                # Handle exception
                pass
            else: 
                # POINT OF FAILURE: Do stuff with orderbook will fail for bitfinex randomly
                book[0][0]
                book[1][0]

```
IndexError('list index out of range')
```
The above code will fail for exchange='bitfinex' and symbol='BTC/USDT' after a while when trying to access the order book. Sometimes it yields an empty ask list, sometimes it yields an empty bid. It happens randomly each few minutes. Is this an expected behaviour?
```

**Comment by kroitor** [comment] 2021-01-03 19:22
@Ricardus312 how do you initialize the exchange instance?

**Comment by Ricardus312** [comment] 2021-01-03 19:38
```
exchange = getattr(ccxt, exchange_id)(self.exch_params)
await exchange.load_markets()
await exchange.watch_order_book(symbol, limit)
```
To make it simple on init all the exchanges are instantiated, manually call load_markets() and save objects on a dict. Then, to start web sockets I do a first call to watch_order_books, and after that it starts the main real time loop.

**Comment by kroitor** [comment] 2021-01-03 19:40
@Ricardus312 what is the value of `limit` in your snippet?, what's included in `exch_params` ? (except the keys).

**Comment by Ricardus312** [comment] 2021-01-03 19:42
I'm using the default limit=None

**Comment by Ricardus312** [comment] 2021-01-03 19:46
Just in case I haven't explained this clearly: it does not yield both ask and bid empty list, it is only one of them: sometimes it is the bid, sometimes it is the ask. Here is a print of my program right now:

```
IndexError('list index out of range')
bitfinex
asks []
bids [[32881, 1.1301, 3], [32880, 0.4498, 3], [32877, 0.21297, 2], [32876, 0.49163946, 2], [32875, 0.4912, 2], [32873, 0.93187356, 2], [32872, 0.06345275, 1], [32871, 0.0915, 1], [32869, 0.13582, 1], [32868, 0.31637301, 1], [32867, 0.1921, 2], [32864, 0.69724078, 4], [32863, 0.0908, 1], [32862, 0.17504, 1], [32860, 0.0917, 1], [32857, 0.1415, 1], [32856, 0.00361165, 1], [32855, 0.09781747, 2], [32854, 0.5938174, 2], [32852, 0.0908, 1], [32851, 0.50629864, 1], [32848, 0.6693707, 2], [32844, 0.72320853, 2], [32843, 0.0002, 1]]
```

Thank you very much for your help

**Comment by kroitor** [comment] 2021-01-03 19:48
@Ricardus312 ok, we will debug this and will get back to you shortly. In the meantime, do you have an issue with this snippet:

```
@Ricardus312 do you have an issue with this complete snippet (running just this code and nothing else):


```Python
import ccxtpro
from asyncio import get_event_loop

print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    exchange = ccxtpro.bitfinex({
        'enableRateLimit': True
    })
    markets = await exchange.load_markets()
    # exchange.verbose = True  # uncomment for debugging purposes
    while True:
        try:
            orderbook = await exchange.watch_order_book('BTC/USDT')
            print(orderbook['bids'][0], orderbook['asks'][0])
        except Exception as e:
            print(type(e).__name__, str(e))
            break
    await exchange.close()


loop = get_event_loop()
loop.run_until_complete(main())
```

↑ If you don't have an issue with it, but do have an issue with some other code, please paste the complete code snippet to reproduce it (remove all irrelevant parts from it and paste it here, plz).

**Comment by Ricardus312** [comment] 2021-01-03 19:57
I have launched your snippet and is running along with my program. If it fails, I should be able to see the error in both of them.

I will tell you about the results.

Thanks.

**Comment by Ricardus312** [comment] 2021-01-03 20:42
Ok, your snippet has given the same error as my code does and they failed at the same time. The full traceback of your snippet is:
```

IndexError                                Traceback (most recent call last)
<ipython-input-3-ce025352c7c1> in main()
     17             orderbook['bids'][0]
---> 18             orderbook['asks'][0]
     19         except Exception as e:

d:\git\ccxt.pro\python\ccxtpro\base\order_book_side.py in __getitem__(self, item)
     67         else:
---> 68             return super(OrderBookSide, self).__getitem__(item)
     69 

IndexError: list index out of range
```

**Comment by kroitor** [comment] 2021-01-03 20:46
@Ricardus312 ok, if you could enable the verbose mode and reproduce it again and paste the verbose log at https://gist.github.com – it would help resolve it quicker. How much time did it take to produce the exception?

**Comment by Ricardus312** [comment] 2021-01-03 21:10
Here is the gist. I have cutted a bit the mid part of the log since it was repetitive. The error happens randomly each few minutes, you should be able to reproduce it after less than 30 minutes. If you need something else please tell me.

https://gist.github.com/Ricardus312/95d24b828d9509d38afbb1362f217945

**Comment by kroitor** [comment] 2021-01-03 21:47
@Ricardus312 weird, but it is running for more than an hour on my side without an issue. However, i'm running it on a *nix os in pure python, without iPython.

In your gist i've noticed that the output should be slightly different if you simply uncomment that verbose line in the snippet I posted above. Which makes think that you may be running some other code, that is slightly different from the code I posted. Is that the case? If yes, please, paste your snippet. Otherwise, it's hard to sync and reproduce it. The other two possible factors are: some differences related to the Windows OS/underlying connection, or some difference with iPython as a wrapper to it. We should rule out all possible differences in code first and foremost for a pure test. And if that does not help, we might need to test and compare to a different system if that is possible. I'd suggest making sure that our code is identical to yours.

**Comment by kroitor** [comment] 2021-01-03 21:50
I will also test on other machines, and will wind up a windows vpc to check that as well.

**Comment by Ricardus312** [comment] 2021-01-03 21:50
I just removed the print statements to avoid hitting the IOPub limit of the notebook and used a different print function to get the full traceback. This is the snippet as I run it (on Jupyter Notebook):

```
import ccxtpro
from asyncio import get_event_loop
import traceback

print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    exchange = ccxtpro.bitfinex({
        'enableRateLimit': True
    })
    markets = await exchange.load_markets()
    exchange.verbose = True  # uncomment for debugging purposes
    while True:
        try:
            orderbook = await exchange.watch_order_book('BTC/USDT')
            orderbook['bids'][0]
            orderbook['asks'][0]
        except Exception as e:
            traceback.print_exception(type(e), e, e.__traceback__)
            break
    await exchange.close()


await main()
```

**Comment by kroitor** [comment] 2021-01-03 21:52
@Ricardus312 do you by chance have an alternative machine / location to test from? I'll do my best to launch a Windows+iPython host and test asap.

**Comment by kroitor** [comment] 2021-01-03 21:54
@Ricardus312 just in case, what's your version of Jupyter?

**Comment by Ricardus312** [comment] 2021-01-03 21:59
Windows 10 Pro
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.1                      py_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.0.2            py37hf63ae98_0
jupyterlab_server         1.0.0                      py_0

I will run the snippet in a pure python script from the command line to see what happens.
I could also try this on an AWS EC2 instance (still Windows).
I'm starting to think that this could be something on the side of the exchange. It makes no sense that this happens randomly and then it runs again.

**Comment by Ricardus312** [comment] 2021-01-03 22:01
BTW my program is running 10 exchanges at the same time, and this is happening only with Bitfinex

**Comment by kroitor** [comment] 2021-01-03 22:01
@Ricardus312 it might be related to the way iPython invokes the asyncio loop, you can change the snippet slightly and see if it makes a difference in iPython:

```Python
import ccxtpro
from asyncio import get_event_loop
import traceback

print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    loop = get_event_loop()
    exchange = ccxtpro.bitfinex({
        'enableRateLimit': True
        'asyncio_loop': loop,
    })
    markets = await exchange.load_markets()
    exchange.verbose = True  # uncomment for debugging purposes
    while True:
        try:
            orderbook = await exchange.watch_order_book('BTC/USDT')
            orderbook['bids'][0]
            orderbook['asks'][0]
        except Exception as e:
            traceback.print_exception(type(e), e, e.__traceback__)
            break
    await exchange.close()


await main()
```

Your version of Jupyter seems old a bit, here they describe a few issues with asyncio invocations in iPython prior to 7.0: https://stackoverflow.com/questions/47518874/how-do-i-run-python-asyncio-code-in-a-jupyter-notebook ← could that be related?

**Comment by kroitor** [comment] 2021-01-03 22:03
@Ricardus312 

> I'm starting to think that this could be something on the side of the exchange.

If that would be the case, it would be the same for everyone and I would probably catch it already, unless it depends on your location. Which is why trying a different host/location would make sense to rule that out.

**Comment by Ricardus312** [comment] 2021-01-03 22:20
From command line, same thing happened, here is the gist with the full log:

**Comment by Ricardus312** [comment] 2021-01-03 22:23
I will try it on AWS

**Comment by kroitor** [comment] 2021-01-03 22:34
@Ricardus312 ok, no worries, i've caught it on my side as well, will debug and will get back to you asap!

**Comment by Ricardus312** [comment] 2021-01-04 23:57
I haven't seen again the error in the last 24 hours while debugging over ETH/USDT. I will switch again to BTC/USDT, and if it does not happen again I think we could consider this as caused by the exchange and close the issue.

**Comment by kroitor** [comment] 2021-01-05 00:01
@Ricardus312 

> I will switch again to BTC/USDT, and if it does not happen again I think we could consider this as caused by the exchange and close the issue.

It is caused by the exchange suddenly closing the socket connection under high load, like we saw yesterday upon BTC hitting the all-time high. So, I believe this is related to the load on their system, which makes it hard to reproduce. But it should not throw an IndexError, so we will add some fixes to handle that properly.

**Closed** 2021-01-09 11:06 UTC
Labels: ccxt.pro, question
