### ISSUE TITLE
CCXT php error: hex2bin(): Input string must be hexadecimal string

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#6307] opened 2019-12-23 20:30 UTC
Hello

- OS: Windows/Lunix
- Programming Language version: PHP 7.2.19
- CCXT version: 1.19
- Exchange: IDEX
- Method: create_order

When i use the ccxt php library to create an idex order it return this error:
```
 ErrorException  : hex2bin(): Input string must be hexadecimal string

  at E:\xxxx\www\xxxxxx\vendor\ccxt\ccxt\php\base\Exchange.php:2740
    2736|         ));
    2737|     }
    2738| 
    2739|     public static function hashMessage($message) {
  > 2740|         $buffer = unpack('C*', hex2bin($message));
    2741|         $prefix = bin2hex("\u{0019}Ethereum Signed Message:\n" . sizeof($buffer));
    2742|         return '0x' . Keccak::hash(hex2bin($prefix . $message), 256);
    2743|     }
    2744| 

  Exception trace:

  1   hex2bin("0xffffffffffffffffffffffffffffffffff......................")
      E:\xxxx\www\xxxxxx\vendor\ccxt\ccxt\php\base\Exchange.php:2740

  2   ccxt\Exchange::hashMessage("0xffffffffffffffffffffffffffffffffffff...........")
      E:\xxxx\www\xxxxxx\vendor\ccxt\ccxt\php\base\Exchange.php:2755

```
can you help me please

**Comment by kroitor** [comment] 2019-12-23 20:32
@mustapha1509 can you post a short but a complete snippet of code to reproduce it? (make it as short as possible and remove all irrelevant parts leaving just the bare minimum, without your keys, of course)

**Comment by mustapha1509** [comment] 2019-12-23 20:50
```
 public function __construct()
    {
        $this->idex = new \ccxt\idex(array(
            'apiKey' => config('api.idex.api_key'),
            'walletAddress' => config('api.idex.wallet_address'),
            'privateKey' => config('api.idex.private_key'),
        ));

        parent::__construct();
    }


    public function make_idex_order($order){
        if($order->amount<25000){
            $crypto = $this->get_crypto($order->instrument);

            if($crypto == "IDEX"){
                $symbol = "IDEX/ETH";
                try{
                    $response = $this->idex->create_order($symbol, 'limit','buy', $order->tokens, $order->price);
                    if($response){
                        $this->info('+++ Idex order created');
                    }
                }catch (Exception $e){
                    $this->error($e->getMessage());
                }
            }
        }

    }
```

**Comment by kroitor** [comment] 2019-12-23 20:57
@mustapha1509 we will need some time to reproduce it on our side and debug it, will get back to you asap

**Comment by mustapha1509** [comment] 2019-12-23 20:59
Thank you, I await your response.

**Comment by frosty00** [comment] 2019-12-24 04:14
its probably because you have "0x" at the front of your apiKey, does it work if you remove the "0x" prefix?

**Comment by kroitor** [comment] 2019-12-24 08:36
@mustapha1509 this should be fixed in the most recent version 1.21.15. Let us know if you still have issues with it. Thx for reporting!

**Comment by mustapha1509** [comment] 2019-12-24 19:25
Sorry, Now I have this error
``` 
Exception  : Invalid characters

  at E:\laragon\www\api-peculium\vendor\ccxt\ccxt\php\static_dependencies\BI\BigInteger.php:328
    324|             }
    325|             if ($base == 16) {
    326|                 $value = str_replace(" ", "", $value);
    327|                 if (!BigInteger::checkHex($value)) {
  > 328|                     throw new \Exception("Invalid characters");
    329|                 }
    330|                 $minus = $value[0] == "-";
    331|                 if ($minus) {
    332|                     $value = substr($value, 1);

  Exception trace:

  1   BI\BigInteger::getBC("0x8a1495cdc051e5faee17d52f1ee76d737ba170c7e702472b6fa644bd2403c3d0")
      E:\laragon\www\api-peculium\vendor\ccxt\ccxt\php\static_dependencies\BI\BigInteger.php:245

  2   BI\BigInteger::__construct("0x8a1495cdc051e5faee17d52f1ee76d737ba170c7e702472b6fa644bd2403c3d0")
      E:\laragon\www\api-peculium\vendor\ccxt\ccxt\php\static_dependencies\BN\BN.php:45

  Please use the argument -v to see more details.
```

**Comment by frosty00** [comment] 2019-12-25 12:51
unfortunately i cannot reproduce your error, are you sure you are on the latest version?

**Comment by kroitor** [comment] 2019-12-25 13:09
@mustapha1509 a verbose output would also help (set `$exchange->verbose = true;` before issuing the failing call and dump the output here, without your keys), or, alternatively, plz post the values used for placing the order.

**Comment by frosty00** [comment] 2019-12-26 12:07
sorry @mustapha1509 I had gmp installed so it wasn't using bcmath. check again the fix should be here )

**Closed** 2019-12-26 12:16 UTC
