### ISSUE TITLE
Bybit JS returns inverse price in "average" for BTCUSD limit orders. 

### ISSUE THREAD

**Issue by furryboffin** [ccxt/ccxt#11159] opened 2022-01-07 11:52 UTC
- OS: linux ubuntu
- Programming Language version: node js : v17.3.0
- CCXT version: 1.66.33

I'm using the current version as you can see. When placing limit orders on BTCUSD perpetual inverse swap, I started getting this problem ( Oddly, this used to be an older problem on the USDT markets ).

The returned order details contain .average which is set to the inverse of .price. Below is an example filled order where this happened:
"average":0.000310173604651162
"price":3224

I am writing a workaround, but I'm not sure if there are any cases where the average is correct. i.e. if a limit order is moved while it's partially filled and then completes filling at a different price?

Could we somehow try to set the average to the price for when a limit order fills entirely at one price?

```
{"info":{"user_id":"541820","position_idx":"0","symbol":"ETHUSD","side":"Buy","order_type":"Limit","price":"3224","qty":"86","time_in_force":"GoodTillCancel","order_status":"Filled","ext_fields":{"o_req_num":"35400335"},"last_exec_time":"1641553113.4685388","last_exec_price":"3224","leaves_qty":"0","leaves_value":"0","cum_exec_qty":"86","cum_exec_value":"0.02667493","cum_exec_fee":"-0.00000666","reject_reason":"EC_NoError","cancel_type":"UNKNOWN","order_link_id":"","created_at":"2022-01-07T10:46:26.523569046Z","updated_at":"2022-01-07T10:58:33.468539Z","order_id":"23ca1fe3-fbe1-4b3a-b84f-5e4ff0ccfdd8","take_profit":"0.00","stop_loss":"0.00","tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"id":"23ca1fe3-fbe1-4b3a-b84f-5e4ff0ccfdd8","timestamp":1641552386523,"datetime":"2022-01-07T10:46:26.523Z","lastTradeTimestamp":1641553113468,"symbol":"ETH/USD","type":"limit","timeInForce":"GTC","postOnly":false,"side":"buy","price":3224,"amount":86,"cost":0.02667493,"average":0.000310173604651162,"filled":86,"remaining":0,"status":"closed","fee":{"cost":0.00000666,"currency":"ETH"},"trades":[],"fees":[{"cost":0.00000666,"currency":"ETH"}]}
```

**Comment by furryboffin** [comment] 2022-02-03 04:21
We seem to have stalled on this issue. Let me know if I could maybe be of assistance.

**Comment by Dan-krm** [comment] 2022-05-20 05:27
> We seem to have stalled on this issue. Let me know if I could maybe be of assistance.

Hi, I can look into this. Can you tell me what method you're using that returns this data?

**Comment by ttodua** [comment] 2022-07-30 17:53
@furryboffin can you please check if such issue still persists? the very strange thing I see in response, is that `cum_exec_value` was `0.02667493` in your response. can you tell, did that correspond to any part of your order (visible in UI).

**Comment by ttodua** [comment] 2022-07-30 18:59
I think we have reproduced the issue and will submit the PR whenever we have a fix.

**Comment by Dan-krm** [comment] 2024-01-17 05:50
Closing this issue because it looks like this issue was resolved when bybit was updated to v5:
```
bybit.createOrder (BTC/USD:BTC, limit, buy, 1, 35000)
2024-01-17T05:36:14.825Z iteration 0 passed in 1502 ms

{
  info: { orderId: 'd30c4f57-5b97-4c3a-aadd-42807723c0a8', orderLinkId: '' },
  id: 'd30c4f57-5b97-4c3a-aadd-42807723c0a8',
  symbol: 'BTC/USD:BTC',
  trades: [],
  fees: []
}
```
```
bybit.fetchOrder (d30c4f57-5b97-4c3a-aadd-42807723c0a8, BTC/USD:BTC)
2024-01-17T05:36:59.385Z iteration 0 passed in 958 ms

{
  info: {
    orderId: 'd30c4f57-5b97-4c3a-aadd-42807723c0a8',
    orderLinkId: '',
    blockTradeId: '',
    symbol: 'BTCUSD',
    price: '35000.00',
    qty: '1',
    side: 'Buy',
    isLeverage: '',
    positionIdx: '0',
    orderStatus: 'New',
    cancelType: 'UNKNOWN',
    rejectReason: 'EC_NoError',
    avgPrice: '0',
    leavesQty: '1',
    leavesValue: '0.00002857',
    cumExecQty: '0',
    cumExecValue: '0',
    cumExecFee: '0',
    timeInForce: 'GTC',
    orderType: 'Limit',
    stopOrderType: 'UNKNOWN',
    orderIv: '',
    triggerPrice: '0.00',
    takeProfit: '0.00',
    stopLoss: '0.00',
    tpTriggerBy: 'UNKNOWN',
    slTriggerBy: 'UNKNOWN',
    triggerDirection: '0',
    triggerBy: 'UNKNOWN',
    lastPriceOnCreated: '0.00',
    reduceOnly: false,
    closeOnTrigger: false,
    smpType: 'None',
    smpGroup: '0',
    smpOrderId: '',
    tpslMode: '',
    tpLimitPrice: '',
    slLimitPrice: '',
    placeType: '',
    createType: 'CreateByUser',
    createdTime: '1705469775691',
    updatedTime: '1705469775693'
  },
  id: 'd30c4f57-5b97-4c3a-aadd-42807723c0a8',
  timestamp: 1705469775691,
  datetime: '2024-01-17T05:36:15.691Z',
  lastTradeTimestamp: 1705469775693,
  lastUpdateTimestamp: 1705469775693,
  symbol: 'BTC/USD:BTC',
  type: 'limit',
  timeInForce: 'GTC',
  postOnly: false,
  reduceOnly: false,
  side: 'buy',
  price: 35000,
  amount: 1,
  cost: 0,
  filled: 0,
  remaining: 1,
  status: 'open',
  fee: { cost: '0', currency: 'BTC' },
  trades: [],
  fees: [ { cost: 0, currency: 'BTC' } ]
}
```
```
bybit.createOrder (BTC/USD:BTC, market, buy, 1)
2024-01-17T05:38:57.609Z iteration 0 passed in 1169 ms

{
  info: { orderId: '584c97ca-6995-4638-9f5b-65b970ee697b', orderLinkId: '' },
  id: '584c97ca-6995-4638-9f5b-65b970ee697b',
  symbol: 'BTC/USD:BTC',
  trades: [],
  fees: []
}
```
```
bybit.fetchPosition (BTC/USD:BTC)
2024-01-17T05:39:41.415Z iteration 0 passed in 743 ms

{
  info: {
    positionIdx: '0',
    riskId: '1',
    riskLimitValue: '150',
    symbol: 'BTCUSD',
    side: 'Buy',
    size: '1',
    avgPrice: '42844.90145673',
    positionValue: '0.00002334',
    tradeMode: '0',
    positionStatus: 'Normal',
    autoAddMargin: '0',
    adlRankIndicator: '2',
    leverage: '10',
    positionBalance: '0.00000235',
    markPrice: '42835.86',
    liqPrice: '100.00',
    bustPrice: '100.00',
    positionMM: '0.00005',
    positionIM: '0.00000023',
    tpslMode: 'Full',
    takeProfit: '0.00',
    stopLoss: '0.00',
    trailingStop: '0.00',
    unrealisedPnl: '0',
    cumRealisedPnl: '-0.00000002',
    seq: '5778668716',
    isReduceOnly: false,
    mmrSysUpdateTime: '',
    leverageSysUpdatedTime: '',
    createdTime: '1705469399514',
    updatedTime: '1705469938484'
  },
  symbol: 'BTC/USD:BTC',
  timestamp: 1705469982289,
  datetime: '2024-01-17T05:39:42.289Z',
  initialMargin: 0.000002333999999999,
  initialMarginPercentage: 0.09999999999995715,
  maintenanceMargin: 0,
  maintenanceMarginPercentage: 0,
  entryPrice: 42844.90145673,
  notional: 0.00002334,
  leverage: 10,
  contracts: 1,
  contractSize: 1,
  marginRatio: 0,
  liquidationPrice: 100,
  markPrice: 42835.86,
  collateral: 0.00000235,
  marginMode: 'cross',
  side: 'long',
  stopLossPrice: 0,
  takeProfitPrice: 0
}
```

**Closed by Dan-krm** 2024-01-17 05:50 UTC
Labels: bug, important
