### ISSUE TITLE
In bybit, fetch_order returns None

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#13818] opened 2022-06-13 08:54 UTC
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.85.51

```
import ccxt
bybit = ccxt.bybit({...})

symbol = 'GLMR/USDT:USDT'
result1 = bybit.create_order(symbol=symbol)
result2 = bybit.fetch_order(id=result1['id'], symbol=symbol)
print(result2)
```

```
None
```

**Comment by carlosmiei** [comment] 2022-06-13 11:13
Hello @kjnh10, can you please post a verbose output so that we can analyze the request and response?

**Comment by carlosmiei** [comment] 2022-06-13 11:14
@kjnh10 Actually I would start by updating the ccxt version I suspect that bug was fixed recently so updating it might solve your problem

**Comment by kjnh10** [comment] 2022-06-13 11:55
I has updated to 1.87.12, and it seems resolves this problem.

Thanks,

**Comment by carlosmiei** [comment] 2022-06-13 13:01
@kjnh10 Happy to hear it, since the issue is solved I'm going to close the issue.

**Closed by carlosmiei** 2022-06-13 13:01 UTC
