### ISSUE TITLE
kucoin  create_limit_buy_order LTC/ETH fails

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#1327] opened 2018-01-17 01:10 UTC
- OS: linux
- Programming Language version: python
- CCXT version: 1.10.738
- Exchange: kucoin
- Method:  create_limit_buy_order

I'm not sure if it's related to this task or not https://github.com/ccxt/ccxt/issues/1298, but I keep getting this error @ kucoin for LTC/ETH pair:

Traceback (most recent call last):
  File "ccwd.py", line 134, in PlaceOrder
    order = exch.create_limit_buy_order(symbol, trade_amount, price*limit_orders_percent)
  File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1016, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/kucoin.py", line 382, in create_order
    'id': self.safe_string(response['data'], 'orderOid'),
  File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 425, in safe_string
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] else default_value
TypeError: argument of type 'NoneType' is not iterable

Problem is that I can't catch if it price matters or not. But it worked @ 0.7 LTC/ETH, and it failed @ 0.4 LTC/ETH and 1.3 LTC/ETH

**Comment by kroitor** [comment] 2018-01-17 01:19
Hi! This issue a duplicate of [this](#1321). It would be helpful, if you could provide verbose output there. Closing this one for now. I suggest moving this discussion to that other post. Thx!

**Closed by kroitor** 2018-01-17 01:19 UTC
Labels: duplicate
