### ISSUE TITLE
Deposit issue

### ISSUE THREAD

**Issue by awais33** [ccxt/ccxt#16682] opened 2023-01-30 12:29 UTC
### ؜

I read the document for the deposit. I followed the steps but I am stuck in one step

step 1: I get the deposit address for deposit crypto i.e USDT through
the exchange.fetchDepositAddress("USDT");
suppose I am using kucoin as an exchange

step 2: I have usdt address, then I login to my Binance account in my mobile app and then withdraw the 20 USDT to the address created in 1st step

step 3: In this step, How ccxt (Kucoin) knows whether it receives 20 USDT or not, any webhook or any other method please help me, because in this case, my Binance account is not connected with ccxt, because I used the Binance from my mobile app and withdraw the crypto to the usdt address.

Please help me
Thanks

**Comment by sc0Vu** [comment] 2023-01-30 14:02
duplicate of ccxt/ccxt#16679

**Closed by sc0Vu** 2023-01-30 14:02 UTC
