### ISSUE TITLE
SyntaxError: Unexpected identifier - let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})

### ISSUE THREAD

**Issue by alexgpark** [ccxt/ccxt#2164] opened 2018-03-08 05:18 UTC
```
/root/node_modules/ccxt/js/base/Exchange.js:353
                    let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node_modules/ccxt/ccxt.js:33:19)

```

My JS code file (which interacts with CCXT) works fine locally and on one of my DigitalOcean servers but gives the above error only when I run it on a second, identical DigitalOcean server - which leads me to believe there is no issue with the application code and that the issue is within CCXT package?

So I tried deleting > reinstalling CCXT and updating the package version - did not fix error.

Totally stumped here :\

- OS: Ubuntu (DigitalOcean Server)
- Programming Language version: JS & Node JS 6.12.4 on 16.04
- CCXT version: 1.11.45 
- Exchange: No particular exchange presented this issue, to my knowledge
- Method: No particular method presented this issue, to my knowledge

^ Hopefully I haven't filled the below fields out wrong (still a novice developer). Please let me know if there is a way I can provide more information.

**Comment by mkutny** [comment] 2018-03-08 07:09
> My JS code file (which interacts with CCXT) works fine locally and on one of my DigitalOcean servers but gives the above error only when I run it on a second, identical DigitalOcean server - which leads me to believe there is no issue with the application code and that the issue is within CCXT package?

So you have three components: an application, a server and `ccxt`. From what I read I assume that all three components are identical (correct me, if I'm wrong).

Still, you somehow managed to believe that the problem is necessarily in `ccxt`. While I don't intend to say that your conclusion is incorrect I still curious what train of thought led you to this believe as it's not apparently obvious.

**Comment by kroitor** [comment] 2018-03-08 08:43
@alexgpark Node.js ver. 6 does not support the modern async-await syntax of ES6, therefore it complains... You will have to upgrade Node.js to at least version 7+ (9+ is even better). Let us know if it does not help. Closing it for now as a duplicate, if you don't mind.

- https://github.com/ccxt/ccxt/issues/1921#issuecomment-366225152
- https://github.com/ccxt/ccxt/issues/222

**Closed by kroitor** 2018-03-08 08:43 UTC
Labels: duplicate, question

**Comment by alexgpark** [comment] 2018-03-08 18:21
thank you very much @kroitor - you were exactly right! 
somehow, I had two different Node versions on the 2 servers running.
after i updated, it began to work.
