### ISSUE TITLE
Why my API key format is considered invalid ?

### ISSUE THREAD

**Issue by GAMinsect** [ccxt/ccxt#18647] opened 2023-07-25 09:01 UTC
### Operating System

It operates on google cloud function

### Programming Languages

python

### CCXT Version

1.57.0

### Description

This is the code I'm using, it runs on **google cloud function** and it should retrieve the balance of my Binance account, however that doesn't happen and it just say that my API key format is incorrect

### Code

```
import ccxt
import json

def get_binance_balance(request):
    try:
        
        api_key = 'MY_API_KEY'
        secret_key = 'MY_SECRET_KEY'
        
        
        # Set up Binance client using ccxt
        binance = ccxt.binance({
            'apiKey': api_key,
            'secret': secret_key
        })
        
        # Fetch the account balance
        balance = binance.fetch_balance()

        # Create a dictionary to store the account balance information
        account_balance = {}

        # Store the account balance in the dictionary
        for asset, info in balance['total'].items():
            if info > 0:
                account_balance[asset] = info

        # Return the account balance as a JSON response
        return json.dumps(account_balance)

    except Exception as e:
        error_message = str(e)
        return json.dumps({'error': error_message})
    except ccxt.BaseError as e:
        # Handle specific ccxt errors
        print("ccxt error:", e)
    except requests.RequestException as e:
        # Handle specific requests library errors
        print("requests error:", e)
    except Exception as e:
        # Handle other general exceptions
        print("Error:", e)

```
Every time i try to execute the code it just gives this error:

> {"error": "binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1690274789108&recvWindow=10000&signature=b22d57d5c03016d9e512da89cd16745d73606827ed8ca9823ebb2cee15fa5726"}

Which has a link that shows this message:
`{"code":-2014,"msg":"API-key format invalid."}`
I checkd my API key and Secret and they are correct and have the necessary requirments to fetch my account balance.

For what i could see online it seemes like it is an header problem, however ccxt should take care of all of that, in fact if i were to replace ccxt.binance with ccxt.coinbasepro this problem wouldn't occure.

Could it be because Google Cloud IP can't get access to the Binance API? (My function operates on a server in Zurich)

Also my function uses a **VPC** since otherwise Binance would ,also, give this error:

> Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error`

If you can find the solution to this problem i would appreciate it a lot, I have been trying to fix it for hours, not joking.

**Comment by GAMinsect** [comment] 2023-07-25 09:31
Ok i'll try to put a new one and see if it works

**Comment by GAMinsect** [comment] 2023-07-25 09:39
So i updated hte version of ccxt to **4.0.36** and the version of python I'm using is **3.8**
It still gives the same error:

> {"error": "binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1690277862998&recvWindow=10000&signature=bc43424815e26c2298d9d6cf0407ed64bc1f4e071f8cfbb368aa735438e068c8"}

Which leads to the same message:
`{"code":-2014,"msg":"API-key format invalid."}`

**Comment by GAMinsect** [comment] 2023-07-25 10:11
Sure I'll check it now

**Comment by GAMinsect** [comment] 2023-07-25 10:35
For what i could the see the API isn't expired and there are no empty spaces in the keys.

In the meantime I'm also trying to make it work on my local machine using VS Code, and for what i can see, there i can retrieve my account balance without any issue, however when i try to create a limit order, and as such active IP restriction on my API since Binance requires so, an put my IPv4 it hgives me 2 errors:

> requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1690280737020&recvWindow=10000&signature=6c7083bd7c53b4c1564c5288cf547b6b1cc001501609ac5b8b29a60883bf0b62

`{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}` 

If you think that also sharing this code can be usefull to trubleshoot this problem let me know, i don't want to "jam" this chat.
And thank you for your patience

**Comment by carlosmiei** [comment] 2023-07-25 11:13
@GAMinsect can you make sure you are running the same version of ccxt on both sides? `console.log(ccxt.version)`

**Comment by GAMinsect** [comment] 2023-07-25 11:18
For Google cloud function in the requirments.txt I have:
`ccxt>=4.0.36`

And when in VS Code when i execute the command line:
`print('CCXT version:', ccxt.__version__)`
It prints out:
`CCXT version: 4.0.36`

So they should both operate on the same version

**Comment by samgermain** [comment] 2023-07-26 02:44
I'm closing this issue as it's a duplicate of https://github.com/ccxt/ccxt/issues/18653

**Closed** 2023-07-26 02:44 UTC
Labels: question
