### ISSUE TITLE
error with watch_order_book on gate

### ISSUE THREAD

**Issue by daqingsu19** [ccxt/ccxt#16794] opened 2023-02-10 01:14 UTC
### Operating System

NAME="CentOS Stream" VERSION="8"

### Programming Languages

python

### Description

 Exception in callback FastClient.receive_loop.<locals>.handler() at ../lib/python3.7/site-packages/ccxt/pro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at ../lib/python3.7/site-packages/ccxt/pro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "../lib/python3.7/site-packages/ccxt/pro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "../lib/python3.7/site-packages/ccxt/pro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "../lib/python3.7/site-packages/ccxt/pro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "../lib/python3.7/site-packages/ccxt/pro/gate.py", line 934, in handle_message
    method(client, message)
  File "../lib/python3.7/site-packages/ccxt/pro/gate.py", line 192, in handle_order_book
    cacheLength = len(storedOrderBook.cache)
AttributeError: 'NoneType' object has no attribute 'cache'

### Code

```
  ob = await self.exchange.watch_order_book('MTRG/USDT')

```

**Comment by daqingsu19** [comment] 2023-02-10 01:15
saw similar issue https://github.com/ccxt/ccxt/issues/16396
my ccxt __version__ = '2.6.58'

**Comment by daqingsu19** [comment] 2023-02-10 14:52
btw fetch_order_book() works.

**Comment by pcriadoperez** [comment] 2023-02-10 18:49
hi @daqingsu19, I was able to reproduce the error on version 2.6.58 but it seems to be working correctly on the latest version. Can you try the upgrading to the latest version to see if the issue is also fixed on your side?

**Comment by daqingsu19** [comment] 2023-02-10 19:23
upgraded to latest 2.7.78 and it works!
thank you!

**Closed** 2023-02-10 19:23 UTC
