### ISSUE TITLE
Livecoin incorrect withdrawal limits

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5191] opened 2019-05-24 19:56 UTC
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu
- Programming Language version: nodejs
- CCXT version: 1.18.545
- Exchange: livecoin
- Method: fetchCurrencies

I use fetchCurrencies methods to get min withdrawal limit. For VRC coin it generates following output (min withdraw amount 0.01):
```
{ id: 'VRC',
  code: 'VRC',
  info:
   { name: 'VeriCoin',
     symbol: 'VRC',
     walletStatus: 'normal',
     withdrawFee: 0.01,
     difficulty: 0.0459433,
     minDepositAmount: 0,
     minWithdrawAmount: 0.01,
     minOrderAmount: 8.794 },
  name: 'VeriCoin',
  active: true,
  fee: 0.01,
  precision: 8,
  limits:
   { amount: { min: 8.794, max: 100000000 },
     price: { min: 1e-8, max: 100000000 },
     cost: { min: 8.794, max: undefined },
     withdraw: { min: 0.01, max: 100000000 },
     deposit: { min: 0, max: undefined } } }

```
But I was unable to withdraw 350 VRC

**Comment by kroitor** [comment] 2019-05-24 19:59
> But I was unable to withdraw 350 VRC

When you say "I was unable" we are not very able to determine what's causing it without the details – we again (and always will) need you to follow these guides precisely and paste your code to reproduce it and your verbose request and response as described here (without your keys): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by denarioresearch** [comment] 2019-05-24 20:08
here is withdraw function output
`Error: livecoin insufficient funds to cover requested withdrawal amount post fees {"fault":null,"userId":null,"userName":null,"id":null,"state":null,"createDate":null,"lastModifyDate":null,"comment":null,"description":null,"amount":null,"currency":null,"wallet":null}`

**Comment by kroitor** [comment] 2019-05-24 20:15
> here is withdraw function output

Can you please post the verbose request and the verbose response?

```JavaScript
;(async () => {

    const ccxt = require ('ccxt')

    const exchange = new ccxt.livecoin ({
        'apiKey': 'YOUR_API_KEY',
        'secret', 'YOUR_SECRET',
        'enableRateLimit': True,
    })

    await exchange.loadMarkets ()

    exchange.verbose = true // ←------- add this after loadMarkets, before your call

    await exchange.withdraw ('VRC', 350, YOUR_ADDRESS)

}) ()
```

**Comment by kroitor** [comment] 2019-05-24 20:24
@denarioresearch let us know if the above does not help. Closing this for now, if you don't mind. Feel free to ask if you have more questions.

**Comment by denarioresearch** [comment] 2019-05-24 20:28
```
Balance:
{ 
  VRC: 443.39044258,
  
}
fetch:
 livecoin POST https://api.livecoin.net/payment/out/coin 
Request:
 { 'User-Agent':
   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
  'Api-Key': '<KEY>',
  Sign:
   '<SIGN>',
  'Content-Type': 'application/x-www-form-urlencoded' } 
 amount=350&currency=VRC&wallet=<WALLET>

handleRestResponse:
 livecoin POST https://api.livecoin.net/payment/out/coin 200 OK 
Response:
 { Server: 'nginx',
  Date: 'Fri, 24 May 2019 20:21:11 GMT',
  'Content-Type': 'application/json;charset=UTF-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie':
   'JSESSIONID=F7DBE55B9EFBF4B104B16E15B587C6EB; Path=/invest; Secure; HttpOnly',
  'Strict-Transport-Security': 'max-age=31536000',
  'Content-Encoding': 'gzip' } 
 {"fault":null,"userId":null,"userName":null,"id":null,"state":null,"createDate":null,"lastModifyDate":null,"comment":null,"description":null,"amount":null,"currency":null,"wallet":null} 

```

The problem is not in fetchCurrencies or withdraw function.
I made HTTP GET request to livecoin api _https://api.livecoin.net/info/coinInfo_ and got response
```
{"name":"VeriCoin","symbol":"VRC","walletStatus":"normal","withdrawFee":0.01,"difficulty":0.0459433,"minDepositAmount":0,"minWithdrawAmount":0.01,"minOrderAmount":9.1305}
```
minWithdrawAmount :0.01 is used in fetchCurrencies but it seems to be incorrect, or 0.01 does not mean 0.01 VRC

**Comment by kroitor** [comment] 2019-05-24 20:33
> minWithdrawAmount :0.01 is used in fetchCurrencies but it seems to be incorrect, or 0.01 does not mean 0.01 VRC

We could only guess what it means then... The problem is that their documentation lacks details on it, and it may be the case of a bug on the exchange side, we've seen those before. 

https://www.livecoin.net/api/public

<img width="853" alt="Screen Shot 2019-05-24 at 23 32 28" src="https://user-images.githubusercontent.com/1294454/58355204-40388080-7e7c-11e9-8221-9745839bdf20.png">

Have you tried reaching out to the Livecoin tech support on this issue?

**Comment by denarioresearch** [comment] 2019-05-24 20:41
yes, I've opened the ticket waiting for their response

**Comment by kroitor** [comment] 2019-05-24 20:45
@denarioresearch alright, let's see what they say... though, i've heard, they don't react too quickly sometimes. Anyways, will be happy for your feedback whether you have the resolution or not. Thx for reporting this!

**Comment by macordalfy** [comment] 2019-12-10 16:41
was there ever a resolution for this ? having the same issue with livecoin

**Comment by kroitor** [comment] 2019-12-10 19:07
@macordalfy 

> was there ever a resolution for this ?

Unfortunately, not yet. We hope to get to it asap. Let us know if you find any clues, we appreciate all help. Thx!

**Comment by macordalfy** [comment] 2019-12-10 19:14
not sure if its related to the same problem, but im also getting the "livecoin insufficient funds to cover requested withdrawal amount post fees" message, although have more than enough coins .. i did see however that 3 out of my 4 tries actually went thru and put the withdrawal in "pending", im assuming thats why it did not return an id, and on the livecoin code it checks if it didnt return an id and if it didnt, it outputs that message "insuficient funds" .... my account seems to have withdrawals blocked for 2 days after I activated the 2step verification, so Im assuming is all related to that .. their API should return better messages I guess ... will know more in 2 days when the block is lifted

**Comment by kroitor** [comment] 2019-12-10 19:16
@macordalfy thx! If that proves to be the case, we will add the necessary workarounds to our implementation. Looking forward to hearing back from you!

**Comment by macordalfy** [comment] 2019-12-13 22:33
i can confirm that it was indeed related to this once the block was lifted after the 48 hour period the withdrawal went through without any issues with the response with the right id etc

**Comment by frosty00** [comment] 2021-11-07 22:02
livecoin is now dead

**Closed by frosty00** 2021-11-07 22:02 UTC
Labels: question
