### ISSUE TITLE
Question about duplicate nonce

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2163] opened 2018-03-08 05:16 UTC
A question. I continue to try and make a custom nonce, because even when ratelimit is enabled, it regularly produces a duplicate nonce error. 

If the Yobit exchange default ratelimit nonce is defined in milliseconds by default as we discussed in #2153, then I do not understand how this could happen in any case - even programmer error. 

In any case, I tried to fix it by using this;

```
// A: custom nonce value
class MyOKCoinUSD extends \ccxt\okcoinusd {
    public function __construct ($options = array ()) {
        parent::__construct (array_merge (array ('i' => 1), $options));
    }
    public function nonce () {
        return $this->i++;
    }
}
```

As well as by this;

```
// B: milliseconds nonce
class MyZaif extends \ccxt\zaif {
    public function __construct ($options = array ()) {
        parent::__construct (array_merge (array ('i' => 1), $options));
    }
    public function nonce () {
        return $this->milliseconds ();
    }
}
```

As per https://github.com/ccxt/ccxt/wiki/Manual (Overriding The Nonce)

Btw, the same page it says for the ratelimit option that "This parameter is not used for now (reserved for future)." (incorrect?)

In any case, both methods above fail. If I use the second, it gives this;

`Assert! ccxt\ExchangeError: yobit unknown "error" value => {"success":0,"error":"invalid nonce (max 2147483646), please generate new key"} in /home/roel/ccxt/php/liqui.php:736
`

If I use the first, I am not sure how to set the custom nonce (I am reading/storing it from/to a file), but if I use the code as-is, it produces;

`
Assert! ccxt\ExchangeError: yobit unknown "error" value => {"success":0,"error":"invalid nonce (has already been used)"} in /home/roel/ccxt/php/liqui.php:736
`

Even if I set 'i'=>1 to a much larger random number which never have been used.

**Comment by mkutny** [comment] 2018-03-08 05:57
> I do not understand how this could happen in any case - even programmer error.

And still...

> In any case, I tried to fix it by using this;

Fixing something that you don't really understand will cause you a lot of pain ) While this strategy surely can bring you positive results if you persistent enough I wouldn't call it the most optimal one.

> "This parameter is not used for now (reserved for future)." (incorrect?)

Yeah, the Manual is outdated in this regard. I also see examples in it don't use `enableRateLimit` (yet).

>  "invalid nonce (max 2147483646), please generate new key"

So if you use milliseconds your nonce is obviously bigger than that number, this is expected.

> "invalid nonce (has already been used)"

If you start from `1` this is also expected.

I suggest you enable verbose output and you should immediately see where the problem is.

**Comment by forexhill** [comment] 2018-03-08 06:58
- I did not start from `1` - in fact tried many different numbers which would not have been used yet.
- There is no additional verbose output than the one given above (and an irrelevant call stack).
- I understand quite well what is happening, but do not understand how the error could happen if what @kroitor mentioned in the other issue is correct; that ccxt\Yobit already uses milliseconds if ratelimit is enabled (then it would be impossible to get a duplicate nonce).

**Comment by mkutny** [comment] 2018-03-08 07:20
> do not understand how the error could happen if what @kroitor mentioned in the other issue is correct; that ccxt\Yobit already uses milliseconds if ratelimit is enabled

Ok, there is a hypothesis that yobit uses milliseconds for nonce but you have some doubts that it's valid.

The hypothesis could be easily tested by looking at the code, or by logging nonce (running exchange in `verbose` mode). That `max 2147483646` from Exception should also ring a bell.

**Comment by forexhill** [comment] 2018-03-08 09:57
Yes it did, hence the question. I will have a look into verbose when possible. Thanks.

**Comment by forexhill** [comment] 2018-03-08 20:28
@kroitor I checked with verbose on. By default it looks like Yobit does not use milliseconds but seconds;

` [3] => nonce=1520540448&method=getInfo^M`

So this would make the assertion given in #2153 inaccurate. So, to fix the nonce, a custom nonce would have to be used (which is fine), but it seems that none of the given methods work for changing it, as described above. Using milliseconds would go over 2147483646, and trying to use the custom procedure (by storing and reading the value from a file), it seems not possible to change the nonce value. Here is what I have tried so far;

```
// A: custom nonce value
class MyOKCoinUSD extends \ccxt\okcoinusd {
    public function __construct ($options = array ()) {
        parent::__construct (array_merge (array ('i' => 1), $options));
    }
    public function nonce () {
        return $this->i++;
    }
}
```

As per manual, but will always give duplicate nonce, even if `=>1` is changed to a good nonce `=>x`.

Also tried;
```
return $this->i++;
```

Changing this to a good nonce.

Could you please give an example how to get this to work please? Thank you & God bless

**Comment by forexhill** [comment] 2018-03-08 20:53
Okay, generated new keys on Yobit and it works now with custom procedure. I have no idea how all the nonce values (tried 1,10000,30000,50000,1000000,10000000 etc.) could have been used on the other key (it's only ~2 weeks old). Still, got it working. Thank you @mkutny @kroitor for all the help. 

Final action; make pull request for manual update (I can do this)

**Comment by forexhill** [comment] 2018-03-08 20:54
@kroitor btw, I am experienced with github etc. and would be happy to contribute where possible.

**Comment by forexhill** [comment] 2018-03-08 21:01
For anyone wanting to reading/storing nonce from a nonce.dat file (can be created with text editor);

```
class _yobit extends \ccxt\yobit{
  public function __construct($options=array()){
    if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist. 
    if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}
    file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.
    parent::__construct(array_merge(array('i'=>$nonce),$options));
  }
  public function nonce(){
    if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist. 
    if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}
    file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.
    return $this->$nonce;
  }
}
```
[...]
`$exchange=new _yobit(array('apiKey'=>'{yourkey}','secret'=>'{yoursecret}','enableRateLimit'=>true,'rateLimit'=>1000,'timeout'=>20000,));  `

**Comment by kroitor** [comment] 2018-03-08 21:11
@forexhill you don't really need a custom procedure with a new key. You can just remove the overrided procedure and use the default nonce as is with a new key...

Now, as for your questions:

> I continue to try and make a custom nonce, because even when ratelimit is enabled, it regularly produces a duplicate nonce error.

I would agree with @mkutny , whenever you find yourself in such a situation, the best way is to make sure to fully understand the nature of the bug, before trying to fix anything.

> If the Yobit exchange default ratelimit nonce is defined in milliseconds by default as we discussed in #2153, then I do not understand how this could happen in any case - even programmer error.

Right, and this is something that is the most important to investigate, all other measures are applied prematurely.

> In any case, I tried to fix it by using this;

Redefining a nonce won't solve a reappearing nonce conflict in general case, unfortunately, so, the fix isn't fixing it really.

> Btw, the same page it says for the ratelimit option that "This parameter is not used for now (reserved for future)." (incorrect?)

Outdated somewhat... Needs to be constantly updated, I'm doing whatever I can to keep it up, really.

> has already been used

Random nonces won't work in general. The nonce not only has to be unique, but also has to be greater than the previous nonce, so a random number will sooner or later hit a nonce smaller than the previously used value, and Yobit will confuse you with their non-intuitive error messaging `{"success":0,"error":"invalid nonce (has already been used)"}`, which in fact means an absolutely different reason: *"you're sending a nonce that is smaller than the biggest nonce I've seen so far with this api key"* (this is what Yobit is trying to tell you, really).

----------------

Anyway, there's a [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) procedure and if you follow if from top to bottom literally one point after the other, you will inevitably try a new key among the first troubleshooting steps. That is something you should have tried in the first place. And this is what, most likely, fixed the issue for you. However, if you run into the same issue again, I'd recommend to stop right there, do some preparation and debugging and in case of a difficulty with it, report the code and verbose output, as usually, we will be happy to help.

Thx, closing it for now, if you don't mind. Feel free to reopen it if needed or just ask questions if any.

**Closed by kroitor** 2018-03-08 21:11 UTC

**Comment by kroitor** [comment] 2018-03-08 21:15
> @kroitor btw, I am experienced with github etc. and would be happy to contribute where possible.

@forexhill your contributions are welcome!) Just make sure to read this doc: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Thanks so much!
