### ISSUE TITLE
OKEX BTC/USD Sudden Volume Drop on Every Friday 08:00 UTC

### ISSUE THREAD

**Issue by esrefozturk** [ccxt/ccxt#5022] opened 2019-04-23 13:51 UTC
Hi,

I was using ccxt to fetch daily volumes of okex exchange. Today, I realized that every Friday at 08:00 UTC, the volume of BTC/USD is dropping suddenly. I have checked BTC/USDT; there is not a sudden decrease in it.

You can see two examples here:

- 19th April 08:00 UTC
![1](https://user-images.githubusercontent.com/30148014/56585770-2985dc00-65e7-11e9-9d93-300a9658b6d1.png)

- 12th April 08:00 UTC
![2](https://user-images.githubusercontent.com/30148014/56585838-45897d80-65e7-11e9-94bf-0f8e46e18f6e.png)

Are these problems coming from ccxt or okex API?

Thanks

- OS: Ubuntu
- Programming Language version: Python3.6
- CCXT version: 1.18.465
 - Exchange: okex
- Method: ccxt.okex.fetch_tickers

**Comment by kroitor** [comment] 2019-04-23 14:02
> Are these problems coming from ccxt or okex API?

As you might have guessed, we don't alter the response of `fetch_tickers` based on datetime, we don't alter it at all in the lib, so the response you get is practically the response from the exchange as is, moreover, in each and every response you get from the lib – you also get the `info` subfield, that contains the raw response from the exchange untouched, so that you could compare it to the response from the lib and make your own conclusions if the lib is lying to you or not. Personally, I don't think that 08:00 UTC is any better than 09:00 UTC, i don't have any preference for either, therefore I didn't add any code that would depend on that into the lib – which is also verifiable just by looking into the sources.

- the error in the lib ← this is easily ruled out by [source code](https://github.com/ccxt/ccxt/blob/master/js/okex.js#L84) + `info`
- the error on the exchange side ← this is still possible
- the error on the user side ← this is still possible and this is the most frequent case to be honest

↑ There might be an error or some manipulation on the exchange side, we will run tests on our side to investigate, in the meantime, I would suggest that you address this question to OKEX tech support and make sure you don't have the error on the storage side, because the above image might be a result of the way you store the data, not of the way it is is served to you.

Will need some time to verify the behavior you describe. If you could reduce it to a short sample to reproduce the issue, that would help resolve it quicker.

**Comment by esrefozturk** [comment] 2019-04-24 12:05
While checking  my usage, I have seen strange behavior:
```
ztrk@srf:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> o = ccxt.okex()
>>> o.fetch_tickers()['BTC/USD']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'BTC/USD'
>>> o.fetch_ticker('BTC/USD')
{'symbol': 'BTC/USD', 'timestamp': 1556107164000, 'datetime': '2019-04-24T11:59:24.000Z', 'high': 5611.25, 'low': 5366.36, 'bid': 5421.19, 'bidVolume': None, 'ask': 5421.2, 'askVolume': None, 'vwap': None, 'open': None, 'close': 5421.2, 'last': 5421.2, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 1332071.0, 'quoteVolume': None, 'info': {'high': 5611.25, 'vol': 1332071, 'day_high': 0, 'last': 5421.2, 'low': 5366.36, 'contract_id': 201904260000034, 'buy': 5421.19, 'sell': 5421.2, 'coin_vol': 24146.64007254, 'day_low': 0, 'unit_amount': 100, 'timestamp': 1556107164000}}
>>> [i for i in o.fetch_markets() if i['symbol'] == 'BTC/USD']
[{'percentage': True, 'taker': 0.0003, 'maker': 0.0002, 'id': 'btc_usd', 'symbol': 'BTC/USD', 'base': 'BTC', 'quote': 'USD', 'baseId': 'btc', 'quoteId': 'usd', 'baseNumericId': 0, 'quoteNumericId': 7, 'info': {'baseCurrency': 0, 'brokerId': 0, 'callAuctionOrCallNoCancelAuction': False, 'callNoCancelSwitchTime': {}, 'collect': '0', 'continuousSwitchTime': {}, 'isMarginOpen': True, 'listDisplay': 0, 'marginRiskPreRatio': 1.2, 'marginRiskRatio': 1.1, 'marketFrom': 118, 'maxMarginLeverage': 5, 'maxPriceDigit': 1, 'maxSizeDigit': 8, 'mergeTypes': '0.1,1,10', 'minTradeSize': 0.001, 'online': 1, 'productId': 20, 'quoteCurrency': 7, 'quoteIncrement': '0.1', 'quotePrecision': 2, 'sort': 30038, 'symbol': 'btc_usdt', 'tradingMode': 3}, 'type': 'future', 'spot': False, 'future': True, 'active': True, 'precision': {'amount': 8, 'price': 1}, 'limits': {'amount': {'min': 0.001, 'max': None}, 'price': {'min': 0.1, 'max': None}, 'cost': {'min': 0.0001, 'max': None}}}]
```

As you can see, when we fetch markets from okex, we see `BTC/USD` but when we fetch all tickers we do not get `BTC/USD` ticker. However, when we try to get only `BTC/USD` ticker, we get some values.

I was using `fetch_ticker` method on my code, it seems that's why I am getting BTC/USD ticker values.

I think there is a bug here. Could you confirm that is a bug?

Thanks

**Comment by esrefozturk** [comment] 2019-04-24 12:26
I have checked the OKEX website. There is not `BTC/USD` trading on their system.

I have checked which API calls are ccxt making:

When I call `ccxt.okex().fetch_tickers()` requests are made to these 2 APIs:

- `www.okex.com/v2/spot/markets/products`
- `www.okex.com/api/v1/tickers.do`

When I call `ccxt.okex().fetch_ticker('BTC/USD')` requests are made to these 2 APIs:

- `www.okex.com/api/v1/future_ticker.do`
- `www.okex.com/v2/spot/markets/products`

When I check these API results, there is no ticker info for `BTC/USD` I am confused at this point. Do you have any suggestions for me to review more?

**Comment by devcon14** [comment] 2019-04-24 22:00
@esrefozturk 
You probably want to call fetch_ticker('BTC/USDT') in order to retrieve spot market stats.
If I remember correctly fetch_ticker('BTC/USD') retrieves the weekly futures contract by default.
What I believe you are noticing is that every Friday at 08:00 UTC the Okex weekly contracts expire and roll over to a new contract after which the volume will reset to 0.

@kroitor It might be wishful thinking but if there was a parameter in the unified API to specify the contract name on derivative exchanges it would be very helpful.
For instance something like:
okex().fetch_ticker('BTC/USD', contract='weekly')
# or bitmex:XBTUSD or bitmex:XBTM19 or deribit:* or kraken_futures:*

It might help avoid confusion in the future.

**Comment by kroitor** [comment] 2019-04-24 22:09
> @kroitor It might be wishful thinking but if there was a parameter in the unified API to specify the contract name on derivative exchanges it would be very helpful.

Currently, we allow to override that via `params`:

```Python
okex().fetch_ticker('BTC/USD', {'contract_type': 'this_week' }) // this_week, next_week, quarter
```

We also have a market type to differentiate `spot` from `futures` markets:

```
Last login: Tue Apr 23 18:19:56 on ttys006
mbp:bot1709 igorkroitor$ cd ../ccxt
mbp:ccxt igorkroitor$ python examples/py/cli.py okex market ETH/BTC
{'active': True,
  ...
 'future': False,
 ...
 'spot': True,
 ...
 'symbol': u'ETH/BTC',
 ...
 'type': 'spot'} ←----------------------------------------

mbp:ccxt igorkroitor$ python examples/py/cli.py okex market BTC/USD
{'active': True,
 ...
 'future': True,
 ...
 'spot': False,
 'symbol': u'BTC/USD',
 ...
 'type': 'future'} ←----------------------------------------
mbp:ccxt igorkroitor$
```

But, yeah, the argument is not unified, the futures trading is not unified completely yet: https://github.com/ccxt/ccxt/issues/4834 ← I suggest to continue there on this subject ) Your thoughts and considerations are always welcome! )

@esrefozturk I believe, the explanation by @devcon14 indeed explains the above shift that you've encountered very well. Therefore I suggest that we close this issue for now, feel free to reopen it if needed or just ask further questions if you have more.

**Closed by kroitor** 2019-04-24 22:09 UTC
Labels: question
