### ISSUE TITLE
New exchange, kraken futures

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#15682] opened 2022-11-14 14:54 UTC
Hi all,

Do you plan to integrate kraken futures(https://docs.futures.kraken.com/) in ccxt?

Thanks

**Comment by samgermain** [comment] 2022-11-14 21:25
There's a [PR](https://github.com/ccxt/ccxt/pull/15133) for it, but it hasn't been merged yet

**Comment by Hadevmin** [comment] 2022-11-14 22:08
@samgermain Ok, thanks.
Do we have an estimate of how long it will take to get approved?

**Comment by samgermain** [comment] 2023-02-14 22:27
Duplicate of #15112

**Closed by samgermain** 2023-02-14 22:27 UTC
Labels: duplicate
