### ISSUE TITLE
can not change futures levevrge in python binance 

### ISSUE THREAD

**Issue by hansonclevin** [ccxt/ccxt#14593] opened 2022-08-05 05:27 UTC
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by sc0Vu** [comment] 2022-08-05 05:30
Hi @hansonclevin 

Would you like to post your python script?

**Comment by samgermain** [comment] 2022-08-05 17:33
Without seeing your code, your error response, or any explanation, we can't answer your question accurately

Posting a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) is usually the quickest way to get an answer from us

----------------

Here's an example where I change the leverage 

```
binanceusdm.setLeverage(15,ADA/USDT)
{'leverage': '15', 'maxNotionalValue': '250000', 'symbol': 'ADAUSDT'}
```

-------------------------------

Note that there are a few reasons why Binance might not let you change your leverage

<div style='width: "100%"'>
<img style='width: "45%"' src="https://i.imgur.com/ZXtXc4Q.png" />
<img style='width: "45%"' src="https://i.imgur.com/5EVCtdO.png" />
</div>

And if you're getting this error, it is probably because you calling the method like `binanceusdm.setLeverage(symbol, leverage)` instead of `binanceusdm.setLeverage(leverage, symbol)`

```
Traceback (most recent call last):
  File "/Users/sam/Documents/dev/CCXT/ccxt/examples/py/cli.py", line 192, in <module>
    result = method(*args)
  File "/Users/sam/Documents/dev/CCXT/ccxt/python/ccxt/binance.py", line 5258, in set_leverage
    if (leverage < 1) or (leverage > 125):
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by samgermain** [comment] 2022-08-12 05:50
I'm going to close this issue. If you have any more questions, feel free to reopen it, but please post more of an explanation and share some of your code if you do reopen it.

**Closed by samgermain** 2022-08-12 05:50 UTC
Labels: question
