### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by Alexandr1227** [ccxt/ccxt#9482] opened 2021-06-30 10:47 UTC
This is my javascript ccxt code for getting account balance.
I am using ccxt 1.52.4 version for my project.
My project is react based project and it has some issues when I am trying to get binance account balance.
Please help me.
This is my code.

const ccxt = require ('ccxt')
var binance = new ccxt.binance({
            apiKey: 'KEY',
            secret: 'SECRET',
            timeout: 30000,
            enableRateLimit: true,
            proxy: 'http://localhost:8080/', 
            options: {
                adjustForTimeDifference: true
            }
        });
        (async () => {
            console.log (await binance.fetchBalance ());
        }) ()

This occurs BigInt convert error and I am not sure why it has this kind of issues.
Help!

![img_20210630](https://user-images.githubusercontent.com/72569202/123948291-1d7bce80-d956-11eb-8003-fa311e3015ea.png)

**Comment by frosty00** [comment] 2021-06-30 10:52
can you pls remove the secret key

**Comment by Alexandr1227** [comment] 2021-06-30 10:55
oh I see. thank you. 
But is there any way for fix this issues?

**Comment by frosty00** [comment] 2021-06-30 10:57
@Alexandr1227 can you also log into binance and delete that key pls

**Comment by frosty00** [comment] 2021-06-30 11:11
can you update to the latest version of ccxt, we shouldn't use Math.pow anywhere in the lib, where is this coming from?

**Comment by Alexandr1227** [comment] 2021-06-30 11:33
I have installed ccxt library with npm install ccxt 
what version should I use for my project??

**Comment by Alexandr1227** [comment] 2021-06-30 12:22
I have changed the version to ccxt@1.49.73 and it doesn't occur errors.
I hope you please check this issues and find out the reasons for our fans.
Thank you.

**Comment by kroitor** [comment] 2021-06-30 20:08
@Alexandr1227 make sure your version is up to date:

```JavaScript
const ccxt = require ('ccxt')
console.log (ccxt.version)
```

What do you see in runtime in React?
Do you have this issue with version 1.52.24?
How do you add CCXT to your react project?

**Comment by Alexandr1227** [comment] 2021-07-01 15:32
I can see 1.52.4
and i have updated with npm install ccxt --save
so please check and let me know the details about our issue

**Comment by kroitor** [comment] 2021-07-01 15:48
@Alexandr1227

- Do you have this issue with version 1.52.24?
- How do you add CCXT to your react project?

**Comment by hanc1208** [comment] 2021-08-25 00:53
It caused by babel. Babel transpiles `**` to `Math.pow`. Using library like Decimal.js can be avoid this problem.

**Comment by hanc1208** [comment] 2021-08-28 01:47
@kroitor But `Precise` module of `ccxt` uses `**` operator. I think it should be replaced into other operator.

**Comment by kroitor** [comment] 2021-08-28 03:47
@hanc1208 thx for your feedback, we are working on a fix!

**Comment by hanc1208** [comment] 2021-11-29 16:17
@kroitor hello, can you update the state of this issue?

**Comment by frosty00** [comment] 2021-11-29 22:23
https://github.com/babel/babel/issues/13109#issuecomment-826287089

**Comment by kroitor** [comment] 2021-11-30 01:27
@hanc1208 check @frosty00's answer – it will help resolve the issue. Closing it for now, since it's in babel, outside of CCXT.

**Closed by kroitor** 2021-11-30 01:27 UTC
Labels: question

**Comment by rueiwoqp** [comment] 2022-01-17 15:59
**UPDATE:**
In my case, running `npx browserslist@latest --update-db` fixed the issue.

**Comment by hanc1208** [comment] 2022-01-18 02:47
@rueiwoqp babel respects browserslist to whether it uses `**` related plugin or not.

**Comment by ragamufin** [comment] 2022-04-26 15:47
For those running react-native in Electron or using react-native-windows, react-native-macos
The browserlist fix did not work for me to resolve the `TypeError: Cannot convert a BigInt value to a number` problem

After a lot of trial and error and searching I found this gist on how to get babel to skip over some of its transformations, specifically the `babel-plugin-transform-exponentiation-operator` transform and that worked for me:

https://gist.github.com/karanjthakkar/3241808022a75d8068f35a33b57e90c5

There's a twitter thread about it as well: https://twitter.com/geekykaran/status/1082218546799755266

**Comment by ragamufin** [comment] 2022-06-09 07:27
Just to add to my above comment. Typescript was bugging out with the changes I made to `babel.config.js`. Things like the `as` operator `named tuples`, etc. weren't working. Making the following modification fixed things:

```javascript
presets: [
    '@babel/preset-typescript'
]
```
