### ISSUE TITLE
Bybit.fetch_tickers() return data with colon

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#18633] opened 2023-07-24 07:26 UTC
### Operating System

Windows 10 

### CCXT Version

2.8.31

### Description

When I call fetch_tickers() function I get something like '10000LADYS/USDT:USDT':{} And this is rather strange considering that bybit.markets() will return the data in a different format, which is my preferred ('BTC/USDT':{} ). I tried to change the params and put a spot there, etc., but this does not help me. I checked the bybit documentation and didn't find anything there. Perhaps you can advise me. Because such a difference in the returned data from only 1 exchange interferes very much

### Code

```
  

```

**Comment by carlosmiei** [comment] 2023-07-24 09:27
Hello @AlwxDavydov,

First and foremost, I noticed that you have a pretty outdated ccxt version I would suggest upgrading it because we did a lot of meaningful updates in the meantime.

Regarding your question, bybit will return the swap tickers by default if no symbol/type is provided but you can easily provide a type in params if you want to retrieve spot tickers only, example:

```Python
tickers = await bybit.fetch_tickers(params = {'type':'spot'})
```

**Comment by ttodua** [comment] 2023-07-24 14:50
@carlosmiei if you are not against, for cleanup purposes I'll close this issue, as your response covers it correctly.
@AlwxDavydov if you still face any issue, feel free to post a follow-up and reopen the issue, so we could answer further.

**Comment by AlwxDavydov** [comment] 2023-07-24 17:04
@carlosmiei Thanks, your answer helped but not completely. As it turned out, not all tokens return by params = {'type':'spot'}), just like 1INCH, it will shown only if I use code with deafult params and looked like '1INCH/USDT:USDT. To be honest, I don't understand why. Initially, I thought that spot is only spot pairs, and default is those pairs that include margin trading, but no. For example WLD/USDC will be returned by params = spot, but in includes margin. So when I call a fetch_tickers() I want to got all pairs and I want it in some format like got all other exchanges.

**Comment by AlwxDavydov** [comment] 2023-07-26 10:58
@ttodua @carlosmiei  The problem was reopened but for 2 days there is no answer. Do I need to write another topic to get an answer? I'm sorry if I'm asking something stupid, I just want an answer and I don't understand if it is visible at all and why there is no answer.

**Comment by AlwxDavydov** [comment] 2023-07-26 11:16
@carlosmiei I'll even add the problem. The fact is that len(bybit.markets) will return 669, but fetch_tickers(
            params={'type': 'spot'}) will return around 280, and  fetch_tickers() will return around 250 pairs. So markets include some derivatives and there are around 550 real spot markets, but they can only be obtained by different calls (with fetch_tickers(params={'type': 'spot'}) and without this pararms).

**Comment by carlosmiei** [comment] 2023-07-26 11:55
@AlwxDavydov Sorry I still don't get what the problem is here.

> The fact is that len(bybit.markets) will return 669,

yes, bybit loads all markets buy default now (spot, swap, futures, options)

> fetch_tickers(
params={'type': 'spot'}) will return around 280,

That is because only returns spot tickers

>  fetch_tickers() will return around 250 pairs

As explained, by default will return only swap tickers

**Comment by AlwxDavydov** [comment] 2023-07-26 12:39
@carlosmiei Once again, I apologize for my stupidity and English. To be clearer, I will explain my task. I get tickers on many exchanges, on all but bybit it will return me all available pairs for spot (what I need) trading. But on bybit, the ticker call needs to be called 2 times to get all the pairs I need. This is annoying, but not such a big problem, the problem is that in spot trading pairs it will return data to me in a different format, namely the last coin and the colon before it("BTC/USDT:USDT"). And I'm rather asking for advice on how I can get my 550 spot pairs (after all, their real number is about it) in the same format, without the last character with a colon.

**Comment by ttodua** [comment] 2023-07-26 13:07
@AlwxDavydov please post your ccxt version

**Closed** 2023-07-26 15:12 UTC
Labels: wontfix/invalid, question
