### ISSUE TITLE
Bithumb fetchBalance

### ISSUE THREAD

**Issue by Umbralith** [ccxt/ccxt#3187] opened 2018-06-19 18:31 UTC
I can't seem to figure out this error, any ideas?

`<pre>ccxt\ExchangeError Object
(
    [message:protected] => bithumb {"status":"5100","message":"Bad Request.(Auth Data)"}
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/vendor/ccxt/ccxt/php/bithumb.php
    [line:protected] => 364
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/vendor/ccxt/ccxt/php/Exchange.php
                    [line] => 979
                    [function] => handle_errors
                    [class] => ccxt\bithumb
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 400
                            [1] => 
                            [2] => https://api.bithumb.com/info/balance
                            [3] => POST
                            [4] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Tue, 19 Jun 2018 18:26:18 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/json
                                        )

                                    [content-length] => Array
                                        (
                                            [0] => 53
                                        )

                                    [connection] => Array
                                        (
                                            [0] => keep-alive
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => __cfduid=d99b8ae72378963b185d18dc3875711ec1529432777; expires=Wed, 19-Jun-19 18:26:17 GMT; path=/; domain=.bithumb.com; HttpOnly
                                            [1] => WMONID=PJP3bRfaFEr; expires=Wed, 19-Jun-2019 18:26:18 GMT; Max-Age=31536000; path=/
                                            [2] => ci_session=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%222b60b37847e7f9b362ea06abcade212b%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%2264.250.109.50%22%3Bs%3A10%3A%22user_agent%22%3Bb%3A0%3Bs%3A13%3A%22last_activity%22%3Bi%3A1529432778%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3B%7Da35361f87d0d3a9c762aeda3d3b4b80af1d5fcc2; expires=Tue, 19-Jun-2018 20:26:18 GMT; Max-Age=7200; path=/
                                        )

                                    [access-control-allow-origin] => Array
                                        (
                                            [0] => *
                                        )

                                    [access-control-allow-methods] => Array
                                        (
                                            [0] => *
                                        )

                                    [access-control-allow-headers] => Array
                                        (
                                            [0] => *
                                        )

                                    [expect-ct] => Array
                                        (
                                            [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                                        )

                                    [server] => Array
                                        (
                                            [0] => cloudflare
                                        )

                                    [cf-ray] => Array
                                        (
                                            [0] => 42d80b0aff784219-MSP
                                        )

                                )

                            [5] => {"status":"5100","message":"Bad Request.(Auth Data)"}
                        )

                )`

**Comment by kroitor** [comment] 2018-06-19 18:32
- https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by Umbralith** [comment] 2018-06-19 18:35
thank you thank you, I will come back

**Comment by kroitor** [comment] 2018-06-19 18:37
@Umbralith this is most likely related to your api credentials, however, without your code and your verbose request/response it's hard to tell. Moreover, for obvious reasons, we can't check your secret credentials, so this is something that you should check on your side. However, this code did work for many users, so this might be a simple copypaste issue, like missing a symbol at the end when selecting the api key to copy, or something like that.

**Comment by kroitor** [comment] 2018-06-19 18:39
It's really hard to tell exactly at this point, because you're not including proper info for debugging it, and the issue is named `Bithumb fetchOrders`, but the error stack in the original post is about `fetchBalance`.

**Comment by Umbralith** [comment] 2018-06-19 18:42
Got the full verbose output and sorry about title, I will be more careful with posting

**Comment by Umbralith** [comment] 2018-06-19 18:42
I will triple check api keys

**Comment by kroitor** [comment] 2018-06-19 18:45
> I will triple check api keys

Yep, if you're sure that those are absolutely correct, then we will need your code and your output as described in the above links. We will be happy if you let us know in case you manage to solve it.

**Comment by Umbralith** [comment] 2018-06-19 19:31
Seems as though every API key I create doesn't work. Nothing wrong on ccxt, just Bithumb. I have to confirm API key activation through email and when I click the email it just says "API Key failed" every single time. I've made about 10 now...thank you for the responses anyways though

**Comment by kroitor** [comment] 2018-06-19 19:35
@Umbralith i guess you should contact Bithumb on this issue then. I'd close this for now if you don't mind, feel free to reopen it if needed / when you have a followup on this. Thx!

**Closed by kroitor** 2018-06-19 19:35 UTC
