### ISSUE TITLE
Phemex buy orders problem with amount in spot orders

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#8181] opened 2020-12-30 16:53 UTC
Sell orders looks ok, they have amount from `baseQtyEv`

```
{
    info: {
      orderID: '6a4930b1-0885-4612-9142-0e952950f181',
      clOrdID: '',
      priceEp: 2826035000000,
      action: 'New',
      execInst: 'None',
      trigger: 'UNSPECIFIED',
      pegPriceType: 'UNSPECIFIED',
      stopDirection: 'UNSPECIFIED',
      bizError: 0,
      symbol: 'sBTCUSDT',
      side: 'Sell',
      baseQtyEv: 1300500,
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      ordStatus: 'New',
      cumFeeEv: 0,
      cumBaseQtyEv: 0,
      cumQuoteQtyEv: 0,
      leavesBaseQtyEv: 1300500,
      leavesQuoteQtyEv: 36752000000,
      avgPriceEp: 0,
      cumBaseAmountEv: 0,
      cumQuoteAmountEv: 0,
      quoteQtyEv: 36752000000,
      qtyType: 'ByQuote',
      stopPxEp: 0,
      pegOffsetValueEp: 0
    },
    id: '6a4930b1-0885-4612-9142-0e952950f181',
    clientOrderId: undefined,
    timestamp: undefined,
    datetime: undefined,
    lastTradeTimestamp: undefined,
    symbol: 'BTC/USDT',
    type: 'limit',
    timeInForce: 'GTC',
    postOnly: false,
    side: 'sell',
    price: 28260.35,
    stopPrice: 0,
    amount: 0.013005,
    cost: 367.52,
    average: 0,
    filled: 0,
    remaining: 0.013005,
    status: 'open',
    fee: { cost: 0, currency: undefined },
    trades: undefined
  }
```

But for `buy` order `baseQtyEv` is 0. Real `amount` on exchange in this case is 0.22787 if we just divide `cost/price` is will be 0,227878061... `amount precision` is 5, so it look like we can calculate `amount` from `price` and `cost` for `buy` orders. Any other ideas?

```
info: {
      orderID: '6cd63a96-3ba4-44d2-881a-0e9e4c9c073f',
      clOrdID: '',
      priceEp: 35067000000,
      action: 'New',
      execInst: 'None',
      trigger: 'UNSPECIFIED',
      pegPriceType: 'UNSPECIFIED',
      stopDirection: 'UNSPECIFIED',
      bizError: 0,
      symbol: 'sBCHUSDT',
      side: 'Buy',
      baseQtyEv: 0,
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      ordStatus: 'New',
      cumFeeEv: 0,
      cumBaseQtyEv: 0,
      cumQuoteQtyEv: 0,
      leavesBaseQtyEv: 0,
      leavesQuoteQtyEv: 7991000000,
      avgPriceEp: 0,
      cumBaseAmountEv: 0,
      cumQuoteAmountEv: 0,
      quoteQtyEv: 7991000000,
      qtyType: 'ByQuote',
      stopPxEp: 0,
      pegOffsetValueEp: 0
    },
    id: '6cd63a96-3ba4-44d2-881a-0e9e4c9c073f',
    clientOrderId: undefined,
    timestamp: undefined,
    datetime: undefined,
    lastTradeTimestamp: undefined,
    symbol: 'BCH/USDT',
    type: 'limit',
    timeInForce: 'GTC',
    postOnly: false,
    side: 'buy',
    price: 350.67,
    stopPrice: 0,
    amount: 0,
    cost: 79.91,
    average: 0,
    filled: 0,
    remaining: 0,
    status: 'open',
    fee: { cost: 0, currency: undefined },
    trades: undefined
  }
```

**Comment by kroitor** [comment] 2021-01-05 14:55
@ndubel if we calculate the amount from cost, it will change with the cost on partial fills, while by design it has to be fixed and it has to correspond to the original ordered amount. We will try to get this resolved with Phemex.

**Comment by kroitor** [comment] 2021-01-13 14:09
@ndubel I got in contact with Phemex, can you please paste your full verbose output for the problematic call to create the buy-limit order, including both the request and the response? We need to see the original params submitted in your request as well as the response from the exchange side. Thx in advance!

**Closed** 2021-01-13 14:20 UTC
