### ISSUE TITLE
Subsequent builds in Docker do not update build directory

### ISSUE THREAD

**Issue by lead4good** [ccxt/ccxt#6910] opened 2020-05-08 12:11 UTC
environment: docker

I just had an issue where transpilation had failed for python, when run for the first time. The same error rooting from the `check-python-syntax` script continued to show up, even though the error was not present anymore in the transpiled python source. There seems to be another folder inside `./python/build/lib/ccxt` which still contained the transpiled code from the first run. The `check-python-syntax` script ran its checks on that code instead the one in `./python/ccxt`

- [ ] npm run script should be added that cleans up build artifacts, if already present  documentation should be added to CONTRIBUTING doc
- [ ] `check-python-syntax` script should check code in `./python/ccxt`, correct?

**Comment by kroitor** [comment] 2020-05-08 12:42
> There seems to be another folder inside ./python/build/lib/ccxt which still contained the transpiled code from the first run. The check-python-syntax script ran its checks on that code instead the one in ./python/ccxt

To be honest, i'm not maintaining that docker container, it has been submitted by one of the users, and we have merged it as is, but we don't guarantee that it works, it may have bugs in it or may be outdated. Instead of running that docker image, i would recommend to simply clone the repo to your local machine and building directly there, having all the deps needed. 

At this point the docker image needs to be fixed and thoroughly tested for all use cases – we didn't have the time to get there yet. So, the docker image is an open unresolved problem

>  npm run script should be added that cleans up build artifacts, if already present documentation should be added to CONTRIBUTING doc

The building scripts work if not in that docker image, so, I believe this is a problem of that specific docker image. I think we should fix the docker image and make it work with the existing set of scripts, that works everywhere else.

>  check-python-syntax script should check code in ./python/ccxt, correct?

Yes, however, that is again not a bug in the building scripts – that's a bug in the docker image. Put simply, this file is wrong: https://github.com/ccxt/ccxt/blob/master/Dockerfile . I didn't have the time to test, rewrite and fix it properly. Other files are probably ok.

**Comment by kroitor** [comment] 2020-05-08 12:45
P.S. The entire problem with Docker may also be related to deprecation of Python 2. CCXT is Python3-only since January 2020. The rest of the world has stopped supporting Python 2.

**Closed** 2020-05-09 22:02 UTC
Labels: question
