### ISSUE TITLE
BingX request for CCXT

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16673] opened 2023-01-29 15:30 UTC
### Exchange Name

BingX

### URL of the Exchange

https://www.bingx.com/en-us/

### URL of the Exchange's API docs

https://bingx-api.github.io/docs/swap/introduce.html

### Why should this exchange be implemented?

BingX has a wide range of perpetual futures being offered (73) as well as a very high daily volume (above 1 billion), thus it would be nice if it could be added as new exchange.

**Comment by sc0Vu** [comment] 2023-01-30 00:28
It's duplicate of issue ccxt/ccxt#13206, we'll keep that open.

**Closed by sc0Vu** 2023-01-30 00:28 UTC
Labels: new exchange
