### ISSUE TITLE
Is there any way to get a link for pair?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9345] opened 2021-06-09 20:54 UTC
I've read some old issues whichever I found, and just to confirm, there is not integrated in this library, the way to retrieve the url of pair, right? I mean i.e.  

`...->getLink('BTC/USDT')`
and if called for binance instance, it returned:
`https://www.binance.com/en/trade/BTC_USDT`
if called for bitfinex,
`https://trading.bitfinex.com/t/BTC:UST`

so, basically it is `siteurl{pair1}x{pair2}` where the divisor is different in most cases(sometimes empty even, like BTCUSDT).

I recall that denial reason was that exchanges change UI too frequently, and maintaining was hard. However, it might have been some help for users like me, who just want a link to exchange-chart in the app. would have been much useful feature. Exchanges doesn't change UI too quickly, might be once in 1-2-3 year, and people would PR the changes once in a several years, could have been experimental feature even, so users wouldn't rely, but just use it as an additional feature.

**Comment by kroitor** [comment] 2021-06-10 09:42
We understand the demand, but the problem is that the exchanges don't really document their web UIs, we've tried adding that before, and it caused more confusion with the outdated and half-working urls than it actually helped. At this point it's not among our priorities. 

> ...->getLink('BTC/USDT')

This won't work – Binance has 3 markets called BTC/USDT:
- spot BTC/USDT pair
- BTC/USDT usdt-margined linear contracts
- BTC/USDT coin-margined inverse contracts

Any "simple" solution here won't work, cause the exchanges have a lot of "aspects" and "sides"...

**Comment by kroitor** [comment] 2021-06-10 09:43
Closing this for now, feel free to reopen it if needed or just ask further questions if any. If you can suggest a decent schema that would account for the exchanges' specifics – we will consider adding it.

**Closed by kroitor** 2021-06-10 09:43 UTC
Labels: question

**Comment by ttodua** [comment] 2021-06-10 10:27
thanks for reply. well i didnt mean margin/etc/etc but the main, entrypoint (can be called so) chart is the spot chart. I dont think it needs to have a complex scheme, as i see that exchanges typically dont touch their chart links in less than 3 years(averagely, maybe even more). and the community might submit PRs once in a three year.

actually that link is not required part of library, but *very* related and useful in apps, which use ccxt and want to have a standartized way to give its users a link to "binance's btc/usdt" or "bittrex's ETH/usd" charts, as that thing also needs to fall under standartization actually, and might have been useful feature. I dont know , you'd better decide it.  thanks

**Comment by kroitor** [comment] 2021-06-10 10:29
@ttodua we will reconsider implementing it, thx for your feedback!

**Comment by ttodua** [comment] 2021-07-05 20:47
this might not be the best way, but there can be such thing in theory:

```
public static function chartlink($exchange, $pair="AAA/BBB", $reversed=false){
	if($reversed) 
		$pair=\swap_pair($pair,'/');

	$f= function($divisor, $uppercase=true) use ($pair){ $pair= str_replace('/',$divisor,$pair); return ($uppercase ? strtoupper($pair) : strtolower($pair)); };

	switch($exchange){
		case "aax": 		return "https://www.aax.com/spot/trade/" .$f(':');
		case "ascendex": 	return "https://ascendex.com/en/cashtrade-spottrading/" . \Puvox\standard_php_library::swap_pair($f('/', false),'/');
		case "bibox": 		return "https://www.bibox.com/en/exchange/full-screen/" .$f('_');
		case "bigone": 	return "https://big.one/en/trade/" . $f('-');
		case "binance": 	return "https://www.binance.com/en/trade/" .$f('_').'?type=spot';
		case "bitcoin": 	return "https://exchange.bitcoin.com/" . $f('-to-', false);
		case "bitcoincom": 	return "https://exchange.bitcoin.com/" . $f('-to-', false);
		case "bitfinex": 	return "https://trading.bitfinex.com/t/" . $f(':');
		case "bitflyer": 	return "https://lightning.bitflyer.com/trade/" . $f('');
		case "bitforex": 	return "https://www.bitforex.com/en/spot/" . $f('_', false);
		case "bitget": 		return "https://www.bitget.com/en/trade/" . $f('_', false);
		case "bithumbpro": return "https://www.bithumb.pro/en-us/spot/trade?q=" . $f('-');
		case "bithumb": 	return "https://en.bithumb.com/trade/order/" . $f('_');
		case "bitmart": 	return "https://www.bitmart.com/trade/en?layout=basic&symbol=" . $f('_');
		case "bitso": 		return "https://bitso.com/market/" . $f('/', false);
		case "bitstamp": 	return "https://www.bitstamp.net/markets/" . $f('/', false);
		case "bittrex": 		return "https://global.bittrex.com/Market/index?MarketName=" . $f('-');
		case "biki": 		return "https://m.biki.cc/trade/" . $f('_');
		case "bitget": 		return "https://www.bitget.com/en/trade/" . $f('_',false);
		case "bitkub": 		return "https://www.bitkub.com/market/" . self::remove_usd_part( $f('/') ) ;
		case "bitrue": 		return "https://www.bitrue.com/trade/" . $f('_',false);
		case "btcturk": 	return "https://pro.btcturk.com/en/pro/exchange/" . $f('_'); 
		case "cex": 		return "https://cex.io/" . $f('-',false);
		case "cexio": 		return "https://cex.io/" . $f('-',false);
		case "coinbase": 	return "https://pro.coinbase.com/trade/" . $f('-');
		case "coinbasepro": return "https://pro.coinbase.com/trade/" . $f('-'); 
		case "coincheck": 	return "https://coincheck.com/buys?pair=" . $f('_', false);
		case "coinhe": 		return "https://coinhe.io/trading/" . $f('-',false);
		case "coinsbit": 	return "https://coinsbit.io/en/trade_classic/" . $f('_');
		case "cointiger": 	return "https://www.cointiger.com/en-us/#/trade_pro?coin=" . $f('_',false);
		case "crypto": 		return "https://crypto.com/exchange/trade/" .$f('_');
		case "cryptocom": 	return "https://crypto.com/exchange/trade/" .$f('_');
		case "digifinex": 	return "https://www.digifinex.com/en-ww/trade/" . $f('/');
		case "exmo": 		return "https://exmo.com/en/trade/" . $f('_');
		case "ftx": 		return "https://ftx.com/trade/". $f('/');
		case "gateio": 		return "https://www.gate.io/trade/".$f('_');
		case "gemini": 		return "https://www.tradingview.com/chart/?symbol=GEMINI:" .$f('');
		case "hitbtc": 		return "https://hitbtc.com/" . $f('-to-', false);
		case "independentreserve": return "https://www.independentreserve.com/market/" . self::remove_usd_part( $f('/') );
		case "hoo": 		return "https://hoo.com/spot/" . $f('-',false);
		case "hotbit": 		return "https://www.hotbit.io/exchange?symbol=" . $f('_');
		case "huobi": 		return "https://www.huobi.com/en-us/exchange/" . $f('_',false);
		case "huobipro": 	return "https://www.huobi.com/en-us/exchange/" . $f('_',false);
		case "indodax": 	return "https://indodax.com/market/". $f('') ;
		case "kraken": 		return "https://trade.kraken.com/charts/KRAKEN:". $f('-');
		case "kucoin": 		return "https://trade.kucoin.com/" .$f('-');
		case "kuna": 		return "https://kuna.io/markets/" .$f('',false);
		case "latoken": 	return "https://latoken.com/exchange/" . $f('_');
		case "lbank": 		return "https://www.lbank.me/exchange/" .  $f('/', false);
		case "liquid": 		return "https://app.liquid.com/exchange/" .  $f('');
		case "luno": 		return "https://www.luno.com/trade/markets/" .  $f('');
		case "mercado": 	return "https://www.mercadobitcoin.com.br/negociacoes/" . self::remove_usd_part( $pair );
		case "mercadobitcoin": return "https://www.mercadobitcoin.com.br/negociacoes/" . self::remove_usd_part( $pair );  
		case "nicehash": 	return "https://www.nicehash.com/my/tradeview/" . $f('');
		case "novadax": 	return "https://www.novadax.com.br/product/orderbook?pair=" . $f('_');
		case "oceanex": 	return "https://oceanex.pro/en/m/trades/" . $f('', false);
		case "okex": 		return "https://www.okex.com/trade-spot/" . $f('-', false);
		case "okcion": 		return "https://www.okcoin.com/en/spot/trade/" . $f('-');
		case "phemex": 		return "https://phemex.com/spot/trade/" . $f(''); 
		case "poloniex": 	return "https://poloniex.com/exchange/" . \Puvox\standard_php_library::swap_pair( $f('_'), '_');
		case "probit": 		return "https://www.probit.com/app/exchange/" . $f('-');
		case "southxchange":return "https://main.southxchange.com/Market/Book/". $f('/');
		case "stek": 		return "https://app.stex.com/en/basic-trade/pair/" . \Puvox\standard_php_library::swap_pair( $f('/') );
		case "therock":		return "https://www.therocktrading.com/en/market/" . $f('');
		case "whitebit":	return "https://whitebit.com/trade/" . $f('_');
		case "upbit":		return "https://upbit.com/exchange?code=CRIX.UPBIT." . \Puvox\standard_php_library::swap_pair( $f('-'), '-');
		case "yobit":		return "https://yobit.net/en/trade/".$f('/');
		case "vcc":			return "https://api.vcc.exchange/exchange/basic?currency=".strtolower(explode('/',$pair)[1])."&coin=".strtolower(explode('/',$pair)[0]);
		case "xt":			return "https://www.xt.com/trade/" . $f('_',false);
		case "zaif":		return "https://zaif.jp/trade_" . $f('_',false);
		case "zb":			return "https://trans.zb.com/" . $f('',false); // "https://www.zb.com/en/lever-trade/" .  $f('_', false);
		default:			return "https://www.google.com/search?q=$exchange+" . $f('-');
	}
}
```

**Comment by kroitor** [comment] 2021-07-06 06:46
@ttodua thanks for your help!
