### ISSUE TITLE
How to open connection to exchange after closing it?

### ISSUE THREAD

**Issue by wardbradt** [ccxt/ccxt#3546] opened 2018-08-02 00:11 UTC
- Programming Language version: Python 3.6.5
- CCXT version: 3.14.301
- Exchange: Binance and all others
- Method: `close()` and `self.session`

If I run the following code:
```
def run_loop_forever():
    binance = ccxt.binance()
    while True:
        asyncio.get_event_loop().run_until_complete(fetch_and_sleep(binance))


async def fetch_and_sleep(exchange):
    tickers = await exchange.fetch_tickers()
    # -------------------
    # other code
    # -------------------
    await asyncio.sleep(10)
```
Eventually I get the below error
```
ccxt.base.errors.ExchangeNotAvailable: binance https://api.binance.com/api/v1/ticker/24hr GET [Errno 54] Connection reset by peer
```
**How can I close, then open, the connection to the exchange?** I have a potential solution below and would like to know if it would work.

I saw that `Exchange.__init__` in ccxt/async/base/exchange.py contains the following:
```
# Create out SSL context object with our CA cert file
context = ssl.create_default_context(cafile=certifi.where())
# Pass this SSL context to aiohttp and create a TCPConnector
connector = aiohttp.TCPConnector(ssl_context=context, loop=self.asyncio_loop)
self.session = aiohttp.ClientSession(loop=self.asyncio_loop, connector=connector)
```
Would the following work?
```
def run_loop_forever():
    binance = ccxt.binance()
    i = 0
    while True:
        asyncio.get_event_loop().run_until_complete(fetch_and_sleep(binance))
        i += 1
        if i % 10 == 0:
            asyncio.get_event_loop().run_until_complete(binance.close())
            binance = asyncio.get_event_loop().run_until_complete(open_connection(binance))


async def fetch_and_sleep(exchange):
    tickers = await exchange.fetch_tickers()
    # -------------------
    # other code
    # -------------------
    await asyncio.sleep(10)


async def open_connection(exchange):
    context = ssl.create_default_context(cafile=certifi.where())
    connector = aiohttp.TCPConnector(ssl_context=context, loop=exchange.asyncio_loop)
    exchange.session = aiohttp.ClientSession(loop=exchange.asyncio_loop, connector=connector)
    return exchange
```

**Comment by kroitor** [comment] 2018-08-02 09:56
> Eventually I get the below error
> `ccxt.base.errors.ExchangeNotAvailable: binance https://api.binance.com/api/v1/ticker/24hr GET [Errno 54] Connection reset by peer`
> How can I close, then open, the connection to the exchange? I have a potential solution below and would like to know if it would work.

You should shift your thinking paradigm. First, you need to understand what `ccxt.base.errors.ExchangeNotAvailable` is. That is an exception. 

An exception is an entity that is "thrown" or "sent" into your code from ccxt to indicate that there was an error. It also contains the type of the error and some debugging info in it, this particular type of exception is `ExchangeNotAvailable`. That type means that the exchange was not able to process your request. 

Also, CCXT is a REST library for now, so, it does not "connect to exchanges", meaning that it does not have any open hanging connections. It operates over HTTP, so it connects upon each request, gets the response, and disconnects. This is the nature of HTTP. You may be confused by the line that says `"Connection reset by peer"`. What it really says is *"well, your previous request failed and the connection associated with it was dropped... So what? ) Nevermind ) You can retry the same request again now or later, it will be a new connection each time"*.

So, instead of "closing" and "reopening" the "exchange connection" upon an exception, you should rather add proper exception handling code. You might think *"omg, how much of code should I add?"*, but actually, in order to handle the situation you described above, not much code is needed:

```Python
async def fetch_and_sleep(exchange):
    try:
        tickers = await exchange.fetch_tickers()
        # -------------------
        # other code
        # -------------------
    except ccxt.ExchangeNotAvailable as e:
        print("Got an exception:" + "\n" + str(e.args) + "\n" + Ignoring to repeat the attempt later.")
        # do nothing, ignore it
    await asyncio.sleep(10)
```

Exception handling and all possible exception types, along with their descriptions are documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

↑ This is only a half of the full story.

The second half of the story is about rate-limiting. You don't seem to use any rate-limiting whatsoever. Yet in the Manual it is emphasized in bold that you're required to enable the rate-limiter (explained below).

The second half of the story is about reasoning, namely the cause of the exception. If you're getting one, you don't always want to ignore it. If it is a recoverable error, like getting `ExchangeNotAvailable` (temporary not available) – then you're ok to just skip it occasionally and just repeat the attempt later. 

Yet, on a critical error you might want to pay attention to it and add more special handling into your system whatever it is you're building. Also, if you're catching `ExchangeNotAvailable` too often in a repeatable fashion – then you might want to look into the details of it more closely, and this is exactly the case with your particular issue. Whenever you start that script, it first works for a while, then it breaks. Then it doesn't work for some time. Then it starts working again and breaks a little bit later again.

The exact cause of the above behavior is the lack of rate-limiting in your code. Exchanges won't like you polling them very frequently, so they will ban you temprorarily (for 10 minutes to an hour) if you're too persistent. So you have to throttle your requests to not be too pushy on them. In order to do that, you should either add your own rate-limiting, like you did with `await asyncio.sleep(10)` or to enable the built-in rate-limiter and adjust it for your needs:

```Python
def run_loop_forever():
    binance = ccxt.binance({
        'enableRateLimit': True,  # ←--------------- add this
    })
    # ... 

async def fetch_and_sleep(exchange):
    try:
        tickers = await exchange.fetch_tickers()
        # -------------------
        # other code
        # -------------------
    except ccxt.ExchangeNotAvailable as e:
        print("Got an exception:" + "\n" + str(e.args) + "\n" + Ignoring to repeat the attempt later.")
        # do nothing, ignore it
    # await asyncio.sleep(10)  # ←----------------- remove this
```

The rate-limiting is also documented in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

↑ That is also not the end of it either ) Your case is even more special, you're fetching tickers. Many of them at once in each request. Exchanges will like that even less. So some exchanges may restrict fetchTickers and impose even more narrow rate limits for that specific call. The above `enableRateLimit` would be enough for practically any exchange... but not for Binance ) They don't allow fetching tickers too frequently, according to [Binance rate-limiting docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics) (they call it "weight" and a "heavy" fetchTickers request). They say, you should not fetch all tickers more frequently than once in 40 seconds. So, if your general usage pattern is to fetch all tickers in a loop from Binance, then you want to tweak the built-in rate limiter like so:

```Python
def run_loop_forever():

    binance = ccxt.binance({

        'enableRateLimit': True,  # ←--------------- add this

        # and this ↓

        'rateLimit': 40 * 1000,  # 40000 milliseconds between consecutive requests

    })
    # ... 

async def fetch_and_sleep(exchange):
    try:
        tickers = await exchange.fetch_tickers()
        # -------------------
        # other code
        # -------------------
    except ccxt.ExchangeNotAvailable as e:
        print("Got an exception:" + "\n" + str(e.args) + "\n" + Ignoring to repeat the attempt later.")
        # do nothing, ignore it
    # await asyncio.sleep(10)  # ←----------------- remove this
```

If you do the above edits, you should end up with this:

```Python
def run_loop_forever():
    binance = ccxt.binance({
        'enableRateLimit': True,  # enable built-in rate-limiter
        'rateLimit': 40 * 1000,  # 40000 milliseconds between consecutive requests

    })
    while True:
        asyncio.get_event_loop().run_until_complete(just_fetch_tickers(binance))

async def just_fetch_tickers(exchange):
    try:
        tickers = await exchange.fetch_tickers()
        # -------------------
        # other code
        # -------------------
    except ccxt.ExchangeNotAvailable as e:
        print("Got an exception:" + "\n" + str(e.args) + "\n" + Ignoring to repeat the attempt later.")
        # do nothing, ignore it

# -----------------------------------------------------------
# not needed ↓↓↓
# async def open_connection(exchange):
#    context = ssl.create_default_context(cafile=certifi.where())
#    connector = aiohttp.TCPConnector(ssl_context=context, loop=exchange.asyncio_loop)
#    exchange.session = aiohttp.ClientSession(loop=exchange.asyncio_loop, connector=connector)
#    return exchange

```

Hope the above answers your question )

**Closed by kroitor** 2018-08-02 09:56 UTC

**Comment by wardbradt** [comment] 2018-08-02 15:10
Thanks for the response. I do not know much about how the internals of RESTful HTTP work; I misinterpreted the meaning of closing the connection.

Also, Binance's rate limiting is structured around the weight of each request, with a public API request relating to a single symbol normally having a weight of 1. As you mentioned, the endpoint `fetch_tickers` requests has a weight of 40. The maximum weight anyone can request per minute is 1200, [per the exchange info](https://api.binance.com/api/v1/exchangeInfo). So, I believe I should be able to request it up to 30 times per minute. Despite this, I do think the error was caused by rate limiting or a lack of it in my code.

**Comment by kroitor** [comment] 2018-08-02 15:41
> The maximum weight anyone can request per minute is 1200, per the exchange info. So, I believe I should be able to request it up to 30 times per minute. 

Unfortunately, this is a little more complicated. Of course, I don't possess immediate info from their engine, but they used to apply machine-learning to profile users and if your behaviour is outstanding from the "common user pattern", then you will hit the limit even before you reach that maximum. This may be outdated a bit, but it used to work like this previously. And it aligns with what you reported.
