### ISSUE TITLE
Kucoin API error: Invalid KC-API-TIMESTAMP

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#5765] opened 2019-09-02 09:23 UTC
When fetching balances using kucoin i get error "Invalid KC-API-TIMESTAMP".

CCXT used is newest version today deployed, used setting and methods work for all other exchanges i use except kucoin (I tested binance, kraken, bitmex, bittrex)

- OS: Debian
- Programming Language version: PHP 7
- CCXT version: latest
- Exchange: kucoin
- Method: ->fetch_balance()

**Comment by kroitor** [comment] 2019-09-02 13:55
I cannot reproduce it on my side based on the input you've provided:

```PHP
mbp:ccxt igorkroitor$ php -f examples/php/cli.php kucoin fetch_balance
kucoin->fetch_balance ()
Array
(
    [info] => Array
        (
            [code] => 200000
            [data] => Array
                (
                    [0] => Array
                        (
                            [balance] => 0.00009788
                            [available] => 0.00009788
                            [holds] => 0
                            [currency] => BTC
                            [id] => 5c6a4fd399a1d81c4f9cc4d0
                            [type] => trade
                        )

                    [1] => Array
                        (
                            [balance] => 3.41060034
                            [available] => 3.41060034
                            [holds] => 0
                            [currency] => SOUL
                            [id] => 5c6a4d5d99a1d8182d37046d
                            [type] => trade
                        )
...
```

- Have you tried going through the troubleshooting sequence?
- Is it a new key?
- Have you tried with a new key?
- Have you checked your system clock?
- Have you checked your timezone?
- Have you checked your verbose output?
- ...

**Comment by kroitor** [comment] 2019-09-10 09:08
@janeCMD let us know if have a followup on this, closing it for now if you don't mind. Feel free to reopen it, or just ask further questions, if any.

**Closed by kroitor** 2019-09-10 09:08 UTC

**Comment by sebastianbugal** [comment] 2022-02-15 18:23
Hey, I am getting the same issue currently any idea what could be contributing to this?

**Comment by kroitor** [comment] 2022-02-15 18:27
@sebastianbugal make sure your system clock is synchronized with UTC. If you're on windows synchronizing the time on system clock settings does not help, the time still fluctuates, so you have to sync it every 10-15 minutes. On linux systems you can use ntpd.

**Comment by mohsenfiroozi1** [comment] 2023-04-08 08:54
I had a same problem. I couldn't solve it with synchronizing system clock with UTC. But I decreased my Python's release to 3.8.6.
The problem is solved.

**Comment by jonasdebeukelaer** [comment] 2023-11-06 03:13
Hi there, I'm getting this problem too, using python 3.11, 3.10, 3.9 and 3.8.6, running in a google run service. App runs fine locally. Any ideas on how to debug this?

**Comment by jonasdebeukelaer** [comment] 2023-11-19 05:44
I'm now getting this for 3.8.6 as well, intermittently. Please advise on how to debug this?
