### ISSUE TITLE
How to get all deposit networks/addresses of token?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15594] opened 2022-11-08 11:54 UTC
As you can see, Binance has 3 chains to deposit token COTI on their exchange,
When I use command `robot.binance.fetch_deposit_address("COTI")`
I got only ERC-20 network in responce: `{'currency': 'COTI', 'address': '0x642790bf32a7209a7c44c18e1b2526105a280990', 'tag': None, 'network': 'ERC20', 'info': {'coin': 'COTI', 'address': '0x642790bf32a7209a7c44c18e1b2526105a280990', 'tag': '', 'url': 'https://etherscan.io/address/0x642790bf32a7209a7c44c18e1b2526105a280990'}}`
Is it possible to get all networks for deposit for any coins?
![изображение_2022-11-08_165240124](https://user-images.githubusercontent.com/44064808/200557190-394f3d36-be88-46bb-9e46-60def2640550.png)

**Comment by samgermain** [comment] 2022-11-09 02:21
Duplicate of #15601

**Closed by samgermain** 2022-11-09 02:21 UTC
Labels: duplicate
