### ISSUE TITLE
Order Cache falling out of sync, Poloniex

### ISSUE THREAD

**Issue by tbrent** [ccxt/ccxt#1801] opened 2018-02-06 22:50 UTC
- OS: macOS 10.13.1
- Programming Language version: Python 2.7.14
- CCXT version: 1.10.981
- Exchange: Poloniex
- Method: ```fetchOrders```

First, thanks for working on such a fantastic library. Really. 🥇.
This is more of a question about best practices and less of an issue/bug.

Looking through the issue history, it looks like users often raise issues related to order fetching, and it looks like the culprit is almost always the order cache. Source:
- (https://github.com/ccxt/ccxt/issues/608)
- [304](https://github.com/ccxt/ccxt/issues/304#issuecomment-335508927)

I've been running into an issue with my Poloniex trades where fetchOrders will occasionally incorrectly return an order as completed and filled even though it was not. For example:

> {'status': 'closed', 'info': {'status': 'open', u'orderNumber': u'414719023990', u'type': 'limit', 'price': u'0.09735495', u'rate': u'0.09735495', u'amount': u'0.89599150', u'date': u'2018-02-06 10:33:59', u'total': u'0.08722920', u'margin': 0, 'side': u'sell', u'startingAmount': u'0.89599150'}, 'fee': None, 'timestamp': 1517913239000, 'price': 0.09735495, 'trades': None, 'side': u'sell', 'datetime': '2018-02-06T10:33:59.000Z', 'symbol': u'ETH/BTC', 'amount': 0.8959915, 'cost': 0.087229207682925, 'type': 'limit', 'id': u'414719023990', 'filled': 0.8959915, 'remaining': 0.0}

When I go to the Poloniex Trade History on the site, there is no corresponding trade. I'm assuming what is happening here is the order is not found during the fetchOpenOrders call, and that results in the order in the cache being marked as ```'closed'```, and the ```'filled'``` attribute gets set equal to the ```'amount'``` value. Looking back in my logs, I think this is the series of steps that results in this behavior:

1. ```cancelOrder``` results in a request timeout. 
2. ```fetchOrders``` returns a list of orders that indicates the order is still open. 
3. ```cancelOrder``` results in the "You have already called cancelOrder" message from Poloniex. 
4. ```fetchOrders``` returns a list of orders that indicates the order is closed and has been filled. 

Here are the corresponding logs I have for each step of 1-4. 

1. `poloniex POST https://poloniex.com/tradingApi request timeout poloniex POST https://poloniex.com/tradingApi request timeout`
2. order extracted from list of all orders:
`{'status': 'open', 'timestamp': 1517913239000, 'price': 0.09735495, 'datetime': '2018-02-06T10:33:59.000Z', 'cost': 0.0872292, 'id': u'414719023990', 'info': {'status': 'open', u'orderNumber': u'414719023990', u'type': 'limit', 'price': u'0.09735495', u'rate': u'0.09735495', u'amount': u'0.89599150', u'date': u'2018-02-06 10:33:59', u'total': u'0.08722920', u'margin': 0, 'side': u'sell', u'startingAmount': u'0.89599150'}, 'fee': None, 'trades': None, 'remaining': 0.8959915, 'symbol': u'ETH/BTC', 'amount': 0.8959915, 'type': 'limit', 'side': u'sell', 'filled': 0.0}`
3. `poloniex {"error":"You have already called cancelOrder or moveOrder on this order. Please wait for that call's response."} poloniex {"error":"You have already called cancelOrder or moveOrder on this order. Please wait for that call's response."}`
4. order extracted from list of all orders: 
`{'status': 'closed', 'info': {'status': 'open', u'orderNumber': u'414719023990', u'type': 'limit', 'price': u'0.09735495', u'rate': u'0.09735495', u'amount': u'0.89599150', u'date': u'2018-02-06 10:33:59', u'total': u'0.08722920', u'margin': 0, 'side': u'sell', u'startingAmount': u'0.89599150'}, 'fee': None, 'timestamp': 1517913239000, 'price': 0.09735495, 'trades': None, 'side': u'sell', 'datetime': '2018-02-06T10:33:59.000Z', 'symbol': u'ETH/BTC', 'amount': 0.8959915, 'cost': 0.087229207682925, 'type': 'limit', 'id': u'414719023990', 'filled': 0.8959915, 'remaining': 0.0}`

As you can see in step 4, ```ccxt``` thinks the order has been filled. 

Is there a best practice that I should follow that would circumvent this problem? Did the cache rework that I see referenced in [569](https://github.com/ccxt/ccxt/issues/569) occur? If not, can I help with the cache rework? 

I'm loving working with ```ccxt``` and again thanks for all your development effort, it's really appreciated.

**Comment by mkutny** [comment] 2018-02-07 10:20
I don't have a balance there, still suspect it has nothing to do with `cancelOrder`. Check if the following reproduces the bug (just try min prices/amounts so not to trigger a trade):
```sh
ccxt> node examples/js/cli createLimitBuyOrder ETH/BTC 0.00000001  0.00000001
ccxt> node examples/js/cli createLimitBuyOrder LTC/BTC 0.00000001  0.00000001
ccxt> node examples/js/cli fetchOrders
```
If you don't have `node` you may try the same with `php` (e.g. `php examples/php/cli`). Unfortunately, there is no python equivalent, so if you have neither I'm afraid you'll need to write a small python snippet.

**Comment by mkutny** [comment] 2018-02-07 11:59
And just out of curiosity: how long does it actually take to cancel an order on Poloniex? Is it seconds or minutes?

And that call to `cancelOrder` - is it blocking until the order is canceled or it returns with a kind of 'pending' state?

**Comment by tbrent** [comment] 2018-02-07 19:32
Cancel order on Poloniex is sub-second latency. Call is blocking.

```
print poloniex.createLimitBuyOrder('ETH/BTC', 1.0,  0.0001)
print poloniex.createLimitBuyOrder('LTC/BTC', 1.0,  0.0001)
print poloniex.fetchOrders()
```

Result
```
{'status': 'open', 'timestamp': 1518031777024, 'price': 0.0001, 'datetime': '2018-02-07T19:29:37.240Z', 'cost': 0.0, 'id': u'415473309949', 'info': {'status': 'open', 'amount': 1.0, u'resultingTrades': [], u'orderNumber': u'415473309949', 'timestamp': 1518031777024, 'price': 0.0001, 'type': 'limit', 'side': 'buy'}, 'fee': None, 'trades': [], 'side': 'buy', 'symbol': u'ETH/BTC', 'amount': 1.0, 'type': 'limit', 'remaining': 1.0, 'filled': 0.0}
{'status': 'open', 'timestamp': 1518031777527, 'price': 0.0001, 'datetime': '2018-02-07T19:29:37.527Z', 'cost': 0.0, 'id': u'150216477206', 'info': {'status': 'open', 'amount': 1.0, u'resultingTrades': [], u'orderNumber': u'150216477206', 'timestamp': 1518031777527, 'price': 0.0001, 'type': 'limit', 'side': 'buy'}, 'fee': None, 'trades': [], 'side': 'buy', 'symbol': u'LTC/BTC', 'amount': 1.0, 'type': 'limit', 'remaining': 1.0, 'filled': 0.0}
[{'status': 'open', 'timestamp': 1518031777000, 'price': 0.0001, 'datetime': '2018-02-07T19:29:37.000Z', 'cost': 0.0001, 'id': u'150216477206', 'info': {'status': 'open', u'orderNumber': u'150216477206', u'type': 'limit', 'price': u'0.00010000', u'rate': u'0.00010000', u'amount': u'1.00000000', u'date': u'2018-02-07 19:29:37', u'total': u'0.00010000', u'margin': 0, 'side': u'buy', u'startingAmount': u'1.00000000'}, 'fee': None, 'trades': None, 'remaining': 1.0, 'symbol': u'LTC/BTC', 'amount': 1.0, 'type': 'limit', 'side': u'buy', 'filled': 0.0}, {'status': 'open', 'timestamp': 1518031776000, 'price': 0.0001, 'datetime': '2018-02-07T19:29:36.000Z', 'cost': 0.0001, 'id': u'415473309949', 'info': {'status': 'open', u'orderNumber': u'415473309949', u'type': 'limit', 'price': u'0.00010000', u'rate': u'0.00010000', u'amount': u'1.00000000', u'date': u'2018-02-07 19:29:36', u'total': u'0.00010000', u'margin': 0, 'side': u'buy', u'startingAmount': u'1.00000000'}, 'fee': None, 'trades': None, 'remaining': 1.0, 'symbol': u'ETH/BTC', 'amount': 1.0, 'type': 'limit', 'side': u'buy', 'filled': 0.0}]```

Working as intended.

**Comment by tbrent** [comment] 2018-02-07 23:13
I'm also seeing the opposite result -- an order is set to `closed` and has a `filled` of 0.0, but the order has filled on Poloniex for some amount. 

This order was partially filled on Poloniex. 
```{'status': 'canceled', 'timestamp': 1518043845000, 'price': 0.10036971, 'datetime': '2018-02-07T22:50:45.000Z', 'cost': 0.3284818, 'id': u'415543444744', 'info': {'status': 'open', u'orderNumber': u'415543444744', u'type': 'limit', 'price': u'0.10036971', u'rate': u'0.10036971', u'amount': u'3.27271850', u'date': u'2018-02-07 22:50:45', u'total': u'0.32848180', u'margin': 0, 'side': u'buy', u'startingAmount': u'3.27271850'}, 'fee': None, 'trades': None, 'remaining': 3.2727185, 'symbol': u'ETH/BTC', 'amount': 3.2727185, 'type': 'limit', 'side': u'buy', 'filled': 0.0}```

**Comment by kroitor** [comment] 2018-02-07 23:20
@tbrent can you please show a snippet of code, namely how you placed the order and how you canceled it.

**Comment by tbrent** [comment] 2018-02-07 23:51
I'm pulling these out of a much larger script so there is code I'm not showing, but this reflects the ordering correctly and I'm not omitting any ```ccxt``` function calls to poloniex that happen in between.

```
order = self.poloniex.createLimitBuyOrder(self.market, amount_coin_2_to_buy, case_2_poloniex_bid)
....
poloniex_orderbook = self.poloniex.fetchL2OrderBook(self.market)
open_ask_order, open_bid_order, last_ask_order, last_bid_order = self.get_poloniex_orders()
# Here open_bid_order contains the same result as the order variable from up above
cancel = self.poloniex.cancelOrder(open_ask_order['id'])
...
open_ask_order, open_bid_order, last_ask_order, last_bid_order = self.get_poloniex_orders()
# Here, depending on which failure case I'm encountering, either last_buy_order is improperly None (I see a trade on Poloniex) or last_ask_order isn't None when it should be (I do not see a trade on Poloniex)

def get_poloniex_orders(self):
    orders = sorted(self.poloniex.fetchOrders(symbol=self.market), key=lambda x: x['timestamp'], reverse=True)
    open_ask_orders = [o for o in orders if o['side'] == 'sell' and o['status'] == 'open']
    open_bid_orders = [o for o in orders if o['side'] == 'buy' and o['status'] == 'open']
    closed_ask_orders = [o for o in orders if o['side'] == 'sell' and o['status'] != 'open' and o['filled'] > 0.0]
    closed_bid_orders = [o for o in orders if o['side'] == 'buy' and o['status'] != 'open' and o['filled'] > 0.0]
    open_ask_order = open_ask_orders[0] if len(open_ask_orders) >= 1 else None
    open_bid_order = open_bid_orders[0] if len(open_bid_orders) >= 1 else None
    last_ask_order = closed_ask_orders[0] if len(closed_ask_orders) >= 1 else None
    last_bid_order = closed_bid_orders[0] if len(closed_bid_orders) >= 1 else None
    return open_ask_order, open_bid_order, last_ask_order, last_bid_order
```

Let me know how I can be more helpful! My script runs successfully for 12-24 hours on average (successfully) before the cache eventually goes out of sync, so I think these are very niche corner cases. Also it's worth mentioning that I reset the cache every 15 minutes, with ```self.poloniex.orders = {}```. That could be complicating things, though I can confirm from looking at my logs that the reset did not occur near the times the cache fell out of sync.

**Comment by kroitor** [comment] 2018-02-08 00:09
> Also it's worth mentioning that I reset the cache every 15 minutes, with self.poloniex.orders = {}.

This was worth mentioning from the very beginning, as this is most likely the reason for the inconsistencies above, as proper order caching relies on info in `.orders`, so if you drop it regularly – you will have a regular crash. It wasn't designed to be dropped at all. You can probably safely remove the already-closed orders, if you're not interested in them, but you can't just set `self.poloniex.orders = {}`.

Have you tried not resetting the cache?

**Comment by tbrent** [comment] 2018-02-08 00:41
I am looking at the logs I have from the occurrence where the cache assigns an order a status of `'closed'` and a `'filled'` of `0.0`, the order from the 5th post in this thread. (Note: This is NOT the failure case I originally posted about)

Before the bug occurs, the cache is reset, open orders are canceled (it probably would be better to reverse this order, but the problem with the Poloniex API is they don't provide a way to query _closed_ orders, correct? So it should still successfully query for open orders after the cache is reset) and I begin again the cycle of placing and cancelling orders. The cache does not fall out of sync at this step. The cache falls out of sync much later, around the ~101th order after ~100 orders have been successfully placed and canceled after the reset.

I agree resetting the cache seems likely to be the proximate cause of the bug, but I would expect the bug to occur after the reset, or for the bug to be about an order that was placed before the reset that `ccxt` was then unable to determine had actually closed. 

Regardless, I'll try not resetting the order cache since I agree the outside view would place a high probability on that being related. 

Thanks for your efforts on this library again.

**Comment by mkutny** [comment] 2018-02-08 15:32
Do you happen to `fetchOrders` by a symbol? Because if you do it may describe your original question.

Snippet (now correct) to reproduce:
```python
await polo.createLimitBuyOrder('ETH/BTC', 0.00000001,  0.00000001)
await polo.createLimitBuyOrder('LTC/BTC', 0.00000001,  0.00000001)
await polo.fetchOrders('ETH/BTC')
```

With regard to:
> I'm also seeing the opposite result -- an order is set to `closed` and has a filled of 0.0, but the order has filled on Poloniex for some amount.

In the snippet that follows the order is canceled, not closed. What you see in the `info` field is an original (cached) response received during order creation. It's carved there forever and does not follow order lifecycle.

**Comment by tbrent** [comment] 2018-02-08 18:39
I'm going to have to wait until Binance trades are back up to report back on the impact of removing the cache reset. 

Following up with @mkutny, I ran the following:


```
print p.createLimitSellOrder('ETH/BTC', 1.0, 1000)
print p.createLimitBuyOrder('BCH/ETH', 1.0, 0.0001)
print p.fetchOrders('ETH/BTC')
```

because I only had balance in ETH to test with, but it should map to your example (note I have here a buy and a sell vs two buys). Also, I'm not sure how you're able to get your orders to go through with such low amounts and prices -- I always get an error indicating the trade amount must be larger, hence the different values I'm using here.

Output:
```
{'status': 'open', 'timestamp': 1518108203212, 'price': 1000.0, 'datetime': '2018-02-08T16:43:23.212Z', 'cost': 0.0, 'id': u'415899251581', 'info': {'status': 'open', 'amount': 1.0, u'resultingTrades': [], u'orderNumber': u'415899251581', 'timestamp': 1518108203212, 'price': 1000.0, 'type': 'limit', 'side': 'sell'}, 'fee': None, 'trades': [], 'side': 'sell', 'symbol': u'ETH/BTC', 'amount': 1.0, 'type': 'limit', 'remaining': 1.0, 'filled': 0.0}
{'status': 'open', 'timestamp': 1518108205849, 'price': 0.0001, 'datetime': '2018-02-08T16:43:25.849Z', 'cost': 0.0, 'id': u'26100270793', 'info': {'status': 'open', 'amount': 1.0, u'resultingTrades': [], u'orderNumber': u'26100270793', 'timestamp': 1518108205849, 'price': 0.0001, 'type': 'limit', 'side': 'buy'}, 'fee': None, 'trades': [], 'side': 'buy', 'symbol': u'BCH/ETH', 'amount': 1.0, 'type': 'limit', 'remaining': 1.0, 'filled': 0.0}
[{'status': 'open', 'timestamp': 1518108201000, 'price': 1000.0, 'datetime': '2018-02-08T16:43:21.000Z', 'cost': 1000.0, 'id': u'415899251581', 'info': {'status': 'open', u'orderNumber': u'415899251581', u'type': 'limit', 'price': u'1000.00000000', u'rate': u'1000.00000000', u'amount': u'1.00000000', u'date': u'2018-02-08 16:43:21', u'total': u'1000.00000000', u'margin': 0, 'side': u'sell', u'startingAmount': u'1.00000000'}, 'fee': None, 'trades': None, 'remaining': 1.0, 'symbol': u'ETH/BTC', 'amount': 1.0, 'type': 'limit', 'side': u'sell', 'filled': 0.0}]
```

In my original examples I am calling fetchOrders by symbol, but all orders I'm placing or fetching fall under the same symbol. So I'm not sure whatever you're bug you're investigating over at #1830 is related.

**Comment by mkutny** [comment] 2018-02-08 19:55
Thanks for following up on this!

Despite cache logic is the same (as to my eyes) the behavior is different from liqui. I don't have a balance on poloniex to check why. My wild guess is that maybe polo returns all orders with `fetchOrders(symbol)`, not limited by the symbol.

You could check that with .verbose property but I don't want to bother you with it.

> Also, I'm not sure how you're able to get your orders to go through with such low amounts and prices

On liqui I go with ('BTC/USDT', 1, 1). For polo I just picked what supposed to be their min limits (provided by fetchMarkets). Given those throw an error maybe these limits are not correct.

**Comment by mkutny** [comment] 2018-02-08 20:09
You know, the only place Polo sets status to 'closed' is here:
https://github.com/ccxt/ccxt/blob/85a91d983010c928c180d51932206c9e05b9ae50/js/poloniex.js#L562-L568

I'd enabled `.verbose` mode and set a DEBUG logging on line 562 which would print current cache. This way you'll be able to match requests, responses and cache updates. Hopefully, this will give an insight what does not behave properly.

**Comment by mkutny** [comment] 2018-02-08 20:27
> print p.fetchOrders('ETH/BTC')

Oops, we forgot to dump the cache after this line. Sorry for that (

```python
print p.createLimitSellOrder('ETH/BTC', 1.0, 1000)
print p.createLimitBuyOrder('BCH/ETH', 1.0, 0.0001)
print p.fetchOrders('ETH/BTC')
print p.orders
```

**Comment by mkutny** [comment] 2018-02-08 21:00
Ok, I finally figured out what's going on.

> I've been running into an issue with my Poloniex trades where fetchOrders will occasionally incorrectly return an order as completed and filled even though it was not... When I go to the Poloniex Trade History on the site, there is no corresponding trade.

> I'm assuming what is happening here is the order is not found during the fetchOpenOrders call, and that results in the order in the cache being marked as 'closed', and the 'filled' attribute gets set equal to the 'amount' value.

You're absolutely right! And it does related to cancelOrder.

So when you cancel an order and then you fetch (open) orders, the order is not in the cache indeed. So ccxt marks it as 'closed' although it was canceled in reality. It would be more appropriate to set the status to `undefined` because we really don't know what happened to that order but I would be not quite comfortable with that.

> Is there a best practice that I should follow that would circumvent this problem? Did the cache rework that I see referenced in 569 occur? If not, can I help with the cache rework?

It does not work as we would like it to be but what exactly the problem you have with that? I mean how does it impact your trading logic?

**Comment by mkutny** [comment] 2018-02-08 21:23
Looks like `cancelOrder` needs to catch `CancelPending` exception and force update the cache.

**Comment by tbrent** [comment] 2018-02-08 22:31
Ah this is making more sense. Thanks for looking into it!

Putting aside the issue of the `undefined` solution since that's a major change, would `fetchOrder` after `cancelOrder` also handle the problem? 

Another thing I have noticed is a great way to get your cache to go out of sync is to call `fetchOrders` with a `limit` value. Once you get enough orders placed above the limit threshold things get funky in the cache, but I think that's expected behavior given the way the cache works.

**Comment by mkutny** [comment] 2018-02-09 10:28
> Putting aside the issue of the undefined solution since that's a major change, would fetchOrder after cancelOrder also handle the problem?

It will be fixed in #1849. Still, I'd appreciate if you could create an order, then send a non-blocking cancellation request and then tried to fetch order in `verbose` mode. We know that Polo responds with `pending` for subsequent cancellation but I wonder what will it respond with on fetch.

> Another thing I have noticed is a great way to get your cache to go out of sync is to call fetchOrders with a limit value.

Right. It won't cause any harm now because in their current state neither Liqui nor Polo limit number of returned orders but we surely need to keep it in mind in case they start too.

**Closed** 2018-02-09 10:49 UTC

**Comment by tbrent** [comment] 2018-02-11 03:29
I've upgraded to 1.10.1074 and I'm still hitting this bug. Here are my logs from most recent run showing where it occurred when a bid failed to cancel due to a request timeout. 

```
DEBUG:root:Canceling Bid # Print message before calling cancelOrder with id '416986457287'
DEBUG:root:poloniex POST https://poloniex.com/tradingApi request timeout poloniex POST https://poloniex.com/tradingApi request timeout
DEBUG:root:------
DEBUG:root:2018-02-10 18:40:02.370603
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "GET /api/v1/depth?symbol=ETHBTC HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): poloniex.com
DEBUG:urllib3.connectionpool:https://poloniex.com:443 "GET /public?command=returnOrderBook&currencyPair=BTC_ETH HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "GET /api/v3/account?timestamp=1518316802758&recvWindow=5000&signature=14c9f10ae424c72182d72a9a967fea24ee9081fd42d40d67a33f6fd4bdf86e44 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://poloniex.com:443 "POST /tradingApi HTTP/1.1" 200 None
DEBUG:root:Completed ask orders: 1
DEBUG:root:Completed bid orders: 1
DEBUG:root:Open ask: None
DEBUG:root:Open bid: None
DEBUG:root:Closed ask: {'status': 'canceled', 'timestamp': 1518316474000, 'price': 0.10017855, 'datetime': '2018-02-11T02:34:34.000Z', 'cost': 0.07353471, 'id': u'416984691055', 'info': {'status': 'open', u'orderNumber': u'416984691055', u'type': 'limit', 'price': u'0.10017855', u'rate': u'0.10017855', u'amount': u'0.73403649', u'date': u'2018-02-11 02:34:34', u'total': u'0.07353471', u'margin': 0, 'side': u'sell', u'startingAmount': u'0.80955837'}, 'fee': None, 'trades': None, 'remaining': 0.73403649, 'symbol': u'ETH/BTC', 'amount': 0.80955837, 'type': 'limit', 'side': u'sell', 'filled': 0.07552187999999993}
DEBUG:root:Closed bid: {'status': 'closed', 'info': {'status': 'open', u'orderNumber': u'416986457287', u'type': 'limit', 'price': u'0.09928044', u'rate': u'0.09928044', u'amount': u'0.07966888', u'date': u'2018-02-11 02:39:42', u'total': u'0.00790956', u'margin': 0, 'side': u'buy', u'startingAmount': u'0.07966888'}, 'fee': None, 'timestamp': 1518316782000, 'price': 0.09928044, 'trades': None, 'side': u'buy', 'datetime': '2018-02-11T02:39:42.000Z', 'symbol': u'ETH/BTC', 'amount': 0.07966888, 'cost': 0.007909561460707199, 'type': 'limit', 'id': u'416986457287', 'filled': 0.07966888, 'remaining': 0.0}
# Here you can see order given by id '416986457287' showing that it was filled for 0.0796. The poloniex UI shows that no bid completed during this time. 
```

This is without any cache reset on my part.

**Comment by mkutny** [comment] 2018-02-11 07:33
Thanks! A really nice-looking log, I'd put it as an example into "How to submit an issue" section )

> it occurred when a bid failed to cancel due to a request timeout

The issue is that it's got canceled on the exchange side, indeed. I added an explanation on how to handle `RequestTimeout` exceptions into the manual here: #1870. I'd like to know if you find it enough to answer your question or maybe you have a suggestion how to phrase it in a better language.

**Comment by tbrent** [comment] 2018-02-11 20:38
The Manual edits look good. Language is understandable. Thanks for taking the time to dive into this. Really appreciate it as well as everything you guys are doing. 

Just to add-in an additional check here for anyone else who looks at this issue later on: in addition to re-trying `cancelOrder` requests you can also track your balance over time, and only honor filled orders if your balance changed nearby when that order was reported as filled. Both these solutions in tandem should be enough to ensure you don't falsely act on an order being executed. 

Thanks again :)
