### ISSUE TITLE
Bit-z: SSL certificate verification failed (Python)

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2459] opened 2018-04-04 23:18 UTC
- OS: Windows
- Programming Language version: Python 
- CCXT version: 1.12.80
- Exchange: Bit-Z
- Method: 

Request: GET https://www.bit-z.com/api_v1/tickerall {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

ExchangeError ("bitz https://www.bit-z.com/api_v1/tickerall GET HTTPSConnectionPool(host='www.bit-z.com', port=443): Max retries exceeded with url: /api_v1/tickerall (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))",) Error

Is it the same problem?
https://github.com/ccxt/ccxt/issues/882

**Comment by kroitor** [comment] 2018-04-04 23:50
Yes, looks like it. What's your `python --version`? Have you tried https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting ?

**Comment by wntsang4** [comment] 2018-04-04 23:56
I am using python 3.6.4.
I have tested it on a new machine with a new IP and got the same error.

**Comment by kroitor** [comment] 2018-04-04 23:59
@wntsang4 can you try reinstalling the dependencies with pip? Pay attention to any libssl versions you have installed... this problem is also frequently caused by outdated root CA files that come with your ssl lib.

**Comment by wntsang4** [comment] 2018-04-05 16:13
aiodns (1.1.1)
aiohttp (3.1.1)
async-timeout (2.0.1)
attrs (17.4.0)
cchardet (2.1.1)
ccxt (1.12.87)
certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
idna-ssl (1.0.1)
multidict (4.1.0)
pip (9.0.3)
pycares (2.3.0)
requests (2.18.4)
setuptools (38.5.1)
urllib3 (1.22)
yarl (1.1.1)

I tried to reinstall all the dependencies with pip and got below response.

Request: GET https://www.bit-z.com/api_v1/tickerall {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.bit-z.com/api_v1/tickerall 403 {'Date': 'Thu, 05 Apr 2018 16:03:50 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Via-JSL': '65dea62,-', 'Set-Cookie': '__jsluid=15b89504a0297cad520942db470a0f88; max-age=31536000; path=/; HttpOnly', 'X-Cache': 'error', 'Content-Encoding': 'gzip'} <!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
body{ background:#fff; font-family: microsoft yahei; color:#969696; font-size:14px;}
.online-desc-con { text-align:center; }
.r-tip01 { color: #333; font-size: 18px; display: block; text-align: center; width: 500px; padding: 0 10px; overflow: hidden; text-overflow: ellipsis; margin: 0 auto 15px; }
.r-tip02 { color: #585858; font-size: 14px; display: block; margin-top: 20px; margin-bottom: 20px; }
#notice-jiasule {
  word-wrap: break-word;
  word-break: normal;
  color:#585858;
  border:1px solid #ddd;
  padding:0px 20px 0px 20px
}
img { border: 0; }
.u-ico{ vertical-align: middle; margin-right: 12px;}
.btn{ padding: 8px 22px; border-radius: 3px; border: 0; display: inline-block;vertical-align: middle;text-decoration: none;}
.btn-g{ background-color: #61b25e; color: #fff;}
.report {color: #858585; text-decoration: none;}
.report:hover {text-decoration: underline; color: #0088CC;}
hr{ border-top: 1px dashed #ddd;}
center{ line-height: 48px; color: #919191;}
</style>
<script type="text/template" id="content_tpl">
    <span class="r-tip01"><%= error_403 %></span>
    <div id='notice-jiasule'>
        <p>å½åç½åï¼<%- url %></p>
        <p>å®¢æ·ç«¯ç¹å¾ï¼<%- user_agent %></p>
        <p>æ¦æªæ¶é´ï¼<%- now %>&nbsp;&nbsp;æ¬æ¬¡äºä»¶ID&nbsp;<%- rule_id %></p>
    </div>
    <span class='r-tip02'>
        <img class='u-ico' alt='' src='/cdn-cgi/image/guest.png' />å¦ææ¨æ¯ç½ç«ç®¡çåï¼è¯·ç»å½ç¥éåå®äºå®å¨&nbsp;
        <a class='btn btn-g' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#pus' target='_blank'>æ¥çè¯¦æ</a>
        &nbsp;æè&nbsp;
        <a class='report' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#hus' target='_blank'>åé¦è¯¯æ¥</a>
    </span>
</script>
<script type="text/javascript" src="/cdn-cgi/js/underscore_min_1.8.3.js"></script>
</head>
<body>
<div class="online-desc-con" style="width:640px;padding-top:15px;margin:34px auto;">
	<img alt="" style="margin: 0 auto 17px auto;" src="/cdn-cgi/image/protected.png" />
    <div id="content_rendered"></div>
	<hr />
	<center>client: 223.17.160.219, server: 65dea62, time: 2018-04-06 00:03:50</center>
</div>
<script>
void(function fuckie6(){if(location.hash && /MSIE 6/.test(navigator.userAgent) && !/jsl_sec/.test(location.href)){location.href = location.href.split('#')[0] + '&jsl_sec' + location.hash}})();
var content = _.template(document.getElementById('content_tpl').innerHTML)({
    error_403: '' || 'å½åè®¿é®çä¼¼é»å®¢æ»å»ï¼å·²è¢«ç½ç«ç®¡çåè®¾ç½®ä¸ºæ¦æª',
    url: document.URL.replace(/\</g,"%3C").replace(/\>/g,"%3E"),
    user_agent: navigator.userAgent,
    now: new Date(new Date() - -8 * 3600000).toISOString().substr(0, 19).replace('T', ' '),
    rule_id: parseInt('[80001]'.replace(/\[|\]/g, '')) || '',
    from: encodeURIComponent(document.referrer.substr(0, 1024)),
    client_ip: '223.17.160.219',
    ref: encodeURIComponent(document.URL.substr(0, 1024))
});
document.getElementById('content_rendered').innerHTML = content;
</script>
<div style="display:none;">
    <script>
        var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fd7682ab43891c68a00de46e9ce5b76aa' type='text/javascript'%3E%3C/script%3E"));
    </script>
</div>
</body>

</html>

**Comment by kroitor** [comment] 2018-04-05 20:46
Is this URL https://www.bit-z.com/api_v1/tickerall available from the same machine in your browser?

**Comment by wntsang4** [comment] 2018-04-06 02:48
Yes

**Comment by kroitor** [comment] 2018-04-06 02:54
@wntsang4 are you using the sync or the async version?

**Comment by wntsang4** [comment] 2018-04-06 02:57
sync version

**Comment by kroitor** [comment] 2018-04-06 02:58
Ok, I'll spend some more time debugging it and will get back to you on this issue. This is most likely due to openssl installation that either comes with Anaconda Python or with a dependecy... Do you know which version of OpenSSL you have?

**Comment by kroitor** [comment] 2018-04-06 03:02
@wntsang4 can you also try pip-uninstalling the `certifi` package to see if it does work normally without it, plz?

**Comment by wntsang4** [comment] 2018-04-06 03:03
'OpenSSL 1.0.2k  26 Jan 2017'

After uninstalling the certifi package, it shows
ModuleNotFoundError: No module named 'certifi'

**Comment by kroitor** [comment] 2018-04-06 03:04
@wntsang4 oh... I'll update it to make certifi optional...

**Comment by kroitor** [comment] 2018-04-06 03:06
@wntsang4 can you plz show your instantiation code?

**Comment by wntsang4** [comment] 2018-04-06 03:09
bitz = ccxt.bitz({
    'apiKey': key,
    'secret': secret,
    'enableRateLimit': True,
    'verbose': True,
})

order_book = bitz.fetch_order_book('LTC/BTC', 3)

**Comment by kroitor** [comment] 2018-04-06 03:27
Yep, it's a python specific-problem, that is caused by transition to a new format of OpenSSL certificates in the community... Apart from the above workaround we can't really do much about it, because it is far beyond our codebase (it's an issue with certifi + OpenSSL + python), therefore some exchanges with older OpenSSL certificates will require the userAgent, which is very non-intuitive... Hope to resolve it soon. I would close it for now if you don't mind. Feel free to reopen it if needed or just ask questions if you have more.

https://www.google.ru/search?q=python+CERTIFICATE_VERIFY_FAILED+777

Thx for your feedback!

**Closed by kroitor** 2018-04-06 03:27 UTC

**Comment by alexsith** [comment] 2018-04-06 04:13
Hi. I just leave comment here. I had the same issue and I didn't do anything about this bug. I guess bitz did some upgrade and broke something. It had been happening for couple days if I correct remember and after that it's gone.

**Comment by kroitor** [comment] 2018-04-06 04:14
Thanks for your involvement, @alexsith !
