### ISSUE TITLE
problem with exchange.parse8601()

### ISSUE THREAD

**Issue by werewere** [ccxt/ccxt#414] opened 2017-10-28 15:24 UTC
Hi, this problem happens randomly so I'm not sure if it has something to do with ccxt itself or if it may be a race condition in my threaded program. From time to time, not always, when I call exchange.parse8601(), it shows the following exception:

```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "nemesis2.py", line 437, in stream_ohlcv
    from___ = exchange.parse8601(from__) 
  File "/Library/Python/2.7/site-packages/ccxt/exchange.py", line 589, in parse8601
    dt = datetime.datetime.strptime(string, "%Y%m%d%H%M%S.%fZ")
AttributeError: 'module' object has no attribute '_strptime'
```

My code is as follows (I'm using relativedelta to extract the last 100 candles since the last time):

```
now = datetime.datetime.now()
from_ = now - relativedelta (minutes=100)
from__='{:%Y-%m-%d %H:%M:%S}'.format(from_)
from___ = exchange.parse8601(from__)
data = exchange.fetch_ohlcv("ETH/USD", "5m", from___)
```

**Comment by kroitor** [comment] 2017-10-28 15:34
Hi, @werewere !

Why do you use parse8601 there at all? You don't need to convert a number (a time value) to to string just to parse it back to a number. Try this:

```
now = exchange.milliseconds ()
from_ = now - 5 * 60 * 1000 * 100  # now - 5 minutes * 60 seconds * 1000 ms * 100 candles
data = exchange.fetch_ohlcv("ETH/USD", "5m", from_)
```

**Comment by kroitor** [comment] 2017-10-28 17:14
Can you paste the shortest possible snippet that is short enough for posting, but works (can be launched) and reproduces/demonstrates the problematic case or the error?

**Comment by werewere** [comment] 2017-10-28 17:51
Yep, you're right. I was doing it more complicated than needed! Your solution is much more elegant.

Regarding the shortest snippet, here goes it (well, its not the shortest-shortest, but I wanted to keep some info). I'm keeping my (bad) number->string->number design to keep it real. It fails about 1/10 times (anyway I just removed the parse8601 method thanks to your solution, so I'm putting it here just for debugging purposes in case it may be some bug in ccxt):

```
import ccxt
import time
import threading
import datetime
from dateutil.relativedelta import *

exchange   = ccxt.poloniex({
    'apiKey': 'KEY',
    'secret': 'SECRET',
})
class Feed (object):

    def __init__(self, instruments=["ETH/BTC", "XRP/BTC", "BCH/BTC"]):
        self.candles=["5m", "15m", "1d"]
        self.candle_dict = {}
        self.lock = threading.Lock()

        for instrument in instruments: #1 thread per pair
            thread = threading.Thread(target=self.stream_ohlcv, args=(instrument,))
            thread.daemon = True
            thread.start()

    def stream_ohlcv(self, instrument="ETH/BTC"):
        while 1:
                try:
                        for candle in self.candles:
                            now = datetime.datetime.utcnow()

                            if candle == "1m":
                                from_ = now - relativedelta (minutes=100)
                            elif candle=="5m":
                                from_ = now - relativedelta (minutes=500)
                            elif candle=="1h":
                                from_ = now - relativedelta (hours=100)
                            elif candle=="1d":
                                from_ = now - relativedelta (days=100)

                            from__='{:%Y-%m-%d %H:%M:%S}'.format(from_)

                            from___ = exchange.parse8601(from__) 

                            data = exchange.fetch_ohlcv(instrument, candle, from___)
                            #do things with data

                except ccxt.RequestTimeout as e: 
                    print(type(e).__name__, e.args, 'Request Timeout (ignoring)')
                except ccxt.ExchangeNotAvailable as e:
                    print(type(e).__name__, e.args, 'Exchange Not Available due to downtime or maintenance (ignoring)')
                except ccxt.AuthenticationError as e:
                    print(type(e).__name__, e.args, 'Authentication Error (missing API keys, ignoring)')

                time.sleep(5)

feed = Feed(["ETH/BTC", "XRP/BTC", "BCH/BTC"])

```

**Comment by kroitor** [comment] 2017-10-29 05:19
@werewere no matter what I do, I can't get an error from this:

```Python
import ccxt
import time
import threading
import datetime

durations = {
    '5m':       5 * 60 * 1000,
    '15m':     15 * 60 * 1000,
    '1d': 24 * 60 * 60 * 1000,
}

class Feed (object):

    def __init__(self, instruments=["ETH/BTC", "XRP/BTC", "BCH/BTC"]):
        self.candles=["5m", "15m", "1d"]
        self.candle_dict = {}
        self.lock = threading.Lock()

        for instrument in instruments: #1 thread per pair
            thread = threading.Thread(target=self.stream_ohlcv, args=(instrument,))
            thread.daemon = True
            thread.start()

    def stream_ohlcv(self, instrument="ETH/BTC"):

        exchange = ccxt.poloniex({'enableRateLimit': True})

        while 1:
                try:
                    for candle in self.candles:
                        from_ = durations[candle]
                        data = exchange.fetch_ohlcv(instrument, candle, exchange.milliseconds() - from_)
                        print (exchange.iso8601 (from_), candle, instrument)
                        #do things with data

                except ccxt.RequestTimeout as e:
                    print(type(e).__name__, e.args, 'Request Timeout (ignoring)')
                except ccxt.ExchangeNotAvailable as e:
                    print(type(e).__name__, e.args, 'Exchange Not Available due to downtime or maintenance (ignoring)')
                except ccxt.AuthenticationError as e:
                    print(type(e).__name__, e.args, 'Authentication Error (missing API keys, ignoring)')


feed = Feed(["ETH/BTC", "XRP/BTC", "BCH/BTC"])
time.sleep(10000)
```

This is the same snippet as yours, but there are a few differences:

1. In your original example you loop through candles= [ '5m', '15m', '1d' ] (← no 1m interval here), whereas in your if/else you check for 1m, 5m, 1h, 1d (← no 15m interval here)...

2. time.sleep was 5 seconds, which is an overkill, you don't need to sleep that much. In fact, you don't need to sleep at all, if you enableRateLimit in Python 2.7. To avoid conflicts we instantiate the non-authenticated exchange in each thread (no need to authenticate for OHLCVs).

3. I removed the dateutil from there to make it shorter.

Anyway, with your snippet or with this one, I was not able to reproduce your error, not even once in 40 launches. Are you sure, this is really the place that is causing trouble and not some other place in your code?

**Comment by kroitor** [comment] 2017-10-29 15:24
If you don't mind, I am closing this issue for now as being somewhat beyond the scope of the library. Feel free to reopen it if needed or just continue posting here, we will try to help as much as we can.

**Closed by kroitor** 2017-10-29 15:24 UTC
Labels: question

**Comment by werewere** [comment] 2017-10-29 15:56
Yep, I tested the problem only with the code I pasted. I'm not sure why it happen though.. Well, I can workaround it with your first solution, so everything is fine :)
