### ISSUE TITLE
fetchMyTrades timestamp mismatch with Poloniex vs Binance

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#2859] opened 2018-05-16 09:56 UTC
- OS: Debian
- Programming Language version: php
- CCXT version: 💯 
- Exchange: poloniex binance
- Method: fetch_my_trades

Hi
I have find out strange thing
for example :
from binance order 
        "timestamp": 1526453562089,
        "datetime": "2018-05-16T02:52:42-04:00",
and from poloniex order
        "timestamp": 1526465204000,
        "datetime": "2018-05-16T06:06:44-04:00",

if i put this timestamps to  fetch_my_trades function as since parameter its works fine on binance but on poloniex i should make timezone correction to make it works (1526465204000-3600000*4)
could you please check it

**Comment by page1** [comment] 2018-05-17 22:55
I'm also seeing a weird timestamp issue with Kraken
* OS: ubuntu
* Programming Language version: python
* CCXT version: 1.14.15
* Exchange: kraken
* Method: fetch_my_trades

One of the trades returned by `exchange.fetchMyTrades(params={'start': latest_id, 'ofs': offset})` has the following odd values.
```
{
   'timestamp': 1526534520085, 
   'datetime': '2018-05-17T05:22:00.850Z', 
   'info': {'time': 1526534520.0857}
}
```
I notice 2 things:
* The timestamp is a truncated value base on info:time loosing precision
* The value in datetime doesn't match the value computed with https://www.epochconverter.com/ in the bold section Thursday, May 17, 2018 5:22:00.**085** AM

On spot check of other timestamps I see other issues but can't put my finger on what transformation might be causing it.

**Comment by binares** [comment] 2018-06-25 03:10
This seems to be a general problem, I tested the .fetchTrades method on different exchanges, the unix ['timestamp'] is off up to 1000ms from the ['datetime']. Probably a rounding problem.

```
#!python
import ccxt
from datetime import datetime
from dateutil.parser import parse

epoch = datetime.utcfromtimestamp(0)

def assert_fetchTrades_timestamps_equal(exchange):
    trades = exchange.fetchTrades(exchange.symbols[0],limit=1)
    ts = trades[0]['timestamp']
    timestr = trades[0]['datetime']

    dt = parse(timestr).replace(tzinfo=None)
    ts2 = int((dt-epoch).total_seconds()*1000)

    if ts != ts2:
        print(exchange.id,ts,ts2,ts2-ts)


for exchange_id in ccxt.exchanges:
    try:
        exchange = getattr(ccxt,exchange_id)({'timeout':5000})
        
        if exchange.has['fetchTrades']:
            exchange.load_markets()
            assert_fetchTrades_timestamps_equal(exchange)
            
    except Exception as e:
        pass
```
binance 1529891397931 1529891398931 1000
bitbank 1529887535002 1529887535200 198
bitfinex2 1529859239032 1529859239320 288
bitflyer 1529888059044 1529888059440 396
bittrex 1529789548997 1529789549997 1000
coinbasepro 1529878787061 1529878787610 549
coinfalcon 1529788183697 1529788184697 1000
gdax 1529878787061 1529878787610 549
gemini 1529895333863 1529895334863 1000
hadax 1529895824997 1529895825997 1000
hitbtc 1494413554710 1494413555710 1000
huobipro 1529891543919 1529891544919 1000
independentreserve 1529819890803 1529819891803 1000
itbit 1527742015993 1527742016993 1000
kraken 1529838647834 1529838648834 1000
lbank 1529895863992 1529895864992 1000
luno 1529857463758 1529857464758 1000
okex 1529894522947 1529894523947 1000

**Comment by kroitor** [comment] 2018-06-25 06:10
@page1 

> I notice 2 things:

> The timestamp is a truncated value base on info:time loosing precision

You're looking into `info` instead of the `timestamp` and `datetime`. Moreover, the values in the `timestamp` and `datetime` are both correct and don't lose precision with decimals, those are just a milliseconds-timestamp and UTC ISO8601 datetime string. Precision is not lost there.

> The value in datetime doesn't match the value computed with https://www.epochconverter.com/ in the bold section Thursday, May 17, 2018 5:22:00.085 AM

<img width="691" alt="screen shot 2018-06-25 at 09 05 47" src="https://user-images.githubusercontent.com/1294454/41833016-4e9503c8-7857-11e8-9d15-7193e63eb77b.png">

This is all documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual

The original problem that was reported by @Showgofar is somewhat different.

@binares will check for that, thx for pointing that out.

**Comment by kroitor** [comment] 2018-06-25 06:20
@binares i think you got an error in your conversion code:

```Python
#!python
import ccxt

def assert_fetchTrades_timestamps_equal(exchange):
    trades = exchange.fetchTrades(exchange.symbols[0],limit=1)
    ts1 = trades[0]['timestamp']
    ts2 = exchange.parse8601(trades[0]['datetime'])

    if ts1 != ts2:
        print(exchange.id, ts1 , ts2, ts2 - ts1)
    else:
        print("They are equal, man:", ts1, ts2)

exchange = ccxt.binance({'timeout':5000})

if exchange.has['fetchTrades']:
    exchange.load_markets()
    assert_fetchTrades_timestamps_equal(exchange)
```

**Comment by binares** [comment] 2018-06-25 09:13
```
#!python 3.6.4
#!Windows 10 Pro x64
import ccxt
import time

def assert_fetchTrades_timestamps_equal(exchange):
    trades = exchange.fetchTrades('ETH/BTC',limit=1)
    ts1 = trades[0]['timestamp']
    ts2 = exchange.parse8601(trades[0]['datetime'])

    if ts1 != ts2:
        print(exchange.id, ts1 , ts2, ts2 - ts1)
    else:
        print("They are equal, man:", ts1, ts2, exchange.iso8601(ts1), exchange.iso8601(ts2))

exchange = ccxt.binance({'timeout':5000})

if exchange.has['fetchTrades']:
    for i in range(10):
        exchange.load_markets()
        assert_fetchTrades_timestamps_equal(exchange)
        time.sleep(2)
```

They are equal, man: 1529917800369 1529917800369 2018-06-25T09:10:00.369Z 2018-06-25T09:10:00.369Z
binance 1529917802578 1529917803578 1000
binance 1529917804673 1529917805673 1000
binance 1529917807751 1529917808751 1000
binance 1529917809879 1529917810879 1000
binance 1529917811924 1529917812924 1000
binance 1529917814625 1529917815625 1000
binance 1529917817569 1529917818569 1000
binance 1529917819594 1529917820594 1000
They are equal, man: 1529917822283 1529917822283 2018-06-25T09:10:22.283Z 2018-06-25T09:10:22.283Z

**Comment by kroitor** [comment] 2018-06-25 12:53
@binares 

```
mbp:ccxt igorkroitor$ cd python/
mbp:python igorkroitor$ python test-trades-timestamp.py
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
('They are equal, man:', 1529931124251, 1529931124251, '2018-06-25T12:52:04.251Z', '2018-06-25T12:52:04.251Z')
mbp:python igorkroitor$ cat test-trades-timestamp.py
#!python
import ccxt
import time

def assert_fetchTrades_timestamps_equal(exchange):
    trades = exchange.fetchTrades(exchange.symbols[0],limit=1)
    ts1 = trades[0]['timestamp']
    ts2 = exchange.parse8601(trades[0]['datetime'])

    if ts1 != ts2:
        print(exchange.id, ts1 , ts2, ts2 - ts1)
    else:
        print("They are equal, man:", ts1, ts2, exchange.iso8601(ts1), exchange.iso8601(ts2))

exchange = ccxt.binance({'timeout':5000})

if exchange.has['fetchTrades']:
    exchange.load_markets()
    for i in range(10):
        assert_fetchTrades_timestamps_equal(exchange)
        time.sleep(2)
mbp:python igorkroitor$
```

**Comment by kroitor** [comment] 2018-06-25 12:54
@binares ok, now I think I found the reason... It is Python3-specific, but I've managed to reproduce the issue. Will debug further and will get back to you on this. Thx again for your help!

**Comment by binares** [comment] 2018-06-25 13:16
@kroitor With a closer look, all timestamps with the 3rd last digit >=5 are off with a positive addition of +1000, whereas 1<=x<5 are correct, and x=0 are off in range of range of +1 to +1000. Your last test only has one identical input timestamp, hence the seeming correctness.

**Comment by frosty00** [comment] 2018-06-25 13:28
https://github.com/ccxt/ccxt/blob/master/js/test/base/functions/test.datetime.js

^ These tests are transpilled into python and php

On my computer all python tests are passing - /Users/carlorevelli/Documents/important/code/arbitrage/ccxt/tests/test_exchange_datetime_functions.py

**Comment by kroitor** [comment] 2018-06-25 13:33
@frosty00 

```
>>> e.iso8601(e.parse_date('1986-04-26T01:23:47.000Z'))
'1986-04-26T01:23:47.000Z'
>>> e.iso8601(e.parse_date('1986-04-26T01:23:47.550Z'))
'1986-04-26T01:23:48.550Z'
>>>
```

**Comment by kroitor** [comment] 2018-06-25 13:35
@frosty00 this is due to `yyyy`, `mm`, `dd`, `hh`, `mm`, `ss`, `msec` parsing in the parse8601, I suppose. Those milliseconds rounding in particular.

**Comment by kroitor** [comment] 2018-06-25 13:37
@frosty00 also, this problem is present in Python3 only, Python2 is ok:

```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> e.iso8601(e.parse8601('1986-04-26T01:23:47.000Z'))
'1986-04-26T01:23:47.000Z'
>>> e.iso8601(e.parse8601('1986-04-26T01:23:47.550Z'))
'1986-04-26T01:23:47.550Z'
>>>
```

**Comment by frosty00** [comment] 2018-06-25 17:56
#3247

**Comment by kroitor** [comment] 2018-06-25 18:18
@binares the problem with timestamp != datetime should go away if you update to most recent version 1.14.268. Thx to @frosty00 for finding time to fix it!

**Comment by Showgofar** [comment] 2018-07-03 10:37
The problem on poloniex is still exist
1)  fetch my trades - > take timestamp from latest trade ($timestamp_poloniex)
2)  fetch my trades (since = $timestamp_poloniex) -> will return zero result 
3)  fetch my trades (since = ($timestamp_poloniex - time zone correction)) -> will return latest trade
time zone correction in my case is 4 hours
 so it will be
4*60*60 * 1000

**Comment by kroitor** [comment] 2018-09-08 23:57
@Showgofar can you make a short snippet to reproduce the issue?

```
mbp:ccxt igorkroitor$ node examples/js/cli poloniex fetchMyTrades LTC/BTC
poloniex.fetchMyTrades (LTC/BTC)
    timestamp |          datetime |   symbol |       id |        order |  type | side |      price |     amount |       cost |                                                              fee
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
1536446800000 | 2018-9-9 01:36:50 | LTC/BTC | 10xxxxxx | 193xxxxxxxxx | limit |  buy | 0.02993239 | 0.02905812 | 0.00086977 |            {"rate":0.002,"cost":0.00005811624,"currency":"LTC"}
91 objects
mbp:ccxt igorkroitor$ node examples/js/cli poloniex fetchMyTrades LTC/BTC 1536446810000
poloniex.fetchMyTrades (LTC/BTC, 1536446810000)
    timestamp |          datetime |   symbol |       id |        order |  type | side |      price |     amount |       cost |                                                   fee
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1536446800000 | 2018-9-9 01:36:50 | LTC/BTC | 10xxxxxx | 193xxxxxxxxx | limit |  buy | 0.02993239 | 0.02905812 | 0.00086977 | {"rate":0.002,"cost":0.00005811624,"currency":"LTC"}
1 objects
mbp:ccxt igorkroitor$
```

**Comment by kroitor** [comment] 2019-04-10 01:00
Let us know if you still experience this issue, need the code to reproduce it. Closing this for now. Thx!

**Closed by kroitor** 2019-04-10 01:00 UTC
