### ISSUE TITLE
Wavesexchange create_order The request has an invalid signature

### ISSUE THREAD

**Issue by kleninmaxim** [ccxt/ccxt#11067] opened 2021-12-29 13:39 UTC
Sorry.
My ccxt verison is: 1.65.38
OS: Linux Ubuntu 20.04
Programming language is: php8.0
Exchange is: wavesexchange
Method is create_order, but I guess it will be on another methods.

```
$exchange_class = '\\ccxt\\' . 'wavesexchange';

$exchange = new $exchange_class(['apiKey' => API_KEY, 'secret' => API_SECRET, 'timeout' => 10000, 'enableRateLimit' => false]);

while (true) {
    try {

        $start = hrtime(true);

        $order = $exchange->create_order("BTC/USDN", "limit", "sell", "0.00001", "60000");

        $time = round((hrtime((true) - $start)) / 10**9, 8);

    } catch (Throwable $e) {
        die("Order NOT created. Error: $e" . PHP_EOL);
    }

    $i++;

    echo "$i) Order created, id: {$order["id"]}, time: $time s" . PHP_EOL;

    $cancel_order = $exchange->cancel_order($order["id"], "BTC/USDN");
}
```

when I run that code it is okay, but sometimes at some indefinite step it can break:
```
10) Order created, id: BVmNN9g6h8DQfTUJbjqBUNTvT83ivwfJriJVsTrRqKV4, time: 10925.5871533 s
11) Order created, id: 3o87SptEMNYC6zEHk3Z4i2G5LRWMuFvgSfTWwp3PfSZW, time: 10926.4394268 s
12) Order created, id: 5forVa1No7B9A8ZGUNgJ366xhoU3iSSpe3dnEEzUBJRQ, time: 10927.2368888 s
13) Order created, id: 2TV97V6rUwMWiK1m4tNgqBcoWRfpqiBoV6s879WSrxwe, time: 10928.1120364 s
14) Order created, id: EU9rq6KdBeobScvEiFyXFQEDk2xfhmXpMUPzTFV8KM3A, time: 10929.4442607 s
Order NOT created. Error: ccxt\AuthenticationError: wavesexchange The signature of order AwSYNfM1BhGkwJZmG9fi9umsbWk39J7L4FdiWuzU2Tf6 is invalid: GenericError(Proof doesn't validate as signature for OrderV3(id=AwSYNfM1BhGkwJZmG9fi9umsbWk39J7L4FdiWuzU2Tf6, sender=herewasmyapikey, matcher=9cpfKN9suPNvfeUNphzxXMjcnn974eme8ZhWUjaktzU5, pair=8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS-DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p, tpe=sell, amount=1000, price=60000000000, ts=1640775577208, exp=1643194777208, fee=300000, feeAsset=WAVES, proofs=Proofs(herewasmanysymbols))) in .../vendor/ccxt/ccxt/php/wavesexchange.php:1783
```
*Before the error, orders are created and canceled normally.

Previous comment is: https://github.com/ccxt/ccxt/issues/11043#issuecomment-1002541755

**Comment by ttodua** [comment] 2022-07-30 14:42
this is duplicate of #11043 , so it should be handled there.

**Closed by ttodua** 2022-07-30 14:42 UTC
Labels: bug, duplicate
