### ISSUE TITLE
Process open FD table is full

### ISSUE THREAD

**Issue by Aliaxander** [ccxt/ccxt#2276] opened 2018-03-15 23:39 UTC
crashed.

- OS:
linux
- Programming Language version:
php 7.0 - php 7.2
- CCXT version:
last
- Exchange:
- Method:

Process open FD table is full
.../ccxt/ccxt/php/Exchange.php:735

**Comment by kroitor** [comment] 2018-03-17 01:52
@Aliaxander can you please post the full verbose output according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? Need to see your code as well, can you make it a short snippet to reproduce the problem? Thx!

**Comment by kroitor** [comment] 2018-03-23 01:15
This is most likely due to creating exchange instances in a loop (most often cause of the above symptom). However, it's hard to tell without seeing the code you're running... Closing it for now, if you don't mind.

**Closed by kroitor** 2018-03-23 01:15 UTC
