### ISSUE TITLE
Poloniex fetch_order isn't working properly

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#669] opened 2017-11-24 13:50 UTC
Poloniex has returnOrderTrades API endpoint which should be used in fetch_order library call. As of now, fetch_orders is used and the cache is checked; which isn't ideal.

**Comment by kroitor** [comment] 2017-11-24 13:53
This issue a duplicate of this: https://github.com/ccxt/ccxt/issues/569. Let's go on there.

**Closed by kroitor** 2017-11-24 13:53 UTC
Labels: duplicate
