### ISSUE TITLE
Watching ohlcv on Binance results in ccxt.base.errors.NetworkError: 1000

### ISSUE THREAD

**Issue by tjappo** [ccxt/ccxt#7233] opened 2020-07-07 10:53 UTC
I am getting this error (ccxt.base.errors.NetworkError: 1000) for the Binance exchange after a couple of hours. This also occurs for BNB/USDT. However, strangely I don't get this error for btc/usdt.

- OS: Linux (Ubuntu)
- Programming Language version: Python 3.7
- CCXT version: latest

Function giving the error `(ccxt.base.errors.NetworkError: 1000)`: 
```
exchange = getattr(ccxtpro, 'binance')({'enableRateLimit': True})
if not exchange.has['fetchOHLCV']:
        raise KeyError('Exchange does not provide the ability to fetch OHLCV candles.')
if not exchange.has['watchOHLCV']:
        raise KeyError('Exchange does not provide the ability to watch OHLCV candles.')
ohlcvs = await exchange.watch_ohlcv(symbol="ETH/USDT", timeframe="1m", limit=2)
if len(ohlcvs) < 2:
      return False
# Copies the ohlcv candles, since ccxt cannot handle in-reference edits
candles = [ohlcvs[0][:], ohlcvs[1][:]]
candles[0][0] = from_unix(candles[0][0])  # Official formed candle, with previous timestamp
candles[1][0] = from_unix(candles[1][0])  # Unofficial candle, representing current timestamp
if not self.last_candles or candles[1][0] > self.last_candles[1][0]:
      self.last_candles = candles
      return True
return False
```
Other function using the data 
```
last_candle = DataFrame([self.last_candles[0]], columns=TOHLCV.get_values()).set_index(TOHLCV.TIMESTAMP.value)
self.historical_minute = self.historical_minute.append(last_candle).tail(min_candles)
```

```
File "/src/mia/blotter/blotter/blotter.py", line 140, in __get_last_candle
     ohlcvs = await self.exchange.watch_ohlcv(symbol=self.strategy.ccxt_pair, timeframe=timeframe, limit=2)
   File "/venv/lib/python3.8/site-packages/ccxtpro/binance.py", line 394, in watch_ohlcv
     return await self.after(future, self.filter_by_since_limit, since, limit, 0, True)
   File "/venv/lib/python3.8/site-packages/ccxtpro/base/exchange.py", line 81, in after
     return method(await future, *args)
   File "/venv/lib/python3.8/site-packages/ccxtpro/binance.py", line 481, in watch_public
     return await self.watch(url, messageHash, self.extend(request, query), messageHash, subscribe)
 ccxt.base.errors.NetworkError: 1000
```

**Comment by kroitor** [comment] 2020-07-07 11:02
@tjappo can you save a verbose log to a file and paste it with gists.github.com ? 
In general, the network error 1000 means a disconnect due to a networking issue. This may be due to connectivity with Binance (certain pairs may be served by different servers on Binance's side). I'd also recommend to reach out to Binance tech support (plz paste their response here, if you will). We will look into what may be causing it. Also, can you try to watch BNB/BTC from a different location (an alternative workstation) ? In your code it's 'ETH/USDT', not 'BNB/BTC', though...
Please, provide as much info as you can, and report to as many places as you can.

**Comment by kroitor** [comment] 2020-07-07 11:03
P.S. Also, a complete code code snippet to reproduce it (including exchange instantiation and the watching loop) would help resolve this issue quicker.

**Comment by tjappo** [comment] 2020-07-07 12:00
I get the same errors for ETH/USDT as well as BNB/USDT. I will do some logging later and will post the output.

**Comment by kroitor** [comment] 2020-07-07 13:05
@tjappo your complete code snippet would also help speed resolving this issue.

**Comment by tjappo** [comment] 2020-07-08 10:37
I updated the complete code snippet. The Binance support answered: `I don't think it has issue from server side, only thing i know is that you have to respone ping message from server,  otherwise it should be fine.`

**Comment by kroitor** [comment] 2020-07-08 10:53
@tjappo the ping-pong responses are enabled by default in CCXT Pro... Can you please paste a short snippet of code to reproduce it? Please, make it short, but complete, namely, don't post separate functions. Instead, reduce your code to the shortest possible snippet to recreate the issue, it should include exchange instantiation code and the watching loop.

Unfortunately, your code snippet does not show a watch loop, it's just one call to watch_ohlcv... Make sure you don't recreate the exchange instance upon every iteration of your watching loop.

Alternatively, try this sample code and let us know if you have an issue with it (make sure no other listeners are running):

- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py/binance-watch-ohlcv.py

```Python
import ccxtpro
import asyncio

print('CCXT Pro version', ccxtpro.__version__)


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


async def main(loop):
    exchange = ccxtpro.binance({
        'enableRateLimit': True,
        'asyncio_loop': loop,
        # 'options': {
        #     'OHLCVLimit': 1000, # how many candles to store in memory by default
        # },
    })
    symbol = 'ETH/USDT'  # or BNB/USDT, etc...
    timeframe = '1m'  # 5m, 1h, 1d
    limit = 10  # how many candles to return max
    method = 'watchOHLCV'
    if (method in exchange.has) and exchange.has[method]:
        max_iterations = 100  # how many times to repeat the loop before exiting
        for i in range(0, max_iterations):
            try:
                ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, limit)
                now = exchange.milliseconds()
                print('\n===============================================================================')
                print('Loop iteration:', i, 'current time:', exchange.iso8601(now), symbol, timeframe)
                print('-------------------------------------------------------------------------------')
                print(table([[exchange.iso8601(o[0])] + o[1:] for o in ohlcvs]))
            except Exception as e:
                print(type(e).__name__, str(e))
                break
        await exchange.close()
    else:
        print(exchange.id, method, 'is not supported or not implemented yet')


asyncio_loop = asyncio.get_event_loop()
asyncio_loop.run_until_complete(main(asyncio_loop))
```

Also, please paste your CCXT Pro version number as shown in the snippet (and in the output you get).

**Comment by kroitor** [comment] 2020-07-10 23:16
@tjappo let me know if you have an issue with the above (plz make sure to follow [the entire comment](https://github.com/ccxt/ccxt/issues/7233#issuecomment-655444283) precisely).

**Comment by tjappo** [comment] 2020-07-13 10:51
I ran the code you gave me in a Kubernetes container and it had one restart. I also attached the logs of that container.
ccxt version: 1.30.94
ccxt pro version: 0.2.89
[ccxt_previous.log](https://github.com/ccxt/ccxt/files/4911952/ccxt_previous.log)

**Comment by kroitor** [comment] 2020-07-14 12:51
@tjappo thank you, i'll test on my side extensively and will get back to you asap.

**Comment by tjappo** [comment] 2020-08-11 08:13
@kroitor Did you already have an extensive look at it?

**Comment by kroitor** [comment] 2020-08-11 10:45
@tjappo we are working on a better version of the python client now, do you still have the same issue with BNB/USDT ?

**Comment by tjappo** [comment] 2020-09-07 09:39
@kroitor We have the problem with every coin. When do you expect to have the new python version ready?

**Comment by kroitor** [comment] 2020-09-07 10:16
@tjappo the new python client will arrive soon: https://github.com/kroitor/ccxt.pro/pull/50
In the meantime a few questions to you:
- Do you have the `try/except` clause around your watch-loop?
- Can you post the entire code you use to reproduce it?
- Do you share the exchange instance among the watch-calls, or do you re-create it prior to every call to the watch-method?
- How many times and how often so you call this snippet:
```Python
exchange = getattr(ccxtpro, 'binance')({'enableRateLimit': True})
if not exchange.has['fetchOHLCV']:
        raise KeyError('Exchange does not provide the ability to fetch OHLCV candles.')
if not exchange.has['watchOHLCV']:
        raise KeyError('Exchange does not provide the ability to watch OHLCV candles.')
ohlcvs = await exchange.watch_ohlcv(symbol="ETH/USDT", timeframe="1m", limit=2)
if len(ohlcvs) < 2:
      return False
# Copies the ohlcv candles, since ccxt cannot handle in-reference edits
candles = [ohlcvs[0][:], ohlcvs[1][:]]
candles[0][0] = from_unix(candles[0][0])  # Official formed candle, with previous timestamp
candles[1][0] = from_unix(candles[1][0])  # Unofficial candle, representing current timestamp
if not self.last_candles or candles[1][0] > self.last_candles[1][0]:
      self.last_candles = candles
      return True
return False
```

**Comment by tjappo** [comment] 2020-09-21 09:31
- The code as I posted before is running within a Docker image in a Kubernetes cluster, such that it reboots if it crashes. This is also already the entire code. 
- The exchange instance is reused for every watch call.
- The snippet should be able to run indefinitely without errors, as we use it as a part of a larger program.

**Comment by kroitor** [comment] 2020-10-14 01:06
@tjappo do you still have the same issue? The text log you've pasted above does not show an error or restart though. If you can, please paste the verbose output for the run that fails or restarts:

```Python
import ccxtpro
import asyncio

print('CCXT Pro version', ccxtpro.__version__)


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


async def main(loop):
    exchange = ccxtpro.binance({
        'enableRateLimit': True,
        'asyncio_loop': loop,
        # 'options': {
        #     'OHLCVLimit': 1000, # how many candles to store in memory by default
        # },
    })
    await exchange.load_markets()
    exchange.verbose = True  # ←------------------- after load markets
    symbol = 'ETH/USDT'  # or BNB/USDT, etc...
    timeframe = '1m'  # 5m, 1h, 1d
    limit = 10  # how many candles to return max
    method = 'watchOHLCV'
    if (method in exchange.has) and exchange.has[method]:
        max_iterations = 100000  # how many times to repeat the loop before exiting
        for i in range(0, max_iterations):
            try:
                ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, limit)
                now = exchange.milliseconds()
                print('\n===============================================================================')
                print('Loop iteration:', i, 'current time:', exchange.iso8601(now), symbol, timeframe)
                print('-------------------------------------------------------------------------------')
                print(table([[exchange.iso8601(o[0])] + o[1:] for o in ohlcvs]))
            except Exception as e:
                print(type(e).__name__, str(e))
                break
        await exchange.close()
    else:
        print(exchange.id, method, 'is not supported or not implemented yet')


asyncio_loop = asyncio.get_event_loop()
asyncio_loop.run_until_complete(main(asyncio_loop))
```

**Comment by ttodua** [comment] 2023-08-01 08:17
I'm closing this issue for now, if any issue persists, please post a follow up.

**Closed by ttodua** 2023-08-01 08:17 UTC
Labels: WS, important
