### ISSUE TITLE
hitbtc2 etimeout error

### ISSUE THREAD

**Issue by munny-lcx** [ccxt/ccxt#7156] opened 2020-06-19 10:59 UTC
what i am doing:

i am trying to getting fetchOHLCV of all the active pair of hitbtc2 ( near 900 pair )

now the problem is when I call fetchOHLCV for all pair.
I received ETIMEDOUT in most of the responses

"hitbtc2 GET https://api.hitbtc.com/api/2/public/candles/ZECBTC?period=M1&from=2020-02-29T18%3A02%3A00.000Z&limit=1000 system request to https://api.hitbtc.com/api/2/public/candles/ZECBTC?period=M1&from=2020-02-29T18%3A02%3A00.000Z&limit=1000 failed, reason: connect ETIMEDOUT 145.239.2.227:443"

but when I open this URL in chrome it open in few secounds.

I read mainly all the solution comments regarding issue but couldn't find the right solution 
I used : {
timeout: 300000 or 40000,
userAgent: false
}

or also with enableRateLimit: true
is their any way to resolve this problem.

**Comment by kroitor** [comment] 2020-06-19 11:10
> is their any way to resolve this problem.

Yes, to resolve this problem, paste your code to reproduce it and your verbose request/response, as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by munny-lcx** [comment] 2020-06-19 11:27
my ccxt version: 1.30.20, updated version
language used: Node.js
Exchange id: hitbtc2
function used: fetchOHLCV  of ccxt exchange

what I am trying: to store ohlcv from Jan 2021
for my algo is: to run  a script in every 4 min though setInterval or corn package.

i store get last store ohlcv from hitbtc ohlcv db

then call fetchOHLCV with since and also with limit 1000.

my code is:
under for loop of all pair list

![image](https://user-images.githubusercontent.com/66307095/85127649-7ac24780-b24d-11ea-8ace-0a588a77f3c4.png)

and under fetchAndStore function: 

create exchange class:
![image](https://user-images.githubusercontent.com/66307095/85127384-f2dc3d80-b24c-11ea-82e6-9874552c1684.png)

call class method fetchOHLCV:

![image](https://user-images.githubusercontent.com/66307095/85127463-169f8380-b24d-11ea-94bd-5fcfa817c91e.png)

getting response:
 
![image](https://user-images.githubusercontent.com/66307095/85127809-c248d380-b24d-11ea-8d5e-32b84e83f00f.png)

in most or the response of ohlcv 


Thank you ccxt for your great support

**Comment by kroitor** [comment] 2020-06-19 12:21
First of, please, never paste your code and text as screenshots – we can't copy and test it. Always read the links we post very carefully, it's literally written there to not post code and text as images. For the future, always paste your code as code and the text as text, as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (do not ignore that)

Secondly, we need a short and complete snippet to reproduce it, otherwise, we will have to reinvent the code for you and resolving the issue will take a much a longer time.

Third, on the screenshots you're not using the rate-limiter, which is required in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Fourth, always reuse a single exchange instance – do not recreate it for every call like you do, otherwise you're resetting the rate-limiting, and the exchange will deny your requests or might even ban you, this is also documented in the Manual. When you do not reuse the exchange instance, you're effectively not reusing the rate limiting (that's a noob mistake, mostly due to a poor structuring of the code on your side), and in that case all your requests will be sent out at once – which will lead to timeouts in most cases.

Here's how your code should look like (it's an example that does what you want, without breaking any rate-limits):

- https://github.com/ccxt/ccxt/blob/master/examples/js/hitbtc-fetch-all-ohlcvs.js

```JavaScript
"use strict";

const ccxt = require ('../../ccxt')

const exchange = new ccxt.hitbtc ({
    'enableRateLimit': true,
})

;(async () => {

    await exchange.loadMarkets ()

    // start from february 2020
    const start = exchange.parse8601 ('2020-02-01T00:00:00Z')
    const timeframe = '1m'
    // get the duration of one timeframe period in milliseconds
    const duration = exchange.parseTimeframe (timeframe) * 1000

    for (const symbol of exchange.symbols) {

        console.log ('-------------------------------------------------------')
        console.log ('Fetching', symbol, timeframe, 'candles')

        let since = start

        do {

            try {
                const candles = await exchange.fetchOHLCV (symbol, timeframe, since)

                if (candles.length) {

                    const first = candles[0]
                    const last = candles[candles.length - 1]

                    console.log (
                        'Fetched', candles.length, symbol, timeframe, 'candles',
                        'from', exchange.iso8601 (first[0]),
                        'to', exchange.iso8601 (last[0])
                    )

                    // store your candles to a database or to a file here
                    // ...

                    since = last[0] + duration // next start from last candle timestamp + duration

                } else {

                    console.log ('Fetched', candles.length, symbol, 'candles')
                    break
                }

            } catch (e) {

                console.log (e.constructor.name, e.constructor.message)
                // retry on next iteration
            }

        } while (since < exchange.milliseconds ())
    }

}) ()
```

Let us know if that does not help.

**Closed by kroitor** 2020-06-19 12:21 UTC
Labels: question
