### ISSUE TITLE
Binance, certificate verify failed (_ssl.c:777)

### ISSUE THREAD

**Issue by mazertwo** [ccxt/ccxt#452] opened 2017-11-02 19:59 UTC
If i get info from Binance, i have error: 
```
ccxt.base.errors.ExchangeNotAvailable: binance GET https://www.binance.com/api/v1/depth?symbol=BCCBTC&limit=100
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
```

**Comment by kroitor** [comment] 2017-11-02 21:10
Hi! Which version are you using? Sync? Async?

**Comment by mazertwo** [comment] 2017-11-03 06:31
Sync.
Ccxt 1.9.230

**Comment by mazertwo** [comment] 2017-11-03 08:23
Code is simple:

import ccxt
binance=ccxt.binance()
orderbook1 = binance.fetch_order_book('ETH/BTC')

Error:

C:\Python\python.exe C:/Users/1/Desktop/test1.py
Traceback (most recent call last):
  File "C:\Python\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Python\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Python\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Python\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\ccxt\exchange.py", line 270, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1))
  File "C:\Python\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/1/Desktop/test1.py", line 3, in <module>
    orderbook1 = binance.fetch_order_book('ETH/BTC')
  File "C:\Python\lib\site-packages\ccxt\exchanges.py", line 1868, in fetch_order_book
    }, params))
  File "C:\Python\lib\site-packages\ccxt\exchanges.py", line 2123, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python\lib\site-packages\ccxt\exchange.py", line 239, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python\lib\site-packages\ccxt\exchange.py", line 281, in fetch
    self.raise_error(ExchangeNotAvailable, url, method, e)
  File "C:\Python\lib\site-packages\ccxt\exchange.py", line 224, in raise_error
    details,
ccxt.errors.ExchangeNotAvailable: binance GET https://www.binance.com/api/v1/depth?symbol=ETHBTC&limit=100 <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

**Comment by kroitor** [comment] 2017-11-03 08:27
Can you try it with a proxy?

```Python
import ccxt
binance=ccxt.binance({'proxy': 'https://cors-anywhere.herokuapp.com/'})
orderbook1 = binance.fetch_order_book('ETH/BTC')
```

or
 

```Python
import ccxt
binance=ccxt.binance({'proxy': 'https://crossorigin.me/'})
orderbook1 = binance.fetch_order_book('ETH/BTC')
```
?

**Comment by mazertwo** [comment] 2017-11-03 08:42
I have two work stations with same IP address.
On first work fine, but on second have 777 error only with binance.
Python versions and OS versions same.
Wery strange problem.

**Comment by kroitor** [comment] 2017-11-03 08:43
@mazertwo and same ccxt versions?

**Comment by mazertwo** [comment] 2017-11-03 08:48
Yep.

**Comment by kroitor** [comment] 2017-11-03 08:51
@mazertwo this may be caused by their routing settings... Very strange indeed. Does any of two examples posted above work on the "problematic" station?

**Comment by mazertwo** [comment] 2017-11-03 08:57
At "probleatic" station work with herokuapp and not work with crossorigin.

**Comment by kroitor** [comment] 2017-11-03 09:44
Well... It is most likely related to the way your network is set up, or Binance may be rejecting to verify their SSL certificate if you are sending your requests from two stations simultaneously. It may also depend on your router... Don't know if we can help here without actually debugging the network for you, because this is somewhat beyond the scope of the library. 

Basically, this error is saying that your station could not verify the authenticity of Binance servers... It may be because their replies don't get through to you, or because they reject to serve that SSL verification for some reason (which may be caused by simultaneous access)...

You can narrow the search field by testing if it is repeatable...

1. Does the working station work every time without proxy?
2. Does the working station work every time with proxy?
3. Does the other station break every time without proxy?
4. Does the other station work every time with proxy?

If it is repeatable, and one machine works all the time and the other does not work all the time, then this is most likely a local issue with your routing/networking settings... Don't know if we can assist beyond above. I'm closing this for now, but we will still investigate into this closely. Need more info...

**Closed by kroitor** 2017-11-03 09:44 UTC

**Comment by mazertwo** [comment] 2017-11-03 10:00
Thank you!

**Comment by kroitor** [comment] 2017-11-08 11:34
https://github.com/ccxt/ccxt/issues/227
