### ISSUE TITLE
KuCoin: PHP errors in parse_order()

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#7234] opened 2020-07-07 13:12 UTC
- OS: Linux
- Programming Language version: PHP 7.2
- CCXT version: 1.30.70

```
PHP Notice:  Undefined index: isActive in kucoin.php on line 1009
PHP Notice:  Undefined index: cancelExist in kucoin.php on line 1010
```

**Comment by kroitor** [comment] 2020-07-07 13:26
@WoK-E can you plz paste the verbose request/response for it?

**Comment by WoK-E** [comment] 2020-07-07 13:39
I'll have to increase the verbosity level, and wait for it to happen again. Will do... pls wait

I think it happens in a couple of cases.
The one I know for sure is when an order is placed and KuCoin rejects it (e.g. because it is below the minimum requirement). If I try to get its status afterwards, I get these errors

**Comment by WoK-E** [comment] 2020-07-07 15:08
I think I found it. When an order is found (the order id is valid), fetch_order() returns the data about the order. When the order id is invalid (no order with that id exists), it returns a list of all orders in the items array (like calling fetch_orders_by_status() with a null status)
Here's the data when the order is not found:
Array
(
    [currentPage] => 1
    [pageSize] => 50
    [totalNum] => 2937
    [totalPage] => 59
    [items] => Array
        (
            [0] => Array
...

**Comment by kroitor** [comment] 2020-07-07 15:19
@WoK-E it's very hard to figure out the cause from the partial output you've posted, though.... can you please paste a complete verbose output for it (plz use GitHub's markdown for readability)....

**Comment by kroitor** [comment] 2020-07-07 15:24
@WoK-E i mean this:

```PHP
$exchange = new \ccxt\kucoin(array(
    'apiKey' => 'YOUR_API_KEY', // replace with your keys
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

$exchange->load_markets();
$exchange->verbose = true;
$exchange->fetch_order($your_nonexistent_id);
```

**Comment by kroitor** [comment] 2020-07-07 15:26
@WoK-E when i do the above, i see this:

```
mbp:ccxt igorkroitor$ php -f examples/php/cli.php kucoin fetch_order abcdef --verbose
...
kucoin->fetch_order (abcdef)
Request: GET https://openapi-v2.kucoin.com/api/v1/orders/abcdef [
    "KC-API-KEY: 5e9055dc2695100008769925",
    "KC-API-TIMESTAMP: 1594135531136",
    "KC-API-PASSPHRASE: 2AIYYS4AH6A5PNA7",
    "KC-API-SIGN: QX3Pc8Ih5V7UJ8NrOjcH9bJa2eSoR0eXFKd+zHotXQw="
] null
Response: GET https://openapi-v2.kucoin.com/api/v1/orders/abcdef 200  {
    "content-type": [
        "application\/json"
    ],
    "content-length": [
        "42"
    ],
    "date": [
        "Tue, 07 Jul 2020 15:25:31 GMT"
    ],
    "set-cookie": [
        "AWSALB=QFpIAvL0apzqObP8c7NjFJd9Yu0kAX5lq7F0zRgmldW5FIt1qc6RbD4dkE8KIBU438ioFiZcwG56t8MF+C97PZ5H+vXoEWToeDNpbP1g7W+ZJuI0\/BEZZ2kL0x86; Expires=Tue, 14 Jul 2020 15:25:31 GMT; Path=\/",
        "AWSALBCORS=QFpIAvL0apzqObP8c7NjFJd9Yu0kAX5lq7F0zRgmldW5FIt1qc6RbD4dkE8KIBU438ioFiZcwG56t8MF+C97PZ5H+vXoEWToeDNpbP1g7W+ZJuI0\/BEZZ2kL0x86; Expires=Tue, 14 Jul 2020 15:25:31 GMT; Path=\/; SameSite=None; Secure"
    ],
    "server": [
        "-"
    ],
    "weight-interval": [
        "SECOND"
    ],
    "weight-expire": [
        "1594135564"
    ],
    "weight-limit": [
        "1800"
    ],
    "weight-remain": [
        "1799"
    ],
    "strict-transport-security": [
        "max-age=9800; includeSubDomains; preload"
    ],
    "x-cache": [
        "Miss from cloudfront"
    ],
    "via": [
        "1.1 0b29dbae3ec4657017234abf5689a8f8.cloudfront.net (CloudFront)"
    ],
    "x-amz-cf-pop": [
        "HEL50-C1"
    ],
    "x-amz-cf-id": [
        "R9UgtCpn8hWTEdCwTOwpy6C--z3hiANJJWoa8r0CucWwQr3KGT076A=="
    ]
} {"code":"400100","msg":"order not exist."}
ccxt\OrderNotFound: order not exist.
```

**Comment by kroitor** [comment] 2020-07-07 15:56
@WoK-E from the above you can see what happens when I submit a wrong non-existent order id to `fetch_order` with KuCoin... You can see both the request and the response there.

However, it's not clear from your output which request is being sent and which response you get. Can you please post the same type of output (including the verbose request+response) here?

**Comment by WoK-E** [comment] 2020-07-07 15:57
Sorry, I didn't understand what you meant.  Actually producing the verbose request/response helped me figure out what was wrong.
I have a bug in my code and I pass a null as the order id, and KuCoin responds with the full list of orders. I was expecting to catch and exception, but none was raised.

Anyway, to reproduce it just call fetch_order_status with null as the order id.

**Comment by kroitor** [comment] 2020-07-08 06:36
@WoK-E `fetch_order_status` expects a non-empty value, otherwise the behavior is undefined. Closing this for now, feel free to reopen it or just ask further questions if any.

**Closed by kroitor** 2020-07-08 06:36 UTC
