### ISSUE TITLE
after updating from 4.1.39 to version ccxt 4.1.50 - 4.1.66 an error appears (in 4.1.39 everything works fine)

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#20138] opened 2023-11-27 04:30 UTC
### Operating System

Debian, Windows

### Programming Languages

Python

### CCXT Version

4.1.50 - 4.1.66

### Description

after updating from 4.1.39 to version ccxt  ccxt **4.1.50 - 4.1.66** an error appears **(in 4.1.39 everything works fine)**:
Future exception was never retrieved
future: <Future finished exception=**DDoSProtection**('binance {"**code":-2015,"msg":"Invalid API-key, IP, or permissions for action**"}')>
Traceback (most recent call last):
File "/home//.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 2218, in load_positions_snapshot
positions = await self.fetch_positions(None, {'type': type})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7242, in fetch_positions
return await self.fetch_positions_risk(symbols, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7294, in fetch_positions_risk
await self.load_leverage_brackets(False, params)
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 6968, in load_leverage_brackets
response = await getattr(self, method)(query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 8029, in request
response = await self.fetch2(path, api, method, params, headers, body, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 1984, in fetch2
return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 220, in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7989, in handle_errors
raise DDoSProtection(self.id + ' ' + body)
ccxt.base.errors.DDoSProtection: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}

**PS/
New API keys have been created and tested in all possible settings. The problem is not in the API keys and access parameters.
I rolled back to version 4.1.39, everything works without errors.**

### Code

```
  

```

**Comment by sc0Vu** [comment] 2023-11-27 05:55
Hi @89d55d5288 

Is this issue related: https://github.com/ccxt/ccxt/issues/20096?

**Comment by 89d55d5288** [comment] 2023-11-27 06:15
> Hi @89d55d5288
> 
> Is this issue related: #20096?

Hi sc0Vu
Correct, when adding the following

                'options': {
                  'watchPositions': {
                    'fetchPositionsSnapshot': False,
                    'awaitPositionsSnapshot': False,
                  },
                }

the error does not come.
But now I don’t know what these settings are disabled and how my algorithm will work. If it's not difficult, please provide an explanation of these settings.

**Comment by hodlerhacks** [comment] 2023-11-27 09:52
Note that I experience this already in v4.0.111. But after updating to the latest, and then rolling back to v4.0.111, the problem is gone. So there is something very interesting going on here.

**Comment by sc0Vu** [comment] 2023-11-29 03:15
Hi @89d55d5288 

We now set position cache in these function `watchBalance`, `watchOrders` and `watchPositions`. If `fetchPositionsSnapshot` is true, the client would load current positions in exchange (from `fetchPositions`). That's why you see permissions issue (suppose you don't authorize futures for that key).

**Comment by hodlerhacks** [comment] 2023-11-29 07:13
Hi @sc0Vu, thanks for clarifying!

I'm not using fetchPositions in my code, but I do use fetchOpenOrders. Could the use of fetchOpenOrders trigger the fetchPositions request?

Does this mean that whenever I use fetchOpenOrders in an application, I need to apply the above options to the exchange?

And does this only apply to Binance, or to any exchange?

**Comment by sc0Vu** [comment] 2023-11-29 12:15
Hi @hodlerhacks 

The fetch* function should work. It also affect bybit, cryptocom and gate (`setPositionsCache`).

**Comment by carlosmiei** [comment] 2023-11-29 12:26
Hello @hodlerhacks, those settings are WebSockets settings and have no impact in the REST side. And noo `fetchOpenorders` does not trigger any `fetchPositions` request. 

Do you think it would be possible to try to reproduce the issue with sandbox keys and then share them with us so we can try to run the exact same thing on our side?

**Comment by hodlerhacks** [comment] 2023-11-29 13:11
Hi @carlosmiei, yes, I'll give it a try.

**Comment by sc0Vu** [comment] 2023-11-30 00:14
Hey @hodlerhacks,

Did you enable futures permission?

**Comment by hodlerhacks** [comment] 2023-11-30 06:32
In my region, Futures are not allowed/available. The same goes for most users of my application. So we cannot enable Futures permissions. The application only does spot trading, so I would expect only spot requests are made. 

In any case, setting the additional options solves the problem. I'm also providing an online programming course that uses CCXT, and this effects the sample applications and videos I have recorded. So would be good to understand if using those options is a temporary workaround, or if this needs to be applied in any application from now on. Then I can inform my students accordingly.

Thanks for the great support gents, much appreciated!

**Comment by carlosmiei** [comment] 2023-11-30 09:57
Hello @hodlerhacks, thanks a lot for your detailed explanations. I think that the issue will be fixed  shortly here: https://github.com/ccxt/ccxt/pull/20174

**Comment by hodlerhacks** [comment] 2023-11-30 10:17
That's great, thanks a lot!

**Comment by carlosmiei** [comment] 2023-11-30 16:33
@hodlerhacks Can you please update to the latest version (4.1.72) and check if the issue is fixed?

**Closed** 2023-12-17 12:13 UTC
Labels: question
