### ISSUE TITLE
Problems with data received from bittrex. fetch_my_trades('XRP/USD') 

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14746] opened 2022-08-19 12:03 UTC
Bad data:
- OS: W10
- Programming Language version: python 3.10.6
- CCXT version: CCXTversion 1.92.32

Good data:
- OS: W10
- Programming Language version: python 3.10.6
- CCXT version: CCXTversion 1.36.92

Hello, I am moving an old bot to the new version of ccxt and I see that the data I receive in the new version is not correct in some cases.
Specifically, in the XRP/USD pair, I am seeing orders that are buy and appear as sell.
I have executed a test in the old version of ccxt that I have and the data appears correctly.
Specifically, there are 3 purchase orders and in the new version of ccxt one of them appears as SELL when it is not.

I have also noticed the error appearing on XRP/USDT. I'm looking to see if it happens in other pairs.

Bad data CCXTversion 1.92.32 - Side Bad - SELL (the order is BUY)

{'info': 
{'id': '4e8294f8-9154-4676-b0da-851f18a15273', 
'marketSymbol': 'XRP-USD', 
'executedAt': '2022-08-18T22:55:09.52Z', 
'quantity': '44.06980492', 
'rate': '0.379050000000', 
'orderId': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'commission': '0.05846630', 
'isTaker': False, 
'direction': 'SELL'}, 
'timestamp': 1660863309520, 
'datetime': '2022-08-18T22:55:09.520Z', 
'symbol': 'XRP/USD', 
'id': '4e8294f8-9154-4676-b0da-851f18a15273', 
'order': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'takerOrMaker': 'maker', 
'type': None, 
'side': None, 
'price': 0.37905, 
'amount': 44.06980492, 
'cost': 16.704659554926, 
'fee': {'cost': 0.0584663, 'currency': 'USD'}, 
'fees': [{'currency': 'USD', 'cost': 0.0584663}]}]

BR

Good data: Side correct - BUY

{'id': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'side': 'buy', 
'order': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'type': 'limit', 
'price': 0.37904999988822274, 
'amount': 44.06980492, 
'cost': 16.70465955, 
'symbol': 'XRP/USD', 
'timestamp': 1660863309520, 
'datetime': '2022-08-18T22:55:09.520Z', 
'fee': {'cost': 0.0584663, 'currency': 'USD'}, 
'info': 
{'id': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'clientOrderId': None, 
'timestamp': 1660863212470, 
'datetime': '2022-08-18T22:53:32.470Z', 
'lastTradeTimestamp': 1660863309520, 
'symbol': 'XRP/USD', 
'type': 'limit', 
'side': 'buy', 
'price': 0.37905, 
'cost': 16.70465955, 
'average': 0.37904999988822274, 
'amount': 44.06980492, 
'filled': 44.06980492, 
'remaining': 0.0, 
'status': 'closed', 
'fee': {'cost': 0.0584663, 'currency': 'USD'}, 
'info': {'id': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27', 
'marketSymbol': 'XRP-USD', 
'direction': 'BUY', 
'type': 'LIMIT', 
'quantity': '44.06980492', 
'limit': '0.379050000000', 
'timeInForce': 'GOOD_TIL_CANCELLED', 
'fillQuantity': '44.06980492', 
'commission': '0.05846630', 
'proceeds': '16.70465955', 
'status': 'CLOSED', 
'createdAt': '2022-08-18T22:53:32.47Z', 
'updatedAt': '2022-08-18T22:55:09.52Z', 
'closedAt': '2022-08-18T22:55:09.52Z'}, 
'trades': None}, 
'takerOrMaker': None}]

Bad data - New version of ccxt

![bad_data_bittrex](https://user-images.githubusercontent.com/108148029/185614220-5d3a1939-4fd6-40f5-ac4d-5e15ce2379ac.jpg)

Good data old version of ccxt

![good_data_oldversion](https://user-images.githubusercontent.com/108148029/185614294-0e2f55d4-1426-4574-ae11-3cd4b44fc8f8.jpg)

**Comment by sc0Vu** [comment] 2022-08-20 01:57
Hi @Curro666 

Is first order supposed to be sell? But we set to None?

```
{'info': {'id': '4e8294f8-9154-4676-b0da-851f18a15273',
'marketSymbol': 'XRP-USD',
'executedAt': '2022-08-18T22:55:09.52Z',
'quantity': '44.06980492',
'rate': '0.379050000000',
'orderId': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
'commission': '0.05846630',
'isTaker': False,
'direction': 'SELL'}}
```

**Comment by Curro666** [comment] 2022-08-21 19:38
> Hi @Curro666
> 
> Is first order supposed to be sell? But we set to None?
> 
> ```
> {'info': {'id': '4e8294f8-9154-4676-b0da-851f18a15273',
> 'marketSymbol': 'XRP-USD',
> 'executedAt': '2022-08-18T22:55:09.52Z',
> 'quantity': '44.06980492',
> 'rate': '0.379050000000',
> 'orderId': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
> 'commission': '0.05846630',
> 'isTaker': False,
> 'direction': 'SELL'}}
> ```

all orders are BUY but CCXTversion 1.92.32 say what one are sell and not real

**Comment by ttodua** [comment] 2022-10-21 09:25
@Curro666 can you tell if the issue is still present?

**Comment by Curro666** [comment] 2022-11-01 03:50
> @Curro666 can you tell if the issue is still present?

Hello, sorry for delay. Im tested now and not be good.

fetch_my_trades > bad side
fetch_order        >  good side

Code:

```
Order = 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27'
Par = 'XRP/USD'

try:
    importaordenes = bittrex.fetch_my_trades(Par)   
    for datos in importaordenes:        
        if datos['order'] == Order:
            print('fetch_my_trades')
            pp.pprint(datos)
except Exception as e:
    print('Error', e)
    
print('----------------------------------------------------')
importaordenes = bittrex.fetch_order(Order, Par)
print('fetch_order')

pp.pprint(importaordenes)
```

pydev debugger: starting (pid: 25156)
CCXT Version: 2.0.103
fetch_my_trades
{   'amount': 44.06980492,
    'cost': 16.704659554926,
    'datetime': '2022-08-18T22:55:09.520Z',
    'fee': {'cost': 0.0584663, 'currency': 'USD'},
    'fees': [{'cost': 0.0584663, 'currency': 'USD'}],
    'id': '4e8294f8-9154-4676-b0da-851f18a15273',
    'info': {   'commission': '0.05846630',
                'direction': 'SELL',
                'executedAt': '2022-08-18T22:55:09.52Z',
                'id': '4e8294f8-9154-4676-b0da-851f18a15273',
                'isTaker': False,
                'marketSymbol': 'XRP-USD',
                'orderId': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
                'quantity': '44.06980492',
                'rate': '0.379050000000'},
    'order': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
    'price': 0.37905,
    'side': 'sell',
    'symbol': 'XRP/USD',
    'takerOrMaker': 'maker',
    'timestamp': 1660863309520,
    'type': None}
----------------------------------------------------
fetch_order
{   'amount': 44.06980492,
    'average': 0.3790499998882228,
    'clientOrderId': None,
    'cost': 16.70465955,
    'datetime': '2022-08-18T22:53:32.470Z',
    'fee': {'cost': 0.0584663, 'currency': 'USD'},
    'fees': [{'cost': 0.0584663, 'currency': 'USD'}],
    'filled': 44.06980492,
    'id': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
    'info': {   'closedAt': '2022-08-18T22:55:09.52Z',
                'commission': '0.05846630',
                'createdAt': '2022-08-18T22:53:32.47Z',
                'direction': 'BUY',
                'fillQuantity': '44.06980492',
                'id': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
                'limit': '0.379050000000',
                'marketSymbol': 'XRP-USD',
                'proceeds': '16.70465955',
                'quantity': '44.06980492',
                'status': 'CLOSED',
                'timeInForce': 'GOOD_TIL_CANCELLED',
                'type': 'LIMIT',
                'updatedAt': '2022-08-18T22:55:09.52Z'},
    'lastTradeTimestamp': 1660863309520,
    'postOnly': False,
    'price': 0.37905,
    'remaining': 0.0,
    'side': 'buy',
    'status': 'closed',
    'stopPrice': None,
    'symbol': 'XRP/USD',
    'timeInForce': 'GTC',
    'timestamp': 1660863212470,
    'trades': [],
    'type': 'limit'}

**Comment by ttodua** [comment] 2022-11-01 21:23
@Curro666 this PR updates bitmex : https://github.com/ccxt/ccxt/pull/15311
so, you will need to wait for it and re-test then.

**Comment by Curro666** [comment] 2022-11-02 16:57
> @Curro666este PR actualiza bitmex: [# 15311](https://github.com/ccxt/ccxt/pull/15311) , por lo que deberá esperar a que se fusione y vuelva a probarlo.

sorry but not bitmex the exchange is Bittrex

**Comment by ttodua** [comment] 2022-11-02 17:43
> > @Curro666este PR actualiza bitmex: [# 15311](https://github.com/ccxt/ccxt/pull/15311) , por lo que deberá esperar a que se fusione y vuelva a probarlo.
> 
> sorry but not bitmex the exchange is Bittrex

ahhh. my bad. i'll revise this tomorrow.

**Comment by Curro666** [comment] 2022-11-04 17:34
> > > @Curro666este PR actualiza bitmex: [# 15311](https://github.com/ccxt/ccxt/pull/15311) , por lo que deberá esperar a que se fusione y vuelva a probarlo.
> > 
> > 
> > sorry but not bitmex the exchange is Bittrex
> 
> ahhh. my bad. i'll revise this tomorrow.

:-)

**Comment by ttodua** [comment] 2022-11-11 19:11
two things for update:
1) whoever is confused, please read  [the difference between trade vs order](https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades)
2) I've reproduced the issue and confirm it. it seems to happen on `maker` orders. 
I'll submit the fix.

**Comment by Curro666** [comment] 2022-11-12 04:25
@ttodua, I don't know what you mean by point 1

To check if it works is very simple. I imagine that you already know it but I put it so you don't have to think too much :-) Modifying a little the code that I put at the beginning you will know if it is right in a matter of seconds.
You look for all the trades made by any pair 'bittrex.fetch_my_trades(pair)', you get the order id and side (buy or sell) then you look in bittrex.fetch_order(Order, Pair) and check if the orders are of the same side as what was obtained previously, if it is the same it is good, if it is the opposite it is bad.


> dos cosas para actualizar:
> 
> 1. quien este confundido, lea    [la diferencia entre comercio y orden](https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades)
> 2. He reproducido el problema y lo confirmo. parece suceder en `maker`las órdenes. 
>    Enviaré la corrección.

**Comment by ttodua** [comment] 2022-11-12 08:33
> @ttodua, I don't know what you mean by point 1
> 
> To check if it works is very simple. I imagine that you already know it but I put it so you don't have to think too much :-) Modifying a little the code that I put at the beginning you will know if it is right in a matter of seconds. You look for all the trades made by any pair 'bittrex.fetch_my_trades(pair)', you get the order id and side (buy or sell) then you look in bittrex.fetch_order(Order, Pair) and check if the orders are of the same side as what was obtained previously, if it is the same it is good, if it is the opposite it is bad.
> 
> > dos cosas para actualizar:
> > 
> > 1. quien este confundido, lea    [la diferencia entre comercio y orden](https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades)
> > 2. He reproducido el problema y lo confirmo. parece suceder en `maker`las órdenes.
> >    Enviaré la corrección.

@Curro666 my answer's first part was not directed to you specifically, because you know what is that, that's why i've noted `whoever is confused...` , and second, I've said that I've reproduced the issue, so no need to worry for further explain, as I've perfectly seen what you meant, and submitted fix. please wait before it gets merged (this issue becomes closed automatically  and you'll be notified when it happens)

**Closed** 2022-11-13 11:16 UTC
Labels: bug

**Comment by Curro666** [comment] 2022-11-16 09:07
Hello, im testing now and are partially solved.

New test:

```
CCXT Version: 2.1.86
fetch_my_trades
{   'amount': 44.06980492,
    'cost': 16.704659554926,
    'datetime': '2022-08-18T22:55:09.520Z',
    'fee': {'cost': 0.0584663, 'currency': 'USD'},
    'fees': [{'cost': 0.0584663, 'currency': 'USD'}],
    'id': '4e8294f8-9154-4676-b0da-851f18a15273',
    'info': {   'commission': '0.05846630',
                'direction': 'SELL',
                'executedAt': '2022-08-18T22:55:09.52Z',
                'id': '4e8294f8-9154-4676-b0da-851f18a15273',
                'isTaker': False,
                'marketSymbol': 'XRP-USD',
                'orderId': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
                'quantity': '44.06980492',
                'rate': '0.379050000000'},
    'order': 'ab43ae40-a7b1-4e8b-9aaa-a3b105adad27',
    'price': 0.37905,
    'side': 'buy',
    'symbol': 'XRP/USD',
    'takerOrMaker': 'maker',
    'timestamp': 1660863309520,
    'type': None}
```
i see what the side of info['direction'] are bad.


BR

**Comment by ttodua** [comment] 2022-11-16 09:20
@Curro666 no, it is not bug in ccxt, `info` object is always whatever exchange api proves, the raw, unaltered data. So, we don't have any connection to the data provided there.
