### ISSUE TITLE
Help with watchMyTrades() dropping inbound messages

### ISSUE THREAD

**Issue by kryptland** [ccxt/ccxt#13848] opened 2022-06-14 11:28 UTC
watchMyTrades on Bitmex seems to be dropping inbound messages intermittently. The code below prints a message when watchMyTrades() returns data, but that doesn't happen consistently. I subclassed the handle_my_trades() method to show when a message is received, for each of which I'd have thought would cause a corresponding assignment to the 'data' variable.

I also noticed this when trying to (hackily) extend the Phemex class to support watchMyTrades, so doesn't seem to be specific to Bitmex. I suspect it's got something to do with the way my async loop is running, but I've been troubleshooting for an embarrassingly long time and can't pinpoint the issue. Help!

- OS: Mac OS 10.15.7
- Programming Language version: Python 3.8.2
- CCXT version: 1.0.48

```
import asyncio
import ccxtpro.bitmex

class myBitmex(ccxtpro.bitmex):
    def handle_my_trades(self, client, message):
        print('Handling incoming message')
        return super().handle_my_trades(client, message)

async def main_loop():
    apikey = 'REDACTED'
    apisecret = 'REDACTED'

    ex = myBitmex({ 'apiKey' : apikey, 'secret' : apisecret, 'newUpdates' : True, 'enableRateLimit' : True })
    ex.set_sandbox_mode(True)
    ex.verbose = True
    while True:
        data = await ex.watchMyTrades()
       print(f'Got data of length: {len(data)}') 
       await asyncio.sleep(0)

if __name__ ==  '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main_loop())
```

Log output (I manually created / closed some orders on Bitmex to generate the inbound messages):
```# py bitmex.py 
fetch Request: bitmex GET https://testnet.bitmex.com/api/v1/instrument/activeAndIndices RequestHeaders: {'Accept-Encoding': 'gzip, deflate'} RequestBody: None
fetch Response: bitmex GET https://testnet.bitmex.com/api/v1/instrument/activeAndIndices 200 ResponseHeaders: {'Date': 'Tue, 14 Jun 2022 11:02:50 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALBTG=rwMTHnzzg0JbWzQA9lyacGz/M09VER6GMEYAR5CXg7bJwpCH8tvipitAHn/HoA7AUMSgewRhm6Y0gjDsKO4LO4QYoNrCQYq6blUvxtqT58BiU5hYTlBLtbamx3GB4Ebt6Y3UIlKWOHUO8mrv5ucyK2BBWaLh4OdzKO124sbRxj46; Expires=Tue, 21 Jun 2022 11:02:50 GMT; Path=/, AWSALBTG=rwMTHnzzg0JbWzQA9lyacGz/M09VER6GMEYAR5CXg7bJwpCH8tvipitAHn/HoA7AUMSgewRhm6Y0gjDsKO4LO4QYoNrCQYq6blUvxtqT58BiU5hYTlBLtbamx3GB4Ebt6Y3UIlKWOHUO8mrv5ucyK2BBWaLh4OdzKO124sbRxj46; Expires=Tue, 21 Jun 2022 11:02:50 GMT; Path=/, AWSALBTG=rwMTHnzzg0JbWzQA9lyacGz/M09VER6GMEYAR5CXg7bJwpCH8tvipitAHn/HoA7AUMSgewRhm6Y0gjDsKO4LO4QYoNrCQYq6blUvxtqT58BiU5hYTlBLtbamx3GB4Ebt6Y3UIlKWOHUO8mrv5ucyK2BBWaLh4OdzKO124sbRxj46; Expires=Tue, 21 Jun 2022 11:02:50 GMT; Path=/', 'X-User-ID': '0', 'X-RateLimit-Limit': '30', 'X-RateLimit-Remaining': '29', 'X-RateLimit-Reset': '1655204571', 'X-Powered-By': 'Profit', 'Etag': 'W/"119ea7-2bVUn+COW1iafq5kl3fy05cgJyk"', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '71b293752c53aaf9-SYD', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: [<REDACTED>]
2022-06-14T11:02:51.181Z connecting to wss://testnet.bitmex.com/realtime with timeout 10000 ms
2022-06-14T11:02:52.279Z connected
2022-06-14T11:02:52.279Z ping loop
2022-06-14T11:02:52.280Z sending {'op': 'authKeyExpires', 'args': ['REDACTED', 1655204571181, 'REDACTED']}
2022-06-14T11:02:52.566Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2022-06-14T11:02:52.568Z message {"success":true,"request":{"op":"authKeyExpires","args":["REDACTED",1655204571181,"REDACTED"]}}
2022-06-14T11:02:54.569Z sending {'op': 'subscribe', 'args': ['execution']}
2022-06-14T11:02:54.866Z message {"success":true,"subscribe":"execution","request":{"op":"subscribe","args":["execution"]}}
2022-06-14T11:02:54.869Z message {"table":"execution","action":"partial","keys":[],"types":{"execID":"guid","orderID":"guid","clOrdID":"","clOrdLinkID":"","account":"long","symbol":"symbol","side":"symbol","lastQty":"long","lastPx":"float","underlyingLastPx":"float","lastMkt":"symbol","lastLiquidityInd":"symbol","simpleOrderQty":"float","orderQty":"long","price":"float","displayQty":"long","stopPx":"float","pegOffsetValue":"float","pegPriceType":"symbol","currency":"symbol","settlCurrency":"symbol","execType":"symbol","ordType":"symbol","timeInForce":"symbol","execInst":"symbol","contingencyType":"symbol","exDestination":"symbol","ordStatus":"symbol","triggered":"symbol","workingIndicator":"boolean","ordRejReason":"","simpleLeavesQty":"float","leavesQty":"long","simpleCumQty":"float","cumQty":"long","avgPx":"float","commission":"float","tradePublishIndicator":"symbol","multiLegReportingType":"symbol","text":"","trdMatchID":"guid","execCost":"long","execComm":"long","homeNotional":"float","foreignNotional":"float","transactTime":"timestamp","timestamp":"timestamp"},"foreignKeys":{"symbol":"instrument","side":"side","ordStatus":"ordStatus"},"attributes":{"account":"grouped","execType":"grouped"},"filter":{"account":402791},"data":[]}
Handling incoming message
2022-06-14T11:03:00.113Z message {"table":"execution","action":"insert","data":[{"execID":"33e7e34f-9d4a-c47e-907e-746b7e01169a","orderID":"8a9967c2-e54a-48f4-80eb-5e9792dc1fe2","clOrdID":"","clOrdLinkID":"","account":402791,"symbol":"XBTUSD","side":"Buy","lastQty":null,"lastPx":null,"underlyingLastPx":null,"lastMkt":"","lastLiquidityInd":"","simpleOrderQty":null,"orderQty":100,"price":22305,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"USD","settlCurrency":"XBt","execType":"New","ordType":"Limit","timeInForce":"GoodTillCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"New","triggered":"","workingIndicator":true,"ordRejReason":"","simpleLeavesQty":null,"leavesQty":100,"simpleCumQty":null,"cumQty":0,"avgPx":null,"commission":null,"tradePublishIndicator":"","multiLegReportingType":"SingleSecurity","text":"Submission from testnet.bitmex.com","trdMatchID":"00000000-0000-0000-0000-000000000000","execCost":null,"execComm":null,"homeNotional":null,"foreignNotional":null,"transactTime":"2022-06-14T11:02:59.964Z","timestamp":"2022-06-14T11:02:59.964Z"}]}
Handling incoming message
2022-06-14T11:03:02.204Z message {"table":"execution","action":"insert","data":[{"execID":"8722dea9-58d9-dda7-fb04-7789226c80b0","orderID":"7958f6ee-ec73-4233-b4a4-0c46774e135a","clOrdID":"","clOrdLinkID":"","account":402791,"symbol":"XBTUSD","side":"Buy","lastQty":null,"lastPx":null,"underlyingLastPx":null,"lastMkt":"","lastLiquidityInd":"","simpleOrderQty":null,"orderQty":100,"price":22305,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"USD","settlCurrency":"XBt","execType":"New","ordType":"Limit","timeInForce":"GoodTillCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"New","triggered":"","workingIndicator":true,"ordRejReason":"","simpleLeavesQty":null,"leavesQty":100,"simpleCumQty":null,"cumQty":0,"avgPx":null,"commission":null,"tradePublishIndicator":"","multiLegReportingType":"SingleSecurity","text":"Submission from testnet.bitmex.com","trdMatchID":"00000000-0000-0000-0000-000000000000","execCost":null,"execComm":null,"homeNotional":null,"foreignNotional":null,"transactTime":"2022-06-14T11:03:02.058Z","timestamp":"2022-06-14T11:03:02.058Z"}]}
Handling incoming message
2022-06-14T11:07:04.753Z message {"table":"execution","action":"insert","data":[{"execID":"0c25d14f-7d19-c951-3d2f-77c81078f156","orderID":"484403fe-d7a4-4ba4-b8b1-676573a4d868","clOrdID":"","clOrdLinkID":"","account":402791,"symbol":"XBTUSD","side":"Buy","lastQty":null,"lastPx":null,"underlyingLastPx":null,"lastMkt":"","lastLiquidityInd":"","simpleOrderQty":null,"orderQty":100,"price":22598,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"USD","settlCurrency":"XBt","execType":"New","ordType":"Market","timeInForce":"ImmediateOrCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"New","triggered":"","workingIndicator":true,"ordRejReason":"","simpleLeavesQty":null,"leavesQty":100,"simpleCumQty":null,"cumQty":0,"avgPx":null,"commission":null,"tradePublishIndicator":"","multiLegReportingType":"SingleSecurity","text":"Submission from testnet.bitmex.com","trdMatchID":"00000000-0000-0000-0000-000000000000","execCost":null,"execComm":null,"homeNotional":null,"foreignNotional":null,"transactTime":"2022-06-14T11:07:04.592Z","timestamp":"2022-06-14T11:07:04.592Z"},{"execID":"f9f1eea9-c9d4-a9c3-45b7-2cb0015e6b70","orderID":"484403fe-d7a4-4ba4-b8b1-676573a4d868","clOrdID":"","clOrdLinkID":"","account":402791,"symbol":"XBTUSD","side":"Buy","lastQty":100,"lastPx":22598,"underlyingLastPx":null,"lastMkt":"XBME","lastLiquidityInd":"RemovedLiquidity","simpleOrderQty":null,"orderQty":100,"price":22598,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"USD","settlCurrency":"XBt","execType":"Trade","ordType":"Market","timeInForce":"ImmediateOrCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"Filled","triggered":"","workingIndicator":false,"ordRejReason":"","simpleLeavesQty":null,"leavesQty":0,"simpleCumQty":null,"cumQty":100,"avgPx":22598,"commission":0.00075,"tradePublishIndicator":"PublishTrade","multiLegReportingType":"SingleSecurity","text":"Submission from testnet.bitmex.com","trdMatchID":"6ea738bb-c291-8fbe-9cc6-4302c8e0fa08","execCost":-442517,"execComm":331,"homeNotional":0.00442517,"foreignNotional":-100,"transactTime":"2022-06-14T11:07:04.592Z","timestamp":"2022-06-14T11:07:04.592Z"}]}
Handling incoming message
Got data of length: 1
```

**Comment by carlosmiei** [comment] 2022-06-14 11:33
Hello @kryptland 

Sorry, I'm not 100% clear yet, in your log can you point me to the inadvertently dropped message? I see 4 trades updates and 4 'Handling incoming message' printed out

**Comment by kryptland** [comment] 2022-06-14 23:13
Hi @carlosmiei - near the bottom of the logs (after the 2022-06-14T11:02:54.869Z timestamp), you can see 3x "Handling incoming message" lines, but only 1 "Got data of length: 1" message, the result being that in this scenario, the 'data' variable is only assigned once out of 3 incoming messages. FYI I've seen this happen with different, unpredictable sequences... it's not always just the last one in a series that gets processed properly.

**Comment by carlosmiei** [comment] 2022-06-20 09:32
Hello @kryptland, sorry for the delay.

After some analysis, I can confirm that no trade is being dropped. You see several updates but if you look carefully you will see that most of them are 'order related' updates (that we're not watching), not trades. You can easily confirm that by checking the 'execType' and as expected there is only one with the 'Trade' value meaning that **watch_my_trades** should have returned only once.
![image](https://user-images.githubusercontent.com/43336371/174570892-91cc2317-802e-4029-93fa-33fe96fe804d.png)

I'll close the issue now because no bug was found but feel free to ping me again if anything.

**Closed by carlosmiei** 2022-06-20 09:32 UTC
Labels: question
