### ISSUE TITLE
Enable Margin Auto-Deposit Status in KuCoin Futures

### ISSUE THREAD

**Issue by clemstar** [ccxt/ccxt#19905] opened 2023-11-09 22:41 UTC
### Operating System

Windows Server 2016

### Programming Languages

Python

### CCXT Version

4.1.46

### Description

Attempting to use the `kucoinfutures` implicit API endpoint `futuresPrivate_post_position_margin_auto_deposit_status` to enable the Margin Auto-Deposit Status for an open position in a market, but I'm receiving an Attribute Error:
```python
AttributeError: 'kucoinfutures' object has no attribute 'futuresPrivate_post_position_margin_auto_deposit_status'
```

I have confirmed its existence here:
```
In: 'futuresprivate_post_position_margin_auto_deposit_status' in dir(ccxt.kucoinfutures())
Out: True
```

What am I missing?

Reference to the API help page for the endpoint:
https://www.kucoin.cloud/docs/rest/futures-trading/positions/modify-auto-deposit-margin-status

### Code

```python
import ccxt
exchange = ccxt.kucoinfutures({
        'apiKey': 'XXXX',
        'secret': 'XXXX',
        'enableRateLimit': True,
        'options': {},
        'password': 'XXXX'
        })   
print('CCXT version:', ccxt.__version__) 
exchange.verbose = True
Market ='APE/USDT:USDT'
exchange.futuresPrivate_post_position_margin_auto_deposit_status({'symbol': Market, 'status': True})

```
Output

```python
CCXT version: 4.1.46
Traceback (most recent call last):

  File ~\venv\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\administrator\documents\python scripts\untitled4.py:19
    exchange.futuresPrivate_post_position_margin_auto_deposit_status({'symbol': Market, 'status': True})

AttributeError: 'kucoinfutures' object has no attribute 'futuresPrivate_post_position_margin_auto_deposit_status'
```

**Comment by pcriadoperez** [comment] 2023-11-10 02:38
Hi @clemstar , can you try `exchange.futuresPrivatePostPositionMarginAutoDepositStatus` ?

**Comment by clemstar** [comment] 2023-11-11 00:07
Yes, that appears to have succeeded in posting the request. However, I'm now getting an Internal Server Error. 

As you can see below, I confirm a position is currently open in the market that I want to enable the auto-deposit status for, but then the Internal Server Error is thrown in response to the request.

Any idea what may be going on here?

**Code**
```
print('CCXT version:', ccxt.__version__) 
Market ='APE/USDT:USDT'
openPosition = exchange.fetch_position(Market)
print(str(openPosition))
exchange.verbose = True
exchange.futuresPrivatePostPositionMarginAutoDepositStatus({'symbol': Market, 'status': True})
```


**Output**
```
CCXT version: 4.1.46
{'info': {'id': '500000000000101024', 'symbol': 'APEUSDTM', 'autoDeposit': False, 'maintMarginReq': 0.007, 'riskLimit': 20000, 'realLeverage': 1.06, 'crossMode': False, 'delevPercentage': 0.02, 'openingTimestamp': 1699504412598, 'currentTimestamp': 1699660838246, 'currentQty': -475, 'currentCost': -65.3061, 'currentComm': 0.07326322, 'unrealisedCost': -64.48284828, 'realisedGrossCost': -0.8232517244, 'realisedCost': -0.7499885044, 'isOpen': True, 'markPrice': 1.439, 'markValue': -68.3525, 'posCost': -64.48284828, 'posCross': 0.0443188382, 'posCrossMargin': 0.0, 'posInit': 64.4828482756, 'posComm': 0.0774060452, 'posCommCommon': 0.07737942, 'posLoss': 0.03735937, 'posMargin': 64.567213789, 'posMaint': 0.56276844, 'maintMargin': 60.6975620646, 'realisedGrossPnl': 0.8232517244, 'realisedPnl': 0.7784432244, 'unrealisedPnl': -3.8696517244, 'unrealisedPnlPcnt': -0.06, 'unrealisedRoePcnt': -0.06, 'avgEntryPrice': 1.358, 'liquidationPrice': 2.705, 'bankruptPrice': 2.715, 'settleCurrency': 'USDT', 'maintainMargin': 0.007, 'riskLimitLevel': 1}, 'id': '500000000000101024', 'symbol': 'APE/USDT:USDT', 'timestamp': 1699660838246, 'datetime': '2023-11-11T00:00:38.246Z', 'lastUpdateTimestamp': None, 'initialMargin': 64.4828482756, 'initialMarginPercentage': 0.9999999999317648, 'maintenanceMargin': 0.56276844, 'maintenanceMarginPercentage': 0.007, 'entryPrice': 1.358, 'notional': 64.48284828, 'leverage': 1.06, 'unrealizedPnl': -3.8696517244, 'contracts': 475.0, 'contractSize': 0.1, 'realizedPnl': 0.7784432244, 'marginRatio': None, 'liquidationPrice': 2.705, 'markPrice': 1.439, 'lastPrice': None, 'collateral': 60.6975620646, 'marginMode': 'isolated', 'side': 'short', 'percentage': None, 'stopLossPrice': None, 'takeProfitPrice': None}

fetch Request: kucoinfutures POST https://api-futures.kucoin.com/api/v1/position/margin/auto-deposit-status RequestHeaders: {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '63dd835a3aa4b90001c945eb', 'KC-API-TIMESTAMP': '1699660838554', 'Content-Type': 'application/json', 'KC-API-PASSPHRASE': '8QCnGzQ6QqWx4U3Ir5TJe6ZDrS69OwgLRsr/m3R0/+4=', 'KC-API-SIGN': 'kAIqFltFytYd52SKdAaH6gQY2hpU2ya3QZty0b3ZqNg=', 'KC-API-PARTNER-SIGN': 'B+72jnYxWQrWA3mjbsiF437/9ZXMGJ6Vc87jGIEyi+c=', 'KC-API-PARTNER': 'ccxtfutures', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"APE/USDT:USDT","status":true}

fetch Response: kucoinfutures POST https://api-futures.kucoin.com/api/v1/position/margin/auto-deposit-status 500 ResponseHeaders: {'Date': 'Sat, 11 Nov 2023 00:00:38 GMT', 'Content-Type': 'application/json', 'Content-Length': '47', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=8+paHgnvJ+ILSILN4tpSvZIbFJkfltafPL6vqBau0tcpxXb+HdiRJVIwz2OUS/YWFrp9Up+jqgslV7hVYFjhegpGoccwoxkEEdroUtBoUm8H6PvferDuDt49aM9b; Expires=Sat, 18 Nov 2023 00:00:38 GMT; Path=/, AWSALBCORS=8+paHgnvJ+ILSILN4tpSvZIbFJkfltafPL6vqBau0tcpxXb+HdiRJVIwz2OUS/YWFrp9Up+jqgslV7hVYFjhegpGoccwoxkEEdroUtBoUm8H6PvferDuDt49aM9b; Expires=Sat, 18 Nov 2023 00:00:38 GMT; Path=/; SameSite=None; Secure, __cf_bm=JM.aHvV5BXictwddV8LfFsVfaZGuJdA2zEzaS0KS02c-1699660838-0-AYlp/2l4ooPYorug/lyJviTLJxboV60LcN70EN3dyRpyfd++3oB1lcaPVhjiQeJbYU53rM4aQxwrvixDdMlB5jE=; path=/; expires=Sat, 11-Nov-23 00:30:38 GMT; domain=.kucoin.com; HttpOnly; Secure; SameSite=None, __cfruid=b65df786e67a4b95161d0eb7b7160c83d7d7ebad-1699660838; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None', 'gw-ratelimit-remaining': '1994', 'gw-ratelimit-limit': '2000', 'gw-ratelimit-reset': '29498', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '824241910a1f913a-FRA'} ResponseBody: {"msg":"Internal Server Error","code":"500000"}
Traceback (most recent call last):

  File ~\venv\Lib\site-packages\ccxt\base\exchange.py:613 in fetch
    response.raise_for_status()

  File ~\venv\Lib\site-packages\requests\models.py:1021 in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: Internal Server Error for url: https://api-futures.kucoin.com/api/v1/position/margin/auto-deposit-status


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File ~\venv\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\administrator\documents\python scripts\untitled4.py:22
    exchange.futuresPrivatePostPositionMarginAutoDepositStatus({'symbol': Market, 'status': True})

  File ~\venv\Lib\site-packages\ccxt\base\types.py:28 in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)

  File ~\venv\Lib\site-packages\ccxt\base\exchange.py:3195 in request
    return self.fetch2(path, api, method, params, headers, body, config)

  File ~\venv\Lib\site-packages\ccxt\base\exchange.py:3192 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\venv\Lib\site-packages\ccxt\base\exchange.py:629 in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\venv\Lib\site-packages\ccxt\kucoin.py:4068 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\venv\Lib\site-packages\ccxt\base\exchange.py:3567 in throw_exactly_matched_exception
    raise exact[string](message)

ExchangeNotAvailable: kucoinfutures Internal Server Error
```

**Comment by pcriadoperez** [comment] 2023-11-18 00:29
Hi @clemstar, I believe the issue is you are passing the symbol with ccxt unified symbol, in this case as you are calling kucoin directly you need to pass it in their format. In this case `APEUSDTM` I'll close the issue for now, but feel free to reach out if this does not solve it.

**Closed by pcriadoperez** 2023-11-18 00:29 UTC
Labels: question

**Comment by clemstar** [comment] 2023-11-18 21:09
Yes, that was the issue. All fixed now. Thanks for the feedback.
