### ISSUE TITLE
New Exchange: Coinbase

### ISSUE THREAD

**Issue by ydkishore30** [ccxt/ccxt#1086] opened 2018-01-06 03:29 UTC

**Comment by kroitor** [comment] 2018-01-06 04:23
Related to:
https://github.com/ccxt/ccxt/issues/466

**Comment by danricho** [comment] 2018-01-09 03:22
+1

**Comment by thiagodl** [comment] 2018-01-10 18:45
Thanks a lot.

**Comment by Bomper** [comment] 2018-01-14 10:06
This issue should be closed as a dupe of #466, which has [better information](https://github.com/ccxt/ccxt/issues/466#issuecomment-353149953) and should be reopened. I'm interested in implementing `fetchBalance()` on Coinbase.

**Closed** 2018-01-14 10:36 UTC
Labels: enhancement
