### ISSUE TITLE
Phemex Fetch Balance 'decimal.DivisionImpossible'

### ISSUE THREAD

**Issue by taylornielson** [ccxt/ccxt#8799] opened 2021-04-02 21:25 UTC
- OS: macOS Catalina
- Programming Language version: Python 3.7.7 and Python 3.8.2
- CCXT version: 1.39.1 and 1.45.98

###I'm just trying to call fetch balance with the Phemex integration###
config = {'credentials': ...}
exchange = ccxt.phemex(config=config)

###The Error###
Exception has occurred: InvalidOperation       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
[<class 'decimal.DivisionImpossible'>]
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/decimal_to_precision.py", line 74, in decimal_to_precision
    missing = abs(dec) % precision_dec
  File "/usr/local/lib/python3.7/site-packages/ccxt/phemex.py", line 706, in fetch_currencies
    maxAmount = float(self.decimal_to_precision(maxValueEv * precision, ROUND, 0.00000001, self.precisionMode))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1373, in load_markets
    currencies = self.fetch_currencies()
  File "/usr/local/lib/python3.7/site-packages/ccxt/phemex.py", line 1362, in fetch_balance
    self.load_markets()
  File "/workspace/app/integrations/ccxt.py", line 85, in authenticate
    self.client.fetch_balance()
  File "/workspace/app/integrations/interfaces.py", line 43, in __init__
    self.authenticate()
  File "/workspace/app/integrations/ccxt.py", line 64, in __init__
    super(CCXTService, self).__init__(user_integration, **kwargs)
  File "/workspace/app/integrations/ccxtimpl/phemex.py", line 16, in __init__
    super().__init__(self.EXCHANGE_ID, user_integration, **kwargs)
  File "/workspace/personal_sandbox.py", line 12, in <module>
    integration = PhemexService(ui)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main (Current frame)
    "__main__", mod_spec)

**Comment by kroitor** [comment] 2021-04-02 21:28
@taylornielson please, paste your verbose output from this code using the most recent version of CCXT (1.45.99+):

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.phemex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance()
```

**Comment by carlosmiei** [comment] 2022-01-31 18:51
Hello @taylornielson 
I can't reproduce this issue anymore, so I believe it's safe to assume that was fixed in the meantime. For that reason, I'm closing it but feel free to reopen it again if needed.

**Closed by carlosmiei** 2022-01-31 18:51 UTC
Labels: question
