### ISSUE TITLE
New Exchange: Pancakeswap

### ISSUE THREAD

**Issue by blademckain** [ccxt/ccxt#9094] opened 2021-04-29 15:35 UTC
Is there any support for the dex [pancakeswap ](https://pancakeswap.finance/)platform in the future?

**Comment by epigramx** [comment] 2021-05-13 08:52
You might want to also look into bogged finance, since that appears to be using limit orders, via pancake.

**Comment by ttodua** [comment] 2024-06-10 14:37
duplicate of #6337

**Closed by ttodua** 2024-06-10 14:37 UTC
Labels: new exchange
