### ISSUE TITLE
Bitvavo 500 when querying balance

### ISSUE THREAD

**Issue by Dom0724** [ccxt/ccxt#15404] opened 2022-10-25 14:12 UTC
When querying the balance for Bitvavo account, the API returns 500/internal error:

> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.bitvavo.com/v2/balance
> 
> During handling of the above exception, another exception occurred:
> ccxt.base.errors.ExchangeError: bitvavo {"errorCode":101,"error":"Unknown error. Operation may or may not have succeeded.

CCXT: 2.0.66, Ubuntu

**Comment by carlosmiei** [comment] 2022-10-25 17:42
Hello @Dom0724, thanks for reporting it we will take a look

**Comment by samgermain** [comment] 2022-10-25 22:17
Sounds like it's a problem with bitvavo's servers, can you try again?

**Comment by AlgoQ** [comment] 2022-10-26 11:57
Hi @Dom0724,

I just tried it out on Ubuntu 22.04 on the latest version of CCXT and everything works as expected. I think the problem is indeed like @samgermain mentioned related to bitvavo's servers.

**Comment by samgermain** [comment] 2022-11-14 21:28
It looks like this was an issue with the Bitvavo server, I'm going to close this issue, feel free to reopen it if you have any more questions

**Closed by samgermain** 2022-11-14 21:28 UTC
Labels: invalid/wontfix
