### ISSUE TITLE
Bitmex wrong timezone

### ISSUE THREAD

**Issue by wesleywilian** [ccxt/ccxt#4446] opened 2019-01-08 01:02 UTC
Hi there

- OS: Ubuntu 18.04
- Programming Language version: Python 3.6.5
- CCXT version: 1.18.114
- Exchange: Bitmex
- Method: bitmex.fetch_ohlcv(symbol, '1h', since=1546041600000)
- Problem: Wrong timezone in candles

Ccxt uses utc right ? If this is correct there is a problem on timezone of candles.
```
$ python3 bitmex-ohlcv-convert-1h-to-4h.py
Candles 1h
[[1546041600000, 3872, 3898.5, 3850, 3889.5, 63846530],
[1546045200000, 3889.5, 3930.5, 3882.5, 3897, 55210619],
...
```

The first line we have (timestamp, ohlcv)
```
[[1546041600000, 3872, 3898.5, 3850, 3889.5, 63846530],
```
1546041600000 = GMT: Saturday, 29 December 2018 00:00:00

Lets check on tradingview (look to the candle open is 3889.5):
![image](https://user-images.githubusercontent.com/13504091/50802545-f3d61500-12cd-11e9-9a10-257385c69a99.png)

Lets check on the api (using startTime 2018-12-29T00:00:00) the first open candle isn't 3889.5
https://www.bitmex.com/api/v1/trade/bucketed?binSize=1h&partial=false&symbol=XBT&count=2&startTime=2018-12-29T00%3A00%3A00-01%3A00
```
[
  {
    "timestamp": "2018-12-29T00:00:00.000Z",
    "symbol": "XBTUSD",
    "open": 3872,
    "high": 3898.5,
    "low": 3850,
    "close": 3889.5,
    "trades": 26097,
    "volume": 63846530,
    "vwap": 3875.969,
    "lastSize": 1127,
    "turnover": 1647263429824,
    "homeNotional": 16472.63429824005,
    "foreignNotional": 63846530
  },
  {
    "timestamp": "2018-12-29T01:00:00.000Z",
    "symbol": "XBTUSD",
    "open": 3889.5,
    "high": 3930.5,
    "low": 3882.5,
    "close": 3897,
    "trades": 22529,
    "volume": 55210619,
    "vwap": 3901.6777,
    "lastSize": 1,
    "turnover": 1415067662600,
    "homeNotional": 14150.67662600004,
    "foreignNotional": 55210619
  }
]
```

Now, lets check on api again but using startTime 2018-12-29T00:00:00-01:00 (Now is correct, the open of the first candle is 3889.5)
https://www.bitmex.com/api/v1/trade/bucketed?binSize=1h&partial=false&symbol=XBT&count=2&startTime=2018-12-29T00%3A00%3A00-01%3A00
```
[
  {
    "timestamp": "2018-12-29T01:00:00.000Z",
    "symbol": "XBTUSD",
    "open": 3889.5,
    "high": 3930.5,
    "low": 3882.5,
    "close": 3897,
    "trades": 22529,
    "volume": 55210619,
    "vwap": 3901.6777,
    "lastSize": 1,
    "turnover": 1415067662600,
    "homeNotional": 14150.67662600004,
    "foreignNotional": 55210619
  },
  {
    "timestamp": "2018-12-29T02:00:00.000Z",
    "symbol": "XBTUSD",
    "open": 3897,
    "high": 3907.5,
    "low": 3886.5,
    "close": 3898.5,
    "trades": 12523,
    "volume": 26896535,
    "vwap": 3895.9015,
    "lastSize": 7500,
    "turnover": 690394924901,
    "homeNotional": 6903.949249009986,
    "foreignNotional": 26896535
  }
]
```

With startTime 2018-12-29T00:00:00-**01:00** we have the same series of the tradingview.

Some code to reproduce
```
from pprint import pprint
import ccxt

bitmex = ccxt.bitmex({
    'enableRateLimit': True,
    'verbose': True,
})

candle = bitmex.fetch_ohlcv("BTC/USD", '1h', since=1546041600000)
pprint(candle)
```
Running with verbose mode we can see this request
```
Request: GET https://www.bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&startTime=2018-12-29+00%3A00%3A00 {'Accept-Encoding': 'gzip, deflate'} None
```
The startTime there is 2018-12-29+00:00:00

Would API be wrong or the tradingview ?

Thanks

**Comment by sgtStrom** [comment] 2019-01-14 00:37
I've come across this issue just an hour ago. It's not the timezone issue. It seems that the timestamp that BitMEX sends when using `/trade/bucketed` endpoint is now a close time of a candlestick, not an open one. You can check it by quering other time frames.

@kroitor I suppose we need a patch for this BitMEX issue.

P.S. By the way, did they announce this change somewhere?

**Comment by sgtStrom** [comment] 2019-01-14 03:11
I had created a ticket on BitMEX and this is the reply I've just received from them:

> Each bucket's timestamp is for the minute that it closes on. Therefore the current bucket will have a timestamp one minute ahead. If the time hits 2:05, then the first bucket will have the timestamp 2:06. When it hits 2:06, that bucket will be finalized.


Seems that this is not a bug and, therefore, we definitely need a fix for BitMEX.
@kroitor please, help us :)

**Comment by hroff-1902** [comment] 2019-02-09 20:24
I found this BitMEX 'feature' long time ago playing with their historical data. They provide each candle with the timestamp when the candle closes, yeah...

Because of this 'feature', for example, the freqtrade bot, which implemented with ccxt, fetches new data every 2 minutes for 1m time interval and every 2 hours for 1h time interval, hehe. The bot assumes the last candle indicates the beginning of the last candle interval (like most of other exchanges).

I thought about the possible solutions here (like ohlcv normalization function converting among others timestamps for candles) and guess it would be okay if one add an additional 'property' of the exchange in ccxt (in the "options" branch in describe() ???), something like, hmm,  "candle_timestamped_with_close_time: True". That would be enough for the application using ccxt to gather info about this feature of the particular exchange and modify its behaviour appropriately or convert timestamps if it needs so.

**Comment by kroitor** [comment] 2019-04-07 02:31
@sgtStrom @hroff-1902 apologies for the delays with my answer on this. Will hopefully get to it and will close this within before the end of next week.

**Comment by sgtStrom** [comment] 2019-04-08 03:05
@kroitor thanks for your answer!
I found out that timestamp in BitMEX candlesticks data is open, not closed. Which way are you going to resolve the issue? I need to know this to prevent any issues after upgrading ccxt.

**Closed** 2019-08-06 21:34 UTC

**Comment by kroitor** [comment] 2019-08-08 01:55
@sgtStrom it has been resolved as follows: https://github.com/ccxt/ccxt/issues/5641
