### ISSUE TITLE
Binance SSL: TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by baeriswyld** [ccxt/ccxt#6807] opened 2020-04-15 17:16 UTC
Hi all,

any idea why I m getting these error messages with Binance Margin accounts.

`HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/userDataStream (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1056)')))`

also:

`ccxt.base.errors.ExchangeError: GET https://api.binance.com/api/v3/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1108)')))`

Did something get depreciated and I missed out on some news ?

Many thanks for your help!

**Comment by coinfielddev** [comment] 2020-04-15 17:20
I am also getting this:
binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: write EPROTO 140498495311176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:802:

**Comment by kroitor** [comment] 2020-04-15 17:21
@baeriswyld hi! Looks like Binance is having problems today: https://github.com/ccxt/ccxt/issues/3057#issuecomment-613945625

This may be caused by an SSL certificate update or something similar. It works on my side now, so we will need more info from you – your ccxt version, your python version, and preferrably, the versions of python's `requests` and as much info as you can provide.

**Comment by kroitor** [comment] 2020-04-15 17:24
Binance has indeed updated their SSL certificate a week ago: 

<img width="1105" alt="Screen Shot 2020-04-15 at 20 22 55" src="https://user-images.githubusercontent.com/1294454/79367685-f3a7d900-7f56-11ea-8e71-82428450e7e5.png">

@baeriswyld @coinfielddev – is your CCXT installation older than one week or younger than one week?

**Comment by coinfielddev** [comment] 2020-04-15 17:24
"version": "1.24.85"

Using NodeJS

message=binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: write EPROTO 140498495311176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:802:
, stack=ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: write EPROTO 140498495311176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at fetchImplementation.catch (/app/node_modules/ccxt/js/base/Exchange.js:389:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7), constructor=class extends BaseClass {

                constructor (message) {

                    super (message)

                /*  A workaround to make `instanceof` work on custom Error classes in transpiled ES5.
                    See my blog post for the explanation of this hack:

                    https://medium.com/@xpl/javascript-deriving-from-error-properly-8d2f8f315801        */

                    this.constructor = Class
                    this.__proto__   = Class.prototype
                    this.name        = className
                    this.message     = message
                }
            }, name=ExchangeNotAvailable
{ ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: write EPROTO 140498495311176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at fetchImplementation.catch (/app/node_modules/ccxt/js/base/Exchange.js:389:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  constructor: [Function: ExchangeNotAvailable],
  name: 'ExchangeNotAvailable' }
{ ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo system request to https://api.binance.com/api/v3/exchangeInfo failed, reason: write EPROTO 140498495311176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at fetchImplementation.catch (/app/node_modules/ccxt/js/base/Exchange.js:389:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  constructor: [Function: ExchangeNotAvailable],
  name: 'ExchangeNotAvailable' }

**Comment by coinfielddev** [comment] 2020-04-15 17:25
This issue started happening about 1 hour ago

**Comment by kroitor** [comment] 2020-04-15 17:27
@coinfielddev yes, i know that, but the quesiton is not when it started, but when you've installed ccxt with its deps (that also includes `certifi` and python `requests`).

Does this help ↓

```
pip3 install certifi -U
```

?

**Comment by kroitor** [comment] 2020-04-15 17:43
@coinfielddev which version of Node do you have?

**Comment by kroitor** [comment] 2020-04-15 17:56
I've notified Binance support about these issues, so we need to wait a bit for a fix or for an explanation.

**Comment by coinfielddev** [comment] 2020-04-15 18:17
FROM node:8-alpine
WORKDIR app
ADD . .
RUN apk add --no-cache --virtual .gyp \
    python \
    make \
    g++ \
    git

RUN npm install -g node-gyp node-pre-gyp
RUN npm install
RUN npm rebuild 
EXPOSE 3000


CMD ["npm", "start"]

**Comment by coinfielddev** [comment] 2020-04-15 18:27
https://twitter.com/cz_binance/status/1250411130289152001

**Comment by kroitor** [comment] 2020-04-15 19:32
Looks like it's mostly fixed: https://twitter.com/cz_binance/status/1250432336774086660
Let us know if you have further difficulties with it. We will be happy if you report back whether the issue is resolved on your side or still persists. Closing this for now, feel free to reopen it or just ask further questions if any. Thx again!

**Closed by kroitor** 2020-04-15 19:32 UTC

**Comment by baeriswyld** [comment] 2020-04-16 13:47
Thank you @kroitor @coinfielddev for your speedy replies.
As you correctly identified, Binance had DNS issues.
Our systems are back to normal and no further issues to report.

Well, I have now the Binance twitter channel on Slack. Maybe that helps in the future.
