### ISSUE TITLE
Backlog is over max capacity of 1000

### ISSUE THREAD

**Issue by jyj545** [ccxt/ccxt#6436] opened 2020-01-31 06:41 UTC
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:linux
- Programming Language version:js
- CCXT version:1.21.64
- Exchange:huobipro
- Method:getMarketOrders
after one thousand query of getMarketOrders,it throws out that error,how to fix it or change the limit of 1000?

**Comment by kroitor** [comment] 2020-01-31 08:48
@jyj545 do you have the rate limiter enabled? Also, can you post the minimal but complete snippet of code to reproduce it (10-20 lines, including the instantiation, but without your keys)? 

- https://github.com/ccxt/ccxt/wiki/FAQ

That error is related to rate limiting in general. We need more info to be able to help.

**Comment by kroitor** [comment] 2020-01-31 08:53
@jyj545 I cannot find a `getMarketOrders()` method or a corresponding endpoint in `huobipro` – need the code to reproduce it.

**Comment by jyj545** [comment] 2020-02-02 07:35
in marketGetDepth

**Comment by kroitor** [comment] 2020-02-02 07:44
@jyj545 Please, read this: https://github.com/ccxt/ccxt/wiki/FAQ

We need 10-20 lines, including the instantiation, but without your keys – remove all irrelevant parts from it until you're left with a small snippet that reproduces the problem. That error is related to rate limiting in general. We need more info to be able to help.

**Comment by jyj545** [comment] 2020-02-15 15:48
errors here
ccxt.browser.js:6195 Uncaught (in promise) Error: Backlog is over max capacity of 1000
    at huobipro.throttle (ccxt.browser.js:6195)
    at huobipro.fetch2 (ccxt.browser.js:4074)
    at huobipro.request (ccxt.browser.js:4081)
    at huobipro.partial (ccxt.browser.js:4030)
    at huobipro.fetchOrdersByStates (ccxt.browser.js:56805)
    at async huobipro.fetchOpenOrdersV1 (ccxt.browser.js:56846)
    at async huobipro.fetchOpenOrders (ccxt.browser.js:56842)
    at async Object.getMyOrders (m_index.ecd752e583b54a5a31ae.js:1)
    at async Object.getMyOrders (m_index.ecd752e583b54a5a31ae.js:1)
    at async a.updateOrdersList (0.164040ff6b587850f069.js:1)
(anonymous) @ ccxt.browser.js:6195
fetch2 @ ccxt.browser.js:4074
request @ ccxt.browser.js:4081
partial @ ccxt.browser.js:4030
fetchOrdersByStates @ ccxt.browser.js:56805
async function (async)
updateOrdersList @ 0.164040ff6b587850f069.js:1
queryMarketOrders @ 0.164040ff6b587850f069.js:1
async function (async)
queryMarketOrders @ 0.164040ff6b587850f069.js:1
(anonymous) @ 0.164040ff6b587850f069.js:1
0.164040ff6b587850f069.js:1 xrp/usdt

**Comment by kroitor** [comment] 2020-02-15 18:04
@jyj545 please read my previous answer carefully. We need your code to reproduce it.

**Comment by jyj545** [comment] 2020-02-16 03:33
this.currentExchange = new ccxt['huobipro']({
                        "apiKey": localStorage.getItem("huobiApiKey"),
                        "secret": localStorage.getItem("huobisecret"),
                        'verbose': false, // set to true to see more debugging output
                        'timeout': 60000,
                        'enableRateLimit': true
                        , // add this
                        'urls': {
                            'api': {
                                'market': 'https://api.huobi.io',
                                'public': 'https://api.huobi.io',
                                'private': 'https://api.huobi.io',
                                'zendesk': 'https://huobiglobal.zendesk.com/hc/en-us/articles',
                            }
                        },
                        'hostname': 'api.huobi.io', // ←---------------  ADD THIS
                        'proxy': cors_api_url
                    })
                    // this.currentExchange.headers = await scrapeCloudflareHttpHeaderCookie (exchange.urls.www)
                    await this.currentExchange.fetchMarkets()
                    this.currentAlisa = 'huobi'
                    return this.currentExchange

**Comment by kroitor** [comment] 2020-02-16 03:37
@jyj545 you said

> after one thousand query of getMarketOrders

But there's no loops in your code, it's just one request there. Can you please paste the complete code? Keep removing everything irrelevant from it until you're left with just 10-20 lines that reproduce the issue. We still need a short but complete working program, not just a part of it. Otherwise it's very hard to tell the cause of the bug, since it may be elsewhere.

**Comment by jyj545** [comment] 2020-02-16 13:11
getMarketOrders: function () {
            clearInterval(this.getMarketOrdersTimer);
            this.getMarketOrdersTimer = setInterval(async () => {
                this.queryMarketOrders()
            }, 5000);
        },
        queryMarketOrders: async function () {
            let pair = this.BusinessCurrency.label + "/" + this.TradingCurrency.label
            console.log(pair)
            let req = await this.orderOperate.getMarketOrders({
                exchange: this.currentExchange,
                pair: pair.toUpperCase()
            });
}
    async getMarketOrders(param) {
        //获取coins

        let result = await ccxtUtils.getMarketOrders(param.exchange, param.pair)
        return result
    },
    async getMarketOrders(exchange, symbol) {
        let ex = await this.getExchange(exchange)
        let res = await ex.fetchOrderBook(symbol)
        return res
    },

**Comment by kroitor** [comment] 2020-02-16 13:19
@jyj545 almost there, can you plz also post the contents of your getExchange() method? The instantiation of the exchange matters here.

**Comment by jyj545** [comment] 2020-02-16 13:25
async getExchange(type) {
        switch (type) {
       
            case "huobi":
                if (this.currentExchange && type === this.currentAlisa) {
                    return this.currentExchange
                } else {
                    this.currentExchange = new ccxt['huobipro']({
                        "apiKey": localStorage.getItem("huobiApiKey"),
                        "secret": localStorage.getItem("huobisecret"),
                        'verbose': false, // set to true to see more debugging output
                        'timeout': 60000,
                        'enableRateLimit': true
                        , // add this
                        'urls': {
                            'api': {
                                'market': 'https://api.huobi.io',
                                'public': 'https://api.huobi.io',
                                'private': 'https://api.huobi.io',
                                'zendesk': 'https://huobiglobal.zendesk.com/hc/en-us/articles',
                            }
                        },
                        'hostname': 'api.huobi.io', // ←---------------  ADD THIS
                        'proxy': cors_api_url
                    })
                    // this.currentExchange.headers = await scrapeCloudflareHttpHeaderCookie (exchange.urls.www)
                    await this.currentExchange.fetchMarkets()
                    this.currentAlisa = 'huobi'
                    return this.currentExchange
                }

**Comment by jyj545** [comment] 2020-02-19 08:57
did u find out why ?

**Comment by kroitor** [comment] 2020-02-19 09:02
@jyj i didn't have the time yet, if you could write a complete short example that reproduces the issue that would help speed it up. If not – i will try to post a working example here as soon as i can.

**Comment by jyj545** [comment] 2020-02-19 15:10
i found that error come from the throttle.js,its content is bellow:
"use strict";

/*  ------------------------------------------------------------------------ */

const { sleep
      , now } = require ('./time')

/*  ------------------------------------------------------------------------ */

module.exports = {

    throttle: function throttle (cfg) {

        let   lastTimestamp = now ()
            , numTokens     = (cfg.numTokens !== undefined) ? cfg.numTokens : cfg.capacity
            , running       = false
            , counter       = 0

        const queue = []

        return Object.assign ((cost) => {

            if (queue.length > cfg.maxCapacity)
                throw new Error ('Backlog is over max capacity of ' + cfg.maxCapacity)

            return new Promise (async (resolve, reject) => {

                try {
                    queue.push ({ cost, resolve, reject })

                    if (!running) {
                        running = true
                        while (queue.length > 0) {
                            const hasEnoughTokens = cfg.capacity ? (numTokens > 0) : (numTokens >= 0)
                            if (hasEnoughTokens) {
                                if (queue.length > 0) {
                                    let { cost, resolve, reject } = queue[0]
                                    cost = (cost || cfg.defaultCost)
                                    if (numTokens >= Math.min (cost, cfg.capacity)) {
                                        numTokens -= cost
                                        queue.shift ()
                                        resolve ()
                                    }
                                }
                            }
                            const t = now ()
                                , elapsed = t - lastTimestamp
                            lastTimestamp = t
                            numTokens = Math.min (cfg.capacity, numTokens + elapsed * cfg.refillRate)
                            await sleep (cfg.delay)
                        }
                        running = false
                    }

                } catch (e) {
                    reject (e)
                }
            })

        }, cfg, { configure: newCfg => throttle (Object.assign ({}, cfg, newCfg)) })
    }
}

/*  ------------------------------------------------------------------------ */
should i change the maxCapacity to avoid the exception?

**Comment by jyj545** [comment] 2020-02-19 15:10
i found that error come from the throttle.js,its content is bellow:
"use strict";

/*  ------------------------------------------------------------------------ */

const { sleep
      , now } = require ('./time')

/*  ------------------------------------------------------------------------ */

module.exports = {

    throttle: function throttle (cfg) {

        let   lastTimestamp = now ()
            , numTokens     = (cfg.numTokens !== undefined) ? cfg.numTokens : cfg.capacity
            , running       = false
            , counter       = 0

        const queue = []

        return Object.assign ((cost) => {

            if (queue.length > cfg.maxCapacity)
                throw new Error ('Backlog is over max capacity of ' + cfg.maxCapacity)

            return new Promise (async (resolve, reject) => {

                try {
                    queue.push ({ cost, resolve, reject })

                    if (!running) {
                        running = true
                        while (queue.length > 0) {
                            const hasEnoughTokens = cfg.capacity ? (numTokens > 0) : (numTokens >= 0)
                            if (hasEnoughTokens) {
                                if (queue.length > 0) {
                                    let { cost, resolve, reject } = queue[0]
                                    cost = (cost || cfg.defaultCost)
                                    if (numTokens >= Math.min (cost, cfg.capacity)) {
                                        numTokens -= cost
                                        queue.shift ()
                                        resolve ()
                                    }
                                }
                            }
                            const t = now ()
                                , elapsed = t - lastTimestamp
                            lastTimestamp = t
                            numTokens = Math.min (cfg.capacity, numTokens + elapsed * cfg.refillRate)
                            await sleep (cfg.delay)
                        }
                        running = false
                    }

                } catch (e) {
                    reject (e)
                }
            })

        }, cfg, { configure: newCfg => throttle (Object.assign ({}, cfg, newCfg)) })
    }
}

/*  ------------------------------------------------------------------------ */
should i change the maxCapacity to avoid the exception?

**Comment by jyj545** [comment] 2020-02-19 15:12
and whats is the queue contains?

**Comment by kroitor** [comment] 2020-02-19 23:27
> i found that error come from the throttle.js,its content is bellow:

We know that from the very beginning of this issue, because that is the only place in CCXT where the backlog is mentioned. In other words, there's no point in copypasting the CCXT code, since we know it by heart )) The question is not where this error is thrown, but why it is thrown from there (if you have everything setup correctly). However, it is hard to tell whether you have everything set up correctly, since you have only pasted parts of your code, but not the complete snippet to reproduce it.

> should i change the maxCapacity to avoid the exception?

Nope, you should follow what I'm telling you if you want this issue to be resolved quickly – we need your code, not the CCXT code.

> and whats is the queue contains?

It contains the promisified queue of requests, which should never reach 1000, if the client code is done correctly. Upon issuing a unified call, a promise is placed into the queue. Later, when the [rate-limiting](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit) time is right, the request is retrieved from the queue and processed. That should never cause the queue backlog to grow above 1000, since in most cases those requests will get processed sooner. If it so happens, that you get that error – that means something is wrong on the user side.

Here is a short but complete snippet of code that does 2000 requests without ever falling with a backlog exception:

- https://github.com/ccxt/ccxt/blob/master/examples/js/basic-orderbook-polling.js

```JavaScript
"use strict";

const ccxt = require ('ccxt')
    , id = 'huobipro'
    , exchange = new ccxt[id] ({ enableRateLimit: true })
    , symbol = 'ETH/BTC'

;(async function main () {

    await exchange.loadMarkets ()

    for (let i = 0; i < 2000; i++) {

        const orderbook = await exchange.fetchOrderBook (symbol)
        console.log (new Date (), i, symbol, orderbook.asks[0], orderbook.bids[0])
    }

}) ()
```

↑ This is a complete program. You can copypaste it entirely to your working folder (where you have the ccxt installed) and launch it with `node basic-orderbook-polling.js`. It will run for several minutes, will make 2000 requests (more than 1000) and will not fail with a backlog error. 

<img width="1112" alt="Screen Shot 2020-02-20 at 02 25 14" src="https://user-images.githubusercontent.com/1294454/74886130-6302b180-5388-11ea-8fdb-11cc8dfc8a2b.png">

You do not have to spend your time editing it too much. You don't have to add the missing parts to that snippet. You can simply copy it, launch it and see the result right away – that it works, because the snippet above is a complete program. 

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

This is what we expect from you – a complete program to reproduce the issue. Something that we can copypaste without editing (we don't have the time to invent the missing bits), to run it and to see the problem on our side (or to see no problem). 

Can you make such a snippet? Otherwise we have to guess the missing parts that you haven't pasted. We need your code to be short but complete. Can you make such a short snippet to reproduce the issue, similar to the one above? 

Most often the user finds the problem in his code upon trying to recreate a reproducible short snippet. That is what you're expected to do. If you manage to have a short but complete snippet that consistently breaks down with a backlog exception – please paste the entire source code of it here.

**Comment by jyj545** [comment] 2020-02-20 03:13
sorry,i have gave all the code i can find about the exception.
and i used a slow corss-anyway serve to aviod access-control-allow-origin problem.its delay upto 6s.
maybe my request has been blocked by the slow network and at last reject the error?

**Comment by kroitor** [comment] 2020-02-20 03:15
> maybe my request has been blocked by the slow network and at last reject the error?

Nope, this does not seem to be the case. First of, I suggest that you try my snippet and tell if it's working for you. If it does work for you – I suggest that you create a similar snippet and post it here (we don't need more parts of the code – we need a complete snippet to reproduce it, therefore the code that you have posted above does not help determine the cause of the issue). If it my snippet does not work – please paste your output.

**Comment by kroitor** [comment] 2020-02-20 03:19
@jyj545 alternatively, you can describe what you are trying to achieve in a short description, and i will try to post an example that does something similar without an error.

**Comment by kroitor** [comment] 2020-02-21 18:39
@jyj545 you may also want to check out this post: https://github.com/ccxt/ccxt/issues/6467 for a possible solution to this issue.

**Comment by kroitor** [comment] 2020-03-28 18:06
Closing this for now, feel free to reopen it if needed or just ask further questions if any.

**Closed by kroitor** 2020-03-28 18:06 UTC
Labels: question
