### ISSUE TITLE
Currency networks format mismatching: Binance 

### ISSUE THREAD

**Issue by rglKali** [ccxt/ccxt#19153] opened 2023-09-10 08:15 UTC
### Operating System

Linux Ubuntu (WSL)

### Programming Languages

Python

### CCXT Version

4.0.66

### Description

When I use fetch_currencies() method on differenet exchanges, I usually see following strucuture of a 'network' in currency['networks']:

'networks': {'ERC20': {'active': True,
                        'deposit': True,
                        'fee': 3.0,
                        'id': 'ETH',
                        'info': {...},
                        'limits': {'deposit': {'max': None, 'min': 0.0},
                                   'withdraw': {'max': None, 'min': 3.0}},
                        'network': 'ERC20',
                        'precision': 1e-08,
                        'withdraw': True}},

But in Binance I see the output, similar to the original output of the Binance API:
'networks': [{'addressRegex': '^(0x)[0-9A-Fa-f]{40}$',
               'addressRule': '',
               'busy': False,
               'coin': 'AGLD',
               'contractAddress': '0x32353a6c91143bfd6c7d363b546e62a9a2489a20',
               'contractAddressUrl': 'https://etherscan.io/token/',
               'country': 'AE,BINANCE_BAHRAIN_BSC,KZ,FR,ES,PL,IT,SE,JP,NL,PL_BE',
               'depositDesc': '',
               'depositEnable': True,
               'entityTag': 'main',
               'estimatedArrivalTime': '5',
               'isDefault': True,
               'memoRegex': '',
               'minConfirm': '6',
               'name': 'Ethereum (ERC20)',
               'network': 'ETH',
               'resetAddressStatus': False,
               'sameAddress': False,
               'specialTips': '',
               'specialWithdrawTips': '',
               'unLockConfirm': '64',
               'withdrawDesc': '',
               'withdrawEnable': True,
               'withdrawFee': '3.59',
               'withdrawIntegerMultiple': '0.00000001',
               'withdrawMax': '9999999',
               'withdrawMin': '7.18'}],

I've already fixed this issue locally, but as far as I see in the header of the exchange file, it's not considered as a good practice.

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

### Code

```
  

```

**Comment by carlosmiei** [comment] 2023-09-10 10:32
Hello @rglKali,
 Yes binance's networks are not fully unified yet, we will try to improve it soon.

Thanks for reporting it.

**Comment by ttodua** [comment] 2023-09-11 14:38
duplicate of https://github.com/ccxt/ccxt/issues/19067

**Comment by ttodua** [comment] 2023-09-11 14:39
small note - they are going to be integrated soon.

**Closed by ttodua** 2023-09-11 14:38 UTC
