### ISSUE TITLE
Question about Huobi insufficient margin error?

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12752] opened 2022-04-12 19:00 UTC
import ccxt

account_huobi = ccxt.huobi({
"apiKey": 'api-key',
"secret": 'secret-key',
'options': {
'defaultType': 'swap',
'defaultSubType': 'linear',
}

})
params_huobi_open = {"offset": "open", "client_order_id": 1,"lever_rate":2}
params_huobi_close = {"offset": "close", "client_order_id": 5, "reduce_only": 1}
amount=10

HuobiPrice = account_huobi.fetch_ticker("ADA/USDT:USDT")["last"]
account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", amount, huobiPrice,params_huobi_open)

I have 150 $ in contract account, when i try to create order order it gives insufficient margin available error even though i have money.

**Comment by carlosmiei** [comment] 2022-04-13 14:29
Hello @flav1ooo,

Huobi has two types of margin accounts, cross and isolated. By default, the isolated one is being used to place the order, so if your funds are in the cross that can explain the problem.

If you really want to place the order using the cross margin account please try to set the `marginType` value with the proper value.

Example:

```Python
exchange = ccxt.huobi({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
    'options': {
        'defaultType': 'swap',
        'marginType': 'cross'
    },
})
````

**Comment by flav1ooo** [comment] 2022-04-13 14:37
> ```python
> 'marginType': 'cross'
> ```

Now it gives error that : huobi {"status":"error","err_code":1500,"err_msg":"One-way mode currently; Unavailable to place orders in hedge mode. ","ts":1649860604458}

**Comment by carlosmiei** [comment] 2022-04-13 15:03
@flav1ooo If you have open orders in one mode (one-way/hedge) you can't place orders in the other.

Also, it is very difficult to debug these problems without a verbose request+response log, if you can please provide it

**Comment by flav1ooo** [comment] 2022-04-13 15:08
> @flav1ooo If you have open orders in one mode (one-way/hedge) you can't place orders in the other.
> 
> Also, it is very difficult to debug these problems without a verbose request+response log, if you can please provide it

I do NOT have any open orders also my verbose in below : 

account_huobi.verbose = True
HuobiPrice = account_huobi.fetch_ticker("ADA/USDT:USDT")["last"]
account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", amount, huobiPrice,params_huobi_open)




[text.txt](https://github.com/ccxt/ccxt/files/8482525/text.txt)

**Comment by carlosmiei** [comment] 2022-04-13 15:36
@flav1ooo Ok, being that, you probably have the "one-way" mode selected. You can change it using the web ui or programmatically doing something like this:

Changing position mode 

```Python
    modeParams = {
        'margin_account': 'USDT',
        'position_mode': 'dual_side' # dual side for hedge mode and single-side for one way
    }
    res = exchange.contractPrivatePostLinearSwapApiV1SwapCrossSwitchPositionMode(modeParams)
    print(res)
````

Using the Web UI:
![image](https://user-images.githubusercontent.com/43336371/163217246-8f9bdad7-e6bf-47d1-bd35-b42aa6c52096.png)

Change it and try to place the order again

**Comment by flav1ooo** [comment] 2022-04-13 16:06
> > ```python
> > 'marginType': 'cross'
> > ```
> 
> It works ! Thank you so much i have just 3 more questions: 1- as you see in the code amount = 10 so it means 10 contract = 100 ADA in huobi how can i switch it to coin? I can switch it on web ui but when i give order by code if amount = 10 it orders 10 contract so 100 ADA
> 
> 2- How can i get BBO Price for any coin ?

3- i get this error now and i dont have any open position: ExchangeError: huobi {"status":"error","err_code":1050,"err_msg":"Customers order number is repeated. Please try again later.","ts":1649865887798}

**Comment by carlosmiei** [comment] 2022-04-13 16:33
@flav1ooo you're welcome

> 1- as you see in the code amount = 10 so it means 10 contract = 100 ADA in huobi how can i switch it to coin? I can switch it on web ui but when i give order by code if amount = 10 it orders 10 contract so 100 ADA

When using the API you have to use the contract measure, you can however have some logic on your side to convert contracts in currency amount and vice-versa, but when using ccxt always pass the number of contracts.

> How can i get BBO Price for any coin ?
You can get it using an implicit endpoint

Example:

```Python
    bboPrice = exchange.contractPublicGetSwapExMarketBbo()
    print(bboPrice)

```

Considering that the main subject of the issue is handled I'll close it, feel free to reopen it if anything

**Closed by carlosmiei** 2022-04-13 16:33 UTC
