### ISSUE TITLE
CEX order status codes do not return expected values.

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#440] opened 2017-11-01 10:01 UTC
UPDATE: It seems whole response for fetchOrder(id) in CEX exchange returns original api reply, not unified results. This should normally be included in 'info'.

Status codes should be returned in unified way, but status codes for CEX exchange are returned in original form as from CEX ('c' for cancelled, 'd' for closed etc). I suppose this is a bug, not expected behavior (?)

**Comment by kroitor** [comment] 2017-11-01 10:11
Hi! This is not an expected behaviour, nor it is a bug. We don't have all order APIs unified yet. Your PRs and contributions will be appreciated! We hope to deliver it soon. If you don't mind I will close this issue as a duplicate of #71 . Thx for your feedback. Stay tuned for updates, we deliver new functionality daily.

**Closed by kroitor** 2017-11-01 10:11 UTC

**Comment by kroitor** [comment] 2017-11-01 10:12
Here's an overview:

<img width="1554" alt="screen shot 2017-11-01 at 13 12 26" src="https://user-images.githubusercontent.com/1294454/32270288-56289434-bf06-11e7-9af1-dfa313668b63.png">
