### ISSUE TITLE
HitBTC offline pairs are reported active

### ISSUE THREAD

**Issue by dinamic** [ccxt/ccxt#4454] opened 2019-01-09 02:37 UTC
HitBTC APIs don't seem to be well designed as they return certain pairs, but no state.

To verify, please have a look at the system health:
- https://hitbtc.com/system-health

If we have a look at BCH as example, ccxt says it is active, but we can see at the page that it is offline. Further usage of the currency in the UI is impossible as well.

Here's what ccxt loadMarkets return for BCH/ETH today:

```
'BCH/ETH': {
    limits: {
        amount: { min: 0.01, max: undefined },
        price: { min: 0.000001, max: undefined },
        cost: { min: 1e-8, max: undefined }
    },
    precision: { price: 6, amount: 2 },
    tierBased: false,
    percentage: true,
    taker: 0.001,
    maker: -0.0001,
    info: {
        id: "BCHETH",
        baseCurrency: "BCH",
        quoteCurrency: "ETH",
        quantityIncrement: "0.01",
        tickSize: "0.000001",
        takeLiquidityRate: "0.001",
        provideLiquidityRate: "-0.0001",
        feeCurrency: "ETH"
    },
    id: "BCHETH",
    symbol: "BCH/ETH",
    base: "BCH",
    quote: "ETH",
    baseId: "BCH",
    quoteId: "ETH",
    active: true
},
```

- OS:
- Programming Language version: nodejs
- CCXT version: 1.18.114
- Exchange: hitbtc, hitbtc2
- Method: loadMarket

**Comment by dinamic** [comment] 2019-01-09 02:39
I having a look at their API playground at https://api.hitbtc.com/api/2/explore/.

It seems like one could get a prompt info whether a given currency is available by issuing requests at `/api/2/public/currency/<currency>`. For example:

```
curl -X GET "https://api.hitbtc.com/api/2/public/currency/BCH" -H "accept: application/json"
```

```
{
  "id": "BCH",
  "fullName": "Bitcoin Cash",
  "crypto": true,
  "payinEnabled": false,
  "payinPaymentId": false,
  "payinConfirmations": 2,
  "payoutEnabled": false,
  "payoutIsPaymentId": false,
  "transferEnabled": true,
  "delisted": false,
  "payoutFee": "0.0018"
}
```

I'm happy to do a PR querying this API endpoint, but the problem is if we do this for every supported currency, we would have a huge number of requests and rate limiting would quickly kick in.

Thoughts on how to mitigate the problem?

**Comment by kroitor** [comment] 2019-01-09 02:48
> Thoughts on how to mitigate the problem?

Well... We actually do load that info in fetchCurrencies already (they have an endpoint for all currencies at once):

- https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L23
- https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L607

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.hitbtc2 ()
const symbol = 'BCH/ETH';
;(async () => {
    await exchange.loadMarkets () // loads both markets and currencies
    const market = exchange.market (symbol)
    if (!market['active']) {
        throw new Error (exchange.id + ' ' + market['symbol'] + ' market is inactive');
    }
    const base = exchange.currency (market['base'])
    if (!base['active']) {
        throw new Error (exchange.id + ' ' + base['code'] + ' base currency is inactive');
    }
    const quote = exchange.currency (market['quote'])
    if (!quote['active']) {
        throw new Error (exchange.id + ' ' + quote['code'] + ' quote currency is inactive');
    }
}) ()
```

We can think of adding that to `fetchMarkets` as well, namely, load all currencies there and check to see if base and quote are both active to drive the market['active'] flag.

Let us know if that doesn't answer the question.

**Comment by dinamic** [comment] 2019-01-09 03:03
Oh, I didn't realize I could get that kind of info from there. Thanks for the hint!

I just tested the example code and it seem there's a minor issue with it - `exchange.currency (market['base'])` fetches `BCHABC`, not `BCH`.

**Comment by kroitor** [comment] 2019-01-09 03:13
> exchange.currency (market['base']) returns BCHABC, not BCH.

Nope it returns a currency object, with an 'active' flag in it...

```
> const ccxt = require ('./ccxt')
undefined
> const exchange = new ccxt.hitbtc2 ()
undefined
> ;(async () => {
... await exchange.loadMarkets()
... const market = exchange.market('BCH/ETH')
... const base = exchange.currency(market['base'])
... console.log (base)
... }) ()
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> { id: 'BCHABC',
  code: 'BCH',
  type: 'crypto',
  payin: true,
  payout: true,
  transfer: true,
  info:
   { id: 'BCHABC',
     fullName: 'Bitcoin Cash ABC',
     crypto: true,
     payinEnabled: true,
     payinPaymentId: false,
     payinConfirmations: 2,
     payoutEnabled: true,
     payoutIsPaymentId: false,
     transferEnabled: true,
     delisted: false,
     payoutFee: '0.0201' },
  name: 'Bitcoin Cash ABC',
  active: true,
  fee: 0.0201,
  precision: 8,
  limits:
   { amount: { min: 1e-8, max: 100000000 },
     price: { min: 1e-8, max: 100000000 },
     cost: { min: undefined, max: undefined },
     withdraw: { min: undefined, max: 100000000 } } }
```

Can you show the code you use to reproduce the error?

**Comment by kroitor** [comment] 2019-01-09 03:30
Basically, the code posted above should work, if it doesn't then please paste yours (reduce it to a small snippet of 5-20 lines, including the exchange instantiation). More about accesing markets and currencies here: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
Closing this for now if you don't mind, feel free to reopen it or ask further questions, if any. Let us know if we can help with anything else here.

**Closed by kroitor** 2019-01-09 03:30 UTC
Labels: question

**Comment by dinamic** [comment] 2019-01-09 09:12
@kroitor, the code works, its just that querying by `BCH` gives us `BCHABC` back.

Please, have a look at the output you provided:

```
   { id: 'BCHABC',
     fullName: 'Bitcoin Cash ABC',
```

What should be the proper way of querying base and quote of `BCH/ETH` with `exchange.currency`?

**Comment by kroitor** [comment] 2019-01-09 09:17
You're looking at the `info` which is just one of the fields of the object returned... The `info` is returned from ccxt in all objects for you to be able to see the raw non-unified exchange response. All other fields except `info` – are parts of the unified CCXT API... The purpose of the `info` field is documented in the Manual as well.

> Please, have a look at the output you provided:

Look carefully, the output I provided actually starts with:

```
{ id: 'BCHABC',
  code: 'BCH', ←------------- you want the code 
```

The difference between currency ids and currency codes is explained here (same with market ids and symbols): https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by dinamic** [comment] 2019-01-09 09:36
Well.. I'm looking at the info, because that's the raw output. Another reason is that according to your code, `BCH` is not offline, but it is.

Feel free to verify on your own, obviously, but this information is plain wrong. Here's what [system health](https://hitbtc.com/system-health) shows for both currencies. It is obvious ccxt is returning the wrong one.

![image](https://user-images.githubusercontent.com/11616/50890280-8ed00b80-1402-11e9-911a-a7d3000cb7e2.png)

![image](https://user-images.githubusercontent.com/11616/50890306-9ee7eb00-1402-11e9-8067-2768a759ca5a.png)

**Comment by dinamic** [comment] 2019-01-09 09:43
It could be my fault for not explaining what I'm trying to do beforehand, apologies for that.

I'm interested in getting info about `Bitcoin Cash (BCH)` and `Ethereum (ETH)`. Could it be I wrongly assumed the pair I'm after is `BCH/ETH`? I'm not sure where the confusion comes from.

**Comment by kroitor** [comment] 2019-01-09 09:46
```
mbp:ccxt igorkroitor$ node examples/js/symbols hitbtc2
Instantiating hitbtc2 exchange

Currencies:

id      | code       | type   | payin | payout | transfer | name                          | active | fee       | precision
--------------------------------------------------------------------------------------------------------------------------
...
BCHABC  | BCH        | crypto | true  | true   | true     | Bitcoin Cash ABC              | true   | 0.0201    | 8
...
BCHSV   | BSV        | crypto | true  | true   | true     | Bitcoin Cash SV               | true   | 0.1701    | 8
...

---------------------------------------------------------------
hitbtc2 has 884 symbols and 523 currencies

mbp:ccxt igorkroitor$ node examples/js/cli hitbtc2 currency BSV
hitbtc2.currency (BSV)
{        id:   "BCHSV",
       code:   "BSV",
       type:   "crypto",
      payin:    true,
     payout:    true,
   transfer:    true,
       info: {                 id: "BCHSV",
                         fullName: "Bitcoin Cash SV",
                           crypto:  true,
                     payinEnabled:  true, ←------------------- their API says "true"
                   payinPaymentId:  false,
               payinConfirmations:  2,
                    payoutEnabled:  true, ←------------------- their API says "true"
                payoutIsPaymentId:  false,
                  transferEnabled:  true, ←------------------- their API says "true"
                         delisted:  false,  ←------------------- their API says it's not delisted
                        payoutFee: "0.1701"           },
       name:   "Bitcoin Cash SV",
     active:    true, ←------------------- we say it's "true"
        fee:    0.1701,
  precision:    8,
     limits: {   amount: { min: 1e-8, max: 100000000 },
                  price: { min: 1e-8, max: 100000000 },
                   cost: { min: undefined, max: undefined },
               withdraw: { min: undefined, max: 100000000 }  } }
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc2 currency BCH
hitbtc2.currency (BCH)
{        id:   "BCHABC",
       code:   "BCH",
       type:   "crypto",
      payin:    true,
     payout:    true,
   transfer:    true,
       info: {                 id: "BCHABC",
                         fullName: "Bitcoin Cash ABC",
                           crypto:  true,
                     payinEnabled:  true, ←------------------- their API says "true"
                   payinPaymentId:  false,
               payinConfirmations:  2,
                    payoutEnabled:  true, ←------------------- their API says "true"
                payoutIsPaymentId:  false,
                  transferEnabled:  true, ←------------------- their API says "true"
                         delisted:  false, ←------------------- their API says it's not delisted
                        payoutFee: "0.0201"            },
       name:   "Bitcoin Cash ABC",
     active:    true, ←------------------- we say it's "true"
        fee:    0.0201,
  precision:    8,
     limits: {   amount: { min: 1e-8, max: 100000000 },
                  price: { min: 1e-8, max: 100000000 },
                   cost: { min: undefined, max: undefined },
               withdraw: { min: undefined, max: 100000000 }  } }
mbp:ccxt igorkroitor$
```

https://api.hitbtc.com/api/2/public/currency

Can you please point out what exactly is wrong?

> I'm not sure where the confusion comes from.

Most likely, because you're missing the BCH details from here:

- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/issues/4311

Let us know if that does not help...

**Comment by dinamic** [comment] 2019-01-09 10:20
I think I got it.. Sorry, I was trying to query info about a currency I don't know much about. I wasn't aware after the fork BCH is non existing and it became BCHABC and BCHSV.

I think I got what you were trying to say there. One thing is unclear to me - if BCH does not exist now, why ccxt maps BCH to BCHABC - it queries the wrong endpoint and gives impression that BCH trading is still a thing.

**Comment by dinamic** [comment] 2019-01-09 10:22
Also this thing happens. Is it a desired effect?

```
node examples/js/cli.js hitbtc2 currency BCHABC

hitbtc2.currency (BCHABC)
ExchangeError hitbtc2 does not have currency code BCHABC
---------------------------------------------------
[ExchangeError] hitbtc2 does not have currency code BCHABC

    at currency              ccxt/js/base/Exchange.js:897      throw new ExchangeError (this.id + ' does not have currency code ' + code)
    at main                  ccxt/examples/js/cli.js:270       const result = await exchange[methodName] (... args)
    at internalTickCallback  internal/process/next_tick.js:77

hitbtc2 does not have currency code BCHABC
```

**Comment by dinamic** [comment] 2019-01-09 10:44
Thanks, mate! This helped me to understand what is happening. I guess the biggest confusion factor for me was the HitBTC website.

**Comment by kroitor** [comment] 2019-01-09 10:48
@dinamic no worries, sometimes their naming can be confusing indeed, but that's the type of inconsistencies that we have target with unified API, symbols and codes, so, if you stick to the CCXT naming standard when you use unified CCXT methods – you should be fine )
