### ISSUE TITLE
including ccxt as dependency in setup.py not working 

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#3474] opened 2018-07-24 13:17 UTC
- OS: Linux
- Programming Language version: python 3.6.5, 3.7.0
- CCXT version: 1.16.89 (latest on pypi at the time of writing)

Including ccxt in a setup.py file and installing using `python setup.py install` fails / blocks the installation.
Below is a very simple setup.py file for an empty project to install ccxt.

I also added the log for this - it get's stuck at the  last line of the log, takes 100% and does nothing for at least 5 minutes (then i killed it), and does not process any further.

Installing directly via `pip install ccxt==1.16.89` works flawlessly within seconds, as well as 
when adding `ccxt==1.16.89` to a requirements file and using `pip install -r requirements.txt`.

Using numpy (see comment in the setup.py file) works fine, so the setup-file itself seems correct.

```
from setuptools import setup

setup(name='setup_test',
      version="0.0.1",
      description='a sample setup',
      url='https://github.com/whatever/whatever',
      author='contributors',
      author_email='all@none.com',
      license='GPLv3',
      packages=['testmodule'],
      install_requires=[
          'ccxt==1.16.89',
          #'numpy',
      ],
      )

```

install logs
``` 
python setup.py install 
running install
running bdist_egg
running egg_info
writing setup_test.egg-info/PKG-INFO
writing dependency_links to setup_test.egg-info/dependency_links.txt
writing requirements to setup_test.egg-info/requires.txt
writing top-level names to setup_test.egg-info/top_level.txt
reading manifest file 'setup_test.egg-info/SOURCES.txt'
writing manifest file 'setup_test.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/testmodule
copying build/lib/testmodule/__init__.py -> build/bdist.linux-x86_64/egg/testmodule
byte-compiling build/bdist.linux-x86_64/egg/testmodule/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/setup_test-0.0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing setup_test-0.0.1-py3.6.egg
Removing /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages/setup_test-0.0.1-py3.6.egg
Copying setup_test-0.0.1-py3.6.egg to /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages
setup-test 0.0.1 is already the active version in easy-install.pth

Installed /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages/setup_test-0.0.1-py3.6.egg
Processing dependencies for setup-test==0.0.1
Searching for ccxt==1.16.89
Reading https://pypi.python.org/simple/ccxt/

```

**Comment by frosty00** [comment] 2018-07-24 14:30
I just tried `python3.6 setup.py install` and it ran normally.

Maybe you don't have the right permissions.

Try

`sudo python3.6 setup.py install`

**Comment by frosty00** [comment] 2018-07-24 14:31
```
Using /usr/local/lib/python3.6/site-packages
Searching for multidict==4.3.1
Best match: multidict 4.3.1
Adding multidict 4.3.1 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for async-timeout==3.0.0
Best match: async-timeout 3.0.0
Adding async-timeout 3.0.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for idna-ssl==1.1.0
Best match: idna-ssl 1.1.0
Adding idna-ssl 1.1.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for attrs==18.1.0
Best match: attrs 18.1.0
Adding attrs 18.1.0 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Finished processing dependencies for ccxt==1.14.205```

**Comment by xmatthias** [comment] 2018-07-24 14:50
it's not about using the setup.py from ccxt, but using ccxt in a "foreign" setup.py file as dependency (sorry if i wasn't clear)

i actually tested it in a venv, so permissions should not be a problem, but i did try sudo too without success.

**Comment by kroitor** [comment] 2018-07-24 14:56
@frosty00 yep, the problem is not with CCXT's setup.py, but when CCXT is a install_requires-dependency. I've tried the above config on my side and it reproduced it.

@xmatthias can you try this:

```
from setuptools import setup

setup(name='setup_test',
      version="0.0.1",
      description='a sample setup',
      url='https://github.com/whatever/whatever',
      author='contributors',
      author_email='all@none.com',
      license='GPLv3',
      packages=['testmodule'],
      extras_require=[
            ':python_version>="3.6.0"': [
                  'ccxt==1.16.89',
            ],
      ],
      )
```

?

**Comment by xmatthias** [comment] 2018-07-24 15:00
it's actually the following (extras_require as a dict, not list)

but produces the same exact problem

```
from setuptools import setup

setup(name='setup_test',
      version="0.0.1",
      description='a sample setup',
      url='https://github.com/whatever/whatever',
      author='contributors',
      author_email='all@none.com',
      license='GPLv3',
      packages=['testmodule'],
      extras_require={
            ':python_version>="3.6.0"': [
                  'ccxt==1.16.89',
            ],
      },
      )

```

```
python setup.py install
running install
running bdist_egg
running egg_info
writing setup_test.egg-info/PKG-INFO
writing dependency_links to setup_test.egg-info/dependency_links.txt
writing requirements to setup_test.egg-info/requires.txt
writing top-level names to setup_test.egg-info/top_level.txt
reading manifest file 'setup_test.egg-info/SOURCES.txt'
writing manifest file 'setup_test.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/testmodule
copying build/lib/testmodule/__init__.py -> build/bdist.linux-x86_64/egg/testmodule
byte-compiling build/bdist.linux-x86_64/egg/testmodule/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying setup_test.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/setup_test-0.0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing setup_test-0.0.1-py3.6.egg
Removing /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages/setup_test-0.0.1-py3.6.egg
Copying setup_test-0.0.1-py3.6.egg to /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages
setup-test 0.0.1 is already the active version in easy-install.pth

Installed /home/xmatt/.pyenv/versions/3.6.5/envs/test_36/lib/python3.6/site-packages/setup_test-0.0.1-py3.6.egg
Processing dependencies for setup-test==0.0.1
Searching for ccxt==1.16.89
Reading https://pypi.python.org/simple/ccxt/


```

**Comment by xmatthias** [comment] 2018-07-24 16:37
running ` python setup.py --verbose  install` shows the problem i think

there are sooooo many versions on pypi from ccxt, and setup-tools appears to run through them all ...


I didn't copy the full output, which could get very long - but i think this is a question of patience - it can be outwaited i think, as it is doing "something" ...

doesn't make sense to me if the version is specified explicitly - but that's not really ccxt's problem, but one from setuptools i think

```
Installed /home/xmatt/.pyenv/versions/3.6.5/envs/newtest36/lib/python3.6/site-packages/setup_test-0.0.1-py3.6.egg
Processing dependencies for setup-test==0.0.1
Searching for ccxt==1.17.1
Reading https://pypi.python.org/simple/ccxt/
Found link: https://files.pythonhosted.org/packages/cf/47/427a4982bda5d9358a171a5652071540bad1957af26930acf18a06bdc96e/ccxt-0.1.5-py2.py3-none-any.whl#sha256=b34d92f1851bd7af50660d3407198d092344f562ab9ea73a4c54717737460f61
Found link: https://files.pythonhosted.org/packages/9b/13/4433d30621609d717a366a6c14026067b35e62361487423e7855f7b458a2/ccxt-0.1.5.tar.gz#sha256=c62dba4c48fb53726e2373b38852a5539421547f9f42920748529249b1830738
Found link: https://files.pythonhosted.org/packages/77/cf/8a160b01e202b02fca2be065878d503679b60aa8f0acd3c786ffca4ad5c2/ccxt-0.1.6.tar.gz#sha256=e8f89f381936d264b03dbc2085298966ac40ca64564564d31f07e3ef34130852
Found link: https://files.pythonhosted.org/packages/a5/4b/2657710a84f1e62862fe9d0665401ea71da9d83ae76a59ad129b8bce4de3/ccxt-0.1.7.tar.gz#sha256=dc6e9895066193c3658a17d84c47d5db1162171a0316715a082d18f3dfba02d7
Found link: https://files.pythonhosted.org/packages/09/6e/225e1d8f0972e29935ff86b8c4adf14db2b5bc57a0813ff59912f1c8279c/ccxt-0.1.8.tar.gz#sha256=bd2b1d4568649341b7c9f93b8d600afab65a913565cb9c3a203abd5acf8bbf45
Found link: https://files.pythonhosted.org/packages/b8/74/651c2a76efd7d4ef1e812a8d4372b2310e7d62f8ec43f79ae306f32b27f8/ccxt-0.1.9.tar.gz#sha256=17c1b220d2a16f7fad8b973e19f60954cb9240fe65cc74962cd2b9173061608f
Found link: https://files.pythonhosted.org/packages/7b/94/8a6355364490b7283c6e472a715229c531eb42f2d55d82dd61cae36383e6/ccxt-0.1.10.tar.gz#sha256=b12ee813a2e69218aef9983e675dd1d4e32a197edc4a98377a04373ed8164517
Found link: https://files.pythonhosted.org/packages/00/62/a16d47b9a6eeb8be7915b070414fcc954036cb4340742d6f97f1e638deb1/ccxt-0.1.11.tar.gz#sha256=f2162fc5c5a75d9f68a6dd59e06a55cf2d809560340e3cdd15939cdfef025256
Found link: https://files.pythonhosted.org/packages/aa/71/fc031f1550a4b841f38d5c577e75e0492a2284c3953f493b67c4791db476/ccxt-0.1.12.tar.gz#sha256=35f3ddc6d9a5a711b2dd7bdf113838e78997d441f6ca24a4cb5d4f726a2fd605
Found link: https://files.pythonhosted.org/packages/11/fd/1039cc30c1e2e921a6cf78f052cbb01bef5ef0db9ca9fd2edfd17d040a31/ccxt-0.1.13.tar.gz#sha256=1699c4e6517a5b258d821dd0d416d42ab8299f4f90d5f9d469288bc43f3777d4
...
```

**Comment by kroitor** [comment] 2018-07-24 16:42
@xmatthias it's a common pitfall with package sites... We've recently contacted composer for approximately the same reason – the website was trying to show all versions, many of them were already outdated a year ago... So, there's very little point in scraping all versions everytime, whether on a website, or in a setup-scripting toolset. Indeed, this looks like a setuptools issue, so I guess, you can try reporting it there. We'll look for possible solutions to this in our turn and will get back to you with our findings. I'd close this for now, feel free to ask further question or to reopen it if needed.

**Closed by kroitor** 2018-07-24 16:42 UTC
