### ISSUE TITLE
How to check network availability for withdraw 

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#16521] opened 2023-01-17 14:13 UTC
### Operating System

Windows 10 

### Programming Languages

JavaScript

### CCXT Version

2.5.47

### Description

Is there a possibility to check the network for withdraw at the moment. I give an example, I use the function to check the network, it is there (Erc20). But trying to withdraw the deposit will not come, because in this network there are technical works on this coin (I found this out by visiting the site). I know that on exchanges like Mexc you can check all networks and their availability on every coin. But on exchanges like a gate, kucoin this cannot be done even with an api key. Is there a way to check the withdraw on a specific network at the current moment before the output? Moreover, how do I use the withdraw function with specific networks, such as  ACALA. What should be indicated in the params {network}, these networks may have different names from exchange to exchange, for example, ACA on the gate, Acala on mexc and generally do not have a network identifier on kucoin. I understand that this function is under development, but how to use the available functions as efficiently as possible, getting the maximum data about networks and avoiding loss of funds during withdrawals

```
const ccxt = require("ccxt");

async function a {
  let gate= new ccxt.gate();
  await gate.loadMarkets();
  console.log(gate.currency("DYP"));  // will see chain - erc20, and it is exist but not available now
}

gate.apiKey = "key";
gate.secret = "secret";

(async () => {
    await gate.withdraw("DYP", 100, "0xdsfsdfsdf", {
      network: "ERC20",  // I do not know what will happen if you perform a similar function. I'm not very experienced and I'm afraid of losing funds. But I know that it is impossible to check this by entering an unrealistic balance. The function will return "Error: You don't have enough balance."
    });
})();

**Comment by samgermain** [comment] 2023-01-18 09:13
You can try the methods `fetchDepositAddressesByNetwork` and `currencies`. If the network is there for deposits, it will be there for withdraws as well

**Comment by AlwxDavydov** [comment] 2023-01-18 14:36
Okay, thank you. Great work. I will continue to work with different networks and report any bugs that I come across/

**Comment by ttodua** [comment] 2023-01-18 14:42
> Okay, thank you. Great work. I will continue to work with different networks and report any bugs that I come across.

you feedback will be appreciated, you can look through any of those PR files, and you can see the networks lists, i.e. here: 
- mexc: https://github.com/ccxt/ccxt/pull/16345/files#diff-321f459daa26ff101cea1bedf2b82d023dcbb2422700f94579df4e193e1323caR405
- binance : https://github.com/ccxt/ccxt/pull/16515/files#diff-13b40969472b078d4e2cb520b264e56efb07c603587c854842cfc45c946f7b82R928
- etc..
- 
and you can revise. if you find any inaccuracy through them, let us know plz. thanks

**Comment by petrkl** [comment] 2023-02-04 11:03
Hi!

I continue question) 
For most of all exchanges working solution to get all withdraw networks and fees is `fetchDepositAddressesByNetwork `
But what about others like Kucoin and OKX?

I understand that methods 

```
$params = array (
    'network' => 'SOL' 
);
```
`$exchange->fetchDepositWithdrawFee("USDT", $params);`
or
`$exchange->fetchTransactionFee("USDT", $params);`

But for one network I need one request.

Is it possible to get information about possible networks and fees for a single request or minimal count requests?

**Comment by ttodua** [comment] 2023-02-04 13:35
it is possible with `fetchCurrencies() -> networks` but almost all exchanges are still pending in these PRs https://github.com/orgs/ccxt/projects/54/views/1
i dont know when the might be reviewed & merged, I advise to ask @carlosmiei about potential ETAs.

**Comment by ttodua** [comment] 2023-09-11 14:43
duplicate of https://github.com/ccxt/ccxt/issues/19067
(please continue further comments in that thread)

**Closed by ttodua** 2023-09-11 14:43 UTC
Labels: duplicate
