### ISSUE TITLE
_ssl.c:629: The handshake operation timed out

### ISSUE THREAD

**Issue by orikalinski** [ccxt/ccxt#5040] opened 2019-04-29 08:20 UTC
Hello,
When i'm trying to use a proxy, I'm starting to get the following exceptions after a while (approximately 10-20 minutes)
Just want to clarify that when I'm getting those errors, I'm getting them on almost half of the requests.

- OS: Ubuntu 16.04
- Programming Language version: Python 3.5.2
- CCXT version: 1.17.60
- Exchange: Binance
- Method: Not something in particular

The full ccxt traceback example:
```
  File "/home/X/.local/lib/python3.5/site-packages/ccxt/binance.py", line 732, in fetch_open_orders
    response = self.privateGetOpenOrders(self.extend(request, params))
  File "/home/X/.local/lib/python3.5/site-packages/ccxt/binance.py", line 904, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/X/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 327, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/X/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 405, in fetch
    self.raise_error(ExchangeError, url, method, e)
  File "/home/X/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 312, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: binance https://api.binance.com/api/v3/openOrders?symbol=NANOBTC&recvWindow=5000&timestamp=1553615028653&signature=X
 GET HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/openOrders?symbol=NANOBTC&recvWindow=5000&timestamp=1553615028653&signature=X (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:629: The handshake operation timed out',)))
```

Any clue what could go wrong?
Thanks,
Ori

**Comment by tezeug** [comment] 2019-04-29 09:02
You’ve exceeded the max. amount of retries (usually order placements). Just wait or change your bot’s code to send less calls, I guess but @kroitor is the professional.

**Comment by orikalinski** [comment] 2019-04-29 09:50
Thanks for the response,
I forgot to mention that I'm not having that without proxies with the same amount of traffic

**Comment by kroitor** [comment] 2019-04-30 00:49
@orikalinski what's your version of the openssl (on both your side and the proxy side) ? Do you have `pyopenssl` installed?

The most probable cause of the issue is with the SSL installation itself. This could influence either your side or it can be an issue on the side of the proxy. In order to check for that – you can try a different (nonrelated) proxy for comparison.

Check out the following:

- https://github.com/ccxt/ccxt/issues/776
- https://github.com/ccxt/ccxt/issues/2522
- https://github.com/ccxt/ccxt/issues/2624

Does any of those issues help?

**Comment by orikalinski** [comment] 2019-04-30 07:13
@kroitor, may I ask which version you believe that cause the issue?
On my in house workers I have 1.0.2g which works just fine. On the proxies, I'm using an external service and waiting for response.
I'm considering using in house solution for the proxies, wondering if 1.1.0g can cause those issues for some reason.

Thanks

**Comment by kroitor** [comment] 2019-04-30 08:02
@orikalinski i'm not sure about 1.0.2g exactly (haven't tested it, so can't say for sure), but i've heard of these types of problems with 1.0.2e, so, updating may help in some cases. 1.0.2g is behind at this point, more than three years old. I'd suggest to investigate in that direction. Let me know if updating doesn't help or resolve anything. I'd close this for now, feel free to reopen it or just post further questions here – will be happy to help as soon as I can.

**Closed by kroitor** 2019-04-30 08:02 UTC
Labels: question
