### ISSUE TITLE
Getting {"code":-2019,"msg":"Margin is insufficient." errors for funded accounts

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7542] opened 2020-08-31 15:26 UTC
OS: Linux PYTHONWORK 5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Programming Language version: Python 2.7.17
CCXT version: latest
Exchange: binance
Method: fapiPrivatePostMarginType, createOrder

Hi,

This is in reference to an earlier message: https://github.com/ccxt/ccxt/issues/7534

I am not understanding why this Order will not go through. I keep getting the following error:
{"code":-2019,"msg":"Margin is insufficient."}

----------------------------------------------------------
This is what is associated with the SPOT account for USDT:
----------------------------------------------------------

command executed:   **wallets = exchange.fetch_balance()**

`{{'symbol': 'USDT', 'requested_data': {'symbol': 'USDT', 'free': 7.74572124, 'used': 0.0, 'total': 7.74572124}, 'symbol_non_zero': [{'symbol': 'USDT', 'free': 7.74572124, 'used': 0.0, 'total': 7.74572124}], 'symbol_non_zero_ct': 1, 'all_non_zero': [{'symbol': 'BTC', 'free': 0.00099955, 'used': 0.0, 'total': 0.00099955}, {'symbol': 'USDT', 'free': 7.74572124, 'used': 0.0, 'total': 7.74572124}], 'all_non_zero_ct': 2}}}`

----------------------------------------------------------
This is what is associated with the FUTURES account for USDT
----------------------------------------------------------

command executed:   **wallets = exchange.fetch_balance()**

`{ {'symbol': 'USDT', 'free': 20.0, 'used': 0.0, 'total': 20.0}, 'symbol_non_zero': [{'symbol': 'USDT', 'free': 20.0, 'used': 0.0, 'total': 20.0}], 'symbol_non_zero_ct': 1, 'all_non_zero': [{'symbol': 'USDT', 'free': 20.0, 'used': 0.0, 'total': 20.0}], 'all_non_zero_ct': 1}`

**NOTE: Even though both use the command "wallets = exchange.fetch_balance()" above, the connections are initiailzed differently**

For the **MARGIN** connection:
```
            conn_exchange = ccxt.binance({
                'apiKey'         : LD_API_KEY,
                'secret'         : LD_API_SECRET,
                'enableRateLimit': True,
                'options'        : { 'defaultType': 'margin', },
                'urls': {
                    'api': {
                        'Public': 'https://api.binance.com/api/v3/',
                        'Private':'https://api.binance.com/api/v3/',
                        }
                    },
            })

```

For the **SPOT** connecton:
```
            conn_exchange = ccxt.binance({
                'apiKey'         : LD_API_KEY,
                'secret'         : LD_API_SECRET,
                'enableRateLimit': True,
            }
```)

For the **FUTURES** connection:

```
            conn_exchange = ccxt.binance({
                'apiKey': LD_API_KEY,
                'secret': LD_API_SECRET,
                'timeout': 30000,
                'enableRateLimit': True,
                'rateLimit': 250,
                'options': { 'defaultType': 'future', },
            })

```
----------------------------------------------------------
This is what was associated with the MARGIN account: 
----------------------------------------------------------	

command executed:         **bank_balance = exchange.fetch_balance( )**



`[{'asset': 'USDT', 'free': '213.83167316', 'locked': '0.00000000', 'borrowed': '0.00000000', 'interest': '0.00000000', 'netAsset': '213.83167316'}, {'asset': 'BTC', 'free': '0.00000000', 'locked': '0.00000000', 'borrowed': '0.00913055', 'interest': '0.00005072', 'netAsset': '-0.00918127'}]
`

ASSETS 

ITEM NUMBER : 0 {'asset': 'USDT', 'free': '213.83167316', 'locked': '0.00000000', 'borrowed': '0.00000000', 'interest': '0.00000000', 'netAsset': '213.83167316'}

ITEM NUMBER : 1 {'asset': 'BTC', 'free': '0.00000000', 'locked': '0.00000000', 'borrowed': '0.00913055', 'interest': '0.00005072', 'netAsset': '-0.00918127'}


I originally had the Margin set for level "10". Because of the error, I changed it to a "3" and then to a  "1" But this did not help. I still kept getting the error.

**Question**:
I am trying to create orders for amounts like $5, $10, $15. Why am I getting the Margin error: {"code":-2019,"msg":"Margin is insufficient."}

```
ETA: 
**I forgot to add the information below (related to executing a SELL order on FUTURES:**
=> CHANGED MARGIN TO 1 (which supposedly is like not taking out any margin at all)

 retval  = exchange.createOrder( in_symbol, k_type, side, in_amount, None, server_params )

debugger>> p ( in_symbol, k_type, side, in_amount, None, server_params )
('BTC/USDT', 'MARKET', 'BUY', 15.0, None, {'newClientOrderId': '22e13c1b59734066a27da7121ba44ece', 'positionSide': 'LONG'})

ccxt.base.errors.ExchangeError: binance {"code":-2019,"msg":"Margin is insufficient."}
> /root/trade_exchange/api_work/trade_binance/bin_market.py(342)create_market_order()
-> retval  = exchange.createOrder( in_symbol, k_type, side, in_amount, None, server_params )
```

**Comment by kroitor** [comment] 2020-08-31 15:59
> I am not understanding why this Order will not go through. I keep getting the following error:
{"code":-2019,"msg":"Margin is insufficient."}

First of all, you have to understand Binance accounts, there's a bunch of them:

- spot account
- margin account (trade spot markets with leverage)
- swap futures account (has its own margin, don't confuse it with the margin account)
- delivery futures account (has its own margin, do not confuse it...)

So, the system is saying that you need margin on your futures account to execute that order.

In order to help you we need your code to reproduce it, including the exchange instantiation, and your verbose request+response (always paste that info, but without your keys of course):

```Python
import ccxt
from pprint import pprint

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

balance = exchange.fetch_balance()
pprint(balance)

symbol = 'BTC/USDT'
type = 'limit'  # or 'market', ...
side = 'buy'  # or 'sell', ...
amount = 123.45  # YOUR AMOUNT HERE
price = 54.321  # YOUR PRICE HERE
params = {
    # YOUR PARAMS HERE, IF ANY
}

exchange.verbose = True  #  enable verbose mode!

order = exchange.create_order(symbol, type, side, amount, price, params)
pprint(order)
```

↑ Edit the above snippet for your values and paste your output including the verbose request and verbose response.

**Comment by cadmufasa** [comment] 2020-08-31 20:34
Hi kroitor and thanks for the response.


A -> spot account
B -> margin account (trade spot markets with leverage)
C -> swap futures account (has its own margin, don't confuse it with the margin account)
D -> delivery futures account (has its own margin, do not confuse it...)

For now, I just want to work with A, B, and C but ...

Question though : On the Binance UI, which item represents D ( "delivery futures account" )
-> JEX or
-> P2P or
-> BPLAY or ....

Before starting this task, could you point me to the code that will allow me to transfer funds from SPOT to the FUTURES Margin account?

Regards.

**Comment by kroitor** [comment] 2020-09-01 13:32
@cadmufasa 

> Question though : On the Binance UI, which item represents D ( "delivery futures account" )

Historically, Binance had a spot account and a futures account (for perpetual contracts or swaps).
There's a bit of a naming confusion here, because perpetual futures contracts are called swaps in CCXT, as opposed to classic futures with a delivery date.
Binance has recently introduced the classic futures, and they did some renaming on their API docs, so previously they had:

- spot+margin
- perpetual futures (swaps)

... and now they have:

- spot+margin
- perpetual futures (swaps)
- delivery futures, this is not implemented in the master branch of CCXT yet, however, the work on it is going on here: 
    - https://github.com/ccxt/ccxt/issues/7117
    - https://github.com/ccxt/ccxt/pull/7474

> Before starting this task, could you point me to the code that will allow me to transfer funds from SPOT to the FUTURES Margin account?

You can do that using the implicit API methods:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-futures

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

from pprint import pprint
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes

code = USDT
amount = 123.45
currency = exchange.currency(code)
response = exchange.sapi_post_futures_transfer({
    'asset': currency['id'],
    'amount': exchange.currency_to_precision (code, amount),
    # 1: transfer from spot account to USDT-Ⓜ futures account.
    # 2: transfer from USDT-Ⓜ futures account to spot account.
    # 3: transfer from spot account to COIN-Ⓜ futures account.
    # 4: transfer from COIN-Ⓜ futures account to spot account.
    'type': 1,  
})
pprint(response)
```

> From what you are saying, each account (SPOT, FUTURES, etc.) has its very own margin account

That is correct.

> If that is true, then my transfer of funds to a MARGIN account would not work in the case of using FUTURES (if I am understanding things correctly).

That is correct.

> Given that being the case, then would not something like the item below resolve the problem? 

Which problem, specifically?

> My understanding is that the command can transfer funds from SPOT to an ISOLATED MARGIN account (which is what I was using for FUTURES).

You should transfer funds from some of your accounts to your futures account in order to trade futures with margin. The Binance's margin account is for spot-markets only, and you can't use it for trading futures, because futures have their own account with its own margin. Transferring to a futures account is done as shown above.

> If so, how would could it be done within CCXT.

You have to clearly specify the task you're trying to solve, so that I could show how that could be done within CCXT. In general, with CCXT you can call any endpoint supported by the exchange, so you can pretty much do anything as long as it is  allowed by the exchange itself. Transferring to a futures margin account is shown above. Let me know if that answers your question or not.

**Comment by cadmufasa** [comment] 2020-09-01 14:13
Hi kroitor,

Thanks for getting back to me so quickly. It is appreciated!

> Which problem, specifically?

Above, I had mentioned receiving the following: 

**{"code":-2019,"msg":"Margin is insufficient."}**

when trying to create an Order using a FUTURES account. I was transferring funds to the MARGIN account - but - the MARGIN account only works with the SPOT and not the FUTURES. The information you provided above should allow me to transfer funds to the FUTURES MARGIN account - and - hopefully - get past this latest error.

I will update the post with my findings.

**Comment by cadmufasa** [comment] 2020-09-01 19:09
@kroitor, Hi

I have been able to transfer funds to the FUTURES account using this command.

        output = exchange.sapi_post_futures_transfer({
                'asset': in_symbol, # like 'USDT' !!! NOT !!! BTC/USDT
                'amount': str( float( in_amount)), # like '10' (it must be in a string format)
                'type': 1,
                })

It does show up in the Binance User Interface as well. 

That was no issue.

The problem was that when executing:

**retval = exchange.createOrder( in_symbol, k_type, side, in_amount, None, server_params )**

I got the following error:
**ccxt.base.errors.ExchangeError: binance {"code":-2019,"msg":"Margin is insufficient."}**

After your input above, I thought to attempt to transfer funds to the ISOLATED MARGIN account directly.
Pls see: https://binance-docs.github.io/apidocs/spot/en/#create-isolated-margin-account-margin

I WAS REFERRING TO THIS FOR ISOLATED MARGIN
------------------------------------------
**https://binance-docs.github.io/apidocs/spot/en/#create-isolated-margin-account-margin**

with a focus of executing this command:

Isolated Margin Account Transfer (MARGIN) <----


TRIED EXECUTING THE FOLLOWING:
--------------------------------
```
    try:
        exchange = initialize_connection( in_futures )
        exchange.load_markets()

        breakpoint()
        # was referreing to :
        #https://binance-docs.github.io/apidocs/spot/en/#create-isolated-margin-account-margin
        pass_in = {
                'asset'     : in_symbol, # like 'USDT' !!! NOT !!! BTC/USDT
                #'asset'     : base_currency, # like 'USDT' !!! NOT !!! BTC/USDT
                'symbol'    : new_symbol, # likeBTCUSDT
                'amount'    : str( float( in_amount)), # like '10' (it must be in a string format)
                'transFrom' : 'SPOT',
                'transTo'   : 'ISOLATED_MARGIN',
                }
        output = exchange.sapi_post_isolated_transfer( pass_in )


        results     = {
            'return_code': t_api.KDC_TR_API_SUCCESS,
            'data' : output,
            }

        return results
```

BUT GOT THIS RESULT
---------------------
**AttributeError("'binance' object has no attribute 'sapi_post_isolated_transfer'")**


How can one execute the following:

Isolated Margin Account Transfer (MARGIN)
**POST /sapi/v1/margin/isolated/transfer (HMAC SHA256)**

in Python?

**Comment by kroitor** [comment] 2020-09-01 19:19
> The problem was that when executing:
> 
> **retval = exchange.createOrder( in_symbol, k_type, side, in_amount, None, server_params )**
> 
> I got the following error:
> **ccxt.base.errors.ExchangeError: binance {"code":-2019,"msg":"Margin is insufficient."}**

First of all, when you mention any error, please, always paste the full code to reproduce it, including the instantiation code, since we can't guess what exactly you're executing on your side without seeing the code itself. Apart from that it is mentioned everywhere, in the Manual and in the FAQ, that we always ask for your verbose request + response in case of any error:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Basically, your code for creating a futures margin order should look like so:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

balance = exchange.fetch_balance()
pprint(balance)

print('-----------------------------------------------------------')

exchange.verbose = True  # ←----------------------- ADD THIS AFTER LOADING THE MARKETS

symbol = 'BTC/USDT'  # YOUR SYMBOL HERE
type = 'market'
side = 'sell'
amount = 123.45  # YOUR AMOUNT HERE
price = None
params = {
    # if any...
}

response = exchange.create_order(symbol, type, side, amount, price, params)
pprint(response)
```

↑ Edit this snippet for your keys, symbol, amount and other values and launch it on your side. Then please copy-paste all of your output here.



> ## I WAS REFERRING TO THIS FOR ISOLATED MARGIN
> **https://binance-docs.github.io/apidocs/spot/en/#create-isolated-margin-account-margin**
> 
> with a focus of executing this command:
> 
> Isolated Margin Account Transfer (MARGIN) <----

Are you trying to place a futures margin order or a spot margin order?



> ## BUT GOT THIS RESULT
> **AttributeError("'binance' object has no attribute 'sapi_post_isolated_transfer'")**
> 
> How can one execute the following:
> 
> Isolated Margin Account Transfer (MARGIN)
> **POST /sapi/v1/margin/isolated/transfer (HMAC SHA256)**
> 
> in Python? Am I missing (or misunderstanding) something? Is there a different/better way to do this?

That method is called `sapi_post_margin_isolated_transfer`. You can see all available methods and their names as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance()
pprint(dir(exchange))
```

However, in your case, if you're trying to place a futures margin order, you don't need to use the margin account for spot markets.

**Comment by cadmufasa** [comment] 2020-09-01 19:21
Thanks again for the quick response. Will apply what you have written.

**Comment by kroitor** [comment] 2020-09-01 19:22
Basically, placing the futures order depends on whether your futures margin mode is ISOLATED or CROSS and depending on that you must either have enough margin on your entire futures-margin account, or enough margin on the futures-margin account for a specific isolated symbol/position.

**Comment by kroitor** [comment] 2020-09-01 19:48
@cadmufasa 

Forget about `sapi` – you don't need it if you want to trade futures.
Futures accounts have their own margin.
This message says that you don't have enough margin on your futures margin account related to your position, it has nothing to do with the spot margin:

```
{"code":-2019,"msg":"Margin is insufficient."}
```

That message will pop up depending on how exactly you want to trade futures, considering the above variety of trading modes.

In short, Binance's API is structured as follows and you should understand the meaning and the difference between ISOLATED vs CROSSED margin mode and the difference between Hedged positions vs One-way positions.

- wapi: funding for withdrawals and deposits (wapi)
- api: spot (api)
- sapi: spot margin
  - CROSSED margin mode
    - Hedged positions
    - One-way positions
  - ISOLATED margin mode
    - Hedged positions
    - One-way positions
- fapi: swap/perpetual futures margin
  - CROSSED margin mode
    - Hedged positions
    - One-way positions
  - ISOLATED margin mode
    - Hedged positions
    - One-way positions
- dapi: classic delivery futures margin
  - CROSSED margin mode
    - Hedged positions
    - One-way positions
  - ISOLATED margin mode
    - Hedged positions
    - One-way positions

↑ You should pick the following:

1. which API you want to trade (fapi, i believe)
2. which specific margin mode you want (CROSSED or ISOLATED)
3. which specific position mode you want (Hedged or One-way)

Differences in margin modes:

- **CROSSED margin mode** = you have one margin account for all your positions, if some position requires too much margin, your entire account is affected, leaving less margin for the other positions, thus you share the same margin _"across"_ all your positions.
- **ISOLATED margin mode** = you have separate margin for each of your positions, if some position runs out of margin the other positions are not affected, thus your positions are _"isolated"_ from one another.

Difference in position modes:

- **One-way position mode** - when you're in this mode, there's no such thing as LONG or SHORT positions. You just buy or sell a number of contracts, and if the price goes down, your PnL goes negative, if the price goes up, your PnL is positive. Thus, the position operates `BOTH` ways, both long and short at the same time, the notion of "long" and "short" is abstracted away from you.
- **Hedge mode** - you either enter a `LONG` position or a `SHORT` position and your PnL calculation rules depend on that.

Which specific mode of trading (margin mode + position mode) do you want?

**Comment by cadmufasa** [comment] 2020-09-01 19:55
> Are you trying to place a futures margin order or a spot margin order?

A Futures Margin Order

> However, in your case, if you're trying to place a futures margin order, you don't need to use the margin account for spot markets.

Yes. My understanding is that there are 2 separate areas of code for funding for each funding combination. For the combination of (futures + margin):

**PART A:** The code below would fund the **FUTURES portion** of the ( futures + margin) account **(called FUTURES)**: 

        output = exchange.sapi_post_futures_transfer({
                'asset': in_symbol, # like 'USDT' !!! NOT !!! BTC/USDT
                'amount': str( float( in_amount)), # like '10' (it must be in a string format)
                'type': 1,
                })

**PART B:** And this one funds the MARGIN code would fund the **MARGIN portion** of the (futures + margin) account **(called FUTURES):**

> That method is called sapi_post_margin_isolated_transfer. 

TBH, I thought that when opening a plain, vanilla Futures order, the program would take into account the amount created in **PART A** - **AND** - the part created in **PART B**  or - at least it would exhaust the funds in **PART A** _before_ pulling from funds in **PART B** 

> Basically, placing the futures order depends on whether your futures margin mode is ISOLATED or CROSSED 

I used ISOLATED mode because if the MARGIN (for CROSSED MARGIN) got low, then the other accounts (and positions) could be "tapped into"/"taken"/"liquidated", etc. should a trade go against me (i.e. other accounts would be "tapped into" to satisfy MARGIN maintenance requirements).

> on your **entire** futures-margin account, 

I take it that this is for CROSSED

> enough **margin** on the futures-margin account 

And this is for ISOLATED

> for a specific isolated symbol/position.

TBH, I thought that when placing a FUTURES order, the This sounds like I would need margin for each "symbol" - ( ex: BTCUSDT, ETHUSDT, EOSUSDT, etc.)

**I take it most people go the Isolated route?**

Thanks again for your inputs (and patience)

I will work on implementing the suggestions.

**Comment by cadmufasa** [comment] 2020-09-01 19:56
Hi again, I just saw your last post. Will go through it.

**Comment by cadmufasa** [comment] 2020-09-01 20:03
Hi kroitor,

Thanks so incredibly much for that explanation! I think I am seeing where I goofed (using **sapi** instead of **fapi**). I would like to correct this. I will update the post with my results. 

Regards.

**Closed** 2020-09-01 21:02 UTC
Labels: question

**Comment by kroitor** [comment] 2020-09-01 21:15
@cadmufasa let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-futures-margin.py

```Python
from pprint import pprint
import ccxt

print('CCXT Version:', ccxt.__version__)

# Must read before your start:
#
#     - https://github.com/ccxt/ccxt/wiki/Manual
#     - https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
#     - https://github.com/ccxt/ccxt/wiki/Manual#unified-api
#
# In short, Binance's API is structured as follows and you should understand
# the meaning and the difference between ISOLATED vs CROSSED margin mode and
# the difference between Hedged positions vs One-way positions.
#
#     - wapi: funding for withdrawals and deposits (wapi)
#     - api: spot (api)
#     - sapi: spot margin
#     - CROSSED margin mode
#         - Hedged positions
#         - One-way positions
#     - ISOLATED margin mode
#         - Hedged positions
#         - One-way positions
#     - fapi: swap/perpetual futures margin
#     - CROSSED margin mode
#         - Hedged positions
#         - One-way positions
#     - ISOLATED margin mode
#         - Hedged positions
#         - One-way positions
#     - dapi: classic delivery futures margin
#     - CROSSED margin mode
#         - Hedged positions
#         - One-way positions
#     - ISOLATED margin mode
#         - Hedged positions
#         - One-way positions
#
# You should pick the following:
#
#     1. which API you want to trade (fapi, i believe)
#     2. which specific margin mode you want (CROSSED or ISOLATED)
#     3. which specific position mode you want (Hedged or One-way)
#
# Differences in margin modes:
#
#     - CROSSED margin mode = you have one futures-margin account for all your positions,
#       if some position requires too much margin, your entire account is affected,
#       leaving less margin for the other positions,
#       thus you share the same margin _"across"_ all your positions
#
#     - ISOLATED margin mode = you have separate futures-margin for each of your positions,
#       if some position runs out of margin the other positions are not affected,
#       thus your positions are _"isolated"_ from one another
#
# Difference in position modes:
#
#     - One-way position mode - when you're in this mode
#       there's no such things as LONG or SHORT positions.
#       You just buy or sell a number of contracts, and
#       if the price goes down, your PnL goes negative,
#       if the price goes up, your PnL is positive.
#       Thus, the position operates `BOTH` ways, both long and short at the same time,
#       the notion of "long" and "short" is abstracted away from you,
#       so there's only one way the position can go and that way is called "BOTH".
#
#     - Hedge mode - you either enter a `LONG` position or a `SHORT` position and
#       your PnL calculation rules depend on that
#       so there's a number of ways a position can go
#
# Which specific mode of trading (margin mode + position mode) do you want?


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True, # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

symbol = 'BTC/USDT'  # YOUR SYMBOL HERE
market = exchange.market(symbol)

exchange.verbose = True  # UNCOMMENT THIS AFTER LOADING THE MARKETS FOR DEBUGGING

print('----------------------------------------------------------------------')

print('Fetching your balance:')
response = exchange.fetch_balance()
pprint(response['total'])  # make sure you have enough futures margin...
# pprint(response['info'])  # more details

print('----------------------------------------------------------------------')

# https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data

print('Getting your positions:')
response = exchange.fapiPrivateV2_get_positionrisk()
print(table(response))

print('----------------------------------------------------------------------')

# https://binance-docs.github.io/apidocs/futures/en/#change-position-mode-trade

print('Getting your current position mode (One-way or Hedge Mode):')
response = exchange.fapiPrivate_get_positionside_dual()
if response['dualSidePosition']:
    print('You are in Hedge Mode')
else:
    print('You are in One-way Mode')

print('----------------------------------------------------------------------')

# print('Setting your position mode to One-way:')
# response = exchange.fapiPrivate_post_positionside_dual({
#     'dualSidePosition': False,
# })
# print(response)

# print('Setting your positions to Hedge mode:')
# response = exchange.fapiPrivate_post_positionside_dual({
#     'dualSidePosition': True,
# })
# print(response)

# print('----------------------------------------------------------------------')

# # https://binance-docs.github.io/apidocs/futures/en/#change-margin-type-trade

# print('Changing your', symbol, 'position margin mode to CROSSED:')
# response = exchange.fapiPrivate_post_margintype({
#     'symbol': market['id'],
#     'marginType': 'CROSSED',
# })
# print(response)

# print('Changing your', symbol, 'position margin mode to ISOLATED:')
# response = exchange.fapiPrivate_post_margintype({
#     'symbol': market['id'],
#     'marginType': 'ISOLATED',
# })
# print(response)

# print('----------------------------------------------------------------------')

# # https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-futures

# code = 'USDT'
# amount = 123.45
# currency = exchange.currency(code)

# print('Moving', code, 'funds from your spot account to your futures account:')

# response = exchange.sapi_post_futures_transfer({
#     'asset': currency['id'],
#     'amount': exchange.currency_to_precision(code, amount),
#     # 1: transfer from spot account to USDT-Ⓜ futures account.
#     # 2: transfer from USDT-Ⓜ futures account to spot account.
#     # 3: transfer from spot account to COIN-Ⓜ futures account.
#     # 4: transfer from COIN-Ⓜ futures account to spot account.
#     'type': 1,
# })

# print('----------------------------------------------------------------------')

# # for ISOLATED positions only
# print('Modifying your ISOLATED', symbol, 'position margin:')
# response = exchange.fapiPrivate_post_positionmargin({
#     'symbol': market['id'],
#     'amount': 123.45,  # ←-------------- YOUR AMOUNT HERE
#     'positionSide': 'BOTH',  # use BOTH for One-way positions, LONG or SHORT for Hedge Mode
#     'type': 1,  # 1 = add position margin, 2 = reduce position margin
# })

# print('----------------------------------------------------------------------')

```

**Comment by kkairu** [comment] 2022-08-21 09:59
I think you need to look at the difference between hedge mode and one-way mode a bit confusing.

Position mode: 

One-way mode: you can only hold position of an asset in one direction either long or short
Hedge mode: you can have 2 positions in opposite direction; one long and one short.

Unless I'm confusing something...
