### ISSUE TITLE
BinanceUSDM, error in method parsePositionRisk (javascript library, Cannot read properties of undefined (reading 'quote'))

### ISSUE THREAD

**Issue by train90** [ccxt/ccxt#12856] opened 2022-04-15 13:40 UTC
Description: I have 6 bots(4 binance futures, 2 ftx futures) on server, each bot started in kubernetes. After near 2 days stable work - 4 bots have the same error in log. This error start at the same time for this 4 bots.
When I restarted each kubernetes pod with problem bot - this error  disappeared. 

I think, my issue is similar with next fixed issue - " Binance fetchPositions+ parseAccountPositions - Cannot read property 'crossMargin' of undefined #9690"

- Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
- Programming Language version: javascript
- CCXT version: 1.74.2

I use this method for fetch positions:
```
await ccxt.fetchPositions();
```

Error stack:
````
{"name" : "strategy", "hostname" : "botlive-607e8bad163b9addfc5ef89edaf39bad-6cfbb85b7c-mf2r4","pid":1,"level":50,"err":{"message":"Cannot read properties of undefined (reading 'quote')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'quote') \n    at binanceusdm.parsePositionRisk (/usr/src/app/node_modules/ccxt/js/binance.js:4677:123)\n   at binanceusdm. fetchPositionsRisk (/usr/src/app/node modules/ccxt/js/binance.js:4962:33) \n at runMicrotasks (‹anonymous>) \n
at processTicksAndRejections (node: internal/process/task queues: 96:5) \n  at async binanceusdm. fetchPositions (/usr/src/app/node modules/ccxt/js/binance.js:4852:20)"}, "msg": "Cannot read properties of undefined (reading 'quote')", "time": "2022-04-15T07:08:35.359Z", "V": 0}
```

**Comment by ttodua** [comment] 2022-08-14 09:21
I've checked and (even though I couldn't reproduce it) the relevant codes & implementation seems to be fixed now and I don't find any room which might cause that issue.

Please let us know if you have any issue again with CCXT, and also post informative log.

**Closed by ttodua** 2022-08-14 09:21 UTC
