### ISSUE TITLE
when exit,  showing error  [TypeError: 'NoneType' object is not callable]

### ISSUE THREAD

**Issue by agz1990** [ccxt/ccxt#5415] opened 2019-07-02 02:26 UTC
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac/Ubuntu 
- Programming Language version:  python 3.7.*
- CCXT version: 1.18.738
- Exchange: huobipro
- Method: __del__

Traceback (most recent call last):
  File "/Users/mcbadm/PycharmProjects/SmartBot/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 360, in __del__
  File "/Users/mcbadm/PycharmProjects/SmartBot/venv/lib/python3.7/site-packages/requests/sessions.py", line 708, in close
  File "/Users/mcbadm/PycharmProjects/SmartBot/venv/lib/python3.7/site-packages/requests/adapters.py", line 319, in close
  File "/Users/mcbadm/PycharmProjects/SmartBot/venv/lib/python3.7/site-packages/urllib3/poolmanager.py", line 204, in clear
  File "/Users/mcbadm/PycharmProjects/SmartBot/venv/lib/python3.7/site-packages/urllib3/_collections.py", line 89, in clear
TypeError: 'NoneType' object is not callable
<img width="1049" alt="WeChat713e148c1645a793b4747a64d6b6b346" src="https://user-images.githubusercontent.com/5153919/60478011-bae29000-9cb3-11e9-96d1-bf8923ae1adb.png">

**Comment by frosty00** [comment] 2019-07-02 12:56
how are you exiting the script? are you using `exit(1)` or `sys.exit(1)` or something similar, because it is possible that does not give the garbage collector a chance to cleanup the objects.

**Comment by kroitor** [comment] 2019-07-02 13:11
@agz1990 Can you paste a minimal snippet of code to reproduce it? 

We need the code as short as possible, 10-20 lines, however, please make it a complete program, including the exchange instantiation code, without your keys, of course. 

Use GitHub markdown for readability as described here: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://guides.github.com/features/mastering-markdown/

&#096;&#096;&#096;Python

# YOUR CODE HERE

&#096;&#096;&#096;

**Comment by kroitor** [comment] 2019-07-09 01:33
Closing this for now until we have a followup. Feel free to reopen it if needed or just ask further questions if any.

**Closed by kroitor** 2019-07-09 01:33 UTC
Labels: question
