### ISSUE TITLE
Is there a way to fetch realized PNL per trade?

### ISSUE THREAD

**Issue by unster** [ccxt/ccxt#9918] opened 2021-09-02 12:36 UTC
Hi team,

I was trying to fetch my realized PNL per trade, so I could i.e. increase the position next time with this PNL. I tried to juggle a bit with this solution https://github.com/ccxt/ccxt/issues/9281 but it seems that there is no way to retrieve this data nor to calculate it. Am I right?

This is all I could fetch:
![scr2](https://user-images.githubusercontent.com/25437340/131844581-c83f7130-60f3-4f64-8361-e65fed15079a.JPG)
![scr1](https://user-images.githubusercontent.com/25437340/131844584-4d642e2a-de0f-4813-9d3c-b50abd60eab0.JPG)

**Comment by ttodua** [comment] 2022-07-25 06:41
Duplicate of #14294

**Closed by ttodua** 2022-07-25 06:41 UTC
Labels: question
