### ISSUE TITLE
websocket API

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#433] opened 2017-11-01 01:12 UTC
Gents,

May I wonder about WebSocket API status for exchanges that support it? I read somewhere that it's in your plans. I'd be happy to be a tester for it. Is it possible to provide some very raw (quick&dirty) doc or few python examples how to use? Providing its implemented in ccxt for some exchanges, I'd be happy to test it out!

Please let me know. Thank you in advance,

**Comment by kroitor** [comment] 2017-11-01 01:20
@Fcl69 yes we are going to add support for WS APIs, but it is not ready yet, we are working on it and hope to deliver soon. If you don't mind, i'm closing this issue as being duplicate of #56 . I suggest to continue there if you have further questions. We will update you upon availability of WS in CCXT anyway. Thx!

**Closed by kroitor** 2017-11-01 01:20 UTC
Labels: duplicate, question

**Comment by Fcl69** [comment] 2017-11-01 03:34
Thank you for a reply, I'll keep an eye on #56
