### ISSUE TITLE
regression issue:  okex cannot get data

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#5346] opened 2019-06-23 23:25 UTC
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: linux alpine
- Programming Language version:
- CCXT version: 1.18.726
- Exchange: okex
- Method:
    load_markets

cannot get any historical data from  okex in the new version. In old version(1.17.416),  data can be got. If I changed the version back, data can be got.

**Comment by kroitor** [comment] 2019-06-23 23:29
Can you please paste your code to reproduce it and verbose request and response (we need both the request and the response) that fails on your side?

```Python
import ccxt
exchange = ccxt.okex({
    'enableRateLimit': True,
    'verbose': True,
})

exchange.load_markets()
```

Ultimately, I'd suggest to migrate to `okex3`, because okex v1 will not be maintained further.

**Comment by kroitor** [comment] 2019-07-04 17:07
Closing this for now, feel free to reopen it if needed. We will need the above information to resolve this.

**Closed by kroitor** 2019-07-04 17:07 UTC
