### ISSUE TITLE
client_session: <aiohttp.client.ClientSession object at 0x000001B7CD7F9B70>

### ISSUE THREAD

**Issue by zhoujinhai** [ccxt/ccxt#2173] opened 2018-03-08 14:03 UTC
I can get the ticker when I use the first code, but when I use async , the code run wrong, how to slove it ! can you help me? I am use python 3.6 on windows 10 .

the first code:
```python
import ccxt
exchange = ccxt.binance()
symbol = 'BTC/USDT'
ticker = exchange.fetch_ticker(symbol)
print(ticker)
```
![image](https://user-images.githubusercontent.com/20365125/37154806-2486f3a6-231c-11e8-8f90-b1a64cd706be.png)

the sencond code:
```python
import asyncio
import ccxt.async as ccxt

async def getticker():
    binance = ccxt.binance()
    print(await binance.fetch_ticker('BTC/USDT'))

asyncio.get_event_loop().run_until_complete(getticker())
```

```
Traceback (most recent call last):
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 124, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\client.py", line 341, in _request
    break
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\helpers.py", line 727, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/python3/test/test.py", line 10, in <module>
    asyncio.get_event_loop().run_until_complete(getticker())
  File "C:\Users\SXY004\Anaconda3\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "E:/python3/test/test.py", line 8, in getticker
    print(await binance.fetch_ticker('BTC/USDT'))
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\binance.py", line 492, in fetch_ticker
    await self.load_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 153, in load_markets
    markets = await self.fetch_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\binance.py", line 345, in fetch_markets
    response = await self.publicGetExchangeInfo()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 139, in fetch
    self.raise_error(RequestTimeout, method, url, e, None)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 274, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v1/exchangeInfo 
binance requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AE4AB39B00>
```

**Comment by frosty00** [comment] 2018-03-08 14:14
You're running an old version of ccxt. Do a git pull or git clone and then run python3 setup.py or pip3

**Comment by zhoujinhai** [comment] 2018-03-08 14:32
thanks！ I can run the second code yestoday， and I have pip install the ccxt , it still show the same mistake

**Comment by frosty00** [comment] 2018-03-08 14:34
Try again, this has been fixed already. I litterally just ran the second code you posted. What is the output of ccxt.__version__

**Comment by zhoujinhai** [comment] 2018-03-08 14:40
![image](https://user-images.githubusercontent.com/20365125/37156666-b08780d2-2321-11e8-9f90-6b314b606d00.png)

**Comment by frosty00** [comment] 2018-03-08 14:59
Oh sorry I didn't see the error log carefully

I was reading 

    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AE4AB39B00>

instead of 

    ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v1/exchangeInfo

strange that the garbage collection doesn't work properly on windows tho.

Anyhow this basically means that the problem is on binance's end, not ours. They have been having issues with api trading recently, checkout: https://np.reddit.com/r/CryptoCurrency/comments/82pf9i/warning_issues_on_binance/

**Comment by zhoujinhai** [comment] 2018-03-08 15:08
thanks your help ! 
when I try this exchange: huobipro bitflyer bitfinex...  the code have show the same error

**Comment by Jackzhangpan** [comment] 2018-03-09 03:43
## sync can do ,but ccxt.async can't work .huobipro ,oken,binance ,etc.. @kroitor

**Comment by kroitor** [comment] 2018-03-09 13:26
@Jackzhangpan can you post your code and verbose output according to these rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by Jackzhangpan** [comment] 2018-03-09 13:52
### The problem is the same as the one upstairs。async can't be used today.  include: binance, huobipro ,okex,.....
![image](https://user-images.githubusercontent.com/22291614/37210104-7bb32c82-23e2-11e8-9b5c-905a6f87f629.png)

**Comment by cmosse** [comment] 2018-03-20 16:55
I got this identical issue as updated CCXT to version 1.11.143. Ran the code in the first post:

  File "C:/Users/Administrator/Desktop/code/maalis/testing.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(getticker())

  File "c:\python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()

  File "c:\python36\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')

All my previously working async functions run into same issue

**Comment by frosty00** [comment] 2018-03-20 17:06
Not the same error, this is problem with how you have implemented your coroutines  

```raise RuntimeError('This event loop is already running')```

^This explains the error

Also when I run it I get:

```
import asyncio
import ccxt.async as ccxt
async def getticker():
    binance = ccxt.binance()
    print(await binance.fetch_ticker('BTC/USDT'))
asyncio.get_event_loop().run_until_complete(getticker())
{'symbol': 'BTC/USDT', 'timestamp': 1521565562224, 'datetime': '2018-03-20T17:06:02.224Z', 'high': 8833.81, 'low': 8230.7, 'bid': 8790.0, 'bidVolume': 0.526696, 'ask': 8790.13, 'askVolume': 9.1e-05, 'vwap': 8484.1899091, 'open': 8390.0, 'close': 8790.13, 'last': 8790.13, 'previousClose': 8380.2, 'change': 400.13, 'percentage': 4.769, 'average': None, 'baseVolume': 43217.528733, 'quoteVolume': 366665721.172899, 'info': {'symbol': 'BTCUSDT', 'priceChange': '400.13000000', 'priceChangePercent': '4.769', 'weightedAvgPrice': '8484.18990910', 'prevClosePrice': '8380.20000000', 'lastPrice': '8790.13000000', 'lastQty': '0.05335900', 'bidPrice': '8790.00000000', 'bidQty': '0.52669600', 'askPrice': '8790.13000000', 'askQty': '0.00009100', 'openPrice': '8390.00000000', 'highPrice': '8833.81000000', 'lowPrice': '8230.70000000', 'volume': '43217.52873300', 'quoteVolume': '366665721.17289903', 'openTime': 1521479162224, 'closeTime': 1521565562224, 'firstId': 28912704, 'lastId': 29202546, 'count': 289843}}
```

**Comment by Iczczaygk** [comment] 2018-03-20 17:09
https://goo.gl/fneCVj
THIDATIP TUSKORN

KALEEZA


ในวันที่ พ. 21 มี.ค. 2018 00:06 frosty00 <notifications@github.com>
เขียนว่า:

**Comment by cmosse** [comment] 2018-03-20 18:15
I meant that I also end up in an error running the async version of the first post, the same you copy-pasted. 
In my humble opinion, that really doesn't explain the error in any way. 
The fact that you are able to run the code, also doesn't really clarify anything.

**Comment by frosty00** [comment] 2018-03-20 20:08
Show all you're code?

Are you using multithreading?

Set `exchange.verbose = True`

**Comment by cmosse** [comment] 2018-03-21 08:13
As stated, I ran the exact code found in the opening post. The exact same code you copy-pasted. Here it is for clarification:

import asyncio
import ccxt.async as ccxt
async def getticker():
    binance = ccxt.binance()
    print(await binance.fetch_ticker('BTC/USDT'))
asyncio.get_event_loop().run_until_complete(getticker())

The strange this is that even as the run ends in an error, I get the response from binance. Verbose gives logical responses, identical synchronous methods.

Testing new_event_loop -> "Cannot run the event loop while another loop is running"

**Comment by kroitor** [comment] 2018-03-21 09:49
@cmosse 

```Python
import asyncio
import ccxt.async as ccxt

async def getticker():
    binance = ccxt.binance()
    ticker = await binance.fetch_ticker('BTC/USDT')
    await binance.close()  # don't forget to close it if you're not using it anymore
    print(ticker)

asyncio.get_event_loop().run_until_complete(getticker())
```

↑ Do you have the same issue with this code when you set up proper destruction handling like it tells you in that error message:

> binance requires to release all resources with an explicit call to the .close() coroutine.

**Comment by cmosse** [comment] 2018-03-21 10:03
I have the error regarding the loop already running - issue, even with closing binance as you posted.

I've been using Spyder for the last year, tried IDLE to run this same thing, as I'm out of ideas -> everything works as expected. Puzzled, but good thing that this seems to be an issue with the latest update of Spyder, not CCXT. 

![image](https://user-images.githubusercontent.com/34720116/37703877-caaef5ca-2cff-11e8-9d74-952c1b43fcb4.png)

**Comment by frosty00** [comment] 2018-03-21 10:06
have you tried:

```
async def getticker():
    binance = ccxt.binance({'asyncio_loop': asyncio.get_event_loop()})
```

or just setting the event loop at the top and always using that loop.

**Comment by kroitor** [comment] 2018-03-21 15:02
Related: #2173

**Comment by kroitor** [comment] 2018-03-22 18:16
@zhoujinhai, @cmosse see the answer here:

https://github.com/ccxt/ccxt/issues/2324#issuecomment-374968303

```
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async as ccxt  # noqa: E402


async def test_gdax():
    gdax = ccxt.gdax()
    markets = await gdax.load_markets()
    await gdax.close()
    return markets

if __name__ == '__main__':  # added this check
    print(asyncio.get_event_loop().run_until_complete(test_gdax()))
```

Hope it helps.

**Closed by kroitor** 2018-03-22 18:16 UTC
Labels: question

**Comment by zhoujinhai** [comment] 2018-03-23 02:33
@kroitor  @frosty00  thanks , it have solved the second problem. but it still can't deal with the first one.

**Comment by kroitor** [comment] 2018-03-23 03:14
@zhoujinhai can you post a minimal code snippet of the "first one" with just one exchange and also show how you handle the errors? You need to add exception-cases, as described here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

**Comment by zhoujinhai** [comment] 2018-03-23 03:40
oh,sorry！now, I have no idea for this problem. and I just use ccxt instead of ccxt.async.
I can get the gdax's informations like the first picture, the code can't run for okex and raise
```RequestTimeout: okex GET https://www.okex.com/v2/markets/products.do ```,the same error also to  huobipro,binance. so I think the problem maybe due to API.
![image](https://user-images.githubusercontent.com/20365125/37810238-f34b0318-2e8d-11e8-87cb-321d9d88e800.png)
```python
import asyncio
import ccxt.async as ccxt

async def getticker():
    exchange = ccxt.okex()
    ticker = await exchange.fetch_ticker('BTC/USDT')
    await exchange.close()
    print(ticker)

asyncio.get_event_loop().run_until_complete(getticker())
```
```
Traceback (most recent call last):
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 124, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\client.py", line 779, in __aenter__
    self._resp = await self._coro
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\client.py", line 404, in _request
    break
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/python3/test/test1.py", line 75, in <module>
    asyncio.get_event_loop().run_until_complete(getticker())
  File "C:\Users\SXY004\Anaconda3\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "E:/python3/test/test1.py", line 71, in getticker
    ticker = await exchange.fetch_ticker('BTC/USDT')
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\okcoinusd.py", line 279, in fetch_ticker
    await self.load_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 153, in load_markets
    markets = await self.fetch_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\okex.py", line 63, in fetch_markets
    markets = await super(okex, self).fetch_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\okcoinusd.py", line 156, in fetch_markets
    response = await self.webGetMarketsProducts()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 139, in fetch
    self.raise_error(RequestTimeout, method, url, e, None)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 274, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: okex GET https://www.okex.com/v2/markets/products.do 
okex requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000010CD8BBA438>
```

**Comment by kroitor** [comment] 2018-03-23 03:43
@zhoujinhai does this work for you:

```Python
import asyncio
import ccxt.async as ccxt

async def getticker():
    exchange = ccxt.okex({'timeout': 30000})
    ticker = await exchange.fetch_ticker('BTC/USDT')
    await exchange.close()
    print(ticker)

asyncio.get_event_loop().run_until_complete(getticker())
```

?

**Comment by zhoujinhai** [comment] 2018-03-23 03:47
can't work !

**Comment by kroitor** [comment] 2018-03-23 03:48
@zhoujinhai and this:

```Python
import asyncio
import ccxt.async as ccxt

async def getticker():
    exchange = ccxt.okex({'proxy': 'https://cors-anywhere.herokuapp.com/'})  # ←------- added proxy here
    ticker = await exchange.fetch_ticker('BTC/USDT')
    await exchange.close()
    print(ticker)

asyncio.get_event_loop().run_until_complete(getticker())

```

**Comment by zhoujinhai** [comment] 2018-03-23 04:31
OK！It can run. thank you so much ! It my fault , I have just open "lantern" and doesn't add proxy .

**Comment by wmltyq** [comment] 2018-12-29 08:14
> Show all your code.
> 
> Are you using multithreading?
> 
> Set `exchange.verbose = True`
> 
> Have you tried `asyncio.new_event_loop`?

asyncio.new_event_loop and asyncio.get_event_loop what is different?

**Comment by frosty00** [comment] 2018-12-29 10:59
@wmltyq one creates a new event loop, the other uses the current event loop. `get_event_loop` is what you need in 99% of cases

**Comment by xy12138** [comment] 2020-12-20 02:04
> OK！It can run. thank you so much ! It my fault , I have just open "lantern" and doesn't add proxy .

hi, i got the same error, what's mean for adding proxy and how should I do? PS:  i can run the code in Linux server which in HK but not in china although i open V2rayN.

**Comment by kroitor** [comment] 2020-12-20 09:15
@xy12138 hi!

- https://github.com/ccxt/ccxt/wiki/Install
- https://github.com/ccxt/ccxt/wiki/Manual

Let us know if that does not answer your questions.
