### ISSUE TITLE
Binance rateLimit

### ISSUE THREAD

**Issue by incompletude** [ccxt/ccxt#1855] opened 2018-02-10 01:16 UTC
Binance rateLimit is 1200ms, not 500ms.

---

Sorry, I'm wrong. The message I'm getting is:

 {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}

But I'm pretty sure I'm inside the limite. Let me do some research.

---

kroitor seems there is something wrong with Binance api. After a few requests, even 2-3s apart, gives me { Error: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}.

**Comment by kroitor** [comment] 2018-02-10 02:34
@incompletude 

> After a few requests, even 2-3s apart, gives me { Error: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute.

Can you make a minimal code snippet to reproduce it? Their rate-limit costs depend on which particular requests you're making, if you're fetching multiple tickers at once, then this is expected...

Standing by for more info and code from you.

**Comment by incompletude** [comment] 2018-02-10 03:21
I'm doing exactly that. Fetching multiple tickers with fetchTickers in a loop. The loop has a 3s interval. Still, need the code? I can do it, no problem, just that I think you have it figured out.

**Comment by kroitor** [comment] 2018-02-10 03:42
@incompletude the thing is that their fetchTickers has a varying rate-limit-costs, and the cost is a multiple of how many *full* tickers you fetch at once. With `fetchTickers()` it means all of them at once. Binance has 264 symbols, so that means you can call it once every 264 periods. Now let's calculate a little:

1. 1200 requests per minute / 60 seconds = 20 requests per second
2. 264 symbols / 20 requests per second = 13.2 seconds between subsequent calls to fetchTickers.

So, if you set a rate limit of 13.2 seconds that would mean you can call it at that rate (set rateLimit: 13200). 

However, there's more to it ) Their periods are not defined to be seconds, but defined in terms of *weight* that is decided and matched against an *average user* with their machine-learning algorithms:

- https://support.binance.com/hc/en-us/articles/115003235691-Binance-API-Trading-Rules
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics

> 24 hour price change statistics. Careful when accessing this with no symbol.
> Weight: 1 for a single symbol; number of symbols that are TRADING / 2 when the symbol parameter is omitted

So, weight != 1 per second and that means the actual calculation is determined in runtime by means of neural networks. In other words, you may still need to tweak rateLimit by trial and error. 

You can use a fetchBidAsks if you are fine having just the current orderbook market prices for all symbols. But you have to adjust your code for Binance anyways. Or, as they say, use their websocket streams, which are not supported in ccxt for now, but, hopefully, will be supported soon.

**Comment by kroitor** [comment] 2018-02-10 03:51
More on this:
- https://github.com/ccxt/ccxt/issues/1223
- https://github.com/ccxt/ccxt/issues/1027
- https://github.com/ccxt/ccxt/issues/870

**Comment by mkutny** [comment] 2018-02-10 08:29
BTW, reading the Manual I've found `fetchL1OrderBook` method. I suppose this name was reserved but currently not in use.

It seems that it aims to return exactly what `fetchBidAsks` does.

**Comment by kroitor** [comment] 2018-02-10 20:09
> I suppose this name was reserved but currently not in use.

That's right.

> It seems that it aims to return exactly what fetchBidAsks does.

In fact, both names don't quite make it to a truly-descriptive name:
- fetchL1OrderBook – what does it return? One bidask (marketprices) for one symbol? For all symbols?
- fetchBidAsks – same story, but even less precise, bidasks can stand for "multiple bids and asks from the same orderbook" or for "one bidask from each orderbook", or maybe even something other...

In both cases the name does not really describe the intent... Still looking for a better naming schema for this part of the unified API... Your suggestions are welcome )

**Comment by mkutny** [comment] 2018-02-11 06:38
> We may end up with fetchL1OrderBooks (note the plural s), as fetching them separately makes even less sense.

Exactly! We already have `fetchOrderBooks` so this proposal looks like a logical extension.

BTW, binance name is `bookTicker ` which is also "book-like".

**Comment by kroitor** [comment] 2018-02-12 01:23
I would close this issue for now, until we have a follow-up on this. We will think of changing that naming part for more unification. Thx!

**Closed by kroitor** 2018-02-12 01:23 UTC
Labels: question

**Comment by mkutny** [comment] 2018-02-17 13:19
Different values of what? )

**Comment by pbajno** [comment] 2018-02-17 13:40
Different values of rateLimit parameter for binance

**Comment by kroitor** [comment] 2018-02-17 18:40
@pbajno without seeing your code and verbose output, it's really hard to help you, can you post more info, please, according to these instructions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. Thx!
