### ISSUE TITLE
bybit error invalid request,please check your server timestamp or recv_window para

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14410] opened 2022-07-19 16:17 UTC
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: bybit
Method: bybit

hi
I am getting this error in bybit exchange
ccxt.base.errors.InvalidNonce: bybit {"ret_code":10002,"ret_msg":"invalid request,please check your server timestamp or recv_window param","ext_code":"","result":null,"ext_info":null,"time_now":1658247100309}

Also I upgraded to the latest version of ccxt

**Comment by sc0Vu** [comment] 2022-07-19 16:49
Hi, may I ask which method did you call?

**Comment by hosseinab** [comment] 2022-07-20 06:16
@sc0Vu 
thanks for response
this function : fetch_order_book

**Comment by hosseinab** [comment] 2022-07-20 09:45
@carlosmiei 

I used this options like this :

exchange = ccxt.bybit({
                'enableRateLimit': True,
                'apiKey': api_key,
                'secret': api_secret,
                'options': {
                    'adjustForTimeDifference': True,
                    'verbose': True,
                    'defaultType': 'spot',
                },
            })

But my problem is not solved

**Comment by carlosmiei** [comment] 2022-07-20 10:18
@hosseinab can you try to sync your system clock with UTC time?

**Comment by hosseinab** [comment] 2022-07-20 11:42
@carlosmiei 
[https://i.ibb.co/RTJXVKt/Untitled.jpg](url)

I synced the computer clock with UTC. But still my problem was not solved

**Comment by hosseinab** [comment] 2022-07-21 15:24
Is there no solution?

**Comment by carlosmiei** [comment] 2022-07-21 15:55
@hosseinab We contacted Bybit regarding this issue, waiting for a response

**Comment by carlosmiei** [comment] 2022-07-22 08:21
@hosseinab @AdriMerle We have been told that increasing the 'recvWindow' might help, can you please try to do that?

You can do it like this:
```Python
exchange.options['recvwindow] = 6000 # default is 5000
exchange.options['recvwindow] = 6500 # default is 5000
exchange.options['recvwindow] = 7000 # default is 5000
# try different values

**Comment by hosseinab** [comment] 2022-07-22 10:04
@carlosmiei 
thanks for response
I tried this code . But it did not solve my problem

**Comment by hosseinab** [comment] 2022-07-24 12:35
no solution?

**Comment by carlosmiei** [comment] 2022-07-24 13:04
@hosseinab we don't know the root cause yet, 
can you please run this and show us the result?

```Python
    await exchange.load_time_difference()
    print(exchange.options['timeDifference']
```

**Comment by hosseinab** [comment] 2022-07-24 13:51
@carlosmiei 
result : 171

**Comment by hosseinab** [comment] 2022-08-01 13:06
Is there no other solution for this problem?

**Comment by ttodua** [comment] 2022-09-08 14:31
@hosseinab In the past I remind that I experienced similar (with other exchange/s). I had linux and tried several methods to sync time, but only one specific method helped to correctly sync (unfortunately I don't remind it, as I have given up that project in the past), so try different ways to force OS to re-sync the time. If that will not help, then we will need to use additional snippet in CCXT core to manually sync time from external source, instead of device.

**Comment by hosseinab** [comment] 2022-09-08 21:18
@ttodua 
hi
I have said the result of my research in this issue :
https://github.com/ccxt/ccxt/issues/14870

**Comment by ttodua** [comment] 2022-09-11 06:26
> @ttodua hi I have said the result of my research in this issue : #14870

ok thnx, however, in next cases, please suffice one issue for same problem, and just tag us as a reminder (if you don't get responses). I'll close this current topic and the discussion can be continued in that topic.

**Closed by ttodua** 2022-09-11 06:26 UTC
Labels: bug

**Comment by sinomos1** [comment] 2022-11-23 08:42
hello did anyone solve this ! i get it randomly time by time ! i used the earlier solution commented here but it started giving the same error after a few days

**Comment by mistahcase** [comment] 2023-03-14 07:46
I'm also getting this randomly. The it looks it is a bybit problem, because the time on their server is wildly off sometimes.

**Comment by kenvinams** [comment] 2023-04-20 10:44
Weirdly I have solved this by running this code first:
`exchange.load_time_difference()`
Before that I added adjust time difference but worked randomly.
```
'options': {
        'adjustForTimeDifference': True,
    }
```

**Comment by weslienlive** [comment] 2023-05-07 07:33
@kenvinams that worked for as well. thanks

**Comment by ykchong45** [comment] 2024-04-07 03:15
```
InvalidNonce: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1712459413959],server_timestamp[1712459412527],recv_window[5000]","result":{},"retExtInfo":{},"time":1712459412527}
```
As for me I had timestamps in the error message, but noticing the `req_timestamp` > `server_timestamp`, I did a Time Sync in the Windows Settings `Time & Languages -> Date & Time -> Additional Settings -> Sync now`. It fixes the problem. 

p.s. I also employed the ` 'adjustForTimeDifference': True` mentioned by @kenvinams .

**Comment by basilgoodluck** [comment] 2025-04-19 16:39
@ykchong45 yes it worked for me too, thanks!
