### ISSUE TITLE
Invalid KC-API-PASSPHRASE on Kucoin v2

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8994] opened 2021-04-15 20:27 UTC
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.47.3
Exchange: All Exchanges
Method: kucoin.createOrder()

Hello!

I encounter a: `AuthenticationError=o=kucoin Invalid KC-API-PASSPHRASE` error for kucoin when I try to `createOrder()`
_(As I use the API keys, I am not sure if I should put the verbose: true as the keys are seen there?)_

I use the `v2` version of kucoin. I have followed this answer for `v2` but still gets the error: 
https://github.com/ccxt/ccxt/issues/8187

I have tried to put both the "API Secret" and the "API Passphrase" as `kucoin.secret` with the same error. I have tried to create 2 new API keys with the same problem. I also tried to use the `kucoin.headers` line.

What could be wrong in this code?

Thank you!
```
create_Order();
async function create_Order() { 

    const kucoin = new ccxt.kucoin({ enableRateLimit: true })
    kucoin.apiKey = "6078xxxxxxxxxxxxxxxxxxxx"; //I have confirmed that this is correct!
    kucoin.secret = "69d00xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"; //I have tried both the "API Secret" and "API Passphrase"
    kucoin.password = "1xxxxx"; //This is the trading password on kucoin which is 6 digits

    kucoin.headers = { 'KC-API-PASSPHRASE': 'myAPIpassphrase' } //I have tried to add this line of code also 

    const response = await kucoin.createOrder("TRX/USDT", "limit", "buy", 10, 0.14);
    console.log(response);
}
```

**Comment by kroitor** [comment] 2021-04-15 21:13
Hi!

Please, paste your verbose output (you can strip your credentials from it) using this snippet:

```JavaScript
const ccxt = require ('ccxt')

async function main () {

    console.log ('CCXT Version:', ccxt.__version__)

    const exchange = new ccxt.kucoin ({
        'enableRateLimit': true,
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'password': 'YOUR_API_PASSWORD',
    })

    await exchange.loadMarkets ()

    exchange.verbose = true

    balance = await exchange.fetchBalance ()
}

main()
```

**Comment by jackpotcityco** [comment] 2021-04-15 22:57
Thanks, I used you code (edited, apiKey, secret, password) and here are the verbose output:

```
CCXT Version: undefined
fetch:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/accounts?type=trade
Request:
 {
  'KC-API-KEY-VERSION': '2',
  'KC-API-KEY': 'xxxxxxxxxxxxxxxxxxxxxxxx',
  'KC-API-TIMESTAMP': '1618527185121',
  'KC-API-PASSPHRASE': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'KC-API-SIGN': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
}
 undefined

handleRestResponse:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/accounts?type=trade 401 Unauthorized
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6408bf7aeca00d46-ARN',
  'Cf-Request-Id': '09795600d300000d46e73c6000000001',
  Connection: 'keep-alive',
  'Content-Length': '51',
  'Content-Type': 'application/json',
  Date: 'Thu, 15 Apr 2021 22:53:05 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d31a9d8228b77cd2b8d05382d35f34d691618527185; expires=Sat, 15-May-21 22:53:05 GMT; path=/; domain=.kucoin.com; HttpOnly; SameSite=Lax, AWSALB=/1MElbipeCkExCzxaDbCmfnDnlgzZPtsQFceAwefXgo2JSeVlXBozRpzxg7xFuM8dtm7DndqoUIgPF2OWkxDBVa7xlI9bXPWezEyguKl/nfj9oEmnS+kLCyvA8q2; Expires=Thu, 22 Apr 2021 22:53:05 GMT; Path=/, AWSALBCORS=/1MElbipeCkExCzxaDbCmfnDnlgzZPtsQFceAwefXgo2JSeVlXBozRpzxg7xFuM8dtm7DndqoUIgPF2OWkxDBVa7xlI9bXPWezEyguKl/nfj9oEmnS+kLCyvA8q2; Expires=Thu, 22 Apr 2021 22:53:05 GMT; Path=/; SameSite=None; Secure, __cfruid=fe5848d73461db28d973f46730beece623740c84-1618527185; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None'
}
 {"code":"400004","msg":"Invalid KC-API-PASSPHRASE"}

C:\myproject\node_modules\ccxt\js\base\Exchange.js:537
            throw new exact[string] (message)
                  ^

AuthenticationError: kucoin Invalid KC-API-PASSPHRASE
```

**Comment by kroitor** [comment] 2021-04-15 23:03
@jackpotcityco ok, got it (i'm assuming you used a new keypair with correct apiKey+secret+password). Plz, hold on, need a bit of time to test on my side, will be back to you shortly!

**Comment by jackpotcityco** [comment] 2021-04-15 23:05
Yes, I used a new keypari with correct: apiKey+secret+password. Yes no problem.

**Comment by IanFLee** [comment] 2021-04-18 00:44
Hello, I'm also having this issue, though not thru ccxt. In ref to the API password, I believe that there's actually a different passphrase that you're prompted to create each time you make an API key/secret, and I have used that as my passphrase as well as trying my 6-digit trading code but neither work for me.

**Comment by kroitor** [comment] 2021-04-18 00:47
@IanFLee hi! Thanks for your feedback! We are investigating, will get this resolved asap.

**Comment by IanFLee** [comment] 2021-04-18 01:25
> @IanFLee hi! Thanks for your feedback! We are investigating, will get this resolved asap.

thank you. I've found my solution, it was a small error hidden somewhere. However OP may find success the same way I did: the API password is different than the 6 digit trading code. thanks again.

**Comment by kroitor** [comment] 2021-04-18 01:41
@jackpotcityco do you use your API password or your trading password?

**Comment by jackpotcityco** [comment] 2021-04-18 02:05
@kroitor I use the trading password. I am not sure if there is an API password? The only thing would be the login password to Kucoin?

**Comment by kroitor** [comment] 2021-04-18 02:15
@jackpotcityco KuCoin is confusing because it has a trading password and an API passphrase (this is the thing you need). First, let's make sure you are using a correct API passphrase – create a new key, and be careful when typing the API passphrase, then let us know if that didn't help.

**Comment by jackpotcityco** [comment] 2021-04-18 02:15
@kroitor, @IanFLee I just now tried to create a new API and I used the `API Passphrase` as password with @kroitors code above. Now it actually worked. This didn't work yesterday as I created 4 new API in the exact same way. That was very strange. I know I tried the exact same thing with the `API Passphrase` but now it worked. I am not sure if there was any temporary problem with their API?

**Comment by kroitor** [comment] 2021-04-18 02:16
> I am not sure if there was any temporary problem with their API?

Most often this is just caused by confusion in a rush. But it did work for me and it didn't break recently. Closing this for now, thx for reporting back!

**Comment by jackpotcityco** [comment] 2021-04-18 02:17
Thanks, that was good to know. Thanks for this help!

**Closed by kroitor** 2021-04-18 02:16 UTC
Labels: question
