### ISSUE TITLE
multiprocessing __del__ exception

### ISSUE THREAD

**Issue by mattou78400** [ccxt/ccxt#8316] opened 2021-01-21 00:39 UTC
Hi everyone,

I'm having below issue with CCXT and Multiprocessing in python

launched multiple processes
each managing one Binance instance (different api keys)

Everything runs fine but bellow error keeps on popping up in the console

```
Exception ignored in: <bound method Exchange.__del__ of ccxt.binance()>
Traceback (most recent call last):
  File "C:\Users\\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 401, in __del__
  File "C:\Users\\Miniconda3\lib\site-packages\requests\sessions.py", line 735, in close
  File "C:\Users\\Miniconda3\lib\site-packages\requests\adapters.py", line 325, in close
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\poolmanager.py", line 217, in clear
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\_collections.py", line 99, in clear
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\poolmanager.py", line 168, in <lambda>
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 471, in close
  File "C:\Users\\Miniconda3\lib\queue.py", line 175, in get
  File "C:\Users\\Miniconda3\lib\threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Exchange.__del__ of ccxt.binance()>
Traceback (most recent call last):
  File "C:\Users\\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 401, in __del__
  File "C:\Users\\Miniconda3\lib\site-packages\requests\sessions.py", line 735, in close
  File "C:\Users\\Miniconda3\lib\site-packages\requests\adapters.py", line 325, in close
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\poolmanager.py", line 217, in clear
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\_collections.py", line 99, in clear
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\poolmanager.py", line 168, in <lambda>
  File "C:\Users\\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 471, in close
  File "C:\Users\\Miniconda3\lib\queue.py", line 175, in get
  File "C:\Users\\Miniconda3\lib\threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```

**Comment by kroitor** [comment] 2021-01-21 00:42
Hi! Please, paste your version numbers, your code to reproduce the issue and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Having just the error dump it's hard to guess the cause of the issue.

**Comment by mattou78400** [comment] 2021-01-21 01:12
I unfortunately can't share much of the code...
I cornered it to the: def __del__(self) function

in ccxt->base->exchange.py

An exception is raised in the "self.session.close() " When running ccxt in parallel processes

Running the tasks one after the other, no sub processes, don't raise any error whatsoever..

I'm a bit puzzled, added a try except around self.session.close() for now...
reduces the error printing

thanks!

**Comment by kroitor** [comment] 2021-01-21 01:16
@mattou78400 we wouldn't ask to paste much of the code – can you paste (or make) a minimal snippet to reproduce it? I mean just the relevant stuff...

**Comment by mattou78400** [comment] 2021-01-25 08:55
Hi,

I'm trying to get a minimum piece of code to replicate the issue, unfortunately I can't easily.

The try/catch does the trick for now

I'll update when I have the bug MVP

thanks!

**Comment by kroitor** [comment] 2021-01-30 13:24
@mattou78400 i'd close this for now, feel free to reopen it if anything.

**Closed by kroitor** 2021-01-30 13:24 UTC
Labels: question

**Comment by zaxaco** [comment] 2022-03-03 17:18
same here
```
import ccxt
import pprint

symbol = 'BTC/USDT:USDT'
timeframe = '1h'
index = 4  # use close price from each ohlcv candle
pp = pprint.PrettyPrinter(indent=index)

exchange_id = 'kucoinfutures'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': API_KEY,
    'secret': SECRET,
    'password': PASSPHRASE
})

exchange.set_sandbox_mode(True) 
response = exchange.fetch_ohlcv(symbol, timeframe, params={
                                'price': 'index', 'reverse': False})
pp.pprint(response )
```
worked but in console:
```
Exception ignored in: <function Exchange.__del__ at 0x0000017A9B89A550>
Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 444, in __del__
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\sessions.py", line 737, in close
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 326, in close
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\poolmanager.py", line 
222, in clear
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\_collections.py", line 100, in clear
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\poolmanager.py", line 
173, in <lambda>
  File "C:\Users\Ali\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 498, in close
TypeError: catching classes that do not inherit from BaseException is not allowed
```

ccxt  1.74.71
Python 3.9.10
