### ISSUE TITLE
wrong withdraw() with mexc api

### ISSUE THREAD

**Issue by franklee00** [ccxt/ccxt#10822] opened 2021-12-09 16:31 UTC
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 20
- Programming Language version: Javascript
- CCXT version:@1.63.32

```
const ccxt = require ('ccxt');
const key = require('./key.json');
const mexc = new ccxt.mexc ();
mexc.apiKey = key.mexc.AccessKey;
mexc.secret = key.mexc.SecretKey;
mexc.requiredCredentials;
mexc.checkRequiredCredentials();

// the address is checked that it's in the whitelist and has a withdraw permission
const address = '';
console.log(await mexc.withdraw('USDT','50',address,'',{chain:'BEP20(BSC)'}));

```

```
ExchangeError: mexc {"code":10212,"msg":"This withdrawal address is not on the commonly used address list or has been invalidated"}
    at mexc.handleErrors (/root/node_modules/ccxt/js/mexc.js:2094:19)
    at /root/node_modules/ccxt/js/base/Exchange.js:670:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/root/node_modules/ccxt/js/base/functions/time.js:203:20)
    at async mexc.withdraw (/root/node_modules/ccxt/js/mexc.js:2034:26)
    at async main (file:///root/arbot/arb/biarb/mexc.mjs:63:21) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by kroitor** [comment] 2021-12-09 16:34
Please, always paste your verbose-mode log:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```JavaScript
const ccxt = require ('ccxt');
const key = require('./key.json');

async function main () {
    const mexc = new ccxt.mexc ();
    mexc.apiKey = key.mexc.AccessKey;
    mexc.secret = key.mexc.SecretKey;
    await exchange.loadMarkets()
    
    exchange.verbose = true // <<<<<<<<<<<<<<<< after loadMarkets
    
    // the address is checked that it's in the whitelist and has a withdraw permission
    const address = '';
    console.log(await mexc.withdraw('USDT','50',address,'',{chain:'BEP20(BSC)'}));
```

**Comment by kroitor** [comment] 2021-12-09 16:37
In fact, the problem is with the empty string in the tag. You should not set it if it is not defined.

This will work.

```JavaScript
console.log(await mexc.withdraw('USDT','50',address,undefined,{chain:'BEP20(BSC)'}));
```

Hope that answers your question. Feel free to reopen it if it does not help.

**Comment by franklee00** [comment] 2021-12-09 17:47
> In fact, the problem is with the empty string in the tag. You should not set it if it is not defined.
> 
> This will work.
> 
> ```js
> console.log(await mexc.withdraw('USDT','50',address,undefined,{chain:'BEP20(BSC)'}));
> ```
> 
> Hope that answers your question. Feel free to reopen it if it does not help.

new msg got:

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at mexc.parseTransaction (/root/node_modules/ccxt/js/mexc.js:1421:24)
    at mexc.withdraw (/root/node_modules/ccxt/js/mexc.js:2036:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///root/arbot/arb/biarb/mexc.mjs:63:21)

**Comment by kroitor** [comment] 2021-12-09 17:52
@franklee00 pushed a fix to it, let me know if you have the same last issue with version 1.63.35+ or not (the new build will arrive in ~20 minutes). Thanks for reporting it.

**Closed** 2021-12-09 17:52 UTC
Labels: question

**Comment by franklee00** [comment] 2021-12-09 17:54
> @franklee00 it actually worked, your transaction went through, but it failed to parse the response. Pushed a fix to it, let me know if you have the same last issue with version 1.63.35+ or not (the new build will arrive in ~20 minutes). Thanks for reporting it.

let me try, thx a lot.
