### ISSUE TITLE
[Bitget] "Implicit API" "swap_post_trace_closetrackorder()" does not work

### ISSUE THREAD

**Issue by yudaiharis** [ccxt/ccxt#9852] opened 2021-08-22 03:19 UTC
@kroitor 
I am very grateful for the guidance of "Implicit API"(#9790). 
However, "swap_post_trace_closetrackorder()" does not work. I also read the manual, but I don't know what to do. Do you have any hints?
"swap_get_trace_currenttrack()" works well, thanks.

```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitget({
   # ...
})
exchange.load_markets()
symbol = 'CMT_BTCUSDT'
market = exchange.market(symbol)
pprint(market)
exchange.verbose = True  # uncomment for debugging purposes

response = exchange.swap_get_trace_currenttrack({
    'symbol': market['id'],
    'pageIndex': '1',
    'pageSize': '100',
})
pprint(response)

trackingNo = int(response[0]['orderNo'])
print('\ntrackingNo: {}'.format(trackingNo))
print(type(trackingNo))

response = exchange.swap_post_trace_closetrackorder({
    'symbol': market['id'],
    'trackingNo': trackingNo,  # use the currentTrack result here
})
pprint(response)
```

```
AttributeError: 'bitget' object has no attribute 'swap_post_trace_closetrackorder'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\haris\OneDrive\デスクトップ\bitget_track3.py in 
     29 pprint(response)
     30 
---> 31 response = exchange.swap_post_trace_closetrackorder({
     32     'symbol': market['id'],
     33     'trackingNo': trackingNo,  # use the currentTrack result here

AttributeError: 'bitget' object has no attribute 'swap_post_trace_closetrackorder'
```

_Originally posted by @yudaiharis in https://github.com/ccxt/ccxt/issues/9790#issuecomment-898138651_

**Comment by carlosmiei** [comment] 2022-01-08 13:40
Hello @yudaiharis,
I'm not able to reproduce it anymore, so I believe it's safe to assume something fixed it in the meantime, and therefore I'm closing the issue.
![image](https://user-images.githubusercontent.com/43336371/148646299-c5d0dc35-90a6-41b3-9184-ed732381f845.png)

Feel free to reopen it if you hit this problem again.

**Closed by carlosmiei** 2022-01-08 13:40 UTC
