### ISSUE TITLE
AuthenticationError: kraken {"error":["EAPI:Invalid key"]}

### ISSUE THREAD

**Issue by JDJoe** [ccxt/ccxt#8634] opened 2021-03-16 11:32 UTC
I removed the old keys because I keep getting the EAPI:Invalid key error. 
Added a new keys in Kraken, but still getting the same error.  

```
 ccxt.base.errors.AuthenticationError: kraken {"error":["EAPI:Invalid key"]}

```

**Comment by JDJoe** [comment] 2021-03-16 12:09
OK, this is some type of cretinism on Kraken API side because it works now.

**Comment by kroitor** [comment] 2021-03-16 19:52
This is an intermittent issue with Kraken's availability, afaik.

Check this duplicate report: 

- https://github.com/ccxt/ccxt/issues/6002

Have you tried reaching out to Kraken's tech support on this?

**Comment by kroitor** [comment] 2021-03-16 19:55
I cannot reproduce it on my side, though, it works with my old keys and the most recent version of CCXT.
Can you check which key is being used and paste your verbose output here?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by JDJoe** [comment] 2021-03-16 19:59
After few times my key got rejected, my IP was temporarily blacklisted. I'll wait when it's cleared and I'll try tomorrow again.

**Comment by kroitor** [comment] 2021-03-17 22:44
@JDJoe let us know if recreating the key helps.

**Comment by kroitor** [comment] 2021-03-20 14:53
@JDJoe closing this for now, feel free to reopen it or just ask further questions if any.

**Closed by kroitor** 2021-03-20 14:53 UTC
Labels: question
