### ISSUE TITLE
retry createOrder if failes

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20051] opened 2023-11-19 16:20 UTC
### Operating System

Linux Ubuntu 22LTS

### CCXT Version

4.1.56

### Description

Hi, for some reason, when I execute a `createOrder`, with what to me appears to be a random factor, I receive the following Error from the Exchange:

InvalidOrder: binance {"code":-1013,"msg":"Filter failure: NOTIONAL"}

It's weird as I'm sure I'm loading the markets correctly, and respecting the NOTIONAL filters for the exchange as follows:
```
        // 1. making sure we have the amount desired
        const amountToUse = await this.adjustAmount(side, amount, symbol, exchange);
        
        // 2. Adjusting the precision for amount and price
        const desiredAmount = exchange.amountToPrecision(symbol, amountToUse);
        const desiredPrice = exchange.priceToPrecision(symbol, price);
```

And then I proceeded to place a limit order using the `createOrder` method.

What surprises me, is that when the same exact order is attempted to be placed after a few seconds (if not minutes) it works correctly.

This is why, I was considering to implement an "retry createOrder" method in order to replace the same order if something goes wrong:

```
        const {result,attempts} = await my_retry(placeTradeCmd, {
            maxAttempts: 12,
            minTimeout: 3000,
            maxTimeout: 1000 * 60,
            factor: 1.5,
        });
```

Now: what I want to ensure, is that I need to avoid at any cost, placing 12 consecutive createOrder by mistake.

In other words, I'd like to know if: 
Is it possible that 'createOrder' throws an Error, even if the exchange successfully placed the order?

I guess that, if an Error is thrown, something went wrong, so, the order has not been placed.

I'll paste the my_retry logic function if anyone else needs it.
implementing

### Code

```
  export async function my_retry(promisifiedFunction, {
    maxAttempts = 3,
    minTimeout = 1000,
    maxTimeout = Infinity,
    factor = 1,
}) {
    let attempts = 0;

    while (attempts < maxAttempts) {
        try {
            const res = await promisifiedFunction(); // If successful, return the result
            return {
                result: res,
                attempts: attempts
            }
        } catch (error) {
            console.error(`Attempt ${attempts + 1} failed: ${error.message}`);
            attempts++;

            const delay = Math.min(minTimeout * Math.pow(factor, attempts), maxTimeout);
            await new Promise(resolve => setTimeout(resolve, delay));
        }
    }

    throw new Error(`Exceeded maximum attempts (${maxAttempts})`);
}


```

**Comment by pcriadoperez** [comment] 2023-11-19 18:33
Hi @fl0wo , thanks for posting your code for others might be able to use it.

> Is it possible that 'createOrder' throws an Error, even if the exchange successfully placed the order?

It shouldn't if it does please report it is either an error on the exchange side, or ccxt side. But if there is an error no order should be fully created.

I'll close this issue for now but feel free to post any other questions.

Also here is the response from AI if it's helpful:
The error you're encountering, `InvalidOrder: binance {"code":-1013,"msg":"Filter failure: NOTIONAL"}`, typically indicates that the order does not meet Binance's minimum notional value requirement. The notional value of an order is calculated as the product of the amount (quantity) and the price. Binance, like many other exchanges, has minimum thresholds for the notional value to prevent spam orders and ensure market liquidity.

To address your specific concerns:

1. **Retry Mechanism**: Implementing a retry mechanism for `createOrder` can be a practical solution, but it comes with the risk of unintended order placements if not carefully managed. Your `my_retry` function appears well-structured to handle retries with exponential backoff. However, it's crucial to ensure that a failed order was not actually placed before retrying.

2. **Is it possible for `createOrder` to throw an error even if the order is successfully placed?**: Yes, this can happen in certain scenarios, especially in cases of network issues or exchange API inconsistencies. For example, the request to create an order might have reached the exchange and the order might have been placed successfully, but due to a network timeout or other communication issue, the confirmation response from the exchange might not reach your application, leading to an error being thrown.

3. **Avoiding Multiple Order Placements**: To prevent placing the same order multiple times, you should implement additional checks:
    - **Check Order Status**: Before retrying, check the order status using the order ID if it's available from the failed request. If the order ID isn't available, you can check your recent orders to see if an order with the same parameters has been placed.
    - **Error Handling**: Differentiate between errors that warrant a retry (like network issues) and those that don't (like an invalid order error). In your case, the `NOTIONAL` error indicates an issue with the order parameters, so retrying without modifying these parameters will likely result in repeated failures.

4. **Handling `NOTIONAL` Error**: To address the `NOTIONAL` error specifically, you should:
    - **Check Minimum Notional Values**: Ensure that your orders meet the minimum notional values required by the exchange. These values can change, so it's good practice to fetch and use the latest market data from the exchange.
    - **Adjust Order Size**: If the error is due to the order not meeting the minimum notional size, you may need to adjust the order size (either the amount or the price, or both) to meet the exchange's requirements.

Your approach to adjusting the amount and price precision is correct, but it's also important to consider the minimum notional value, which might be the root cause of the issue you're experiencing.

**Closed by pcriadoperez** 2023-11-19 18:33 UTC
Labels: question
