### ISSUE TITLE
Bybit klines WS in multiple symbols error concatenate str to int

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#20103] opened 2023-11-23 11:54 UTC
### Programming Languages

Python

### CCXT Version

4.1.46

### Description

in ccxt/pro/bybit.py
line 372 / 373
it needs str(timeframeId) instead of timeframeId cause timeframeId is an integer and you can't concatenate str with int.

### Code

```
  

```

**Comment by carlosmiei** [comment] 2023-11-23 12:22
Hello @nikky78 what's the method being used here?

**Comment by nikky78** [comment] 2023-11-23 12:44
Échange.watch_klines(symbol)

**Comment by carlosmiei** [comment] 2023-11-23 12:53
@nikky78 You meant `watch_ohlcv` ? Can you share with us all the arguments used to call the method?

**Comment by nikky78** [comment] 2023-11-23 12:55
Yea my bad, I wasn't in front of my laptop. 
Watch_ohlcv(symbol, limit=1)

**Comment by nikky78** [comment] 2023-11-23 12:58
I did the modification I mention above and it works now

**Comment by carlosmiei** [comment] 2023-11-23 13:00
@nikky78 I still don't know what the problem is, locally I can't reproduce

```
p bybit watchOHLCV "BTC/USDT" "1h" 1  --sandbox
Python v3.11.5
CCXT v4.1.62
bybit.watchOHLCV(BTC/USDT,1h,1)
[[1700744400000, 29324.89, 29325.0, 29300.51, 29324.99, 0.052175]]
```

**Comment by nikky78** [comment] 2023-11-23 13:02
On swap market.
For symbol in symbols:
   Await exchange.watch_ohlcv(symbol, limit=1)

**Comment by carlosmiei** [comment] 2023-11-23 14:02
Works fine as well:
```
p bybit watchOHLCV "BTC/USDT:USDT" "1h" 1  --sandbox
Python v3.11.5
CCXT v4.1.62
bybit.watchOHLCV(BTC/USDT:USDT,1h,1)
[[1700748000000, 37241.0, 37276.6, 37230.4, 37276.6, 139.364]]
[[1700748000000, 37241.0, 37276.9, 37230.4, 37276.9, 140.705]]
[[1700748000000, 37241.0, 37276.9, 37230.4, 37276.9, 142.046]]
```

**Comment by nikky78** [comment] 2023-11-23 14:24
Yes, try multiple symbols

**Comment by carlosmiei** [comment] 2023-11-23 14:32
@nikky78 What's the symbol failing for you? Also can you provide a stacktrace?

**Comment by carlosmiei** [comment] 2023-11-24 16:22
@nikky78 Will close this issue, please re-open it with more details if needed.

**Closed by carlosmiei** 2023-11-24 16:22 UTC
