### ISSUE TITLE
[ccxt.pro] open price does not match last minute close price for build_ohlcvc

### ISSUE THREAD

**Issue by xarthurx** [ccxt/ccxt#12654] opened 2022-04-06 09:25 UTC
I wrote a script to `watch_trades` and calculate the `ohlcv` using `build_ohlcvc(trades)` once the last minute is finished.
But the **open** price does not match the **close** price of the previous minute:

## `pro`: `watch_trades`  + `build_ohlcvc`
```
New DATA added:
            timestamp     open     high      low    close   volume
0 2022-04-06 09:10:00  2.61885  2.63085    2.612  2.62605   7161.0
1 2022-04-06 09:11:00   2.6248  2.64805  2.62425  2.64805  23759.0
2 2022-04-06 09:12:00   2.6495   2.6495  2.63685   2.6375  30576.0
```

## `non-pro`: `fetch_ohlcv`
Using the `ccxt` `non-pro` version and `fetch_ohlcv` gives the following results:
```
            timestamp     open     high      low    close   volume
0  2022-04-06 07:41:00  2.44300  2.45345  2.44210  2.45150  104563.88285
1  2022-04-06 07:42:00  2.45145  2.45160  2.44410  2.44440  102422.49925
2  2022-04-06 07:43:00  2.44440  2.44570  2.43005  2.43705   56166.47170
3  2022-04-06 07:44:00  2.43705  2.43830  2.43290  2.43570   10986.85700
4  2022-04-06 07:45:00  2.43560  2.43970  2.43070  2.43585   50215.61940
```

Is this an issue of the `build_ohlcvc` or something else?
Is there a way to fix it?

**Comment by kroitor** [comment] 2022-04-06 09:43
> Is this an issue of the build_ohlcvc or something else?

This is not an issue, it's by design. The true info is returned in both cases, depending on how you look at it.
If you define the open price as the price of the first trade within that period, then your open price does not have to be the same as the closing price (this is probably more correct financially)
If you define the open price as the closing price of the last candle, then your open price will match the closing price, obviously (this is better-looking on charts)

> Is there a way to fix it?

Yes, you can easily enforce the open = previous close rule in Python like this:

```Python
ohlcv = exchange.build_ohlcvc(trades, '1m')
ohlcv = [ohlcv[0]] + [[ohlcv[i][0], ohlcv[i - 1][4], ohlcv[i][2], ohlcv[i][3], ohlcv[i][4], ohlcv[i][5]] for i in range(1, len(ohlcv))]
```

**Closed by kroitor** 2022-04-06 09:43 UTC
Labels: question
