### ISSUE TITLE
CCXT_Okex.futures_get_instruments_instrument_id_book({'instrument_id': 'BTC-USDT-200925'})   is not load accurate value.

### ISSUE THREAD

**Issue by tjddnjs124** [ccxt/ccxt#6994] opened 2020-05-22 16:23 UTC
![image](https://user-images.githubusercontent.com/26290547/82688263-88f36700-9c93-11ea-954c-a6b2d8dd7c81.png)

i want current bid/ask value in Okex,
so i use that code , 
-----------------------------------------
okex_futures3.futures_get_instruments_instrument_id_book({'instrument_id': 'BTC-USDT-200925'})
----------------------------------------

but return value is not accurate value ..

why?

and how can i fix or replace the code ?

thx bro

**Comment by kroitor** [comment] 2020-05-22 16:40
1. First, please read this **very carefully**: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

    Always paste your source code here using [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

    &#096;&#096;&#096;Python
    put your code here – something we can copypaste and launch
    don't paste one line of code, paste your full short complete code snippet to reproduce it
    it has to be short but complete including exchange instantiation, but without your keys of course
    &#096;&#096;&#096;

    &#096;&#096;&#096;
    your output here
    &#096;&#096;&#096;

    Please don't paste screenshots – always paste your code and output in plain text as shown above.


2. We also need to know your Python version, your CCXT version and other info as mentioned in the FAQ.

3. On your screenshot,  it says "binance_futures", however, on the left the OKEX website is shown. Are you sure you're polling a correct exchange? To rule that out we need to see the full short code snippet you use (including the exchange instantiation). 

4. Also, if you're using REST polling then it will take time for your request to travel towards the exchange and back (roundtrip-time). In general, with REST+HTTPS you will see the values slightly delayed, because it will take time for the exchange response to reach your machine. This is caused by the nature of the underlying networking stack. If you want real-time data, then you probably need to listen to OKEX websockets with [CCXT Pro](https://ccxt.pro/) to minimize the networking delays.

**Comment by ttodua** [comment] 2022-07-16 14:16
The issue has never got any follow-up from op and the issue remains unknown. Closing this topic for now.

**Closed by ttodua** 2022-07-16 14:16 UTC
Labels: question
