### ISSUE TITLE
fetch_ticker in upbit

### ISSUE THREAD

**Issue by jshuh999** [ccxt/ccxt#22500] opened 2024-05-15 09:55 UTC
### Operating System

Ubuntu 22.04.4 LTS

### Programming Languages

Python

### CCXT Version

4.2.95

### Description

I wrote a program using ccxt to retrieve coins with high upward trends on the Upbit exchange. However, I'm experiencing an issue where coins with low upward trends are being returned. When I query through the Upbit API directly, it returns the results correctly.

### Code

```
exchange = ccxt.upbit({'apiKey': UPBIT_API_KEY, 'secret': UPBIT_SECRET_KEY})
tickers = exchange.fetch_tickers()

tickers_sorted = sorted(
    (ticker for ticker in tickers.values() if ticker['percentage'] is not None and ticker['symbol'].endswith(ticker_lang)),
    key=lambda x: x['percentage'],
    reverse=True
)

```

**Comment by carlosmiei** [comment] 2024-05-15 10:55
Hello @jshuh999, what do you mean exactly by "low upward trends are being returned" ?

**Comment by jshuh999** [comment] 2024-05-16 05:20
Hello, I’m, sorry. English is my second language.I think upbit API retrieves correct tickers, but ccxt retrieves incorrect tickers.It seems that incorrect data is being entered in ticker[‘percentage’] from fetch_tickers()  When I sort ticker[‘percentage’] with reverse=True, incorrect data retrieved.On May 15, 2024, at 7:55 PM, Carlos Gonçalves ***@***.***> wrote:﻿
Hello @jshuh999, what do you mean exactly by "low upward trends are being returned" ?

**Comment by carlosmiei** [comment] 2024-05-16 09:38
@jshuh999 Got it, thanks for clarifying it, we will take a look

**Comment by Dan-krm** [comment] 2024-05-17 07:46
Hi @jshuh999 I looked into fetchTicker, fetchTickers and parseTicker on upbit and they're using the `signed_change_rate` from the exchange response for the ccxt `percentage` value in our parsed response.

That seems to be the correct expected behavior so I'm not sure how to resolve your issue for you.

Could you provide an example of the incorrect response and the correct response that you're expecting?

This is the endpoint we're using for fetchTicker/fetchTickers:
https://docs.upbit.com/reference/ticker%ED%98%84%EC%9E%AC%EA%B0%80-%EC%A0%95%EB%B3%B4
https://global-docs.upbit.com/reference/tickers

**Comment by Dan-krm** [comment] 2024-06-13 05:41
@jshuh999 closing this issue for now, feel free to reopen it if you can share a reproduceable example showing any incorrect data

**Closed by Dan-krm** 2024-06-13 05:41 UTC
