### ISSUE TITLE
Composer fails to load the latest codeset

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#4735] opened 2019-02-23 08:05 UTC
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.18.287
- Exchange: -
- Method: -

"composer update" only loads up to version 1.18.281

**Comment by kroitor** [comment] 2019-02-23 12:56
Indeed, the version updates were delayed. However, it self-resolved, apparently, the update delay was on the Packagist side. Thanks for your attention, really appreciate your help! Let us know if you notice anything!

**Comment by WoK-E** [comment] 2019-02-24 17:09
Hi Igor,

Composer is still stuck at 1.18.281. I've tried installing ccxt/ccxt on 4 different systems (and actually on 4 different continents), 3 of which were fresh systems.

Packagist shows that it has the latest version (https://packagist.org/packages/ccxt/ccxt shows that it has version 1.18.291), so either packagist is somehow misbehaving, or there is a problem with the packaging.

Best regards,
Agis

**Comment by kroitor** [comment] 2019-02-24 17:10
@WoK-E ahh, I see, ok, thx for the followup! We will reach out to them to resolve this. I will get back to you on this as soon as I hear from them!

**Comment by kroitor** [comment] 2019-02-28 16:39
@WoK-E alright, we have received an update from the Packagist+Composer, the issue is now fixed, so both should show the version up-to-date. Thank you for reporting! Let us know if anything!

**Closed by kroitor** 2019-02-28 16:39 UTC
