### ISSUE TITLE
handle_liquidation error (Python)

### ISSUE THREAD

**Issue by timborden** [ccxt/ccxt#23349] opened 2024-08-07 13:31 UTC
### Operating System

OSX

### Programming Languages

Python

### CCXT Version

4.3.61

### Description

Trying to use the new `watchLiquidationsForSymbols` and `watchLiquidations` methods (thanks for the addition @pcriadoperez!)....appear to have run into an error when processing a liquidation WebSocket message.

### Code

There's an assignment error in the `handle_liquidation` method:
```
File ".../site-packages/ccxt/pro/okx.py", line 476, in handle_liquidation
    self.liquidations[symbol] = liquidations
    ~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
```

Digging through the code, I can't see where the `self.liquidations` is initialised....but it appears to be initialised as `None`:
```
❯ python
>>> import ccxt.pro as ccxt
>>> okx = ccxt.okx()
>>> okx.liquidations
>>> type(okx.liquidations)
<class 'NoneType'>
>>> okx.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'okx' object has no attribute 'foo'
```

**Comment by carlosmiei** [comment] 2024-08-07 13:35
Hello @timborden, thanks for reporting it, we will take a look

**Comment by carlosmiei** [comment] 2024-08-07 15:04
Hello @timborden can you please upgrade your ccxt version and try again? It should be fixed now.

**Comment by timborden** [comment] 2024-08-09 08:56
Woah...that was fast...thanks @carlosmiei!

I can confirm, there's no error with the new version. I am still testing the `watchLiquidationsForSymbols` and `watchLiquidations` methods....will let you know if I run into anything else.

Cheers.

**Comment by ttodua** [comment] 2024-08-09 09:02
@timborden `watchLiquidations` is being also fixed in binance, will be merged soon, however `watchLiquidationsForSymbols` should be working as intended.

**Closed** 2024-08-09 09:02 UTC
Labels: bug

**Comment by timborden** [comment] 2024-08-09 09:05
@ttodua thanks for the heads up! ....will watch for the new version

**Comment by timborden** [comment] 2024-08-16 09:49
@ttodua - spotted an issue with `watchLiquidationsForSymbols` for Binance - https://github.com/ccxt/ccxt/issues/23416#issuecomment-2293143799

....not sure if it's related to the fix you mentioned....FYI
