### ISSUE TITLE
gateio watchTrades timestamp key error

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#6806] opened 2020-04-15 14:36 UTC
- OS: ubuntu 16.04
- Programming Language version: python 3.6.5
- CCXT version: ccxt (1.26.40) ccxtpro (0.1.57)

```
client = ccxtpro.gateio()
since = datetime.utcnow()
while True:
    trades = await client.watch_trades(ccxt_symbol, since=int(since.timestamp() * 1000))
```

```
/python3.6/site-packages/ccxt/base/exchange.py", line 1670, in <listcomp>
4|test  |     array = [entry for entry in array if entry[key] >= since]
4|test  | KeyError: 'timestamp'
```

**Comment by kroitor** [comment] 2020-04-15 14:55
Hi @jaseisen105 !

This works on my side, does it work for you? If not, can you plz share more details, or your full minimal snippet to reproduce it (including the instantiation of the async loop).

```Python
# -*- coding: utf-8 -*-

import asyncio
import ccxtpro

from datetime import datetime

async def loop(exchange, symbol):
    since = datetime.utcnow()
    timestamp = int(since.timestamp() * 1000)
    while True:
        trades = await exchange.watch_trades(symbol, since=timestamp)
        print('--------------------------------------------------------------')
        print('Received', len(trades), 'after', exchange.iso8601 (timestamp))
        print('waiting for next update...')


async def main():
    exchange = ccxtpro.gateio({'enableRateLimit': True})  # rate-limit is required!
    await loop(exchange, 'BTC/USDT')
    await exchange.close()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by jaseisen105** [comment] 2020-04-15 15:19
Hi @kroitor -

That works for me.  What's odd is that if I isolate my code into a small script it works fine too (pretty similar to yours).  It also works fine as-is for other ccxtpro exchanges

I run a bunch of code using async in my full program so wondering if it's some race condition.  Probably will be a difficult issue to track down :/

**Comment by kroitor** [comment] 2020-04-15 15:21
@jaseisen105 if you can make a reproducible snippet, i'll do my best to resolve it asap. Unfortunately, without some substantial code my guesses wouldn't really help. Hope for your understanding.

**Comment by kroitor** [comment] 2020-04-15 15:25
@jaseisen105 it may depend on the symbol in question, which pair is it?

**Comment by jaseisen105** [comment] 2020-04-15 23:34
Hi @kroitor - was able to reproduce it

The issue occurs when requesting `watchTrades` across many markets

Sample of how to reproduce below

```
all_get_pairs = ["BTC/USDT", "ETH/USDT"...]

async def go(pair):
    while True:
        try:
            since = datetime.utcnow()
            while True:
                trades = await client.watch_trades(pair, since=int(since.timestamp() * 1000))
                since = datetime.utcnow()
                print(f"{pair} : {trades}")
        except:
            log.exception(f"error: {pair}")
            return

for p in all_get_pairs:
    event_loop.create_task(go(p))

event_loop.run_forever()

```

**Comment by kroitor** [comment] 2020-04-16 00:02
@jaseisen105 awesome, thank you very much for the effort! We will debug this and will get back to you shortly.

**Comment by jaseisen105** [comment] 2020-04-16 02:21
Great, thanks!  FYI the rate limiter was enabled for the above

**Comment by frosty00** [comment] 2020-04-16 07:33
it seems that upon subscribing to another symbol gateio drops all the other subscribed symbols, so we need to remember which symbols have already been subscribed to and make a new subscription to all of them. i've seen the pattern where websocket apis return multiple symbols in the response and you have to resolve different futures from one message on other exchanges as well.

**Comment by kroitor** [comment] 2020-04-17 19:49
@jaseisen105 the bug was fixed by @frosty00 (many thanks) in https://github.com/kroitor/ccxt.pro/pull/30, so it should work normally in CCXT Pro version 0.1.64+ Let us know if you still have issues or difficulties with it. It will be awesome if you report back whether the issue is resolved on your side or not. We appreciate your feedback! Thx!

**Closed by kroitor** 2020-04-17 19:49 UTC
Labels: ccxt.pro

**Comment by jaseisen105** [comment] 2020-04-18 15:47
Hi @kroitor @frosty00 

I just retried and unfortunately am still seeing issues.  Initially, every call to `await watch_trades` yielded the timestamp error.  Now the first call to `await watch_trades` errors out and after that I don't get any other messages.  It could be that there's no trades happening on the exchange but I'm subscribed to a bunch of popular pairs so there probably is action happening there.

**Comment by kroitor** [comment] 2020-04-18 15:52
@jaseisen105 got it, must be a leftover somewhere, will fix that shortly. Thank you!

**Comment by frosty00** [comment] 2020-04-18 16:50
I can't reproduce the error: it's working for me...

**Comment by kroitor** [comment] 2020-04-18 17:34
@jaseisen105 apparently, the bug is still there, we're working on the proper fix now, will let you know as soon as it arrives! Thx again!
