### ISSUE TITLE
Add TradeOgre Exchange

### ISSUE THREAD

**Issue by Sokanon** [ccxt/ccxt#16401] opened 2023-01-09 20:53 UTC
### Exchange Name

TradeOgre

### URL of the Exchange

https://tradeogre.com/

### URL of the Exchange's API docs

https://tradeogre.com/help/api

### Why should this exchange be implemented?

This exchange usually contains low-cap coins and newly introduced Proof-of-Work coins. It would be great for the Proof-of-Work community.

**Comment by samgermain** [comment] 2023-01-10 01:21
Closing because it's a duplicate of https://github.com/ccxt/ccxt/issues/2150

**Closed by samgermain** 2023-01-10 01:21 UTC
Labels: duplicate, new exchange

**Comment by carlosmiei** [comment] 2023-01-16 11:43
Hello @sohaibkanon,
Can you please reach out to us on discord or telegram?

**Comment by sohaibkanon** [comment] 2023-01-18 02:03
Sounds good!

**Comment by sohaibkanon** [comment] 2023-01-18 02:04
@carlosmiei What's the server link?

**Comment by carlosmiei** [comment] 2024-03-17 17:32
@Sokanon Will add it soon

**Comment by Sokanon** [comment] 2024-03-21 20:18
Cool thank you

**Comment by carlosmiei** [comment] 2024-03-22 09:23
@Sokanon It is already available if you update your ccxt version!

**Comment by Sokanon** [comment] 2024-03-24 15:13
I do what to bring to light that tradeogre has been doing some shady stuff lately and ripping people off. Though not sure if its of importance to the repo but maybe it can be marked as a flag for the exchange
