### ISSUE TITLE
New Exchange: 1inch Integration

### ISSUE THREAD

**Issue by ssoruf** [ccxt/ccxt#17270] opened 2023-03-20 04:56 UTC
I would like to add a new exchange. 1inch is a dex aggregator that allows you to use APIs. This is the link https://docs.1inch.io

Can someone do this paid for me?

**Comment by Jones098** [comment] 2023-03-29 08:51
Please release coins

**Comment by ttodua** [comment] 2024-06-10 14:49
duplicate of https://github.com/ccxt/ccxt/issues/6337

**Closed by ttodua** 2024-06-10 14:49 UTC
Labels: new exchange
