### ISSUE TITLE
Network property in Currency structure differs between exchanges

### ISSUE THREAD

**Issue by PovarovDenis** [ccxt/ccxt#19067] opened 2023-08-31 13:38 UTC
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.0.78

### Description

Here is an example of the Currency object from Binance:

```
{
  id: 'PUNDIX',
  name: 'Pundi X',
  code: 'PUNDIX',
  precision: 8,
  info: {
    coin: 'PUNDIX',
    depositAllEnable: true,
    withdrawAllEnable: true,
    name: 'Pundi X',
    free: '0',
    locked: '0',
    freeze: '0',
    withdrawing: '0',
    ipoing: '0',
    ipoable: '0',
    storage: '0',
    isLegalMoney: false,
    trading: true,
    networkList: [ [Object] ]
  },
  active: true,
  deposit: true,
  withdraw: true,
  networks: [
    {
      network: 'ETH',
      coin: 'PUNDIX',
      entityTag: 'main',
      withdrawIntegerMultiple: '0.00000001',
      isDefault: true,
      depositEnable: true,
      withdrawEnable: true,
      depositDesc: '',
      withdrawDesc: '',
      specialTips: '',
      specialWithdrawTips: '',
      name: 'Ethereum (ERC20)',
      resetAddressStatus: false,
      addressRegex: '^(0x)[0-9A-Fa-f]{40}$',
      addressRule: '',
      memoRegex: '',
      withdrawFee: '8.12',
      withdrawMin: '16',
      withdrawMax: '9999999',
      minConfirm: '6',
      unLockConfirm: '64',
      sameAddress: false,
      estimatedArrivalTime: '5',
      busy: false,
      country: 'AE,BINANCE_BAHRAIN_BSC,KZ,FR,ES,PL,IT,SE,JP,NL,PL_BE',
      contractAddressUrl: 'https://etherscan.io/token/',
      contractAddress: '0x0fd10b9899882a6f2fcb5c371e17e70fdee00c38'
    }
  ],
  fee: 8.12,
  fees: { ETH: 8.12 },
  limits: {
    leverage: { min: null, max: null },
    amount: { min: null, max: null },
    price: { min: null, max: null },
    cost: { min: null, max: null }
  }
}
```

And here is an example of the Currency object from Huobi:

```
{
  info: {
    currency: 'pundix',
    assetType: '1',
    chains: [ [Object] ],
    instStatus: 'normal'
  },
  code: 'PUNDIX',
  id: 'pundix',
  active: true,
  deposit: true,
  withdraw: true,
  fee: null,
  name: null,
  limits: {
    amount: { min: null, max: null },
    withdraw: { min: 0.32, max: 30419.7528 }
  },
  precision: 1e-8,
  networks: {
    ERC20: {
      info: [Object],
      id: 'pundix',
      network: 'ERC20',
      limits: [Object],
      active: true,
      deposit: true,
      withdraw: true,
      fee: 15.15871213,
      precision: 1e-8
    }
  }
}
```

In Binance `networks` property is an array of items, in Huobi it is an object.

Another issue is that I don't even know how to find out that the currency supports the same network on different exchanges, cos in Binance `network` property has `ETH` value, but in Huobi it has `ERC20` value, what I assume is the same network actually, but it has different ids.

**Comment by carlosmiei** [comment] 2023-09-01 13:56
Hello @PovarovDenis,

Currencies and networks are not entirely unified yet, so yes, some discrepancies between different exchanges might arise. I would say that the huobi's format is the expected one, and most exchanges are adopting it already. 

>  Binance network property has ETH value, but in Huobi it has ERC20 value, what I assume is the same network actually, but it has different ids.

Again binance is the outliar here, most of the time you will find `ERC20` as the network code when referring to ERC20 tokens or `ETH` if we're referring to the main `ETH` currency. 
 

We will try to speed up the Binance unification,  thanks a lot for reporting it.

**Comment by ttodua** [comment] 2023-09-02 19:45
there has been similar requests in the past, like issues # 14814, 16521, 17496 etc. 
We take users feedback in account and we are already in process of networks unification. stay tuned and subscribe to announcements whenever it will be complete: https://t.me/ccxt_announcements (or https://discord.com/channels/690203284119617602/1057748769690619984 )

**Comment by ttodua** [comment] 2023-09-11 14:47
duplicate of https://github.com/ccxt/ccxt/issues/12795 (please post further comments there)

**Closed by ttodua** 2023-09-11 14:47 UTC
Labels: bug
