### ISSUE TITLE
Connection closed by remote server, closing code 1008 - compare with cryptofeed library

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#12031] opened 2022-02-19 19:46 UTC
I made comparation of two libraries  ccxtpro and cryptofeed. 
I found that if numbers of watched symbols = 199 than ccxtpro returns (Connection closed by remote server, closing code 1008) after > 10 seconds, but cryptofeed still works without error. 

Bellow are samples of codes which I used for test. 
What could be reason of error for ccxtpro?

CCXTPRO

```
# -*- coding: utf-8 -*-

from asyncio import run, gather
import ccxtpro


print('CCXT Pro Version:', ccxtpro.__version__)


async def loop(exchange, symbol):
    while True:
        try:
            trades = await exchange.watch_trades(symbol)
            print(exchange, symbol, len(trades), trades[0]['id'], trades[-1]['id'], trades[0]['timestamp'], trades[-1]['timestamp'])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails


async def main():
    exchange = ccxtpro.binance({'newUpdates': True})
    markets = await exchange.load_markets()
    symbols = [symbol for symbol in markets.keys()]
    symbols = symbols[:199]


    await gather(*[loop(exchange, symbol) for symbol in symbols])
    await exchange.close()


run(main())

```

CRYPTOFEED
```

'''
Copyright (C) 2017-2022 Bryant Moscon - bmoscon@gmail.com
Please see the LICENSE file for the terms and conditions
associated with this software.
'''
from decimal import Decimal

from cryptofeed import FeedHandler
from cryptofeed.defines import CANDLES, BID, ASK, BLOCKCHAIN, FUNDING, GEMINI, L2_BOOK, L3_BOOK, LIQUIDATIONS, OPEN_INTEREST, PERPETUAL, TICKER, TRADES, INDEX
from cryptofeed.exchanges import (Binance)



async def trade(t, receipt_timestamp):
    assert isinstance(t.timestamp, float)
    assert isinstance(t.side, str)
    assert isinstance(t.amount, Decimal)
    assert isinstance(t.price, Decimal)
    assert isinstance(t.exchange, str)
    print(f"Trade received at {receipt_timestamp}: {t}")



def main():
    config = {'log': {'filename': 'demo.log', 'level': 'DEBUG', 'disabled': False}}
    # the config will be automatically passed into any exchanges set up by string. Instantiated exchange objects would need to pass the config in manually.
    f = FeedHandler(config=config)

    pairs = Binance.symbols()[:199]
    f.add_feed(Binance(symbols=pairs, channels=[TRADES], callbacks={TRADES: trade}))

    f.run()


if __name__ == '__main__':
    main()
```

**Comment by sc0Vu** [comment] 2022-04-09 09:45
Hi @YuriyTigiev

The script both works great on my computer, my `ccxt.pro` version: `1.0.57`. Let me know if it doesn't work.

**Comment by ttodua** [comment] 2022-07-31 10:41
I've tested out this too at this moment, and I don't see any issue. It might have been because of other reasons probably, also CCXT had bunch of updates since then.
So, I'll close this topic, but if anyone experiences any issue, please let us know.

**Comment by caiusCitiriga** [comment] 2022-11-12 01:32
experienced same issue with ccxt 2.1.55. Tried to run trades watch on 200 markets on binance

**Comment by ttodua** [comment] 2022-11-12 08:36
> experienced same issue with ccxt 2.1.55. Tried to run trades watch on 200 markets on binance. But it was an occasional error. I believe it was originated due to the fact that I've continuously killed and started the app, making ccxt loose track of the actual throttling (?) not sure.

yes, that 'might be' also case as only running instance has the temporary memory of it's throttles/etc. so, if you come across the issue with same running instance, then it will be bug on ccxt side, but you havent yet confirmed that as I see. so, please see if you find any bug, I'll be pleased to see your report again.

**Comment by caiusCitiriga** [comment] 2022-11-13 18:54
Here to update again :) 

After a few researches I've found out that this specific error code on Binance it means:
```
-1008 SERVER_BUSY
Spot server is currently overloaded with other requests. Please try again in a few minutes.
```

**Comment by sevenjay** [comment] 2023-11-21 01:18
ccxt version 4.1.30 In my case, watch_trades will encounter the error 1008 when the Binance spot symbols more than 198.

**Comment by pcriadoperez** [comment] 2024-05-19 21:35
Closing this issue as it should have been solved with binance with this PR: https://github.com/ccxt/ccxt/pull/15737
Feel free to reach out with any other questions or errors, or if you see again the issue

**Closed by pcriadoperez** 2024-05-19 21:35 UTC
Labels: bug, important

**Comment by quantitative-technologies** [comment] 2024-09-23 04:02
This issue is not solved for me. 

I am on `ccxt` version 4.4.6. 

Here is an MRE demonstrating this error, calling the `watch_ticker(symbol)` api call for many symbols:

```python
from asyncio import gather, run, sleep, timeout
from collections import defaultdict
from datetime import datetime, timezone

import ccxt.pro as ccxtpro

TIME_LIMIT = 10  # Time limit in seconds
MAX_SYMBOLS = None  # None to use all symbols


class OrderBookManager:
    def __init__(self, exchange_id, symbols, time_limit):
        self.exchange = getattr(ccxtpro, exchange_id)()
        self.symbols = symbols
        self.market_data = defaultdict(lambda: defaultdict(dict))
        self.time_limit = time_limit
        self.error_count = 0

    def format_timestamp(self, timestamp):
        return datetime.fromtimestamp(timestamp / 1000, tz=timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%S.%f"
        )[:-3]

    async def watch_ticker(self, symbol):
        while True:
            try:
                ticker = await self.exchange.watch_ticker(symbol)
                timestamp = ticker["timestamp"]
                if timestamp is None:
                    continue
                iso_timestamp = self.format_timestamp(timestamp)

                self.market_data[symbol]["ticker"] = {
                    "timestamp": iso_timestamp,
                    "volume": ticker["baseVolume"],
                    "quoteVolume": ticker["quoteVolume"],
                }
                print(
                    f"Updated ticker for {symbol} at {iso_timestamp}: 24h Volume: {self.market_data[symbol]['ticker']['volume']}, Quote Volume: {self.market_data[symbol]['ticker']['quoteVolume']}"
                )
            except Exception as e:
                self.error_count += 1
                print(f"Error watching ticker for {symbol}: {str(e)}")
                await sleep(1)  # Wait before retrying

    async def watch_all_tickers(self):
        tasks = [self.watch_ticker(symbol) for symbol in self.symbols]
        await gather(*tasks)

    async def run_watch_tickers(self):
        try:
            await self.exchange.load_markets()
            async with timeout(self.time_limit):
                await self.watch_all_tickers()
        except TimeoutError:
            print(f"Time limit of {self.time_limit} seconds reached. Exiting...")
        finally:
            await self.exchange.close()
            print(
                f"Received updates for {len(self.market_data)} out of {len(self.symbols)} symbols."
            )
            print(f"Total # of errors: {self.error_count}")
            

def common_symbols_binance_poloniex_constant() -> list[str]:
    """Hard-coded, current (at time of creation) list of common symbols for binance-poloniex exchange pair."""
    return [
        "RLC/USDT",
        "SOL/USDT",
        "HIGH/USDT",
        "AXS/USDT",
        "LOOM/USDT",
        "LOKA/USDT",
        "WLD/USDT",
        "AI/USDT",
        "MDT/BTC",
        "LUNC/USDT",
        "RAY/USDT",
        "SNX/BTC",
        "ALT/USDT",
        "AMP/BTC",
        "STRK/USDT",
        "HFT/USDT",
        "LRC/USDT",
        "LRC/BTC",
        "RSR/USDT",
        "FARM/USDT",
        "BNX/USDT",
        "PLA/USDT",
        "XRPBULL/USDT",
        "ORDI/USDT",
        "SAND/BTC",
        "IMX/USDT",
        "LTC/USDT",
        "STEEM/BTC",
        "BTC/USDC",
        "ZRX/BTC",
        "NMR/USDT",
        "YGG/USDT",
        "LPT/USDT",
        "REEF/USDT",
        "XEC/USDT",
        "AUDIO/USDT",
        "OGN/USDT",
        "G/USDT",
        "GMX/USDT",
        "HIFI/USDT",
        "TLM/USDT",
        "GMT/USDT",
        "PEPE/USDT",
        "AVAX/USDT",
        "GLM/BTC",
        "COMP/USDT",
        "NFP/USDT",
        "DAI/USDT",
        "STG/USDT",
        "PORTO/USDT",
        "CHZ/USDT",
        "YFI/USDT",
        "GLM/USDT",
        "TRU/USDT",
        "XTZ/USDT",
        "ETH/BTC",
        "SNX/USDT",
        "LTC/USDC",
        "LAZIO/USDT",
        "GNS/USDT",
        "GTC/USDT",
        "LINK/USDT",
        "FTM/BTC",
        "BAR/USDT",
        "TRX/BTC",
        "REN/USDT",
        "XRP/USDT",
        "CVX/USDT",
        "METIS/USDT",
        "ZRX/USDT",
        "XMR/BTC",
        "AVA/BTC",
        "DCR/BTC",
        "SNT/BTC",
        "OOKI/USDT",
        "BCH/USDT",
        "DOGE/BTC",
        "EOS/USDT",
        "CTSI/USDT",
        "FTT/USDT",
        "SLP/USDT",
        "BNT/USDT",
        "EOS/BTC",
        "SAND/USDT",
        "OG/USDT",
        "XMR/USDT",
        "ZK/USDT",
        "MKR/USDT",
        "FIDA/USDT",
        "EOS/ETH",
        "GHST/USDT",
        "SPELL/USDT",
        "BAT/BTC",
        "APE/USDT",
        "ENA/USDT",
        "TRU/BTC",
        "BTT/TRX",
        "SOL/BTC",
        "ZRX/ETH",
        "DIA/USDT",
        "PIXEL/USDT",
        "DOT/BTC",
        "ARDR/BTC",
        "BAT/USDT",
        "T/USDT",
        "NEXO/USDT",
        "TRX/USDC",
        "ZEC/ETH",
        "TRB/USDT",
        "FTM/USDT",
        "XLM/USDT",
        "FRONT/BTC",
        "OSMO/USDT",
        "ADA/USDT",
        "ZEC/BTC",
        "POLS/USDT",
        "BICO/USDT",
        "BLUR/USDT",
        "AAVE/BTC",
        "RUNE/USDT",
        "RIF/USDT",
        "SNT/USDT",
        "BNB/USDC",
        "OMG/USDT",
        "MDT/USDT",
        "FIL/USDT",
        "KP3R/USDT",
        "BSV/USDT",
        "PSG/USDT",
        "ERN/USDT",
        "STPT/USDT",
        "SANTOS/USDT",
        "POLY/BTC",
        "PYR/USDT",
        "NEO/USDT",
        "STEEM/USDT",
        "BURGER/USDT",
        "SUPER/USDT",
        "SHIB/USDT",
        "XLM/BTC",
        "FRONT/USDT",
        "GAS/BTC",
        "CVP/USDT",
        "AGIX/USDT",
        "C98/USDT",
        "ALPHA/USDT",
        "XRP/BTC",
        "DOGE/USDT",
        "OP/USDT",
        "GRT/USDT",
        "MANA/BTC",
        "BAND/USDT",
        "DEGO/USDT",
        "GAS/USDT",
        "STORJ/BTC",
        "DAR/USDT",
        "QTUM/USDT",
        "SXP/BTC",
        "LOOM/BTC",
        "CHR/USDT",
        "AVA/USDT",
        "LSK/USDT",
        "APT/USDT",
        "JST/USDT",
        "UNI/USDT",
        "QUICK/USDT",
        "LQTY/USDT",
        "XRP/USDC",
        "FLOKI/USDT",
        "STX/USDT",
        "FXS/USDT",
        "CVC/BTC",
        "BOND/USDT",
        "MLN/USDT",
        "FET/USDT",
        "LINK/BTC",
        "ILV/USDT",
        "VOXEL/USDT",
        "JUV/USDT",
        "STMX/USDT",
        "PENDLE/USDT",
        "ATM/USDT",
        "LSK/BTC",
        "GALA/USDT",
        "EPX/USDT",
        "REQ/USDT",
        "CRV/USDT",
        "ETC/BTC",
        "AMP/USDT",
        "CLV/USDT",
        "ALPINE/USDT",
        "MANA/USDT",
        "GFT/USDT",
        "PEOPLE/USDT",
        "SXP/USDT",
        "LTC/BTC",
        "BAL/USDT",
        "ATOM/USDT",
        "BNB/USDT",
        "DOT/USDT",
        "NEAR/USDT",
        "WIN/USDT",
        "ADA/BTC",
        "PERP/USDT",
        "ETC/ETH",
        "DUSK/USDT",
        "ARDR/USDT",
        "TRX/USDT",
        "WOO/USDT",
        "DASH/BTC",
        "ARB/USDT",
        "CAKE/USDT",
        "ETH/USDC",
        "LDO/USDT",
        "ETHFI/USDT",
        "ZRO/USDT",
        "TNSR/USDT",
        "ICP/USDT",
        "CHR/BTC",
        "RDNT/USDT",
        "ASR/USDT",
        "NEO/BTC",
        "BANANA/USDT",
        "EGLD/USDT",
        "QI/USDT",
        "AERGO/USDT",
        "RENDER/USDT",
        "AAVE/USDT",
        "API3/USDT",
        "ZEC/USDT",
        "YFII/USDT",
        "AVAX/BTC",
        "BONK/USDT",
        "ALPACA/USDT",
        "JUP/USDT",
        "XEM/USDT",
        "LUNA/USDT",
        "DYDX/USDT",
        "MAV/USDT",
        "ASTR/USDT",
        "BTS/USDT",
        "CVC/USDT",
        "CITY/USDT",
        "OM/USDT",
        "UMA/USDT",
        "OCEAN/USDT",
        "BTT/USDC",
        "ALICE/USDT",
        "XEM/BTC",
        "ETC/USDT",
        "AKRO/USDT",
        "JTO/USDT",
        "BAKE/USDT",
        "FIL/BTC",
        "ATOM/BTC",
        "DCR/USDT",
        "DASH/USDT",
        "WIF/USDT",
        "WIN/TRX",
        "SUN/USDT",
        "XVS/USDT",
        "ENS/USDT",
        "SC/BTC",
        "PORTAL/USDT",
        "INJ/USDT",
        "BTS/BTC",
        "WNXM/USDT",
        "ENJ/USDT",
        "SUI/USDT",
        "VGX/USDT",
        "SSV/USDT",
        "BOME/USDT",
        "TUSD/USDT",
        "KSM/USDT",
        "BSV/BTC",
        "HNT/USDT",
        "KNC/USDT",
        "QTUM/BTC",
        "BCH/BTC",
        "SUSHI/USDT",
        "RPL/USDT",
        "MKR/BTC",
        "AEVO/USDT",
        "AGLD/USDT",
        "ID/USDT",
        "INJ/BTC",
        "BADGER/USDT",
        "STORJ/USDT",
        "SC/USDT",
        "ACM/USDT",
        "BTT/USDT",
        "ETH/USDT",
        "BTC/USDT",
        "ACE/USDT",
        "MBOX/USDT",
        "NEIRO/USDT",
        "TURBO/USDT",
        "POL/USDT",
        "POL/BTC",
    ]

async def main():
    exchange_id = 'binance'  # Replace with your desired exchange
    all_symbols = common_symbols_binance_poloniex_constant()
    symbols = all_symbols[:MAX_SYMBOLS] if MAX_SYMBOLS is not None else all_symbols
    time_limit = TIME_LIMIT  
    manager = OrderBookManager(exchange_id, symbols, time_limit)
    await manager.run_watch_tickers()
    
if __name__ == "__main__":
    run(main())
```

If I run this, here is the final output:

```console
...
Updated ticker for ALICE/USDT at 2024-09-23T03:28:20.204: 24h Volume: 2780248.29, Quote Volume: 3086368.37099
Updated ticker for ETH/USDT at 2024-09-23T03:28:20.878: 24h Volume: 256902.9913, Quote Volume: 665119690.637989
Updated ticker for ACE/USDT at 2024-09-23T03:28:20.132: 24h Volume: 5055314.9, Quote Volume: 12309279.7402
Updated ticker for YGG/USDT at 2024-09-23T03:28:20.648: 24h Volume: 12886962.9, Quote Volume: 5708614.84101
Time limit of 10 seconds reached. Exiting...
Received updates for 218 out of 299 symbols.
Total # of errors: 549
```

So there are hundreds of errors such as:

```console
Error watching ticker for XRP/USDT: Connection closed by remote server, closing code 1008
```

On the other hand, setting `MAX_SYMBOLS` to 200 symbols, it runs error-free:

```console
...
Updated ticker for VOXEL/USDT at 2024-09-23T04:01:04.583: 24h Volume: 29606592.1, Quote Volume: 4949670.439
Updated ticker for FIL/USDT at 2024-09-23T04:01:04.593: 24h Volume: 4411294.54, Quote Volume: 16410401.62344
Updated ticker for LUNC/USDT at 2024-09-23T04:01:04.078: 24h Volume: 88597109223.27, Quote Volume: 7451232.10869441
Time limit of 10 seconds reached. Exiting...
Received updates for 168 out of 200 symbols.
Total # of errors: 0
```
