### ISSUE TITLE
Poloniex -- trade history issues

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#608] opened 2017-11-16 12:31 UTC
For startes, when manually using:

```
            trade_history = await exchange.private_post_returntradehistory(
                {
                    'currencyPair': 'all',
                    'start': start,
                    'limit':
                        10000,  # this is the maximum that they allow, if not specified then it is 500
                }
            )
```

and parsing the results; 

```
 {'amount': '1.xxxxxx',
  'category': 'exchange',
  'date': '<redacted>',
  'fee': '0.00250000',
  'globalTradeID': <int redacted>,
  'orderNumber': '<int redacted>',
  'rate': '<float redacted>',
  'total': '<float redacted>',
  'tradeID': '<int redacted>',
  'type': 'buy'}]
```

your function parse_order in poloniex fails miserably. I'm not sure is it the same with open orders. Using the ```fetch_closed_orders``` isn't working on Poloniex at all (at least for me with default settings). Can you please provide some example usecase, and setup if market=None to fetch all currencyPairs. 

Furthermore:
```python 
    def parse_order(self, order, market=None):

...
        if market:
            symbol = market['symbol']
```

Isn't what I expected to see the least, name it parse_market or something like that (I assumed it meant force market to be x. Also I recommend naming it symbol since it's in the rest of the API, as well as many exchanges APIs)

**Comment by nmiculinic** [comment] 2017-11-16 12:45
If I'm using default fetch_close_orders it cannot find any order

**Comment by nmiculinic** [comment] 2017-11-16 12:46
I see why:
```    async def fetch_orders(self, symbol=None, since=None, limit=None, params={}):
```
is lying...It's only fetching OpenOrders

**Comment by nmiculinic** [comment] 2017-11-16 12:54
I've looked over unified API
```
createOrder (symbol, type, side, amount[, price[, params]])
createLimitBuyOrder (symbol, amount, price[, params])
createLimitSellOrder (symbol, amount, price[, params])
createMarketBuyOrder (symbol, amount[, params])
createMarketSellOrder (symbol, amount[, params])
cancelOrder (id[, symbol[, params]])
fetchOrder (id[, symbol[, params]])
fetchOrders ([symbol[, params]])
fetchOpenOrders ([symbol[, params]])
fetchClosedOrders ([symbol[, params]])
```

I propose changing it to:

```
createLimitBuyOrder (symbol, amount, price[, params])
createLimitSellOrder (symbol, amount, price[, params])
createMarketBuyOrder (symbol, amount[, params])
createMarketSellOrder (symbol, amount[, params])
cancelOrder (id: str)
fetchOrder (id: str)
fetchOrders (ids: List[str])
fetchAllOrders(symbol: Optional[str])
fetchOpenOrders (symbol: Optional[str])
fetchClosedOrders (symbol: Optional[str])
```

(I'm using python3 type hinting, which I cannot recommend more.)

Fetch Order should only accept id. FetchOrders in previous API is unclear what exactly is doing? Replace it with fetchAllOrders to be explicit in fetching both open and closed orders.

Also internally I'm passing order output through https://pypi.python.org/pypi/voluptuous schema..I recommend doing the same here since it will fail loudly in case of error:
```python
    order_schema = voluptuous.Schema({
        'id':
            str,
        'datetime':
            arrow.get,
        'status':
            voluptuous.validators.In({'open', 'closed', 'canceled'}),
        'symbol':
            str,
        voluptuous.Optional('type'):
            voluptuous.validators.In({'limit', 'market'}),
        'side':
            voluptuous.validators.In(['buy', 'sell']),
        'price':
            voluptuous.Coerce(float),
        'amount':
            voluptuous.Coerce(float),
        voluptuous.Optional('filled'):
            voluptuous.Coerce(float),
        voluptuous.Optional('remaining'):
            voluptuous.Coerce(float),
    },
                                          extra=voluptuous.ALLOW_EXTRA,
                                          required=True)

```

I'm using voluptuous.ALLOW_EXTRA, but you shouldn't. This is mostly for my purposes. I recommend formalizing this schema https://github.com/ccxt/ccxt/wiki/Manual#order-structure , and you use it as:

```python
    return order_schema(order)
```

It will be pretty loud on violation (read raise exception)

**Comment by kroitor** [comment] 2017-11-16 18:08
Hi!

> For startes, when manually using private_post_returntradehistory and parsing the results your function parse_order in poloniex fails miserably.

The parse_order function should not be used for parsing trades. A trade is not the same as the order. So, to parse trades, you need to call parse_trade.

> Using the fetch_closed_orders isn't working on Poloniex at all (at least for me with default settings). 

1. Poloniex does not offer a method for fetching ( closed orders / all orders ) at all. It inly has "open orders" API endpoint.
2. Our users asked us to emulate fetch_closed_orders by using an order_cache, that is invalidated via fetch_open_orders. 
3. When an order is placed it gets cached (if it was placed by the unified API call to create_order).
4. If the order was not placed by ccxt (own order), it does not get cached and there's no practical way ccxt can find about it from poloniex.
5. The order cache is exposed in the `.orders` property, so a user can serialize and deserialize it between the runs to save the order history.
6. From this perspective, we are choosing between
   a) not implementing an fetch_closed_orders API for Poloniex at all (why would we throw it away?)
   b) or emulating it with at least some methods that are available with Poloniex (we choose this case).
7. The order cache only works with the unified API, so if you're using custom Polo methods like you do with private_post_returntradehistory, you can't parse it with functions from the unified API. Moreover, the correct parsing function is `parse_order` for orders, `parse_trade` for trades.

> Can you please provide some example usecase, and setup if market=None to fetch all currencyPairs.

Can you please provide some example usecase, and setup if market=None to fetch all currencyPairs.

```
# examples
symbol=None
poloniex.fetch_my_trades (symbol)
poloniex.fetch_open_orders (symbol)
poloniex.fetch_closed_orders (symbol)
poloniex.fetch_orders (symbol)
poloniex.private_post_returntradehistory ({
    'currencyPair': 'all',
    ...
})
poloniex.private_post_returnopenorders ({
    'currencyPair': 'all',
    ...
})
```

> Furthermore parse_order(self, order, market=None), isn't what I expected to see the least, name it parse_market or something like that.

Why would I name the function **for parsing an order** structure `parse_market` ? I think `parse_order` is the most suitable name for this kind of task.

> If I'm using default fetch_close_orders it cannot find any order

That's because of point 4 above.

> I see why: fetch_orders() is lying...It's only fetching OpenOrders

It doesn't lie, you either have it (use it), or not have it at all (because Poloniex doesn't offer a better way to fetch all orders, see point 1).

> (I assumed it meant force market to be x. Also I recommend naming it symbol since it's in the rest of the API, as well as many exchanges APIs)

Those particular lines are doing the other kind of job, actually...

> I've looked over unified API, I propose changing it to:

> cancelOrder (id: str)

Cannot remove symbol from there, because many exchanges require it even for cancelling an order by known id. They still demand a submitted symbol.

> Fetch Order should only accept id. 

Nope, it should also allow to pass the symbol, otherwise it won't work with several exchanges at all.

> fetchOrder (id: str)
> fetchOrders (ids: List[str])

Same reasoning, can't remove symbol from these methods, a lot of exchanges **require** it. There are exchanges that require the symbol, even when you are fetching an order by a particular id.

> fetchAllOrders(symbol: Optional[str])
> fetchOpenOrders (symbol: Optional[str])
> fetchClosedOrders (symbol: Optional[str])

Can't remove the since and limit params from these methods, because many exchanges allow "scrolling" through partial history.

> FetchOrders in previous API is unclear what exactly is doing?

Mm.... Fetching orders? If there's no indication on closed or open orders in the method name, I guess, it means "fetch all". We can rename it to fetchAllOrders.

> I'm using python3 type hinting, which I cannot recommend more.
> Also internally I'm passing order output through https://pypi.python.org/pypi/voluptuous schema.

We are going to add Python type hinting for that. Thx for the advice.

More info on the above Poloniex issues is here:

https://github.com/ccxt/ccxt/issues/96
https://github.com/ccxt/ccxt/pull/102
https://github.com/ccxt/ccxt/issues/569 ← we're about to rework the order cache here
https://github.com/ccxt/ccxt/issues/304#issuecomment-335508927

I would close this issue as somewhat duplicate of the above, If you don't mind. To me it looks like most of your questions come from the fact that you are mixing the usage of custom Poloniex API with the unified API. You should probably stick to either this or that. Feel free to ask if you have any remaining questions. 

Thank you!

**Closed by kroitor** 2017-11-16 18:08 UTC
Labels: duplicate, question

**Comment by kroitor** [comment] 2017-11-17 02:07
```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
>>> import ccxt
>>> ccxt.poloniex().has
{'fetchClosedOrders': 'emulated', 'fetchOpenOrders': True, 'fetchOrders': 'emulated', 'fetchTickers': True, 'fetchOHLCV': True, 'withdraw': True, 'fetchOrder': 'emulated', 'fetchMyTrades': True}
>>> 
```
