### ISSUE TITLE
Polling Binance fetchTickers every 5 seconds triggers a ban

### ISSUE THREAD

**Issue by deltacat** [ccxt/ccxt#1027] opened 2018-01-02 09:15 UTC
I tried use param {enableRateLimit: true} to handle rate limit.
A strange thing about 'binance': when I call fetchTickers() to polling tickers (e.g., every 5 seconds), it will throw an error 
`{"code":-1003,"msg":"Way too many requests; IP banned until 1514883415037."}`
This should not happened, 5 seconds should not trigger limit. Is there some extra info to explain this? I tried find information from ccxt and binance api docs, no idea.

Ref to: #929

**Comment by kroitor** [comment] 2018-01-02 12:25
Hi!

Binance uses a Machine Learning rate-limiting algorithm that scores your requests against an *average user* and accounts for the *weight* of each call.

From Binance: 
> For users who are having issues with temporary trading bans:
> Our risk management system is a machine learning system; there are no "hard rules" we can give you to follow. Trading behavior is evaluted against the "average user" and if you deviate too far, you'll get a trading ban ranging from 5 minutes to 3 days.
> To help you understand how the system works: imagine there's an "abuse score".
> Your abuse score goes up if:
> 1) You front run the book.
> 2) You spam orders/cancels very quickly without trading.
> 3) Your "conversation rate" is low; "conversation rate" is 'numTrades / (orders + cancels)' over 24hours.
> 4) Your "weight" is low; "weight" is 'totalTradedQty / (orders + cancels)' over 24hours.
> 5) When trading on symbols that have BNB as the base or quote asset, the amount of abuse score you get for deviating from the norm on the above is amplified.
> This is not a complete/exhaustive list of the metrics evaluted, but this should help point you in the right direction.

```
Ninj0r, [04.12.17 10:44]
You're rated against "average user"

Ninj0r, [04.12.17 10:44]
and how far you deviate.

Ninj0r, [04.12.17 10:44]
So there's no "You can X in Y amount of time"

Ninj0r, [04.12.17 10:44]
it's an ML algo

Igor Kroitor, [04.12.17 10:45]
yes, I understand what machine learning is, of course, but is there a practically-deduced limit that we can use to protect ourselves from getting banned (if that happens)?

Ninj0r, [04.12.17 12:48]
Past the guidelines I gave in the API, no. That's what we can offer at this time.
```

Next, if you go here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics

You will notice that they have a special weight for the "all tickers" endpoint:

![binance-api-docs](https://user-images.githubusercontent.com/1294454/34483625-ce013d3a-efd0-11e7-895e-f51d8cb21d79.jpg)

They say, that if you're fetching all tickers, the rate limit should be multiplies by the amount of active traded symbols. They have **234** active symbols, so, it looks like you should not be polling their tickers more than once in 234 seconds. Unfortunately, there isn't an easy workaround for this, if you're mixing your requests. If you are only doing one type of `fetchTickers()` request, then you can raise the rateLimit to 234 000 milliseconds (once in 234 seconds).

Let me know if this answers your question or not.

**Comment by deltacat** [comment] 2018-01-02 12:47
Thanks a lot. This answer is very clear.

But it means watching prices of binance would be a big problem. :(

**Comment by kroitor** [comment] 2018-01-02 12:49
@deltacat yes, indeed. We can't really work around this on client side. I'm closing this for now, if you don't mind. Feel free to reopen it if needed, or just ask questions, if you have any. Thx!

**Closed by kroitor** 2018-01-02 12:49 UTC
Labels: question

**Comment by eMDi101** [comment] 2018-01-03 23:23
Hi,
I just want to switch to this library and now I have the same error.
Before I used the python-binance library of sammchardy and I could call up tickers in 0.5 seconds without any problems.

https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L358

Cheers

**Comment by kroitor** [comment] 2018-01-03 23:35
Hi, @eMDi101 ! Thanks for the notice!
The thing is: we are talking of the `allBookTickers` endpoint.
The library of sammchardy uses the `allPrices` endpoint – that one does not return full info, it will output price info only, without 24h ohlcv.

Now, in ccxt we support both endpoints, the `allBookTickers` + the `allPrices` as well, but for the tickers we use `allBookTickers` by default beause it gives us 24h stats – that is more than just prices: https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L98

Next, if you look here carefully through each endpoint here:
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#24hr-ticker-price-change-statistics
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-price-ticker
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-order-book-ticker

You will quickly notice two things:
1. Both `allPrices` and `allBookTickers` are now renamed to new endpoints, thefore both ccxt and sammchardy are outdated, but we are working on the update (will be there in several hours).
2. The rate limiting for 24h stats is much more restrictive that for price-only tickers. This explains the difference that you were asking about.

We are also going to switch to price-only tickers by default for Binance in one of the upcoming releases. Will update you here.

**Comment by hippylover** [comment] 2018-01-12 14:31
Hi, just read this thread. It would be nice if you had the same data returned for every call so it's easier for a user to know what a call returns. If that is not possible or comes with limitations on one exchange you can have a function, eg:
`ccxt.quirks()
...
 binance, fetchTickers: Due to rate-limits in binance it's only possible to call this every 234 seconds, if you only need price data you can use ...`

or something like that(you know this the best).

I imagine you'll get a lot of these quirks and it'll be impossible to get everything into calls that always return the same things, but you shouldnt actively try to make calls return different data depending on exchange because then it'll be 10x harder to make good use of your "unified" api.

However if you have a function called quirks or whatever, everyone can more easily work around those quirks when they have to appear because of exchange weirdness and everyone will know exactly which functions are perfect and which ones are not.

My 5 c.

**Comment by kroitor** [comment] 2018-01-12 14:35
Thanks a lot, I'll definitely take that into consideration, of course, however, the problem is not that I don't know what to do, but that I don't have enough time to do it all on my own, you see ;)

**Comment by hippylover** [comment] 2018-01-12 14:37
Haha. I know your pain. Trust me. It's an insanely ambitious project(please just focus on python support wink wink nudge nudge).

I might help you out in the future but only with python stuff because that's the only language i know XD.

**Comment by hippylover** [comment] 2018-01-12 14:42
Anyway, i hope i made my point clear(sometimes i think i can't express myself clearly enough). What i mean is that function x should always return output y so a programmer writing code for multiple exchanges know what to expect.

If that can't be supported with exchange r, then mention their way of doing things as a note in quirks.

**Comment by kroitor** [comment] 2018-01-12 14:47
@hippylover yeah, that's clear, thx. We are already adding the so-called *"metainfo"* for that. That includes such exchange properties as `.has`, `.requires`, and some other... And we are expanding the set of descriptive properties as well.

Btw, if you read and try what's written here, literally:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
↑ you'll be surprised to find out that you actually know how to code not just in Python, but easily code in four languages at once, wink-wink. We will be happy for all contributions.

**Comment by hippylover** [comment] 2018-01-12 14:48
Haha, i'll take a look.

**Comment by orkenstein** [comment] 2018-01-17 11:11
@kroitor how to contact Binance tech team? Especially Ninj0r?

**Comment by kroitor** [comment] 2018-01-17 11:18
@orkenstein use their telegram chat channel

**Comment by orkenstein** [comment] 2018-01-17 11:26
@kroitor what's its name? @binance_support is a channel now:

> Most issues can be resolved with the relevant FAQ articles at support.binance.com .
> If you still need help, Please submit your support request using the following link.  Selecting the correct issue type will expedite the support process.
> https://support.binance.com/hc/en-us/requests/new
> - Binance Support Team

[Reddit](https://www.reddit.com/r/binance/comments/7p4cgj/how_do_i_access_the_binance_support_channel_on/) says:
> Telegram support channel was closed recently.

**Comment by kroitor** [comment] 2018-01-17 11:27
@orkenstein https://t.me/binance_api_english
