### ISSUE TITLE
watchOrderBooks('SOL/USDC:USDC') Promise won't resolve due to different product ID. 

### ISSUE THREAD

**Issue by Gsuz** [ccxt/ccxt#22157] opened 2024-04-15 12:58 UTC
### Operating System

mac os 

### Programming Languages

JavaScript

### CCXT Version

4.2.96

### Description

There seems to still be some sort of alias issue with coinbase markets. I'm listening to perp market with symbol
 SOL/USDC:USDC
It has an Id of SOL-PERP-INTX as seen in the screenshot. My promise is never resolved. I also tried using SOL-PERP-INTX as the symbol which still won't resolve my promise. 

![Screenshot 2024-04-15 at 12 49 31](https://github.com/ccxt/ccxt/assets/310239/242caf3e-94f8-473c-9ae6-e13527a01832)

### Code

```
        logger.info(`Watching coinbase orderbook for ${symbol}`)
          this.exchange.verbose = true
          const orderbook = await this.exchange.watchOrderBook(symbol)
          logger.info('orderbook received')

```

**Comment by carlosmiei** [comment] 2024-04-15 13:07
Hello @Gsuz, thanks for reporting it, will take a look asap.

**Comment by carlosmiei** [comment] 2024-04-15 13:32
@Gsuz Can you please post the message that coinbase sends to you? I'm seeing a weird "ack" with empty subscriptions

```
2024-04-15T13:31:49.355Z onOpen
2024-04-15T13:31:49.357Z sending {
  type: 'subscribe',
  product_ids: [ 'SOL-PERP-INTX' ],
  channel: 'level2',
  api_key: 'Y2sIJQvfrNSrWuoW',
  timestamp: '1713187908',
  signature: 'd55889500cb6c8810adb4b692c98c0bf920e299d10ff266f5a63e6ce458e4a95'
}
2024-04-15T13:31:49.470Z onMessage {
  channel: 'subscriptions',
  client_id: '',
  timestamp: '2024-04-15T13:31:49.434453347Z',
  sequence_num: 0,
  events: [ { subscriptions: {} } ]
}
```

**Comment by Gsuz** [comment] 2024-04-15 13:44
same -> 

```
2024-04-15T13:42:17.022Z onMessage {
  channel: 'subscriptions',
  client_id: '',
  timestamp: '2024-04-15T13:42:17.015753044Z',
  sequence_num: 0,
  events: [ { subscriptions: {} } ]
}
```

**Comment by carlosmiei** [comment] 2024-04-15 14:25
@Gsuz I will reach out to them to check if there's any issue with perps over WS.

**Comment by carlosmiei** [comment] 2024-04-15 21:51
@Gsuz They just confirmed that futures over WS is a work in progress.

**Comment by Gsuz** [comment] 2024-04-16 00:14
thank you that explains it.

**Comment by carlosmiei** [comment] 2024-04-16 09:25
@Gsuz Since this is not directly related to CCXT I'm going to close the issue, but feel free to reopen it if anything

**Closed by carlosmiei** 2024-04-16 09:25 UTC
Labels: bug
