### ISSUE TITLE
SSL problem  ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo

### ISSUE THREAD

**Issue by xianhaiGitHub** [ccxt/ccxt#9234] opened 2021-05-23 07:51 UTC
- OS: win 10 
- Programming Language version: python 3.8
- CCXT version: 1.50.24
 -  pip version: 21.1.1
 - 
 when i use ccxt to fetch binance exchange data  meet the error on below：
and i use VPN lantern to connect internet，but have this problem 
```
`binance_exchange = ccxt.binance({
    'apiKey': 'FUgqKtAvxxxxxxxxxxxxxxx4k4kzNwHcJw8g1FGCb2YYB0mkQEqeGzDNeuiJHbxlzqbkSHfYf',
    'secret': 'n5gqnfvyeGxxxxxxxxxxxxxxx4mRUkFBp4DacHijYiDxZDAmaoOcWzzcnEC4bltwCbeuTkrJwuq',
    'timeout': 30000,
    'enableRateLimit': True,
})
print(binance_exchange.fetch_markets())`




**requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))**
```
**more error info like this**：
`D:\PythonProject\venv\Scripts\python.exe D:/FQT/cryptocurrency/BitTrading.py
['aax', 'aofex', 'ascendex', 'bequant', 'bibox', 'bigone', 'binance', 'binanceus', 'bit2c', 'bitbank', 'bitbay', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitforex', 'bitget', 'bithumb', 'bitkk', 'bitmart', 'bitmex', 'bitpanda', 'bitso', 'bitstamp', 'bitstamp1', 'bittrex', 'bitvavo', 'bitz', 'bl3p', 'braziliex', 'btcalpha', 'btcbox', 'btcmarkets', 'btctradeua', 'btcturk', 'buda', 'bw', 'bybit', 'bytetrade', 'cdax', 'cex', 'coinbase', 'coinbaseprime', 'coinbasepro', 'coincheck', 'coinegg', 'coinex', 'coinfalcon', 'coinfloor', 'coingi', 'coinmarketcap', 'coinmate', 'coinone', 'coinspot', 'crex24', 'currencycom', 'delta', 'deribit', 'digifinex', 'equos', 'eterbase', 'exmo', 'exx', 'fcoin', 'fcoinjp', 'flowbtc', 'foxbit', 'ftx', 'gateio', 'gemini', 'gopax', 'hbtc', 'hitbtc', 'hollaex', 'huobijp', 'huobipro', 'idex', 'independentreserve', 'indodax', 'itbit', 'kraken', 'kucoin', 'kuna', 'lakebtc', 'latoken', 'lbank', 'liquid', 'luno', 'lykke', 'mercado', 'mixcoins', 'ndax', 'novadax', 'oceanex', 'okcoin', 'okex', 'paymium', 'phemex', 'poloniex', 'probit', 'qtrade', 'rightbtc', 'ripio', 'southxchange', 'stex', 'surbitcoin', 'therock', 'tidebit', 'tidex', 'timex', 'upbit', 'vbtc', 'vcc', 'wavesexchange', 'whitebit', 'xbtce', 'xena', 'yobit', 'zaif', 'zb']
Traceback (most recent call last):
  File "D:\PythonProject\venv\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\PythonProject\venv\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\PythonProject\venv\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\PythonProject\venv\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\PythonProject\venv\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\PythonProject\venv\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\pc\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\pc\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\pc\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PythonProject\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\PythonProject\venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\PythonProject\venv\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    response = self.session.request(
  File "D:\PythonProject\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PythonProject\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\PythonProject\venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/FQT/cryptocurrency/BitTrading.py", line 47, in <module>
    print(binance_exchange.fetch_markets())
  File "D:\PythonProject\venv\lib\site-packages\ccxt\binance.py", line 829, in fetch_markets
    response = getattr(self, method)(query)
  File "D:\PythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 474, in inner
    return entry(_self, **inner_kwargs)
  File "D:\PythonProject\venv\lib\site-packages\ccxt\binance.py", line 2975, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "D:\PythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 495, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\PythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 632, in fetch
    raise NetworkError(details) from e
**### ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo**

Process finished with exit code 1

``
here is my debug,and when i use broswer to query data, that is ok
![image](https://user-images.githubusercontent.com/26544622/119263922-9e3b0280-bc13-11eb-92c7-9247c39afa5b.png)

![image](https://user-images.githubusercontent.com/26544622/119264036-21f4ef00-bc14-11eb-9d81-e5fff58cbe52.png)

**Comment by kroitor** [comment] 2021-05-23 15:34
> and i use VPN lantern to connect internet，but have this problem

This error `Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))` says that your proxy is not available, are you sure you have the VPN properly configured?

**Comment by xianhaiGitHub** [comment] 2021-05-23 15:41
i 

> > and i use VPN lantern to connect internet，but have this problem
> 
> This error `Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))` says that your proxy is not available, are you sure you have the VPN properly configured?
i use lantern ,and i can use youtube.com  and goolgle  in China,but i don't no why have this error ,
![image](https://user-images.githubusercontent.com/26544622/119267219-28896380-bc20-11eb-85ff-0b317e53b958.png)

**Comment by SailorChina** [comment] 2021-09-08 06:09
同样的问题，我也连不上

**Comment by MrChenGG** [comment] 2021-10-19 07:29
我也遇到这个问题 有人解决这个问题了吗？

**Comment by conseb** [comment] 2021-12-17 07:17
用vs运行一下试试呢，我的pycharm显示同样的错误。vs就可以

**Comment by inewplay** [comment] 2022-03-23 08:13
没有，现在这个问题我也卡住了

**Comment by angdychen** [comment] 2022-08-22 01:50
add ccxt proxies, ex.

exchange = ccxt.binance({
    'proxies': {
        'http': 'socks5://localhost:8659',
        'https': 'socks5h://localhost:8659',
    },
})

you should change the port no(ex. 8659) according to your VPN port no

**Comment by danielgxm** [comment] 2022-10-14 12:31
> add ccxt proxies, ex.
> 
> > exchange = ccxt.binance({
> > 'proxies': {
> > 'http': 'socks5://localhost:8659',
> > 'https': 'socks5h://localhost:8659',
> > },
> > })
> 
> you should change the port no(ex. 8659) according to your VPN port no

thank you!

**Comment by jakehockey10** [comment] 2022-12-02 01:55
I am receiving this same error when I use version 2.2.49.  But if I use version 2.2.39, I don't get this error.

**Comment by pengfengyong** [comment] 2024-06-17 09:24
> add ccxt proxies, ex.
> 
> > exchange = ccxt.binance({
> > 'proxies': {
> > 'http': 'socks5://localhost:8659',
> > 'https': 'socks5h://localhost:8659',
> > },
> > })
> 
> you should change the port no(ex. 8659) according to your VPN port no

very good

**Comment by ttodua** [comment] 2024-08-16 14:01
i'll close this topic, but if anyone has any specific issues, feel free to open

**Closed by ttodua** 2024-08-16 14:01 UTC
Labels: bug
