### ISSUE TITLE
Bitfinex margin info errors on both bitfinex.py and bitfinex2.py

### ISSUE THREAD

**Issue by jdieks** [ccxt/ccxt#5247] opened 2019-06-05 19:31 UTC
- OS: *
- Programming Language version: ptyhon
- CCXT version: 593 and newer
- Exchange: bitfinex + bitfinex2
- Method: bitfinex.private_post_margin_infos & bitfinex2.privatePostAuthRInfoMarginKey

Hi,

So I'm running into a weird issue.
I setup bitfinex with bitfinex = ccxt.bitfinex()
then I setup the keys.

I try to get the margin balance, so I use this code:
```Python
account_balance = bitfinex.private_post_margin_infos()[0]['margin_balance']
```

For my old bitfinex account this just works, but if I create a new one (or other users try my code and create a new account) they run into this error: 
```
bitfinex https://api.bitfinex.com/v1/margin_infos POST 500 Server Error: Internal Server Error for url: https://api.bitfinex.com/v1/margin_infos 
```
I really can't get my head around why it works with my key that's a year old or so and not with new keys. Bitfinex themselves are looking into this issue too, do you guys think it's a bug on their side?

The second issue I'm having is with the bitfinex2 code. Because bitfinex.py is not working I'm trying this as the exception:
```Python
bitfinex2.privatePostAuthRInfoMarginKey()
```
But the response I'm getting is this:
```
bitfinex2 https://api.bitfinex.com/v2/auth/r/info/margin/{key} POST 500 Server Error: Internal Server Error for url: https://api.bitfinex.com/v2/auth/r/info/margin/%7Bkey%7D ["error",10020,"key: invalid"]
```
Is this an error on my side or is this an error on the bitfinex side?

Thanks for the help and the advice!! :)

**Comment by jdieks** [comment] 2019-06-05 19:43
I probably need to add that if I use this way of calling the function (I think that's how the manual says it should work):
bitfinex2.privatePostAuthRInfoMarginKey({ key: str(bitfinex2.apiKey) })
I get this error:
"name 'key' is not defined"

**Comment by kroitor** [comment] 2019-06-05 19:43
The second one is definitely an issue on your side. You're not [passing parameters](https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods) properly when using [implicit methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods)

If you look at the URL: `https://api.bitfinex.com/v2/auth/r/info/margin/{key}` ← this `{key}` should be substituted for a `key` parameter, according to bitfinex v2 docs (this is exchange-specific). The `key` should contain a value of the currency id (see the [explanation of symbols vs ids here](https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids)).

Also, you should be using the [rate-limiting](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit).

So, the second issue is solved easily if you follow the Manual precisely:

```Python
from pprint import pprint
import ccxt
exchange = ccxt.bitfinex2 ({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

exchange.load_markets()  # load symbols, currencies and ids

currency = exchange.currencies['USD']

request = {
    'key': currency['id']
}

# exchange.verbose = True  # uncomment this to see the verbose request/response

response = exchange.privatePostAuthRInfoMarginKey(request)
pprint(response)
```

Also, when posting code or error output here, please, follow the guides precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Use [markdown](https://guides.github.com/features/mastering-markdown/) for readability, surround your code and output with triple backticks  (&#096;&#096;&#096;):

&#096;&#096;&#096;Python
your code
&#096;&#096;&#096;

&#096;&#096;&#096;
your output
&#096;&#096;&#096;

**Comment by jdieks** [comment] 2019-06-05 19:49
Hi kroitor,

Thanks for the very quick response!
I did read the manual multiple times, but i think I misunderstood the "key" in this second effort indeed, like you say above.

I will try what you wrote above and will report back..

why the bitfinex.py is not working for new keys is beyond me though.. Hope you understand.

Just for information, I am rate limiting.. I have build my own rate limiter, but using that one or turning the one in ccxt on does not seem to make a difference..

**Comment by kroitor** [comment] 2019-06-05 19:57
> why the bitfinex.py is not working for new keys is beyond me though.. Hope you understand.

Have you looked into permissions for that key? Have you asked your users how they have set up their permissions on their keys?

![Screen-Shot-2019-06-05-at-22 53 08](https://user-images.githubusercontent.com/1294454/58985894-fb4e0b80-87e4-11e9-8826-6ec5ddbc9f43.jpg)

**Comment by jdieks** [comment] 2019-06-05 20:55
Hi Kroitor,

I'm still testing the bitfinex2 option which is harder to get to work than I though.. 

```Python
bitfinex2.load_markets()
code = 'USD'
currency = bitfinex.currencies[code]
request = {
                      'key': currency['id'] 
                    }
account_balance = bitfinex2.privatePostAuthRInfoMarginKey(request)
```
does:
```
bitfinex2 https://api.bitfinex.com/v2/auth/r/info/margin/USD POST 500 Server Error: Internal Server Error for url: https://api.bitfinex.com/v2/auth/r/info/margin/USD ["error",10020,"key: invalid"]
```

If I set the code to 'BTC' I get the same result.


To answer your question above,  we did not try with withdraw activated till a couple of minutes ago because my own key does not have that either.
We did try it now with the same results I posted in the first post (POST 500 error)

I'm starting to think this really is an issue on their end...

**Comment by kroitor** [comment] 2019-06-05 21:05
@jdieks 

> does:
> `bitfinex2 https://api.bitfinex.com/v2/auth/r/info/margin/USD POST 500 Server Error: Internal Server Error for url: https://api.bitfinex.com/v2/auth/r/info/margin/USD ["error",10020,"key: invalid"]`

The proper url should've been https://api.bitfinex.com/v2/auth/r/info/margin/fUSD, not https://api.bitfinex.com/v2/auth/r/info/margin/USD, because the id is `fUSD`, not `USD`.


```Python
# I suppose that the initialization code is the same on your side

exchange.load_markets()  # load symbols, currencies and ids
code = 'USD'  # set your unified currency code here
currency = exchange.currencies[code]
request = {
    'key': currency['id']  # ← this line gets the id fUSD by unified code USD
}
print('Request:')
pprint(request)
response = exchange.privatePostAuthRInfoMarginKey(request)
print('Response:')
pprint(response)
```

Alternatively:

```Python
# ...
request = {
    'key': 'fBTC',  # specify the id directly, fBTC, fUSD, etc..
}
print('Request:')
pprint(request)
response = exchange.privatePostAuthRInfoMarginKey(request)
print('Response:')
pprint(response)
```

I will check that on my side... for some reason bitfinex is not accessible from my location atm... looks like you did break it ))

**Comment by jdieks** [comment] 2019-06-05 21:10
haha, oh boy.. 
I did indeed read the fUSD in the print of the symbols but it was indeed not in the url.
I will place it there manually just to test..

**Comment by kroitor** [comment] 2019-06-05 21:10
Ok, now i have reproduced it on my side...

<img width="853" alt="Screen Shot 2019-06-06 at 00 07 49" src="https://user-images.githubusercontent.com/1294454/58990693-2c333e00-87ef-11e9-93a1-9b80df76486a.png">

@jdieks looks like you're right, other endpoints like fetch_balance do work normally... So it is likely on the exchange side...

**Comment by jdieks** [comment] 2019-06-05 21:13
Do you think it's wise if I send this conversation to bitfinex support?

**Comment by kroitor** [comment] 2019-06-05 21:16
I tried with other values for "key" as well, and it still says that the key is invalid. And it doesn't mean the apiKey, it means the key from the query. Apparently, something in the v2 is broken. Because it's still a beta. Most likely they will not reply or will reply: "it's a beta".

I've tried `private_post_margin_infos()` with v1 and it works on my side (v1 is "stable", not "beta"):

<img width="859" alt="Screen Shot 2019-06-06 at 00 13 36" src="https://user-images.githubusercontent.com/1294454/58991066-107c6780-87f0-11e9-8b3d-90a066c5f10c.png">

<img width="855" alt="Screen Shot 2019-06-06 at 00 15 33" src="https://user-images.githubusercontent.com/1294454/58991158-3bff5200-87f0-11e9-9876-1ce44f48a921.png">

**Comment by jdieks** [comment] 2019-06-05 21:18
So the first issue I was having is that indeed in exactly the same code my key for the v1 works.
But a key for a new account does not work. If you like, maybe we can give you a test key in private of a new account that's tested not to work.

**Comment by kroitor** [comment] 2019-06-05 21:21
> But a key for a new account does not work.

Have you checked the permissions for the new key? It should have margin read and write enabled (`private_post_key_info()`).

```
mbp:ccxt igorkroitor$ python examples/py/cli.py bitfinex private_post_key_info
{u'account': {u'read': True, u'write': False},
 u'funding': {u'read': True, u'write': True},
 u'history': {u'read': True, u'write': False},
 u'orders': {u'read': True, u'write': True},
 u'positions': {u'read': True, u'write': True},
 u'wallets': {u'read': True, u'write': True},
 u'withdraw': {u'read': False, u'write': True}}
mbp:ccxt igorkroitor$
```

**Comment by jdieks** [comment] 2019-06-05 21:31
![image](https://user-images.githubusercontent.com/31446949/58991990-e32cbb00-87e9-11e9-91aa-37a3c5b0c6ef.png)
These are the settings we are currently testing with..

This is his personal account, but we have also made a new test account with a key I just tested and it doesn't work either.

Since It's a test account without any money I can share the key with you if you like

**Comment by kroitor** [comment] 2019-06-05 21:32
> Since It's a test account without any money I can share the key with you if you like

If that key doesn't work for you, it won't make a difference if I try it on my side most likely... I'll try with a new key on my side first.

**Comment by jdieks** [comment] 2019-06-05 21:33
well on my account a new key works.. but on a totally new account it seems to give issues

**Comment by kroitor** [comment] 2019-06-05 21:37
> but on a totally new account it seems to give issues

Let's make it a bit more clear – you have tried personally to create a new account, passed the signup, created the new key there, made sure the permissions are correct, and it doesn't work, is that right? I mean, you've witnessed this yourself and I don't have to reproduce this procedure to check for that, right? Or does that other account belong to someone else?

**Comment by jdieks** [comment] 2019-06-05 21:39
OK.. I see your point. The other accounts do belong to someone I trust very much but I did indeed not make them myself.
I did see a lot of screenshots.
It's getting late, but I will make an account myself to check that tomorrow morning and report back..

**Comment by kroitor** [comment] 2019-06-05 21:40
> It's getting late, but I will make an account myself to check that tomorrow morning and report back..

Ok, I'd be happy if you let me know whether you resolved it or not, if it doesn't work on a new account, we'll think further...

**Comment by kroitor** [comment] 2019-06-05 21:42
It does work with a new key on my side, so, I believe, this is key-specific or account-specific.

**Comment by jdieks** [comment] 2019-06-05 21:49
OK I have actually just tested a new account. The timezone is set to Amsterdam (might make a difference for a server it runs on I guess).
![image](https://user-images.githubusercontent.com/31446949/58992980-81ba1b80-87ec-11e9-9ef4-6c205dbd9b08.png)

I do indeed get the same server error..

**Comment by kroitor** [comment] 2019-06-05 21:52
> I do indeed get the same server error..

Got it, thx for reporting back, really appreciate it! Looks like it's indeed on the exchange's side. If you have an open ticket with Bitfinex, you can post links to this discussion there if that helps.

**Comment by jdieks** [comment] 2019-06-05 21:54
Yeah I think that's the wisest thing to do. The other person indeed has an open ticket. I will ask him to refer to this thread.

I will report back if we have news.

**Comment by kroitor** [comment] 2019-06-05 21:57
@jdieks another common reason for that type of behavior with exchanges – is that margin wallet initialization can take place after moving some funds to the margin account. However, I cannot test it with a new account right away. And this may be a waste of time after all, if the issue is somewhere deeper in their system.

**Comment by jdieks** [comment] 2019-06-06 10:21
Bitfinex actually already answered: 
```
Yes we have actually identified the issue. It does seem to be related to the age of the account (I.E newer accounts are experiencing this issue). 

A patch will be rolled out tomorrow. Thanks for the detailed issue analysis. 
```

**Comment by kroitor** [comment] 2019-06-06 17:36
Thx for reporting @jdieks ! Very helpful!

**Comment by kroitor** [comment] 2019-06-08 00:31
@jdieks hey) Just wanted to ask if you have tried testing it again after the fix? Does it work on your side with a new account now?

**Comment by jdieks** [comment] 2019-06-08 18:45
I just tested it.. seems to work now!

**Comment by kroitor** [comment] 2019-06-08 21:35
@jdieks alright! Thank you, appreciate your involvement! Closing this for now. Let us know if anything.

**Closed by kroitor** 2019-06-08 21:35 UTC
Labels: bug, question
