### ISSUE TITLE
Huobi watch my trades dont work fine.

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14987] opened 2022-09-13 12:00 UTC
CCXTversion 1.92.97
CCXTProversion 1.2.25

Hello,
I have been doing various tests in ccxtpro and I have seen that the separate huobi streams work fine but if we mix public streams with private streams there is an error. After many unsuccessful tests I searched for some reference code and found this one.
https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams-with-keys.py

I tested it directly and saw that it works correctly. I changed binance for huobi and put their keys and I saw that it doesn't work and it gives me this error.

2022-09-13T11:56:20.884Z message b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xabV\xcaLQ\xb2R2T\xd2Q*.I,)-\x06r\xf2\xb3A\xbc\xd2\xa4\xa4T\x90TnbQvj\x89^RIriqJ\x89^nR\x81\x9e\xa1\xa9\x01PE\tP\xad\xa1\x99\x99\xb1\x81\xb9\x81\xa1\x85\x81\xa1\xb1i-\x00\x1f[p\x7fM\x00\x00\x00'
Exception in callback FastClient.receive_loop.<locals>.handler() at M:\bots\HuobiWin\ccxtpro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at M:\bots\HuobiWin\ccxtpro\base\fast_client.py:20>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "M:\bots\HuobiWin\ccxtpro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "M:\bots\HuobiWin\ccxtpro\base\aiohttp_client.py", line 40, in handle_message
    self.handle_text_or_binary_message(data)
  File "M:\bots\HuobiWin\ccxtpro\base\aiohttp_client.py", line 26, in handle_text_or_binary_message
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

BR

**Comment by carlosmiei** [comment] 2022-09-13 12:57
Hello @Curro666 thanks for reporting it, 

is it possible to provide some verbose logs where we can see the raw messages arriving from the exchange?

**Comment by carlosmiei** [comment] 2022-09-13 13:36
@Curro666, actually I managed to reproduce it on my end, so no need to send additional logs.

**Comment by Curro666** [comment] 2022-09-13 13:36
@carlosmiei yes, 

```
2022-09-13T13:35:17.486Z connecting to wss://api.huobi.pro/ws/v2 with timeout 10000 ms
2022-09-13T13:35:17.486Z connecting to wss://api.huobi.pro/ws with timeout 10000 ms
2022-09-13T13:35:18.431Z connected
2022-09-13T13:35:18.431Z ping loop
2022-09-13T13:35:18.432Z sending {'params': {'authType': 'api', 'accessKey': 'xxxxxxxxxxxxxxxxxx', 'signatureMethod': 'HmacSHA256', 'signatureVersion': '2.1', 'timestamp': '2022-09-13T13:35:17', 'signature': 'dcySvXyiEUGed8MTjNnsLoams8qHs+bQ0Ox1DUssGOg='}, 'action': 'req', 'ch': 'auth'}
2022-09-13T13:35:18.461Z connected
2022-09-13T13:35:18.461Z ping loop
2022-09-13T13:35:18.462Z sending {'sub': 'market.btcusdt.mbp.150', 'id': '1'}
2022-09-13T13:35:18.569Z sending {'sub': 'market.ethbtc.mbp.150', 'id': '2'}
2022-09-13T13:35:18.669Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2022-09-13T13:35:18.669Z sending {'sub': 'market.ethbtc.trade.detail', 'id': '3'}
2022-09-13T13:35:18.671Z message {"action":"req","code":200,"ch":"auth","data":{}}
2022-09-13T13:35:18.703Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2022-09-13T13:35:18.704Z message b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xabV\xcaLQ\xb2R2T\xd2Q*.I,)-\x06r\xf2\xb3A\xbc\xd2\xa4\xa4T\x90TnbQvj\x89^RIriqJ\x89^nR\x81\x9e\xa1\xa9\x01PE\tP\xad\xa1\x99\x99\xb1\x81\xb9\x99\xa1\xa1\xb9\xa5\x91Y-\x00[\xcek\xc3M\x00\x00\x00'
Exception in callback FastClient.receive_loop.<locals>.handler() at M:\bots\HuobiWin\ccxtpro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at M:\bots\HuobiWin\ccxtpro\base\fast_client.py:20>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "M:\bots\HuobiWin\ccxtpro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "M:\bots\HuobiWin\ccxtpro\base\aiohttp_client.py", line 40, in handle_message
    self.handle_text_or_binary_message(data)
  File "M:\bots\HuobiWin\ccxtpro\base\aiohttp_client.py", line 26, in handle_text_or_binary_message
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2022-09-13T13:35:18.786Z sending {'action': 'sub', 'ch': 'accounts.update#2'}
2022-09-13T13:35:18.811Z message b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00e\x8d\xcb\n\x83@\x0cE\xff%\xeb!$q&\xce\xf8\x11\xddt).|AE\x04[\xb5\x1b\xf1\xdf;\xa3\x8b\x16\xba\t\x9cs/7;\xb4\x0f(`\xaa_c\xbfb\xb3\xb6\xdb\xd2\xad853\xb2#0\xb0.P\xb0jF\xb92{b\x8ejhG(vX\xfa\xe7m\x9bb\xec\x82\x13RQ\xe7c:\xbf\xfa\xf7\xfd/q\xde@3tq\xac,\x85\xad\x10\xaa7\xf1\x08y\xcd*\x93\x1c;\x0c\xc9\xd1\x89Y \xf4\x92\xd0]\xec=\x86\xc4ra.\x98\xf3\xb7\xad\x82\xd6F\xb4J\x1c\xc2\xe5\x980\xb3g\xa52P/\xe3\xef\xf3\x90\xbc\xb8\xaa:\x8e\x0f\xaf\x0f\xa2\xc8\x02\x01\x00\x00'
2022-09-13T13:35:19.029Z message {"action":"sub","code":200,"ch":"accounts.update#2","data":{}}
2022-09-13T13:35:19.030Z message {"action":"push","ch":"accounts.update#2","data":{"currency":"koi",
```

**Comment by carlosmiei** [comment] 2022-09-13 13:38
@Curro666 thanks, we're currently waiting for Huobi's response since that binary message seems to be invalid and crashes our client

**Comment by Curro666** [comment] 2022-09-13 13:42
> @Curro666 thanks, we're currently waiting for Huobi's response since that binary message seems to be invalid and crashes our client

only fail in mix streams. If only use private work fine, if only use public work fine too.

**Comment by carlosmiei** [comment] 2022-09-13 13:43
@Curro666 yes I noticed that too 🙁

**Comment by Curro666** [comment] 2022-09-13 14:06
@carlosmiei  remember this ticket?
https://github.com/ccxt/ccxt/issues/14891
with this code if I use exmo and watchMyTrades  it does not return the data of the new orders, if I put binance for example it works correctly.

**Comment by carlosmiei** [comment] 2022-09-14 11:31
@Curro666 we will check it thanks

**Comment by Curro666** [comment] 2022-09-15 13:16
hello @carlosmiei, did you find the problem?

BR

**Comment by carlosmiei** [comment] 2022-11-16 12:26
Hello @Curro666 so you're saying that if you subscribe to multiple topics simultaneously, you don't get the error?

**Comment by Curro666** [comment] 2022-11-16 19:08
> Hello @Curro666 so you're saying that if you subscribe to multiple topics simultaneously, you don't get the error?

yes, it has been working without errors in this way 4:30

**Comment by carlosmiei** [comment] 2022-11-16 22:25
@Curro666 I've tested and seems to be working fine both ways (single stream or multiple streams). For that reason, I'm going to close this issue, feel free to re-open it if anything!

**Closed by carlosmiei** 2022-11-16 22:25 UTC
Labels: bug, WS, important

**Comment by Curro666** [comment] 2022-12-01 09:10
> @Curro666 I've tested and seems to be working fine both ways (single stream or multiple streams). For that reason, I'm going to close this issue, feel free to re-open it if anything!

Hello,
the solution I proposed the other day is nothing more than a patch. Actually the problem persists and in this way it can be temporarily avoided but it ends up giving the same error after time. Sometimes it takes 2 hours, other times 15 minutes and other times about 10 hours. This exchange with the mix of public and private calls does not work well.

BR

**Comment by lovepocky** [comment] 2023-05-16 03:01
these binary message is gzipped. that might be handle in `handle_text_or_binary_message`

```python
data = b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00e\x8d\xcb\n\x83@\x0cE\xff%\xeb!$q&\xce\xf8\x11\xddt).|AE\x04[\xb5\x1b\xf1\xdf;\xa3\x8b\x16\xba\t\x9cs/7;\xb4\x0f(`\xaa_c\xbfb\xb3\xb6\xdb\xd2\xad853\xb2#0\xb0.P\xb0jF\xb92{b\x8ejhG(vX\xfa\xe7m\x9bb\xec\x82\x13RQ\xe7c:\xbf\xfa\xf7\xfd/q\xde@3tq\xac,\x85\xad\x10\xaa7\xf1\x08y\xcd*\x93\x1c;\x0c\xc9\xd1\x89Y \xf4\x92\xd0]\xec=\x86\xc4ra.\x98\xf3\xb7\xad\x82\xd6F\xb4J\x1c\xc2\xe5\x980\xb3g\xa52P/\xe3\xef\xf3\x90\xbc\xb8\xaa:\x8e\x0f\xaf\x0f\xa2\xc8\x02\x01\x00\x00'

json.loads(gzip.decompress(data).decode())

{'ch': 'market.btcusdt.mbp.150',
 'ts': 1663076118011,
 'tick': {'seqNum': 159520626581,
  'prevSeqNum': 159520626558,
  'bids': [[21420.68, 0.620863],
   [21415.98, 0.0],
   [21390.82, 0.05],
   [21388.92, 0.2],
   [21372.71, 0.0],
   [21362.44, 0.460199],
   [21310.34, 0.0]],
  'asks': [[21420.69, 0.025]]}}
```
