### ISSUE TITLE
Please add TradeOgre

### ISSUE THREAD

**Issue by oti5** [ccxt/ccxt#21743] opened 2024-03-15 16:14 UTC
### Exchange Name

TradeOgre

### URL of the Exchange

https://tradeogre.com

### URL of the Exchange's API docs

https://tradeogre.com/help/api

### Why should this exchange be implemented?

Because:
KYC not required
Have some cryptocurrencies
No have one officially supported tradebot
No have tradingbot in TradeOgre

**Comment by samgermain** [comment] 2024-03-17 00:06
Duplicate of #2150

**Closed by samgermain** 2024-03-17 00:06 UTC
Labels: new exchange

**Comment by carlosmiei** [comment] 2024-03-17 17:31
@oti5 Will add it soon
