### ISSUE TITLE
Cryptopia: canceled order reported as closed

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#2155] opened 2018-03-07 11:54 UTC
- OS: Win 7
- Programming Language version: python 3.6
- CCXT version: 1.11.38
- Exchange: cryptopia
- Method: fetchOrder

When an order is cancelled, fetchOrder should return 'status':'canceled', but in context with cryptopia, it returns 'status':'closed'

Example:
After I placed an order:
exchange.fetchOrder(428161051,symbol)
{'id': '428161051', 'info': {'OrderId': 428161051, 'TradePairId': 5634, 'Market': 'PURA/BTC', 'Type': 'Buy', 'Rate': 5.4e-05, 'Amount': 10.0, 'Total': 0.00054, 'Remaining': 10.0, 'TimeStamp': '2018-03-07T11:36:06.2612757'}, 'timestamp': 1520422566261, 'datetime': '2018-03-07T11:36:06.261Z', 'status': 'open', 'symbol': 'PURA/BTC', 'type': 'limit', 'side': 'buy', 'price': 5.4e-05, 'cost': 0.00054, 'amount': 10.0, 'filled': 0.0, 'remaining': 10.0, 'fee': None}

After I cancelled the order: 
exchange.fetchOrder(428161051,symbol)
{'id': '428161051', 'info': {'OrderId': 428161051, 'TradePairId': 5634, 'Market': 'PURA/BTC', 'Type': 'Buy', 'Rate': 5.4e-05, 'Amount': 10.0, 'Total': 0.00054, 'Remaining': 10.0, 'TimeStamp': '2018-03-07T11:36:06.2612757'}, 'timestamp': 1520422566261, 'datetime': '2018-03-07T11:36:06.261Z', 'status': 'closed', 'symbol': 'PURA/BTC', 'type': 'limit', 'side': 'buy', 'price': 5.4e-05, 'cost': 0.00054, 'amount': 10.0, 'filled': 10.0, 'remaining': 0.0, 'fee': None}

-> note: status:closed.

Interesting is the fact that the info contains 'filled':10.0 which is also wrong since none of the order was filled.

**Comment by kroitor** [comment] 2018-03-07 14:29
> After I cancelled the order:

Do you reinitialize the exchange class instance between the two actions, namely, do you create a new instance of cryptopia after creating the order and before canceling it?

**Comment by stabilus** [comment] 2018-03-07 16:32
no, placing and canceling of order happens right after eachother, no reinitialization, no new instance, 

this produces the error after initializing the exchange):

symbol='BTC/USDT'
amount=0.005
price=10000
result=exchange.createLimitBuyOrder(symbol,amount,price)
time.sleep(5)
print(exchange.fetchOrder(result['id'],symbol))
time.sleep(5)
exchange.cancelOrder(result['id'],symbol)
time.sleep(5)
print(exchange.fetchOrder(result['id'],symbol))

**Comment by payala** [comment] 2018-05-06 17:14
I have seen this effect happening too. I believe it could be related with the issue fixed in #2773

**Comment by payala** [comment] 2018-05-07 19:59
@stabilus I've tried to reproduce this by running the steps you provided with ccxt 1.11.38 to see if #2773 fixes this issue, but after the last step the order shows as 'canceled'. So I couldn't reproduce the problem.

**Closed** 2018-05-22 09:47 UTC
