### ISSUE TITLE
'<' not supported between instances of 'int' and 'NoneType' in await exchange.watchOrders()

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17762] opened 2023-05-03 12:24 UTC
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.89

### Description

While working on a routine which calculates PnL on the fly using watchOrderbook and watchOrders streams, I encountered an *"'<' not supported between instances of 'int' and 'NoneType'"* error

- Error does not occur immediately (error triggers when data from the watchOrders websocketstream is received)
- Error doesn't always happen (if no data is received from the watchOrders websocketstream is received => no error)
- Error happens only when multiple watch methods are used (only using watchOrders) doesn't trigger the error

```
import ccxt
import ccxt.pro as ccxtpro
import os, sys, platform, traceback
import socket, requests
import asyncio, aiohttp
import traceback

async def watch_ticker_listener(exchange, exit_event, symbol):
    print(f"Setting up watch ticker routine")
    while not exit_event.is_set():
        try:
            try:
                tck = await exchange.watchTicker(symbol)
                print(tck)
            except:
                traceback.print_exc()

        except CancelledError:
            print ("Cancelled ticker routine")
            await exchangepro.close()

        except Exception as e:
            print(f"{e}")
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            print(exc_type, fname, exc_tb.tb_lineno)
            await exchangepro.close()

async def watch_orderbook_listener(exchange, exit_event, symbol):
    print(f"Setting up watch orderbook routine")
    orderbook_level = 5
    while not exit_event.is_set():
        try:
            try:
                orderbook = await exchange.watchOrderBook(symbol, orderbook_level)
                print('BIDS : ',orderbook['bids'][0], " ASKS :", orderbook['asks'][0], " PRICE : ",(orderbook['bids'][0][0]+orderbook['asks'][0][0])/2)
            except:
                traceback.print_exc()

        except CancelledError:
            print ("Cancelled orderbook routine")
            await exchangepro.close()

        except Exception as e:
            print(f"{e}")
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            print(exc_type, fname, exc_tb.tb_lineno)
            await exchangepro.close()

async def watch_orders_listener(exchange, exit_event):
    print(f"Setting up watch orders routine")
    while not exit_event.is_set():
        try:
            try:
                orders = await exchange.watchOrders()
                print(orders)
            except:
                traceback.print_exc()
                exit_event.set()

        except CancelledError:
            print ("Cancelled watch orders routine")
            await exchangepro.close()

        except Exception as e:
            print(f"{e}")
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            print(exc_type, fname, exc_tb.tb_lineno)
            await exchangepro.close()


######################################
### MAIN PROGRAM STARTS HERE 
async def main():
    print("Loading markets")
    await exchangepro.loadMarkets()

    tasks = []

    tasks.append(asyncio.create_task(watch_orders_listener(exchangepro, exit_event)))
    tasks.append(asyncio.create_task(watch_ticker_listener(exchangepro, exit_event, symbol)))
    tasks.append(asyncio.create_task(watch_orderbook_listener(exchangepro, exit_event, symbol)))

    try:
        await asyncio.gather(*tasks)

    except (ccxt.RequestTimeout, ccxt.NetworkError) as e:
        print(f"Request error occurred: {e} ...")

    except Exception as e:
        print(f"{e}{Style.RESET_ALL}")
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        print(exc_type, fname, exc_tb.tb_lineno)
        await exchangepro.close()

########################################
### WRAPPER FOR MAIN PROGRAM

customOptions = {
    'defaultType': 'future', # or 'margin' or 'spot'
    'adjustForTimeDifference': True,
    'newOrderRespType': 'FULL',
    'defaultTimeInForce': 'GTC'
}

exchangepro = ccxtpro.binance({
    'apiKey':  apikey,
    'secret':  apisecret,
    'enableRateLimit': False,
    'options': customOptions
})

exit_event = asyncio.Event()

symbol = 'ETH/USDT'

try:
    asyncio.run(main(), debug=False)

except KeyboardInterrupt:
    exit_event.set()
    print("Program interrupted by user")
```

>Traceback (most recent call last):
> File "./CCXT-WS-PNLTEST", line 70, in watch_orders_listener
>    orders = await exchange.watchOrders()
>  File "/usr/local/lib/python3.8/dist-packages/ccxt/pro/binance.py", line 1204, in watch_orders
>    return self.filter_by_symbol_since_limit(orders, symbol, since, limit)
>  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/exchange.py", line 2202, in >filter_by_symbol_since_limit
>    return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit, 'timestamp')
>  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1503, in filter_by_value_since_limit
>    return self.filter_by_limit(array, limit, key)
>  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1493, in filter_by_limit
>    ascending = (array[0][key] < array[len(array) - 1][key])  # true if array is sorted in ascending order based on >'timestamp'
>TypeError: '<' not supported between instances of 'NoneType' and 'int'

### Code

```
  

```

**Comment by spc789** [comment] 2023-05-03 15:57
btw v3.0.86 works correct

**Comment by carlosmiei** [comment] 2023-05-03 15:58
> btw v3.0.86 works correct

@spc789 Yeah it is being caused by an update we merged recently, but we will try to fix it as soon as possible

**Comment by samgermain** [comment] 2023-05-04 00:24
@carlosmiei So the problem is because `timestamp` isn't being assinged, even though it's in `info`, we could use safestring here like `this.safeString(array[0], key, 0)`, so that the default it 0, but that's not really correct.

Here's one example of array, the timestamp is in `info` but not assigned in the regular object, I don't know how that's possible

```
[
    {
        "info": {
            "s": "BTCUSDT",
            "c": "electron_qQobhDQ25xcJHrRjsSmS",
            "S": "BUY",
            "o": "LIMIT",
            "f": "GTC",
            "q": "0.135",
            "p": "25000",
            "ap": "0",
            "sp": "0",
            "x": "CANCELED",
            "X": "CANCELED",
            "i": 146619740980,
            "l": "0",
            "z": "0",
            "L": "0",
            "n": "0",
            "N": "USDT",
            "T": 1683157819289,
            "t": 0,
            "b": "0",
            "a": "0",
            "m": False,
            "R": True,
            "wt": "CONTRACT_PRICE",
            "ot": "LIMIT",
            "ps": "BOTH",
            "cp": False,
            "rp": "0",
            "pP": False,
            "si": 0,
            "ss": 0
        },
        "symbol": "BTC/USDT:USDT",
        "id": "146619740980",
        "clientOrderId": "electron_qQobhDQ25xcJHrRjsSmS",
        "timestamp": 1683157794234,
        "datetime": "2023-05-03T23: 49: 54.234Z",
        "lastTradeTimestamp": None,
        "type": "limit",
        "timeInForce": "GTC",
        "postOnly": False,
        "side": "buy",
        "price": 25000.0,
        "stopPrice": 0.0,
        "triggerPrice": 0.0,
        "amount": 0.135,
        "cost": 0.0,
        "average": None,
        "filled": 0.0,
        "remaining": 0.135,
        "status": "canceled",
        "fee": None,
        "trades": [],
        "fees": [],
        "reduceOnly": None
    },
    {
        "info": {
            "s": "BTCUSDT",
            "c": "electron_iCmyUhvI6AbkzzQ7POpA",
            "S": "BUY",
            "o": "STOP",
            "f": "GTC",
            "q": "1.903",
            "p": "29196",
            "ap": "0",
            "sp": "29195.60",
            "x": "CANCELED",
            "X": "CANCELED",
            "i": 146600912616,
            "l": "0",
            "z": "0",
            "L": "0",
            "n": "0",
            "N": "USDT",
            "T": 1683157828450,
            "t": 0,
            "b": "0",
            "a": "0",
            "m": False,
            "R": True,
            "wt": "MARK_PRICE",
            "ot": "STOP",
            "ps": "BOTH",
            "cp": False,
            "rp": "0",
            "pP": True,
            "si": 0,
            "ss": 0
        },
        "symbol": "BTC/USDT:USDT",
        "id": "146600912616",
        "clientOrderId": "electron_iCmyUhvI6AbkzzQ7POpA",
        "timestamp": None,
        "datetime": None,
        "lastTradeTimestamp": None,
        "type": "stop",
        "timeInForce": "GTC",
        "postOnly": False,
        "side": "buy",
        "price": 29196.0,
        "stopPrice": 29195.6,
        "triggerPrice": 29195.6,
        "amount": 1.903,
        "cost": 0.0,
        "average": None,
        "filled": 0.0,
        "remaining": 1.903,
        "status": "canceled",
        "fee": None,
        "trades": [],
        "fees": [],
        "reduceOnly": None
    }
]
```

**Comment by carlosmiei** [comment] 2023-05-04 08:08
> @carlosmiei So the problem is because `timestamp` isn't being assinged, even though it's in `info`, we could use safestring here like `this.safeString(array[0], key, 0)`, so that the default it 0, but that's not really correct.
> 
> Here's one example of array, the timestamp is in `info` but not assigned in the regular object, I don't know how that's possible
> 
> ```
> [
>     {
>         "info": {
>             "s": "BTCUSDT",
>             "c": "electron_qQobhDQ25xcJHrRjsSmS",
>             "S": "BUY",
>             "o": "LIMIT",
>             "f": "GTC",
>             "q": "0.135",
>             "p": "25000",
>             "ap": "0",
>             "sp": "0",
>             "x": "CANCELED",
>             "X": "CANCELED",
>             "i": 146619740980,
>             "l": "0",
>             "z": "0",
>             "L": "0",
>             "n": "0",
>             "N": "USDT",
>             "T": 1683157819289,
>             "t": 0,
>             "b": "0",
>             "a": "0",
>             "m": False,
>             "R": True,
>             "wt": "CONTRACT_PRICE",
>             "ot": "LIMIT",
>             "ps": "BOTH",
>             "cp": False,
>             "rp": "0",
>             "pP": False,
>             "si": 0,
>             "ss": 0
>         },
>         "symbol": "BTC/USDT:USDT",
>         "id": "146619740980",
>         "clientOrderId": "electron_qQobhDQ25xcJHrRjsSmS",
>         "timestamp": 1683157794234,
>         "datetime": "2023-05-03T23: 49: 54.234Z",
>         "lastTradeTimestamp": None,
>         "type": "limit",
>         "timeInForce": "GTC",
>         "postOnly": False,
>         "side": "buy",
>         "price": 25000.0,
>         "stopPrice": 0.0,
>         "triggerPrice": 0.0,
>         "amount": 0.135,
>         "cost": 0.0,
>         "average": None,
>         "filled": 0.0,
>         "remaining": 0.135,
>         "status": "canceled",
>         "fee": None,
>         "trades": [],
>         "fees": [],
>         "reduceOnly": None
>     },
>     {
>         "info": {
>             "s": "BTCUSDT",
>             "c": "electron_iCmyUhvI6AbkzzQ7POpA",
>             "S": "BUY",
>             "o": "STOP",
>             "f": "GTC",
>             "q": "1.903",
>             "p": "29196",
>             "ap": "0",
>             "sp": "29195.60",
>             "x": "CANCELED",
>             "X": "CANCELED",
>             "i": 146600912616,
>             "l": "0",
>             "z": "0",
>             "L": "0",
>             "n": "0",
>             "N": "USDT",
>             "T": 1683157828450,
>             "t": 0,
>             "b": "0",
>             "a": "0",
>             "m": False,
>             "R": True,
>             "wt": "MARK_PRICE",
>             "ot": "STOP",
>             "ps": "BOTH",
>             "cp": False,
>             "rp": "0",
>             "pP": True,
>             "si": 0,
>             "ss": 0
>         },
>         "symbol": "BTC/USDT:USDT",
>         "id": "146600912616",
>         "clientOrderId": "electron_iCmyUhvI6AbkzzQ7POpA",
>         "timestamp": None,
>         "datetime": None,
>         "lastTradeTimestamp": None,
>         "type": "stop",
>         "timeInForce": "GTC",
>         "postOnly": False,
>         "side": "buy",
>         "price": 29196.0,
>         "stopPrice": 29195.6,
>         "triggerPrice": 29195.6,
>         "amount": 1.903,
>         "cost": 0.0,
>         "average": None,
>         "filled": 0.0,
>         "remaining": 1.903,
>         "status": "canceled",
>         "fee": None,
>         "trades": [],
>         "fees": [],
>         "reduceOnly": None
>     }
> ]
> ```

@samgermain `filterByLimit` has to work without a timestamp because it is not guaranteed we will have one available

**Closed** 2023-05-04 10:04 UTC
Labels: bug
