### ISSUE TITLE
Python fetchOrderBook memory leak

### ISSUE THREAD

**Issue by dingyaguang117** [ccxt/ccxt#3996] opened 2018-10-15 04:10 UTC
- OS: MacOS/Ubuntu
- Programming Language version: Python 2.7.10
- CCXT version: 1.17.373
- Exchange: All
- Method: fetchOrderBook

Memory increase so fast, and seem never be recycled

**Comment by dingyaguang117** [comment] 2018-10-15 04:32
this is the objects increase after each invoke(by pympler)
```python
                                              types |   # objects |   total size
=================================================== | =========== | ============
                                               dict |        1233 |      1.34 MB
                                               list |        7421 |    780.01 KB
                                            unicode |        7966 |    546.92 KB
                                                str |        6132 |    358.42 KB
                                                int |         548 |     12.84 KB
                                              float |         401 |      9.40 KB
                                               code |          18 |      2.25 KB
                                            weakref |          15 |      1.29 KB
  <class 'urllib3.packages.ordered_dict.OrderedDict |           1 |      1.02 KB
                                               type |           1 |    904     B
                                 wrapper_descriptor |           9 |    720     B
                         builtin_function_or_method |           9 |    648     B
                       <class 'urlparse.SplitResult |           4 |    416     B
                                function (__init__) |           3 |    360     B
                                  getset_descriptor |           5 |    360     B
```

**Comment by dingyaguang117** [comment] 2018-10-15 05:06
seem load markets used many memory

**Comment by dingyaguang117** [comment] 2018-10-17 02:59
Thank you very much!
My program fetch a lot of different exchanges' order. so I have to create a lot of exchange instances.

can you try the code below, just create exchange every time. the memory increase even I delete the instance immediately 

```
# -*- coding: utf-8 -*-

import os
import sys
import psutil


# -----------------------------------------------------------------------------

this_folder = os.path.dirname(os.path.abspath(__file__))
root_folder = os.path.dirname(os.path.dirname(this_folder))
sys.path.append(root_folder + '/python')
sys.path.append(this_folder)

# -----------------------------------------------------------------------------

import ccxt  # noqa: E402

# -----------------------------------------------------------------------------



while True:
    exchange = ccxt.poloniex({
        'enableRateLimit': True,
    })
    orderbook = exchange.fetch_order_book('ETH/BTC')
    process = psutil.Process(os.getpid())
    print(exchange.iso8601(exchange.milliseconds()), process.memory_info()[0])
    del exchange
```

this is the result 
```
('2018-10-17T02:55:43.793Z', 24956928L)
('2018-10-17T02:55:45.880Z', 26472448L)
('2018-10-17T02:55:47.971Z', 27942912L)
('2018-10-17T02:55:50.105Z', 29368320L)
('2018-10-17T02:55:52.195Z', 30892032L)
('2018-10-17T02:55:54.273Z', 32391168L)
('2018-10-17T02:55:56.356Z', 24637440L)
('2018-10-17T02:55:58.449Z', 26181632L)
('2018-10-17T02:56:00.545Z', 27742208L)
('2018-10-17T02:56:02.652Z', 29323264L)
('2018-10-17T02:56:04.733Z', 30945280L)
('2018-10-17T02:56:06.814Z', 32514048L)
('2018-10-17T02:56:08.898Z', 34045952L)
('2018-10-17T02:56:10.984Z', 35577856L)
('2018-10-17T02:56:13.068Z', 36118528L)
('2018-10-17T02:56:15.149Z', 37679104L)
('2018-10-17T02:56:17.244Z', 39194624L)
('2018-10-17T02:56:19.329Z', 40075264L)
('2018-10-17T02:56:21.418Z', 41529344L)
('2018-10-17T02:56:23.517Z', 43057152L)
('2018-10-17T02:56:25.608Z', 41123840L)
('2018-10-17T02:56:27.696Z', 42610688L)
('2018-10-17T02:56:29.773Z', 44220416L)
('2018-10-17T02:56:31.852Z', 45883392L)
('2018-10-17T02:56:33.936Z', 47427584L)
('2018-10-17T02:56:36.033Z', 48930816L)
('2018-10-17T02:56:38.122Z', 50581504L)
('2018-10-17T02:56:40.224Z', 52072448L)
('2018-10-17T02:56:42.312Z', 53506048L)
('2018-10-17T02:56:44.416Z', 55164928L)
('2018-10-17T02:56:46.505Z', 56774656L)
('2018-10-17T02:56:48.587Z', 58269696L)
('2018-10-17T02:56:50.672Z', 59777024L)
('2018-10-17T02:56:52.755Z', 61407232L)
('2018-10-17T02:56:54.844Z', 60301312L)
('2018-10-17T02:56:56.925Z', 61370368L)
('2018-10-17T02:56:59.013Z', 70586368L)
('2018-10-17T02:57:01.105Z', 72101888L)
('2018-10-17T02:57:03.199Z', 73703424L)
('2018-10-17T02:57:05.278Z', 75292672L)
('2018-10-17T02:57:07.358Z', 76800000L)
('2018-10-17T02:57:09.433Z', 78372864L)
('2018-10-17T02:57:11.510Z', 79831040L)
('2018-10-17T02:57:13.592Z', 81367040L)
('2018-10-17T02:57:15.671Z', 82976768L)
('2018-10-17T02:57:17.762Z', 84545536L)
('2018-10-17T02:57:19.849Z', 86061056L)
('2018-10-17T02:57:21.925Z', 87584768L)
('2018-10-17T02:57:24.013Z', 89206784L)
('2018-10-17T02:57:26.110Z', 90800128L)
('2018-10-17T02:57:28.185Z', 92356608L)
('2018-10-17T02:57:30.264Z', 93904896L)
('2018-10-17T02:57:32.364Z', 95404032L)
('2018-10-17T02:57:34.448Z', 96993280L)
('2018-10-17T02:57:36.537Z', 98586624L)
('2018-10-17T02:57:38.625Z', 100110336L)
('2018-10-17T02:57:40.707Z', 101675008L)
('2018-10-17T02:57:42.802Z', 103235584L)
('2018-10-17T02:57:44.885Z', 101031936L)
('2018-10-17T02:57:46.964Z', 101945344L)
('2018-10-17T02:57:49.050Z', 103378944L)
('2018-10-17T02:57:51.135Z', 104968192L)
('2018-10-17T02:57:53.239Z', 103153664L)
('2018-10-17T02:57:55.332Z', 104689664L)
('2018-10-17T02:57:57.419Z', 106151936L)
('2018-10-17T02:57:59.500Z', 107761664L)
('2018-10-17T02:58:01.583Z', 109350912L)
('2018-10-17T02:58:03.668Z', 110411776L)
('2018-10-17T02:58:05.804Z', 110592000L)
('2018-10-17T02:58:07.890Z', 101601280L)
('2018-10-17T02:58:09.981Z', 103157760L)
```

**Comment by ngugcx** [comment] 2018-10-24 06:54
+1
I hit the same issue with ccxt.cryptopia. So it seems it's not about some specific exchange.

**Comment by ngugcx** [comment] 2018-10-24 11:46
The result of ccxt.coinex with the same code as dingyaguang117:
('2018-10-24T11:40:13.243Z', 40615936)
('2018-10-24T11:40:17.770Z', 43634688)
('2018-10-24T11:40:19.904Z', 46333952)
('2018-10-24T11:40:22.009Z', 49303552)
('2018-10-24T11:40:24.143Z', 52277248)
('2018-10-24T11:40:26.281Z', 54980608)
('2018-10-24T11:40:28.417Z', 57954304)
('2018-10-24T11:40:30.531Z', 60956672)
('2018-10-24T11:40:32.638Z', 63660032)
('2018-10-24T11:40:34.907Z', 66633728)
('2018-10-24T11:40:37.040Z', 69718016)
('2018-10-24T11:40:39.153Z', 72417280)
('2018-10-24T11:40:41.274Z', 75497472)
('2018-10-24T11:40:43.391Z', 78348288)
('2018-10-24T11:40:45.595Z', 81268736)
('2018-10-24T11:40:47.713Z', 83972096)
('2018-10-24T11:40:49.835Z', 86921216)
('2018-10-24T11:40:51.946Z', 89894912)
('2018-10-24T11:40:54.081Z', 92717056)

**Comment by ngugcx** [comment] 2018-10-24 13:42
@kroitor , I guess the problem is that the base class defines __del__.
We may need to remove the usage of requests session.

**Comment by kroitor** [comment] 2018-10-25 13:53
@ngugc to me this looks like memory leaking somewhere from web3 deps, going to debug it asap. Thx for your help!

**Comment by ngugcx** [comment] 2018-11-12 14:14
@kroitor , hava you debugged it? thanks.

**Comment by Brendy88** [comment] 2018-11-28 09:45
+1
I am hitting the same issue. Has it been resolved?

**Comment by kroitor** [comment] 2018-12-22 06:19
The problem with lies within the Python memory management itself:

- https://docs.python.org/2.7/c-api/memory.html
- https://docs.python.org/3/c-api/memory.html

> It is important to understand that the management of the Python heap is performed by the interpreter itself and that the user has no control over it, even if they regularly manipulate object pointers to memory blocks inside that heap. The allocation of heap space for Python objects and other internal buffers is performed on demand by the Python memory manager through the Python/C API functions listed in this document.

So, I'm afraid you can't really assume that it will free the memory on `del exchange`:

```Python
while True:
    exchange = ccxt.poloniex({
        'enableRateLimit': True,
    })
    orderbook = exchange.fetch_order_book('ETH/BTC')
    process = psutil.Process(os.getpid())
    print(exchange.iso8601(exchange.milliseconds()), process.memory_info()[0])

    del exchange  # ←--------- does not really call __del__ here
```

The destructor is called upon termination of the program,  but isn't called in the loop, you can test it yourself if you add `print('something')` to your destructor. Also, Python memory manager is greedy, so it will take up as much as it can, before garage collection.

I would even recommend an even simpler script, without a call to `fetch_order_book`:

```Python
while True:
    exchange = ccxt.poloniex({
        'enableRateLimit': True,
    })
    process = psutil.Process(os.getpid())
    print(exchange.iso8601(exchange.milliseconds()), process.memory_info()[0])
    del exchange  # ←--------- does not really call __del__ here
```

↑ This one works on my side like so: it starts and runs and the counter of used memory grows constantly until it reaches a certain level, in my case, 1.5Gb, and growth stops there and the counter starts fluctuating around a fixed number.

So, ultimately, it may turn out that this isn't an issue at all, it depends on the understanding of the underlying memory management mechanisms.

Let me know if that is not the case with your system (try running the script for longer until it reaches the limit and starts recycling your memory – that will depend on the amount of free vram on your machine).

**Comment by kroitor** [comment] 2018-12-26 05:46
So, as I've shown above, it is not related to web3, nor it is related to class instantiation or anything with `__del__` or whatever – the memory usage grows even if we don't recreate the class. I thinks, this is how python garbage collection works. Therefore I suggest to close the issue until we have a followup on this from anybody.

**Comment by ngugcx** [comment] 2018-12-26 06:12
There are cycle references in CCXT, and the explicit __del__ prevents them from being garbage collecting.

**Comment by kroitor** [comment] 2018-12-26 06:16
@ngugcx 

> There are cycle references in CCXT, and the explicit del prevents them from being garbage collecting.

It would be great if you could help finding them and fixing them )

**Comment by ngugcx** [comment] 2018-12-26 06:20
`import gc
import time
import os
import sys 
import psutil
import ccxt


if __name__ == '__main__':  
    gc.enable()
    gc.set_debug(gc.DEBUG_COLLECTABLE | gc.DEBUG_UNCOLLECTABLE | \ 
        gc.DEBUG_INSTANCES | gc.DEBUG_OBJECTS)
    
    # MethoTest()
    loop = 10
    while loop > 0:
        exchange = ccxt.poloniex({
            'enableRateLimit': True,
        })  
        process = psutil.Process(os.getpid())
        print(exchange.iso8601(exchange.milliseconds()), process.memory_info()[0])
        del exchange  #--------- does not really call __del__ here
        loop -= 1
    
    print 'gc-ing...'
    _unreachable = gc.collect()
    print 'unreachable num: %d' % _unreachable
    print 'leak num: %d' % len(gc.garbage)
    
    time.sleep(3)`

Try the above code.
Without comment out __del__:
**unreachable num: 1503
leak num: 10**

after comment out __del__
**unreachable num: 980
leak num: 0**

**Comment by kroitor** [comment] 2018-12-26 06:21
> Try the above code.

I did, and it really shows the same result, it confirms a leak, but it doesn't really help in finding it )

**Comment by ngugcx** [comment] 2018-12-26 11:51
I'll try to find the circle when getting some free time.
But I insist that python __del__ is not like C++ dctor, it cannot be used to guarantee resource release.
Python garbage collector can handle cycle references correctly if the objects have no __del__.
Maybe we should consider to change the way of using requests.

**Comment by kroitor** [comment] 2018-12-26 11:53
> I'll try to find the circle when getting some free time.

That would be awesome! Thx!

> Maybe we should consider to change the way of using requests.

What would you suggest?

**Comment by ngugcx** [comment] 2018-12-26 12:16
How about using requests.request instead of session.request?
Are there special reasons of using session.request, for performance?

**Comment by ngugcx** [comment] 2018-12-26 17:32
```
import gc
import time
import os
import sys 
import psutil
import ccxt
import objgraph

if __name__ == '__main__':  
    loop = 5 
    exchange = None
    test = None
    while True:
        objgraph.show_growth()
        exchange = ccxt.poloniex({
            'enableRateLimit': True,
        })  
        objgraph.show_growth()
        objgraph.show_backrefs(exchange, max_depth=5, filename = "indirect.dot")
        print('=================================')
        loop -= 1
        time.sleep(1)
        
    time.sleep(3)
```
In order to narrow down the problem, I minimized base/exchange and poloniex.py.
By running the above code, indirect.dot was generated:
![image](https://user-images.githubusercontent.com/44153489/50452726-d3759480-0976-11e9-9e93-5ff58b97b7d5.png)

The code causes this cycle:
```
    def define_rest_api(self, api, method_name, options={}):
        delimiters = re.compile('[^a-zA-Z0-9]')
        for api_type, methods in api.items():
            for http_method, urls in methods.items():
                for url in urls:
                    url = url.strip()
                    split_path = delimiters.split(url)

                    uppercase_method = http_method.upper()
                    lowercase_method = http_method.lower()
                    camelcase_method = lowercase_method.capitalize()
                    camelcase_suffix = ''.join([Exchange.capitalize(x) for x in split_path])
                    lowercase_path = [x.strip().lower() for x in split_path]
                    underscore_suffix = '_'.join([k for k in lowercase_path if len(k)])

                    camelcase = api_type + camelcase_method + Exchange.capitalize(camelcase_suffix)
                    underscore = api_type + '_' + lowercase_method + '_' + underscore_suffix.lower()

                    if 'suffixes' in options:
                        if 'camelcase' in options['suffixes']:
                            camelcase += options['suffixes']['camelcase']
                        if 'underscore' in options['suffixes']:
                            underscore += options['suffixes']['underscore']

                    partial = functools.partial(getattr(self, method_name), url, api_type, uppercase_method)
                    **setattr(self, camelcase, partial)
                    setattr(self, underscore, partial)**
```

Maybe there are other cycles.

**Comment by kroitor** [comment] 2018-12-26 17:37
From your screenshot it follows that it means these lines:

```Python
partial = functools.partial(getattr(self, method_name), url, api_type, uppercase_method)
setattr(self, camelcase, partial)
setattr(self, underscore, partial)
```

However, I don't see anything cyclic or any reason for these lines to leak memory here – it's just a very basic partial construct. Any ideas on how we could resolve this?

**Comment by frosty00** [comment] 2018-12-26 17:38
yeah I was just looking at this code also:

```
gc.get_referrers(ccxt.livecoin())
Out[5]: 
[<bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.request of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.amount_to_precision of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.append_fiat_currencies of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.build_ohlcv of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.calculate_fee of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.cancel_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.check_address of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.check_required_credentials of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.check_required_dependencies of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.common_currency_code of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.convert_ohlcv_to_trading_view of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.convert_trading_view_to_ohlcv of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.cost_to_precision of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_limit_buy_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_limit_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_limit_sell_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_market_buy_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_market_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.create_market_sell_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.create_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.currency_id of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.currency_to_precision of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.define_rest_api of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.edit_limit_buy_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.edit_limit_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.edit_limit_sell_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.edit_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.eth_decimals of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.eth_unit of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fee_to_precision of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_bids_asks of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_closed_orders of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_currencies of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_deposit_address of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_deposits of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_fees of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_free_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_l2_order_book of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_markets of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_my_trades of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_ohlcv of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_open_orders of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_order_book of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_order_status of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_order_trades of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_orders of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_partial_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_ticker of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_tickers of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_total_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_trades of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.fetch_trading_fees of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_transactions of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_used_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.fetch_withdrawals of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_array of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_currency_since_limit of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_since_limit of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_symbol of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_symbol_since_limit of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.filter_by_value_since_limit of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.find_broadly_matched_key of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.find_market of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.find_symbol of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.handle_errors of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.handle_rest_errors of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.handle_rest_response of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.load_fees of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.load_markets of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.load_trading_limits of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.market_id of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.market_ids of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_balance of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_bid_ask of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_bids_asks of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_json of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_ohlcv of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_ohlcvs of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.parse_order of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_order_book of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.parse_order_status of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_orders of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.parse_ticker of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_timeframe of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method livecoin.parse_trade of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_trades of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_trading_view_ohlcv of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.parse_transactions of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.populate_fees of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.precision_from_string of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.prepare_request_headers of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.price_to_precision of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.purge_cached_orders of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.raise_error of <ccxt.livecoin.livecoin object at 0x110873da0>>,
 <bound method Exchange.set_markets of <ccxt.livecoin.livecoin object at 0x110873da0>>]
```

If you comment out the setattr or the call to define_rest_api then we get no references to Exchange.request 

It's the 26th so I have to play red dead redemption but will be down to debug this in depth tomorrow (';

**Comment by ngugcx** [comment] 2018-12-27 02:06
```
        for key in settings:
            if hasattr(self, key) and isinstance(getattr(self, key), dict):
                setattr(self, key, self.deep_extend(getattr(self, key), settings[key]))
            else:
                setattr(self, key, settings[key])

        if self.api:
            self.define_rest_api(self.api, 'request')
```

```
        # convert all properties from underscore notation foo_bar to camelcase notation fooBar
        for name in dir(self):
            if name[0] != '_'and name[-1] != '_' and '_' in name:
                parts = name.split('_')
                camelcase = parts[0] + ''.join(self.capitalize(i) for i in parts[1:])
                setattr(self, camelcase, getattr(self, name))
```

All cyclic references are from the above code.
I have no idea how to fix it without changing current framework.
Removing the __del__ may be the easiest way, after all, it's too easy to write code with cyclic references

**Comment by frosty00** [comment] 2018-12-27 18:35
#4394 fixes the issue, in python3 at least...

**Closed** 2019-01-09 13:32 UTC
