### ISSUE TITLE
Library won't bundle together with react-scripts (create-react-app, webpack, uglify)

### ISSUE THREAD

**Issue by johny** [ccxt/ccxt#1916] opened 2018-02-15 20:00 UTC
When trying to generate production bundle for react app generated with create-react-app the library causes error:

```
react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

./node_modules/ccxt/js/base/errors.js:36 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-js" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

CRA team refers to this issue: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

- OS: Mac OS X 10.13.2 (High Sierra)
- Programming Language version: Javascript, Node JS 8.9.4, 
- React scripts: `1.1.0`
- CCXT version: `^1.10.1116`
- Exchange: any?
- Method: `/node_modules/ccxt/js/base/errors.js`

**Comment by kroitor** [comment] 2018-02-15 20:17
> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

This message itself is a few years old %))))

Basically all modern JS environments, all browsers and common Node versions are ES6-compliant (mostly), nowadays. So, that recommendation itself is outdated now. And there's no reason to continue supporting the ES5 and those shitty frameworks that can't compile both ES5/ES6 – that will motivate them to finally switch to ES6 in the best interest of all mankind. )

A partial solution to it is covered here:
- https://github.com/ccxt/ccxt/issues/606
- https://github.com/ccxt/ccxt/issues/299
- https://github.com/ccxt/ccxt/issues/225
- https://github.com/ccxt/ccxt/pull/612

Let us know if it does not answer your question.

**Comment by johny** [comment] 2018-02-16 15:25
Hey @kroitor - thanks for the hint. 

I agree, it doesn't make sense to support both ES5&ES6 - especially form modern apps.
I'll check it, maybe its just some settings.

**Comment by kroitor** [comment] 2018-02-25 16:48
I'm closing it until we have a follow-up, if you don't mind. Feel free to reopen it if needed, or just ask questions, if you still have them. Thx!

**Closed by kroitor** 2018-02-25 16:48 UTC
Labels: question

**Comment by jmparsons** [comment] 2018-05-17 08:40
What's the proposed solution exactly? I don't personally want to eject my create react app. I can, but then I'd have to modify webpack and if I'm doing that I might as well do parcel or something. Without the ES5, I have to do serious plumbing to get it to work. Should I just fork and build a dist folder?

I've looked at all those [issues](https://github.com/ccxt/ccxt/issues/1916#issuecomment-366048633) and tried to re-apply them using [react-app-rewired](https://github.com/timarney/react-app-rewired) and [react-app-rewire-babel-loader](https://github.com/dashed/react-app-rewire-babel-loader) no dice yet. It isn't so much as getting it working locally - it works fine, but deploying anywhere in a node environment it fails.

I would not mind rewiring it if there were instructions, but so far everything I've seen does not work.

**Comment by jmparsons** [comment] 2018-05-17 12:02
@kroitor Hey I'm new to this package and don't know if it used to be compatible with ES5 and was removed on purpose. I forked it and got it working:

https://github.com/jmparsons/ccxt

And tested it with a scoped package:

https://www.npmjs.com/package/@jmparsons/ccxt

**Comment by kroitor** [comment] 2018-05-26 08:26
@jmparsons thanks for reporting back! Would you submit a PR? )

**Comment by colbycornish** [comment] 2018-06-06 07:50
@jmparsons @kroitor Any update on this? We're having similar issues with react and ccxt integration, but it sounds like a proposed fix may have worked?

**Comment by jmparsons** [comment] 2018-06-06 08:07
@colbycornish I got it working and will make a pull request soon, been real busy with work.

**Comment by kroitor** [comment] 2018-06-06 14:34
@jmparsons 

> will make a pull request soon

that would be awesome! ) thx!

**Comment by colbycornish** [comment] 2018-06-12 16:46
@jmparsons Just giving this a friendly bump. I know I've seen at 4 or 5 support tickets regarding this issue, so I'm sure your updates would help a number of different projects :). Let me know if there's anything you need / any way to help!

**Comment by jmparsons** [comment] 2018-06-12 18:09
@colbycornish I’ll have a PR tomorrow. Need to test the dist, so it won’t pollute code base. A proxy is still required from what I’ve experienced.

**Comment by colbycornish** [comment] 2018-06-12 18:20
@jmparsons No worries - thanks for the update!

**Comment by jmparsons** [comment] 2018-06-15 01:13
@kroitor I've added a PR https://github.com/ccxt/ccxt/pull/3140. I cherry picked from my local build, so hopefully everything works. It just requires a `build:dist` before being publised to npm.

**Comment by kroitor** [comment] 2018-06-15 03:43
@jmparsons 

After taking a deeper look into it... 

Do you know of a way to include the ES6 version from Node and the ES5-version from a React/ES5 environment only? Because if you don't we won't be able to merge this particular PR as it is right away.

You see, we have been looking for it for a long time, so, if this was that easy, we would have fixed it already. Unfortunately, the is a little deeper. And, in fact, we had the same webpack.config.js a few months ago in this repo (can find it in the history), however, it doesn't really work well for everybody. So we trashed it completely.

There's a problem with merging this PR, this particular line:

https://github.com/ccxt/ccxt/pull/3140/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R5

It kinda solves the issue for ES5-people, but breaks it for ES6 and Python...

The main problem with this line is that it will force everyone to use the ES5-version.
Webpack+Uglify failed to transpile certain code with promises + timeouts, so, instead of trying to fix the monster, we switched to ES6-only, because most modern browsers (99% of them) will support ES6. However, the guys from create-react-app still use UglifyJS which does not even support classes properly, so occasionally there someone comes saying *"hey, your module does not work in my app!"*. This has some viral nature, because they still teach this "technique" in their tutorials all over the internet.

From here we have to choose:

- Either waste time on supporting the virus of outdated ES5 frameworks and answer *"ok, we will try to make the older code work, though it should have died already..."*
- Recommend to switch to ES6 completely by saying *"hey, just dump that shit and use modern syntax"* – as soon as the transition to ES6 happens everyone will be happy, so you really should push on create-react-app and UglifyJS for them to actually catch up with the progress. Stop using their packages – this will hurry them up )))

This way, it breaks the thing for people who do not want all the burden of ES5 in their newer Node projects. Also, ES5 adds significant overhead: http://incaseofstairs.com/six-speed/. This is the key reason not to switch to ES5 for everybody. At this point, hopefully, the reasons for not merging PR #3140 are well-explained.

As for the Python, the `dist` folder was used to compile python pip package files on Travis, so it was in the `npmignore` on purpose  so you have mixed them up a little. No worries about it and there's no problem relocating it, but the main problem with ES5 is still present. We need to find a way to make ES5 optional. Do you know something about it?

**Comment by jmparsons** [comment] 2018-06-15 05:30
@kroitor I had came across an es6 project with a very nice setup, but I haven't been able to find it again - es6 compatible wrappers for imports. 

Most times I see rollup - https://github.com/rollup/rollup/wiki/pkg.module - used to point to es6 based modules.

```js
{
  "name": "my-package",
  "version": "0.1.0",
  "main": "dist/my-package.umd.js",
  "module": "dist/my-package.esm.js" // this one
}
```

**Comment by munrocket** [comment] 2018-07-14 20:51
>Do you know of a way to include the ES6 version from Node and the ES5-version from a React/ES5 environment only?
Check this [article](https://hackernoon.com/7-different-ways-to-use-es-modules-today-fc552254ebf4), it anser at your question. Rollup is pretty cool, it concat all dependency in one js file, exactly what you need. Also you can check usage example at my [project](https://github.com/munrocket/ta-math) I will add es5 babel bundle generation soon.

**Comment by phuaky** [comment] 2018-09-13 10:34
Im facing some issues here:

ERROR in ./~/ccxt/js/theocean.js
Module parse failed: .../node_modules/ccxt/js/theocean.js Unexpected token (110:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (110:10)

webpack: Failed to compile.

**Comment by kroitor** [comment] 2018-09-13 10:38
@phuaky what's your node version? `node --version` ?

**Comment by phuaky** [comment] 2018-09-13 10:40
hi @kroitor, v10.6.0

**Comment by phuaky** [comment] 2018-09-13 10:45
im thinking perhaps its being excluded in the webpack.config?
`  module: {
    loaders: [
      {
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['react', 'es2015', 'stage-1']
        }
      }
    ]
  },`
If this is the cause of the error, how do i include them?

**Comment by kroitor** [comment] 2018-09-13 10:48
@phuaky this is an issue with your babel/webpack setup, as you can see from here, this is not an issue with the CCXT library itself. Check you transpilation configs and make sure you're transpiling it properly. Issues of this kind are usually solved with a plugin for your transpiler (webpack/babel plugin).

- https://github.com/SimulatedGREG/electron-vue/issues/175
- https://stackoverflow.com/questions/40880142/issues-parsing-async-functions-with-webpack
- https://github.com/apollographql/meteor-integration/issues/27
- https://github.com/gatsbyjs/gatsby/issues/3931#issuecomment-412593629

> im thinking perhaps its being excluded in the webpack.config?

Exactly!

- https://github.com/ccxt/ccxt#javascript-npm

<img width="1098" alt="screen shot 2018-09-13 at 13 47 09" src="https://user-images.githubusercontent.com/1294454/45484058-8ec54500-b75b-11e8-9d04-c7c005e10286.png">

> When compiling with Webpack and Babel, make sure it is not excluded in your babel-loader config.

------

> If this is the cause of the error, how do i include them?

See the links above. Most often you want to install and configure babel-runtime. Also, read this post and links from there: https://github.com/ccxt/ccxt/issues/299. Let us know if that does not help.

**Comment by kroitor** [comment] 2018-09-13 10:49
@phuaky https://github.com/ccxt/ccxt/issues/225#issuecomment-331905178

**Comment by phuaky** [comment] 2018-09-13 11:50
Im still not able to transpile properly even after going through the suggestions and trying out a few ways. 
is there another way to just exclude all node_modules except ccxt?
my current code 
<img width="496" alt="screen shot 2018-09-13 at 7 49 24 pm" src="https://user-images.githubusercontent.com/21034468/45486576-2fccf380-b78e-11e8-83df-72d264286173.png">
