### ISSUE TITLE
amountToLots strange values

### ISSUE THREAD

**Issue by Pmant** [ccxt/ccxt#1102] opened 2018-01-07 07:59 UTC
Method amountToLots returns unexpected values. Depending on the input, it even changes input values, which are multiples of lot size. 
Tested on hitbtc2 and cryptopia, other exchanges may be affected as well.

- OS: Windows 10
- Programming Language: Node.js
- CCXT version: 1.10.579
- Exchange: multiple
- Method: amountToLots

```
const ccxt = require ('ccxt');
const cryptopia = new ccxt.cryptopia({});
const hitbtc2 = new ccxt.hitbtc2({
    apiKey: '123',
    secret: '456'
});

(async () => {
    await hitbtc2.loadMarkets();
    await cryptopia.loadMarkets();

    console.log(hitbtc2.markets['KMD/BTC'].lot);                //= 0.01
    console.log(hitbtc2.amountToLots('KMD/BTC', 4.271));        //= 4.27
    console.log(hitbtc2.amountToLots('KMD/BTC', 4.27));         //= 4.26

    console.log(cryptopia.markets['KMD/BTC'].lot);              //= 1e-8
    console.log(cryptopia.amountToLots('KMD/BTC',4.271));       //= 4.271
    console.log(cryptopia.amountToLots('KMD/BTC',4.27));        //= 4.26999999
    console.log(cryptopia.amountToLots('KMD/BTC',4.26999999));  //= 4.26999998
})();

>node test.js
0.01
4.27
4.26
1e-8
4.271
4.26999999
4.26999998
```

**Comment by kroitor** [comment] 2018-01-07 14:31
Hi! We are going to rework this soon for a much better support for arbitrary precision. In the meantime, if you don't mind, I'd suggest to move this discussion to #522 , as a duplicate of the same nature. Thanks for reporting!

**Closed by kroitor** 2018-01-07 14:31 UTC

**Comment by kroitor** [comment] 2018-01-07 17:43
@Pmant added a workaround to it, it will pass your values "as is", untouched, to Cryptopia for now.
