### ISSUE TITLE
Withdrawal from Huobi problem

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15789] opened 2022-11-22 16:02 UTC
Hello. I test withdrawals from Huobi to Kucoin and I got some problems.
First, when I try to do this: `huobi.withdraw("USDT", 15, my_address, tag=None, params={"network": "ERC20"})`
I got
`ccxt.base.errors.BadRequest: huobipro {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null}`
Why?
Ok, then I change network name to "ETH" and got this: `ccxt.base.errors.PermissionDenied: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}`
My questions are:
1) How should the name of the network be given for any exchange? When I withdrawed from MEXC, I filled network params with "ERC20" and "BEP20". It worked. Now on Huobi it doesn't.
2) What temporary addresses mean and how to fix it?

**Comment by samgermain** [comment] 2022-11-23 01:41
> And question #3. Now I am trying to withdraw from Kucoin. First, it gives me error Kucoin needs to have a number for withdraw with only 6 decimal numbers after "." Ok, done it, but now with this code:
> 
> ```
> exchangeA = exchangeA
> coin = coin
> amount = exchangeA.fetch_balance()["free"][coin]
> if exchangeA==self.kucoin:
>     begining=''
>     final = ''
>     if '.' in str(amount):
>         begining+=str(amount).split(".")[0]+'.'
>         if len(str(amount).split(".")[1])>6:
>             final+=str(amount).split(".")[1][:5]
>         else:
>             final+=str(amount).split(".")[1]
>     else:
>         begining = str(amount)
>     amount = float(begining+final)
> address = address
> exchangeA.withdraw(coin, amount, address, tag=None, params={"network": network})
> ```
> 
> I got this `ccxt.base.errors.BadRequest: kucoin account.available.Amount`

This error happens when the balance in your account is lower than the amount you are trying to withdraw, note that kucoin has both a main and trading account. The trading account is your spot account

![](https://i.imgur.com/LXMLY4l.png)

> Ok, then I change network name to "ETH" and got this: ccxt.base.errors.PermissionDenied: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}

I'm not exactly sure what this error means, it's from the huobi exchange, but because it's `PermissionDenied` I think it may be referring to your ip address, so I think you may be trying to withdraw from a non-approved ip address

@ttodua @pcriadoperez @sc0Vu Can one of you try to reproduce this error? The api key I'm using has no withdraw permissions, and I am unable to create a new key or edit my key

> `ccxt.base.errors.BadRequest: huobipro {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null}`

This is a bug, I will push a PR to fix it

**Comment by KindSpidey** [comment] 2022-11-23 07:05
@samgermain ok, thanks, will wait answers from your guys. But a question. I added minus fee to withdraw for Kucoin. And I try to withdraw BUSD, but getting error `ccxt.base.errors.BadRequest: kucoin Invalid chainId` 
I put in chain parametr BEP20 - error, BSC - error. So what should I do, if there are only these names for Binance network? Or is there any command where I can get all exchange networks and see their correct status?

**Comment by KindSpidey** [comment] 2022-11-23 13:22
@samgermain can you help with Kucoin? I'm trying to withdraw BUSD from Kucoin to MEXC. Give "BEP20" - error `ccxt.base.errors.BadRequest: kucoin Invalid chainId` . 
Give "BSC" - same error `ccxt.base.errors.BadRequest: kucoin Invalid chainId`
Why does it happen? Before it I tested withdraw with USDT TRC20 and everything worked. Kucoin allows to withdraw BUSD by BEP20 and MEXC allows to deposit BUSD with BEP20

**Comment by ttodua** [comment] 2022-11-23 17:35
@samgermain as I see you have already grasped the problem and as you self-assigned, I suppose that you'll push the PR and after that, I'll test it with real withdrawals. the problem seems just to be the need of `this.networkCodeToId` base method

**Comment by samgermain** [comment] 2022-11-23 21:45
> @samgermain as I see you have already grasped the problem and as you self-assigned, I suppose that you'll push the PR and after that, I'll test it with real withdrawals. the problem seems just the need of `this.networkCodeToId` base method , with huobi and kucoin too.

I believe it has to do with the default value of safeStringUpper and safeStringLower not being returned as uppercase and lowercase. See https://github.com/ccxt/ccxt/pull/15812

**Comment by ttodua** [comment] 2022-11-24 09:00
also `ccxt.base.errors.BadRequest: kucoin account.available.Amount` needs to be `InsufficientFunds` instead of `BadRequest`

**Comment by KindSpidey** [comment] 2022-11-24 14:59
@ttodua @samgermain can you notify me here that bugs are fixed, wheb you made it?

**Comment by samgermain** [comment] 2022-11-24 20:16
> @ttodua @samgermain can you notify me here that bugs are fixed, when you made it?

The issue will be closed when the bugs are fixed

**Comment by KindSpidey** [comment] 2022-11-25 13:37
@samgermain well, I hope this will be fixed soon, because I have a very important project that is ready in everything except withdrawing funds from Huobi and Kucoin

**Comment by samgermain** [comment] 2022-11-25 20:49
> @samgermain well, I hope this will be fixed soon, because I have a very important project that is ready in everything except withdrawing funds from Huobi and Kucoin

Try pestering @carlosmiei

**Comment by samgermain** [comment] 2022-11-25 20:52
> @samgermain well, I hope this will be fixed soon, because I have a very important project that is ready in everything except withdrawing funds from Huobi and Kucoin

You can try using `ETH` or lowercase `erc20` in the meantime. You can often check what the working values will be inside `options['networks']` or `options['networksById']`

**Comment by KindSpidey** [comment] 2022-11-26 09:41
> > @samgermain well, I hope this will be fixed soon, because I have a very important project that is ready in everything except withdrawing funds from Huobi and Kucoin
> 
> You can try using `ETH` or lowercase `erc20` in the meantime. You can often check what the working values will be inside `options['networks']` or `options['networksById']`

trc20 didnt work. trx worked, but got error `ccxt.base.errors.PermissionDenied: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}` Do you know, how to fix it? Address for withdrawal is in my Withdrawal Huobi Addresses (but WhiteList is not activated)

**Comment by ttodua** [comment] 2022-11-26 17:47
as visible a bit above, I've linked a PR ( https://github.com/ccxt/ccxt/pull/15842 ) that fixes network-unification for huobi specifically. you have to wait for its merge.
@samgermain just as a note, `params={"network": "erc20"}`  erc20 wont work, as currency specific ids are very unintelligent in huobi API and above PR fixes it.

**Comment by KindSpidey** [comment] 2022-11-26 18:01
@ttodua @samgermain can you notify me here that bugs are fixed, wheb you made it? thank you. But can you check Kucoin withdraw too? It has same problems as Huobi

**Comment by ttodua** [comment] 2022-11-28 09:07
@KindSpidey thanks for pinging, I will check with kucoin too, after  #15842 is merged (@carlosmiei).

**Comment by samgermain** [comment] 2022-11-28 21:35
> @KindSpidey thanks for pinging, I will check with kucoin too, after #15842 is merged (@carlosmiei lmk if anything remains there).

Can you test it now with the recent `safeStringLower` default value updates? I think that will be enough

**Comment by ttodua** [comment] 2022-11-28 21:44
> pestering

In addition to lower/upper cases, there were missing unified network id->code definitions for huobi, and that's I've added in the referred PR. however, both of our PRs will do the job completed.
I'll do the same for kucoin in upcoming day/s.

**Comment by KindSpidey** [comment] 2022-11-29 08:11
@samgermain tested. Everything works fine. Love u guys

**Comment by KindSpidey** [comment] 2022-11-29 08:12
@ttodua is there any PR/issue I can follow to get know, that Kucoin is ready too?

**Comment by ttodua** [comment] 2022-12-03 08:31
> 

Not yet, waiting for huobi PR to get merged at first, which would have some impact how we handle kucoin too.

**Comment by KindSpidey** [comment] 2022-12-03 10:12
> > 
> 
> Not yet, waiting for huobi PR to get merged at first, which would have some impact how we handle kucoin too. 

Got it and wait for it. A few days ago I tested huobi with TRC20 and it worked. Now i tried to withdraw on ERC20 on MEXC and got error
`ccxt.base.errors.BadRequest: huobipro {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null`}

**Comment by ttodua** [comment] 2022-12-03 10:15
Most of other exchanges might need to get networks unified. after huobi I'll do for them one-by-one, so in queue: kucoin, mexc ...

**Comment by KindSpidey** [comment] 2022-12-03 10:19
> Most of other exchanges might need to get networks unified. after huobi I'll do for them one-by-one, so in queue: kucoin, mexc ... 

As ccxr pro tester i can say MEXC works good, huobi has problems. Binance and Bybit have ETH/BSC instead of ERC20/BEP20

**Comment by KindSpidey** [comment] 2022-12-03 18:35
@ttodua just found a bug or whatever it is. Now if I try to withdraw from Huobi by ERC20 (withdraw USDT for example) - it works. But i bought token BBF and tried to withdraw it to MEXC via ERC20 - got `ccxt.base.errors.BadRequest: huobipro {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null}`
I've checked: BBF has active ERC20-withdraw status
So what is it and why? Can you fix it?

**Comment by KindSpidey** [comment] 2022-12-05 08:41
@ttodua alright, wait for huobi-PR

**Closed** 2022-12-08 00:31 UTC
Labels: bug

**Comment by dmatora** [comment] 2023-03-30 04:26
isn't this supposed to be fixed long time ago?
calling huobi.withdraw("BULL", 15, my_address, tag=None, params={"network": "MATIC"}) is getting translated to
 {"address":address,"currency":"bull","chain":"PRC20","amount":15} 
 and returns 
 {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null}
