### ISSUE TITLE
CoinbasePro error on watchTrades 

### ISSUE THREAD

**Issue by Abyiss-Zach** [ccxt/ccxt#9963] opened 2021-09-09 18:41 UTC
Hello,
I upgraded both CCXT and CCXT Pro to the latest version and I receive this error at random times throughout the day when I watch Coinbasepro trades for multiple markets. Sometimes it takes a few minutes to happen; sometimes it takes a few hours. I noticed that a similar error used to happen with BinanceUS immediately when using more than 4 symbols. The [BinanceUS solution](https://github.com/ccxt/ccxt/issues/9907) works perfectly so far. I am thinking that the solution to this coinbasepro issue could be closely related to the BinanceUS solution.
Here is the exact issue:

```
NetworkError: connection closed by remote server, closing code 1006
    at WsClient.onClose ({Path}\node_modules\ccxt.pro\js\base\Client.js:227:25)
    at WebSocket.onClose ({Path}\node_modules\ws\lib\event-target.js:136:16)
    at WebSocket.emit (node:events:365:28)
    at WebSocket.emitClose ({Path}\node_modules\ws\lib\websocket.js:246:10)
    at TLSSocket.socketOnClose ({Path}\node_modules\ws\lib\websocket.js:1058:15)
    at TLSSocket.emit (node:events:377:35)
    at node:net:661:12
    at TCP.done (node:_tls_wrap:578:7)
```

This issue will happen for multiple markets at once. This is just one of the stack traces. I do not think that the issue is connecting to multiple markets, but maybe its some sort of throttling error. I can attach my error logs if needed as well.

- OS: Windows 10
- Programming Language version: node v16.2.0 (also using typescript v4.4.2) 
- CCXT version: "1.56.18"
- CCXTPRO version: "0.8.51"

My code that produces the error is kind of complex, but I tried to boil it down as much as possible.

```
function main() {
	exchangeConns = []
	exchangeConns.push(new ccxtpro("coinbasepro"))
	exchangeConns.push(new ccxtpro("binanceus"))

	//kinda pseudocode, but the idea is that all markets are added from both exchanges. 
	exchangeMarkets = []
	exchangeMarkets.push (exchangeConns[0].fetch_markets())
	exchangeMarkets.push (exchangeConns[1].fetch_markets())

	//iterate through all of the markets for both exchanges and and start the tradeWS function for each market
	for (let i = 0; i < exchangeConns.length; i ++){
		for (let j = 0; j < exchangeMarkets[i].length; j++){
			if (exchangeMarkets [i][j]){
				await TradeWS(exchangeConns[i], exchangeMarkets[i][j])       
			}
		}
	}
}

async tradesWS(exchange:any, symbol:string) {
    const limit = 1
    while (true) {
        try {
	    //returns an array of trades
            const data = await exchange.watchTrades (symbol, limit)
            for (let i = 0; i < data.length; i++){
		console.log(data[i])									
            }   
        } catch (e) {
            console.log(e)
        }
    }
}

main()
```

**Comment by kroitor** [comment] 2021-09-10 23:35
@Abyiss-Zach thanks for your thorough report, we will investigate and will be back to you with a fix asap.

**Comment by Abyiss-Zach** [comment] 2021-09-14 13:53
I have a little update on what I think this could be. The error still only happens only on occasion. My logs have revealed that this only happens when I am at my computer, which my mode app runs runs on. Perhaps this could be the result of some sort of brief network/processor interrupt?

**Comment by kroitor** [comment] 2021-09-15 10:37
@Abyiss-Zach thank could be the cause, however, it's not easy to replicate and handle... Trying to catch it on my side.

**Comment by ttodua** [comment] 2022-07-25 05:53
Late reply here, but at first, you'd better to use `load_markets` instead of `fetch_markets`:
```
exchangeMarkets.push (await exchangeConns[0].load_markets())
exchangeMarkets.push (await exchangeConns[1].load_markets())
```

also, your code/logic doesn't seem correct, as you have  `await TradeWS(` in the loop, the most first call will never be stuck (as it's awaited) there, so maybe you try to use it without `await`.

please let us know after you test that at first,

**Comment by ttodua** [comment] 2024-08-24 13:21
i can no longer reproduce this issue. closing for now. if anyone still has any issues, let us know again

**Closed by ttodua** 2024-08-24 13:21 UTC
Labels: bug, ws
