### ISSUE TITLE
fetch_ohlcv() keeps doubling in size (repeat data-documented as well as I can)

### ISSUE THREAD

**Issue by mw130** [ccxt/ccxt#4277] opened 2018-12-04 17:30 UTC
- OS: Mojave 
- Programming Language version: Python 3
- CCXT version: 1.17.581
- Exchange: All exchanges
- Method: fetch_ohlcv

Hi @kroitor 
I've been debugging for days and I've exhausted all possibilities it could be on my end, so I wanted to ask if this might be a ccxt error. 
I am running this below method inside of another outer method (included after it( that is a while loop which starts from present time, gets as much OHLCV data as it can, and calls the next set of data. I will include both functions for reference. 
The issue is, in `fetch_and_process_ohlcv_from_exhange`, the OHLCV list size returned keeps doubling.. first 500, then 1000, then 2000, 4000 and up to 16k that I've seen. I know len of ohlcv returned can vary, but the highest I've seen an API return for one call is 1k, so something is definitely up. I also run an external validator and logger and can see that while my logic seems right for putting the data in, I just end up with a bunch of repeats. My leading hypothesis is that because I "go back in time more with each call" with subtracting from the since param, ccxt might be caching/storing all the previously called data, but that doesn't even explain it because then the ohlcv len would grow linearly, not by a factor of two.
Below I've included both function
```python    
def fetch_and_process_ohlcv_from_exchange(self, client, curr_exchange, coin_pair, file_handle, then, trials_allowed=3):
        try:
            ohlcv = []
            ohlcv = client.fetch_ohlcv(coin_pair, timeframe='1m', since=then)
            if ohlcv is not None and len(ohlcv) > 0:
                print("Getting data from  " + curr_exchange + " on " + coin_pair)
                #if (ohlcv[0][0] != then) and not self.first_query:
                    #logging.debug("Wrong time returned. Requested: " + str(then)
                                 # + " but got " + str(ohlcv[0][0])) + " on " + curr_exchange + coin_pair
                    #pass
                # self.write_ohlcv_to_file(ohlcv, file_handle)
                logging.debug("Getting data from  " + curr_exchange + " on " + coin_pair)
                #file_handle.seek(0, 0)

                #self.write_ohlcv_to_file(ohlcv, file_handle)
                self.first_query = False
                return ohlcv
            else:

                logging.debug("Getting zero length ohlcv from " + curr_exchange + " on " + coin_pair)
                print("Getting zero length ohlcv from " + curr_exchange + " on " + coin_pair)
                return None
        except KeyError:
            logging.debug("Timeframe not available, breaking out of coin pair")
            return None
        except (ccxt.DDoSProtection,
                ccxt.AccountSuspended,
                ccxt.AuthenticationError,
                ccxt.NetworkError,
                ccxt.NullResponse,
                requests.ConnectionError,
                requests.ReadTimeout,
                requests.TooManyRedirects,
                requests.exceptions.SSLError,
                requests.exceptions.HTTPError) as e:
            logging.exception(e)
            if trials_allowed > 0:
                ohlcv = self.fetch_and_process_ohlcv_from_exchange(client, curr_exchange, coin_pair, file_handle, then, trials_allowed=trials_allowed - 1)
            else:
                return None
        except (ccxt.ExchangeError,
                ccxt.ExchangeNotAvailable) as e:
            logging.exception(e)
            logging.debug("Trying next coin pair...")
            return None
```

Below is the function which calls `fetch_and_process_ohlcv_from_exchange` inside a loop.
```python
def scrape_coin_pair(self, client, curr_exchange, coin_pair, now, folderpath):
        filepath_to_check = self.create_text_output_file(folderpath, curr_exchange, coin_pair)
        then = client.parse8601('2018-11-20 00:00:00')
        empty_times = 0
        temp_time = now - 100
        with open(filepath_to_check, 'a') as file_handle:
            ohlcv_list = []
            #this below is the logic for getting the data starting at present up till past. OHLCV_list ends up becoming something like 1st element len(500), 2nd elem len(1000), 3rd elem len(2000) etc. 
            while then <= temp_time:  # get as many datapoints as possible, add them to file, and continue
                ohlcv = self.fetch_and_process_ohlcv_from_exchange(client, curr_exchange, coin_pair, file_handle, temp_time)
                if ohlcv is not None:
                    #print(str(ohlcv[-1][0]))
                    temp_time = ohlcv[0][0] - (1 * self.minute * len(ohlcv))
                    logging.debug("scraping: time: " + str(then) + " for: "
                                  + str(curr_exchange) + " "
                                  + str(coin_pair)
                                  + " OHLCV size: " + str(len(ohlcv)))
                    ohlcv_list.append(ohlcv)

                else:
                    empty_times+=1
                    if(empty_times == 5):
                        continue
                    temp_time -= 500 * 60 * 1000  # This is an arbitrary number so that it doesn't get stuck when fetch_ohlcv returns []
                    logging.debug("Empty OHLCV returned on " + " " + str(then) + " " + str(curr_exchange) + " " + str(coin_pair))
            if ohlcv_list is not None:
                try:
                    ohlcv_list.reverse()
                    self.remove_duplicates_and_write(ohlcv_list, file_handle)

                except TypeError:
                    print("None/zero size ohlcv_list")
                    return
```
By the way, for clarity, this backwards scraping is so that the program doesn't get hung up / have to go through a ton of useless calls when it is called for a time way before the data existed (time saver). I also reset ohlcv every time since python only has pass by ref, but that didn't help.

**Comment by kroitor** [comment] 2018-12-05 02:14
Hi, @mw130 !

> I wanted to ask if this might be a ccxt error

It could be a CCXT error, however, in this particular case I'm almost sure it isn't. But anyways, let's first clarify a few things...

> ccxt might be caching/storing all the previously called data, but that doesn't even explain it because then the ohlcv len would grow linearly, not by a factor of two

We don't cache the OHLCV data anywhere inside the library, the OHLCV is always the data as returned by the exchange. But there's a significant caveat with some exchanges – they might not have the OHLCV endpoint and therefore their OHLCV candles are emulated (built from) the list of recent public trades. The question to you is: do you understand how `fetch_ohlcv()` emulation works with exchanges that don't have OHLCV? Just in case, here's a brief explanation:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-emulation
- https://github.com/ccxt/ccxt/issues/3178#issuecomment-410340912

Now, back to your question... To me the primary cause of the doubling seems to be coming from the following:

```Python
def scrape_coin_pair(self, client, curr_exchange, coin_pair, now, folderpath):
        # ...
        with open(filepath_to_check, 'a') as file_handle:
            ohlcv_list = []  # ←----- you create it here and it is never equal to None starting from here
            while then <= temp_time:  
                # ↓ you fetch the next portion of OHLCVs here
                ohlcv = self.fetch_and_process_ohlcv_from_exchange(client, curr_exchange, coin_pair, file_handle, temp_time)
                if ohlcv is not None:
                    # ...
                    ohlcv_list.append(ohlcv)  # ←--- you append to ohlcv_list here, effectively growing it in size
                    # ...
            if ohlcv_list is not None:  # it is never None
                try:
                    ohlcv_list.reverse()
                    # ↓ you append the entire list (that grows upon each iteration) to the file
                    self.remove_duplicates_and_write(ohlcv_list, file_handle)
```

Now, that last bit is supposed to remove duplicates and write the data to the file. However, you didn't post the source code of `remove_duplicates_and_write`, which makes it hard to guess what's happening there with the `ohlcv_list`.

My guess is:
1. you append to `ohlcv_list` on each iteration (it grows)
2. you're writing the entire list to the file upon each iteration (the file grows)

That explains the geometric progression (x2) that you get upon each iteration – you're probably appending old + new data to the old data upon each iteration, effectively doubling it in size upon each write. Even if there were no duplicates in ohlcv_list, appending to it and then writing the entire list to a file upon each iteration will produce the doubling effect, for obvious reasons.

I can see there's a few other issues with how you do the time traversal for the candles (in particular, you need to take the oldest timestamp for `since` in `fetch_ohlcv` from the fetched candles themselves, not in an arbitrary fashion. But, before we resolve those as well, we need you to clarify this first issue with `remove_duplicates_and_write`. Can you paste the source of it? Or, do you, maybe, see the error in it already, based on the explanation I tried to give above?

**Comment by mw130** [comment] 2018-12-05 15:29
@kroitor 
Sorry. Here are the other two you need to fully get it (both file writes and remove_dups_and_write). Before, I was just writing the ohlcv data directly with write_to_file, but due to this issue I made the remove_dups_and_write, although it still quite doesn't return the correct data. It's also very inefficient in runtime :P. 
```python
def write_ohlcv_to_file(self, ohlcv, file_handle):
        for prices in ohlcv:
            prices = map((lambda x: str(x)), prices)
            prices_string = ', '.join(prices) + '\n'
            file_handle.write(prices_string)
            file_handle.flush()
def remove_duplicates_and_write(self, ohlcv_list, file_handle):
        final_list = []
        temp_set = set()
        for index, item in enumerate(ohlcv_list):
            if index > 0:
                #union = set(ohlcv_list[index-1]).union(ohlcv_list[index])
                #temp_set.update(union)
                for ind, individual in enumerate(ohlcv_list[index]):
                    for second_ohlcv in ohlcv_list[index-1]:
                        if individual ==second_ohlcv:
                            ohlcv_list[index].remove(individual)
                            print("Duplicate found & removed")
                #self.write_ohlcv_to_file(ohlcv_list[index], file_handle)
            #return ohlcv_list
        for ohlcv in ohlcv_list:
            self.write_ohlcv_to_file(ohlcv, file_handle)

**Comment by mw130** [comment] 2018-12-07 16:33
@kroitor just wanted to add, ohlcv_list will get reassigned for each coin pair, but also shouldn't keep appending double size data with ohlcv_list.append(ohlcv). This seems to be the man issue?

**Comment by mw130** [comment] 2018-12-08 20:20
@kroitor Thanks so much. I tried with a smaller sample and it worked as expected - I care mostly about Binance. With it, I was getting max 500 size ohlcvs, as expected.

**Comment by mw130** [comment] 2018-12-12 16:01
@kroitor just wanted to check in and ask if there are any updates to this on your side

**Comment by mw130** [comment] 2018-12-17 15:39
@kroitor just wanted to check in to see if there are possibly any updates, given that all the code is available now. I have gone through it repeatedly and unfortunately can't get it working correctly at all. You are sure it cannot be a ccxt issue?

**Comment by kroitor** [comment] 2018-12-17 15:54
@mw130 apologies for the delay, i will look into it again as soon as I can and will let you know about my findings, hopefully in a day or, maybe, a few... hope for your understanding.

**Comment by kroitor** [comment] 2018-12-23 00:33
@mw130 once again, sorry for taking so long... To be honest, I didn't have the time to debug your script. There's too much of redundancy in it – recursive calls and a lot of other syntactic overhead – so I don't know the exact cause of error in your particular code, but I suspect either the list grows progressively because of that recursion or due to writing to the file in append mode.

But, hey, I have some good news for you as well: instead of trying to reproduce and fix the issue with the parts of your script posted above, I created a simplified version of the script that does scrape the candles from Binance and saves them to a csv file, check it out here: 

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py

That example script basically does the same thing that your script does, but it's a bit shorter and it demonstrates that the growth does not occur within CCXT. It fetches all candles first and then writes them to a file, outputting the count in process and upon finishing. So, at this point, I think you should apply step-by-step debugging to see what might be wrong with your recursive version.

Let me know if that answers your question and if I can help with anything else here.

**Comment by kroitor** [comment] 2018-12-25 03:10
I'd close this for now if you don't mind, feel free to reopen it if needed or just ask further questions if any, will be happy to answer!

**Closed by kroitor** 2018-12-25 03:10 UTC
Labels: question

**Comment by mw130** [comment] 2019-01-10 18:04
@kroitor Thanks very much for that. Code is clean and concise. One thing I have noticed though is that it caps the amount of data it gets, in a weird way. For example If I request minute long data from 1/3/19 to now, I'll get 12k for each coinpair. However, I will likewise get 12k for each pair if I do from 12/3/18 (which for Binance is weird because it will make datapoints with 0 volume even when there were no trades, so 12k means it didn't get a full OHLCV) - the first data point *is* 12/3/18 though, and the last *is* the current date. Any idea what might be going on? This is with what you provided

**Comment by mw130** [comment] 2019-01-11 17:11
@kroitor No rush but just wanted to add to my above comment. I'm attaching a csv file which I ran to get data from 11/3/18 to now (ETHBTC on Binance). I also run a logging script that checks the timestamp of each row to make sure the difference is 60000 (1m) and logs if not. I am really surprised, because you see that the start and end dates are what are expected (the end date is 3 days ago, not sure why this is since I used the now() method) but I only get 21k datapoints, which is (21k/(60*24)) =  14.5 days, not 2 months, although the start and end are what I wanted and there aren't any time discrepancies.

**Comment by kroitor** [comment] 2019-01-12 13:51
@mw130 that's very interesting... However, I didn'g get the csv file... Can you tell the datetimes of some of those "holes" for me to check on my side?

**Comment by mw130** [comment] 2019-01-13 17:20
@kroitor I fixed this. Super weird - I was running on raspberry pi and I think maybe it was some weird OS feature that caused it, ran fine on OSX. The absolute last thing I'd ask on this topic when you get the chance is, now the data is gotten perfectly, however what did change is for Binance for example after getting ETHBTC it stops. So it only gets ETHBTC then stops (doesn't happen on other exchanges) and this wasn't happening before. I have this all with a for loop going through every coinpair, so I'm confused why it's not working.

**Comment by mw130** [comment] 2019-01-13 17:31
@kroitor Awesome! :)
