### ISSUE TITLE
New Exchange: Pancakeswap

### ISSUE THREAD

**Issue by Benjam6** [ccxt/ccxt#16484] opened 2023-01-13 23:26 UTC
### Exchange Name

Pancakeswap

### URL of the Exchange

https://pancakeswap.finance/swap

### URL of the Exchange's API docs

https://github.com/pancakeswap/pancake-info-api

### Why should this exchange be implemented?

There are arbitrage opportunities between DEX's like Pancakeswap and between Binance.

**Comment by ttodua** [comment] 2024-06-10 14:36
duplicate of: #6337

**Closed by ttodua** 2024-06-10 14:36 UTC
Labels: question, new exchange
