### ISSUE TITLE
Typescript 3.2 TypeError: this.publicGetExchangeInfo is not a function

### ISSUE THREAD

**Issue by novatrix** [ccxt/ccxt#4451] opened 2019-01-08 15:09 UTC
- OS: OSX
- Programming Language version: Typescript 3.2
- CCXT version: 1.18.114
- Exchange: binance
- Method: fetchBalance

I get this error when trying to fetchBalance():

```TypeError: this.publicGetExchangeInfo is not a function```

```
import * as ccxt from 'ccxt';

  async function test() {
  const exchange = new ccxt.binance ({
    api: '',
    secret: '',
    verbose: true
  });

  exchange.fetchBalance().then((balance) => {
    console.log(balance);
  }).catch((error) => {
    console.log(error);
  });
}

test();
```

**Comment by kroitor** [comment] 2019-01-08 23:06
@taish i wonder if you have the same issue with TypeScript?

**Comment by arenddeboer** [comment] 2020-04-12 12:38
The problem here is the options key 'api' which should be 'apiKey'
Took me an embarrassing amount of time to figure this out. Maybe an options validator could have prevented this.

**Comment by kroitor** [comment] 2020-04-12 12:44
@arenddeboer the validator is actually there, so it's not entirely clear how you end up bypassing it:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1854
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L128
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L328

**Comment by kroitor** [comment] 2020-04-12 12:45
@novatrix closing this for now, please change `'api'` → `'apiKey'`:
- https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup

@arenddeboer would be great if you could post the code you use that manages to bypass that check...

**Closed by kroitor** 2020-04-12 12:45 UTC

**Comment by arenddeboer** [comment] 2020-04-12 13:02
@kroitor thanks for the quick reply. 
I use: 
```
const ccxt = require('ccxt')
exchange = new ccxt.binance({
    api: 'test',
    secret: 'test',
})

exchange.load_markets().then((data) => {
    console.log('data', data)
})
```

Which yields:
```
(node:8996) UnhandledPromiseRejectionWarning: TypeError: this[method] is not a function
    at binance.fetchMarkets (/home/username/Documents/dev/projects/tradeBot/server/node_modules/ccxt/js/binance.js:345:42)
    at binance.loadMarkets (/home/username/Documents/dev/projects/tradeBot/server/node_modules/ccxt/js/base/Exchange.js:686:36)
    at Object.<anonymous> (/home/username/Documents/dev/projects/tradeBot/server/src/test.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
(node:8996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by kroitor** [comment] 2020-04-12 13:05
@arenddeboer what do you see if you add the proper error handling:

```
const ccxt = require('ccxt')
exchange = new ccxt.binance({
    api: 'test',
    secret: 'test',
})

exchange.load_markets().then((data) => {
    console.log('data', data)
}).catch ((e) => {
    console.log (e)
    process.exit ()
})
```

↑ It should report with a required credential missing error.

**Comment by kroitor** [comment] 2020-04-12 13:08
@arenddeboer also, does it happen with the most recent version of CCXT ?

**Comment by arenddeboer** [comment] 2020-04-12 13:28
I was running an older version, but using the latest (1.26.9) does not change the error message.
With your example 
```
const ccxt = require('ccxt')
exchange = new ccxt.binance({
    api: 'test',
    secret: 'test',
})

exchange.fetch_balance().then((data) => {
    console.log('data', data)
}).catch ((e) => {
    console.log (e)
    process.exit ()
})
```

I see the same: 

```
 node src/test.js 
TypeError: this[method] is not a function
    at binance.fetchMarkets (/home/username/Documents/dev/projects/tradeBot/server/node_modules/ccxt/js/binance.js:356:45)
    at binance.loadMarketsHelper (/home/username/Documents/dev/projects/tradeBot/server/node_modules/ccxt/js/base/Exchange.js:690:36)
    at binance.loadMarkets (/home/username/Documents/dev/projects/tradeBot/server/node_modules/ccxt/js/base/Exchange.js:698:40)
    at Object.<anonymous> (/home/username/Documents/dev/projects/tradeBot/server/src/test.js:26:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by arenddeboer** [comment] 2020-04-12 13:40
It looks like ```this.checkRequiredCredentials()``` is checked at sign(), which is after this method is called.

**Comment by kroitor** [comment] 2020-04-12 15:44
@arenddeboer you should not override the api property, because it contains the endpoint definitions: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties. So, any value there will break the entire exchange:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L83

Let me know if that does not answer the question.

**Comment by arenddeboer** [comment] 2020-04-12 16:07
I'm not overriding anything as far as I know. Just running ```const ccxt = require('ccxt')
exchange = new ccxt.binance({
    api: 'test',
    secret: 'test',
})

exchange.fetch_balance().then((data) => {
    console.log('data', data)
}).catch ((e) => {
    console.log (e)
    process.exit ()
})```

Should give you the same error I think.
I was trying to say that this TypeError occurs way before you check the provided options in the sign function using ```this.checkRequiredCredentials()```. At least that's what it looks like from a cursory glans at the ccxt code. 

Anyway, it all works. Thanks for providing this excellent library!

**Comment by kroitor** [comment] 2020-04-12 16:21
> I'm not overriding anything as far as I know. 

Oh yes you do – you override all (any) exchange properties by supplying the to the exchange constructor. When you specify the `api` property there – you're effectively overriding the default value containing all the api endpoints. This is why it breaks. You're indeed overriding those properties as described here (without noticing it):

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-exchange-properties-upon-instantiation

> I was trying to say that this TypeError occurs way before you check the provided options in the sign function using this.checkRequiredCredentials(). At least that's what it looks like from a cursory glans at the ccxt code.

The problem is deeper than just checking the credentials, because apart from auth-properties, there are non-auth properties like `exchange.api`, `exchange.urls`, and other... So, this problem is not related to authentication at all. This problem is more related to not following the Manual exactly.

**Comment by kroitor** [comment] 2020-04-12 16:25
P.S. We will think of adding a better warning for the user. Thx for the feedback, it is really appreciated.

**Comment by arenddeboer** [comment] 2020-04-12 16:27
I guess it's time to RTFM :-)
Thanks for all the feedback
