### ISSUE TITLE
Kraken watch_order_book gets crossed a lot

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#8717] opened 2021-03-25 20:19 UTC
- OS: ubuntu 14
- Programming Language version: python 3.6
- CCXT version: 1.44.4 / 0.6.16

The kraken order book seems to get in a bad state quite often.  My code looks something like below.  The error gets hit a lot according to my logs.

```
client = ccxtpro.kraken()
limit = 25
while True:
    ccxt_orderbook = await client.watch_order_book(
        ccxt_symbol,
        limit=limit,
        params={}
    )
    book = Level2Book("kraken", self.pair, ccxt_orderbook['bids'], ccxt_orderbook['asks'])

    if book.best_bid >= book.best_ask:
        log.error(f"{self} book looks wrong best_bid={book.best_bid} best_ask={book.best_ask}")
```

**Comment by kroitor** [comment] 2021-03-25 20:21
@jaseisen105 thanks for your report, we have received the same reports from other users on the same issue with Kraken, working on a fix right now.

**Comment by jaseisen105** [comment] 2021-03-25 20:21
Understood, thank you!

**Comment by naveenvhegde** [comment] 2021-03-28 19:55
this may not be issue with ccxt book building logic. 

this was raised with kraken support and kraken knows this problem exists with their streaming api.

if at all happened to fix, do let me know pls.

**Comment by ulexxander** [comment] 2021-04-06 06:22
Hello, guys!
I have this problem too, sometimes kraken ccxt client just stops updating prices without throwing any errors in **watchOrderBook**.
Any updates on it?
Thank you.

**Comment by kroitor** [comment] 2021-04-06 06:29
@ulexxander we have located the cause of the issue using the info from the user reports, working on a fix and will hopefully push it today.

**Comment by frosty00** [comment] 2021-04-08 10:26
This is fixed now

**Closed** 2021-04-08 10:26 UTC
Labels: ccxt.pro
