### ISSUE TITLE
Kraken replies with a CAPTCHA - to retrieve the minimum order sizes

### ISSUE THREAD

**Issue by JDJoe** [ccxt/ccxt#6811] opened 2020-04-16 08:24 UTC
This is directly from Kraken support: 

> Following updates to CCXT's API library, some users have experienced issues as the library is trying to retrieve the minimum order sizes from our support pages, but due to the Zendesk security settings, either a captcha page or an HTTP 403 error is returned instead of the actual support page.

**Comment by kimasplund** [comment] 2020-04-16 09:16
just update ccxt or

> exchange = ccxt.kraken({
>     'enableRateLimit': True,
>     'options': {  # ←--------------------- inside 'options' subkey
>         'fetchMinOrderAmounts': False,  # ←---------- set to False 
>     }
> })

**Comment by kroitor** [comment] 2020-04-16 14:30
@JDJoe this is a duplicate (plz use the search https://github.com/ccxt/ccxt/issues?q=kraken+is%3Aissue+is%3Aclosed+).

See the explanation and the workaround below:

- https://github.com/ccxt/ccxt/issues/6797
- https://github.com/ccxt/ccxt/issues/6795#issuecomment-613451098
- https://github.com/ccxt/ccxt/issues/6700
- https://github.com/ccxt/ccxt/issues/6701

Kraken's official answer: 

> we are aware of the recent issue that CCXT experienced when a security change to our support pages prevented the minimum order sizes from being retrieved via our support pages. Our REST API developers are in the process of adding the minimum order sizes to the REST API AssetPairs endpoint, which would make the minimum order sizes available more efficiently (and more reliably). We do not yet have an expected availability date for this update, but I will keep track of the progress, and let you know when more information is available.

In the meantime, you can workaround the issue, by setting `fetchMinOrderAmounts` option to `false`. 

```Python
exchange = ccxt.kraken({
    'enableRateLimit': True,
    'options': {  # ←--------------------- inside 'options' subkey
        'fetchMinOrderAmounts': False,  # ←---------- set to False 
    }
})
```

That way you will effectively lose the information about the minimal limits, but the other functionality will keep working.

If you want to keep the info on limits, then upgrading to the most recent version of CCXT also fixes the issue.

Let me know if that does not answer the question.

**Comment by bodcat** [comment] 2020-04-18 12:43
I am still getting this error. Here is my code:

import ccxt
  
kraken = ccxt.kraken({
    'enableRateLimit': True,
    'options': { # ←--------------------- inside 'options' subkey
        'fetchMinOrderAmounts': False, # ←---------- set to False
    }
})

print(kraken.fetch_ticker('BTC/USD'))

**Comment by kroitor** [comment] 2020-04-18 12:44
@bodcat what's your version of CCXT? Do you have the same issue with the most recent version?

**Comment by bodcat** [comment] 2020-04-18 16:32
Turns out my pip installation was screwed so it had not upgraded. Fix that and it is working now. Thanks

**Comment by kroitor** [comment] 2020-04-18 16:41
@bodcat thank you for reporting back, appreciate it!

**Comment by Princeton007** [comment] 2020-05-14 15:58
Hi @kroitor ,
I have the same issue but with CCXT version: 1.27.61

´´´
ticker = trading.kraken_exchange.fetch_ticker(config.kraken_symbol.upper())
´´´

Using the following: 
´´´
exchange = ccxt.kraken({'apiKey': config.kraken_apikey,
                                               'secret': config.kraken_secret,
                                               'enableRateLimit': True,
                                               'timeout': 30000,
                                               'options': {'fetchMinOrderAmounts': False}
                                               })
´´´

It throws me 
ccxt.base.errors.ExchangeNotAvailable: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden

When I run the same Code in Pycharm on the same machine it works, Python script on Raspberry Pi works, but when generating a windows .exe with pyinstaller I get this error. 

Any suggestions?

Thanks!

**Comment by kroitor** [comment] 2020-05-14 18:31
@Princeton007

> Any suggestions?

I assume that you have resolved the issue by updating CCXT to the most recent version. If you see exactly this URL in your output: `https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-` – that usually means that you think that your version of CCXT is up date, but it's not. You can check your actual runtime version by running this small snippet in your actual environment like so:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)  # this will print the real version that you're actually using
```

Most often the problem is caused by pip installation or by pip updating the wrong folder or something similar. That can happen if you have multiple versions of Python on the same system. And it can be resolved by cleaning up your environment/system/configuration from the older or conflicting versions of packages and package managers.

Hope it helps.

**Comment by Princeton007** [comment] 2020-05-14 18:49
Hi,
you were fast, i deleted the post already because hoping it was before you started answering. 

I'm actually printing ccxt version always so I noticed that pyinstaller uses an older xxct from somewhere, now I have to search from where. but your guess was 100% correct! I'll try on a different pc tonight.
Thanks again! 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.05.20, 20:32 schrieb Igor Kroitor <notifications@github.com>:

   
  @Princeton007 
   
   Any suggestions? 
   
  I assume that you have resolved the issue by updating CCXT to the most recent version. If you see exactly this URL in your output: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- – that usually means that you think that your version of CCXT is up date, but it's not. You can check your actual runtime version by running this small snippet in your actual environment like so: 
  
   import ccxt

print('CCXT Version:', ccxt.__version__)  # this will print the real version that you're actually using
   
  Most often the problem is caused by pip installation or by pip updating the wrong folder or something similar. That can happen if you have multiple versions of Python on the same system. And it can be resolved by cleaning up your environment/system/configuration from the older or conflicting versions of packages and package managers. 
  Hope it helps.

**Closed** 2020-06-01 02:47 UTC
Labels: duplicate, question

**Comment by davidmasin** [comment] 2020-06-14 14:21
Hi,
I understood that for now fetch of fetchMinOrderAmounts has been set to false in CCXT to overcome Kraken API error messages. Below is email which I today received from Kraken. So maybe minimum order size fetch can be re-enabled?
Thanks

EMAIL FROM KRAKEN:
It was a busy and productive week for our API team, and I am happy to share an enhancement for our REST API.
A long standing ask from our clients has been to fetch order minimums per asset pair as part of our reference market data. This feature is now available !!!

You can now fetch order minimums using field ‘ordermin’ field via AssetPairs endpoint on Kraken spot REST API.

Endpoint: https://api.kraken.com/0/public/AssetPairs
Documentation: https://www.kraken.com/features/api#get-tradable-pairs

**Comment by kroitor** [comment] 2020-06-14 14:22
@davidmasin we have added it yesterday, please update your version and you'll be fine.

**Comment by kroitor** [comment] 2020-06-14 14:35
P.S.

> So maybe minimum order size fetch can be re-enabled?

There's no need anymore to fetch them with a standalone call since that info has been added to the Kraken's API endpoint on the Kraken side. The minimums should just work. Let us know if you have issues or difficulties with that.
