### ISSUE TITLE
OKX create_order_ws freeze task

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#23127] opened 2024-07-17 17:03 UTC
### Operating System

 Ubuntu 22

### Programming Languages

Python

### CCXT Version

Ccxt 4.2.25

### Description

Create_oder_ws freeze all async task "trade". It stop and my count doesnot increase

### Code

```
  async def trade(exchange):
    while True:
        data['count'] += 1
        if ...:
            await exchange.create_order_ws(... 'market', 'sell' ...)
        await asyncio.sleep(0.1)

```

**Comment by carlosmiei** [comment] 2024-07-19 08:33
Hello @interenet,

What's the best way of reproducing this issue?
Locally seems to be working fine

```
 p okx createOrderWs "LTC/USDT" market sell 0.1 --sandbox
Python v3.12.3
CCXT v4.3.63
okx.createOrderWs(LTC/USDT,market,sell,0.1)
{'amount': None,
 'average': None,
 'clientOrderId': 'e847386590ce4dBCa606777bee2fe43a',
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '1639992035150331904',
 'info': {'clOrdId': 'e847386590ce4dBCa606777bee2fe43a',
          'ordId': '1639992035150331904',
          'sCode': '0',
          'sMsg': 'Order successfully placed.',
          'tag': 'e847386590ce4dBC',
          'ts': '1721377971344'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': False,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}
```

**Comment by interenet** [comment] 2024-07-21 15:57
Pls try perform over 100 sells in loop with maximum speed

**Comment by carlosmiei** [comment] 2024-07-22 16:46
@interenet I think I managed to reproduce the issue, taking a look now

**Comment by interenet** [comment] 2024-07-22 20:41
No help. The error remains.
Pls try this code.
With delay=1 it works fine. But with delay=0.2 it makes only 1 order.

Also you can start several tasks 'trade' for some symbols and task freeze after second order.

```
import ccxt.pro
import asyncio

delay = 0.2

async def trade(exchange):
    count = 0
    while True:
        count += 1
        r = await exchange.create_order_ws('ETH/USDT', 'limit', 'buy', 0.0001, 3000)
        await asyncio.sleep(delay)
        await exchange.cancel_order_ws(r['id'], 'ETH/USDT')
        await asyncio.sleep(delay)
        print (count)

async def main():
    exchange = ccxt.pro.okx({
                             'apiKey': 'xxx',
                             'secret': 'xxx',
                             'password': 'xxx',
                             'enableRateLimit': True,
                              #'newUpdates': False,
                             'options':{
                                         'checksum': False,
                                         'createMarketBuyOrderRequiresPrice': False,
                                        }
                             })

    tasks = [
             asyncio.create_task(trade(exchange)),
            ]
    done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED,)


asyncio.run(main())
```

**Comment by carlosmiei** [comment] 2024-07-22 20:50
@interenet We didn't release the fix yet, will be released in a few minutes

**Comment by carlosmiei** [comment] 2024-07-23 08:17
@interenet We released a new version with the fix, can you update your ccxt version and try again pls? It should be working as expected now

**Comment by interenet** [comment] 2024-07-24 13:27
Yes! It works fine! Thanks )

**Comment by carlosmiei** [comment] 2024-07-24 13:47
@interenet thanks for confirming it!

**Closed by carlosmiei** 2024-07-24 13:47 UTC
Labels: bug
