### ISSUE TITLE
Bitfinex Authentication Error

### ISSUE THREAD

**Issue by nagabrahmam-mantha** [ccxt/ccxt#6959] opened 2020-05-17 01:09 UTC
Hi,

I am new here and trying to use the CCXT platform to connect with my Bitfinex account. Basically, what I want to do is to get a list of my trades to be printed in the browser (Later I will use that data for other purposes). I followed the manual and the browser examples but for some reason I cannot get the private data to print (I am able to get the public data). The error I am getting is "InvalidNonce bitfinex {"message":"Nonce is too small."}".  You can find the error all the way at the bottom 

I have pasted my HTML/JS code and also the output. Please note I changed the API key and secret to "X" and "Y". I am really new here, and any help would be appreciated. Below are the details:

- OS: Windows 10
- CCXT version: 1.27.88

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS

<!DOCTYPE HTML>
<html>
  <head>
    <title>CCXT Basic example for the browser</title>

    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>

    <script>
      document.addEventListener ("DOMContentLoaded", function () {
        alert ('CCXT' + (ccxt.isBrowser ? ' browser' : '') + ' version ' + ccxt.version + ' supporting '+ ccxt.exchanges.length.toString () + ' exchanges');

        const proxy = 'https://cors-anywhere.herokuapp.com/'

        const exchange = new ccxt.bitfinex ({
          'proxy': proxy,
          'apiKey': 'x', //Replaced with dummy key for github issue
          'secret': 'y', //Replaced with dummy secret for github issue
          'timeout': 10000000,
          'verbose': true,
        })

        const symbol = "BTC/USD"
        const since = 1588374610000
        const limit = 1

        exchange.fetchMyTrades (symbol, since, limit).then (MyTrades => {
          const text = [
            JSON.stringify (MyTrades, undefined, '\n\t')
          ]
          document.getElementById ('content').innerHTML = text.join (' ')

        }).catch (e => {
          const text = [
            e.constructor.name,
            e.message,
          ]
          document.getElementById ('content').innerHTML = text.join (' ')
        })
      })
    </script>
  </head>

  <body>
    <h1>Hello, CCXT!</h1>
    <pre id="content"></pre>
  </body>
</html>

```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS

fetch:
 bitfinex GET https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/symbols 
Request:
 {} 
 undefined 

ccxt.browser.js:3803 handleRestResponse:
 bitfinex GET https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/symbols 200 OK 
Response:
 {Access-Control-Allow-Origin: "*", Cache-Control: "max-age=0, private, must-revalidate", Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5949626cedc2cf08-IAD", Cf-Request-Id: "02c1bbd80d0000cf08842cd200000001", …} 
 ["btcusd","ltcusd","ltcbtc","ethusd","ethbtc","etcbtc","etcusd","rrtusd","zecusd","zecbtc","xmrusd","xmrbtc","dshusd","dshbtc","btceur","btcjpy","xrpusd","xrpbtc","iotusd","iotbtc","ioteth","eosusd","eosbtc","eoseth","sanusd","sanbtc","saneth","omgusd","omgbtc","omgeth","neousd","neobtc","neoeth","etpusd","etpbtc","etpeth","qtmusd","qtmbtc","avtusd","edousd","edobtc","edoeth","btgusd","btgbtc","datusd","datbtc","dateth","qshusd","yywusd","gntusd","gntbtc","gnteth","sntusd","sntbtc","snteth","ioteur","batusd","batbtc","bateth","mnausd","mnabtc","funusd","funeth","zrxusd","zrxbtc","zrxeth","tnbusd","tnbbtc","tnbeth","spkusd","trxusd","trxbtc","trxeth","rcnusd","rlcusd","rlcbtc","aidusd","sngusd","repusd","repbtc","repeth","elfusd","necusd","necbtc","neceth","btcgbp","etheur","ethjpy","ethgbp","neoeur","neojpy","neogbp","eoseur","eosjpy","eosgbp","iotjpy","iotgbp","iosusd","iosbtc","ioseth","aiousd","aiobtc","requsd","rdnusd","lrcusd","lrcbtc","waxusd","waxbtc","daiusd","daibtc","daieth","agiusd","bftusd","bftbtc","mtnusd","odeusd","odebtc","odeeth","antusd","antbtc","anteth","dthusd","mitusd","stjusd","xlmusd","xlmeur","xlmgbp","xlmbtc","xlmeth","xvgusd","xvgbtc","mkrusd","mkrbtc","mkreth","kncusd","kncbtc","poausd","evtusd","lymusd","utkusd","veeusd","orsusd","aucusd","poyusd","fsnusd","cbtusd","zcnusd","ncausd","cndusd","cndeth","ctxusd","paiusd","seeusd","essusd","atmusd","hotusd","dtausd","iqxusd","iqxeos","wprusd","zilusd","bntusd","absusd","xrausd","manusd","dgxusd","dgxeth","vetusd","vetbtc","utnusd","tknusd","gotusd","goteur","goteth","xtzusd","xtzbtc","cnnusd","boxusd","trxeur","trxgbp","trxjpy","mgousd","rteusd","yggusd","mlnusd","wtcusd","csxusd","omnusd","omnbtc","intusd","drnusd","pnkusd","pnketh","dgbusd","dgbbtc","bsvusd","bsvbtc","babusd","babbtc","wlousd","vldusd","enjusd","onlusd","rbtusd","rbtbtc","ustusd","euteur","eutusd","gsdusd","udcusd","tsdusd","paxusd","rifusd","rifbtc","pasusd","vsyusd","vsybtc","mkrdai","bttusd","bttbtc","btcust","ethust","clousd","clobtc","impusd","ltcust","eosust","babust","scrusd","gnousd","genusd","atousd","atobtc","atoeth","wbtusd","xchusd","eususd","wbteth","xcheth","leousd","leobtc","leoust","leoeos","leoeth","astusd","foausd","ufrusd","zbtusd","okbusd","uskusd","gtxusd","kanusd","okbust","okbbtc","uskust","usketh","uskbtc","uskeos","gtxust","kanust","ampusd","algusd","algbtc","algust","btcxch","swmusd","triusd","loousd","ampust","dusk:usd","dusk:btc","uosusd","uosbtc","rrbusd","rrbust","dtxusd","ampbtc","fttusd","fttust","paxust","udcust","tsdust","btc:cnht","ust:cnht","cnh:cnht","chzusd","chzust","xaut:usd","xaut:btc","xaut:ust","btcf0:ustf0","ethf0:ustf0","xautf0:ustf0","btcdomf0:ustf0"] 

ccxt.browser.js:3803 fetch:
 bitfinex GET https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/symbols_details 
Request:
 {} 
 undefined 

ccxt.browser.js:3803 handleRestResponse:
 bitfinex GET https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/symbols_details 200 OK 
Response:
 {Access-Control-Allow-Origin: "*", Cache-Control: "max-age=0, private, must-revalidate", Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5949626e4ab1096b-IAD", Cf-Request-Id: "02c1bbd8ef0000096b1708a200000001", …} 
 [{"pair":"btcusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"2000.0","minimum_order_size":"0.0006","expiration":"NA","margin":true},{"pair":"ltcusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"ltcbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"ethusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"ethbtc","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"etcbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"0.6","expiration":"NA","margin":true},{"pair":"etcusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"0.6","expiration":"NA","margin":true},{"pair":"rrtusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"150.0","expiration":"NA","margin":false},{"pair":"zecusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"20000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"zecbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"20000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"xmrusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"xmrbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"dshusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.06","expiration":"NA","margin":true},{"pair":"dshbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.06","expiration":"NA","margin":true},{"pair":"btceur","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"2000.0","minimum_order_size":"0.0006","expiration":"NA","margin":true},{"pair":"btcjpy","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.0006","expiration":"NA","margin":true},{"pair":"xrpusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"200000.0","minimum_order_size":"20.0","expiration":"NA","margin":true},{"pair":"xrpbtc","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"200000.0","minimum_order_size":"20.0","expiration":"NA","margin":true},{"pair":"iotusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"26.0","expiration":"NA","margin":true},{"pair":"iotbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"26.0","expiration":"NA","margin":true},{"pair":"ioteth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"26.0","expiration":"NA","margin":true},{"pair":"eosusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"eosbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"eoseth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"sanusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"36.0","expiration":"NA","margin":true},{"pair":"sanbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"36.0","expiration":"NA","margin":true},{"pair":"saneth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"36.0","expiration":"NA","margin":true},{"pair":"omgusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"omgbtc","price_precision":5,"init 

ccxt.browser.js:3803 fetch:
 bitfinex POST https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/mytrades 
Request:
 {X-BFX-APIKEY: "x", X-BFX-PAYLOAD: "x", X-BFX-SIGNATURE: "x"} 
 {"nonce":"1589677049466","request":"/v1/mytrades","symbol":"BTCUSD","limit_trades":1,"timestamp":1588374610} 

ccxt.browser.js:3718 POST https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/mytrades 400 (Bad Request)
executeRestRequest @ ccxt.browser.js:3718
fetch @ ccxt.browser.js:3838
fetch2 @ ccxt.browser.js:3848
request @ ccxt.browser.js:3852
partial @ ccxt.browser.js:3793
fetchMyTrades @ ccxt.browser.js:14373
async function (async)
fetchMyTrades @ ccxt.browser.js:14362
(anonymous) @ index.html:26
ccxt.browser.js:3803 handleRestResponse:
 bitfinex POST https://cors-anywhere.herokuapp.com/https://api.bitfinex.com/v1/mytrades 400 Bad Request 
Response:
 {Access-Control-Allow-Origin: "*", Cache-Control: "no-cache", Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5949626fbc9309a8-IAD", Cf-Request-Id: "02c1bbd9d7000009a8683b5200000001", …} 
 {"message":"Nonce is too small."} 

```

**Comment by kroitor** [comment] 2020-05-17 01:13
Hi!

Sounds like you've been using the API key with some other software previously, and trying to reuse the same key again with different software. This is not really an issue with the Bitfinex API, it is an issue with the software you've been using that key with. That software will screw your nonce too high, and then you can't use other software with lower nonces and with that same key (will get an error from bitfinex). The issue is easily fixed by creating a new api keypair. You should be able to verify that by creating a fresh new API key and trying it with CCXT (which will use a nonce in milliseconds and will not screw it).

Let us know if that does not help.

Duplicates:

- https://github.com/ccxt/ccxt/issues/5972#issuecomment-541470298
- https://github.com/ccxt/ccxt/issues/39#issuecomment-316843817
- https://github.com/ccxt/ccxt/search?q=bitfinex+nonce+too+small&type=Issues

**Closed by kroitor** 2020-05-17 01:13 UTC
Labels: duplicate, question

**Comment by kroitor** [comment] 2020-05-17 01:14
P.S. Also, make sure that you enable the rate limiter: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

**Comment by nagabrahmam-mantha** [comment] 2020-05-17 02:01
@kroitor Enabling the rate limiter and changing the API keys worked. Very quick response and great support! Thanks!
