### ISSUE TITLE
A way to check minimal withdraw

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4608] opened 2019-02-03 19:33 UTC
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Ubuntu:
- Python:
- newest:
- All:
- idk:

Hello, how I can check the minimal withdraw amount on any exchange, for example withdrawal minimum for XRP on binance is 22 xrp, how I can get this value?

**Comment by frosty00** [comment] 2019-02-03 21:48
if you look at `binance.currencies['XRP']['limits']['withdraw']['min'/'max']` ;)

**Comment by kroitor** [comment] 2019-02-03 21:51
> look at binance.currencies['XRP']['limits']['withdraw']['min'/'max'] ;)

@frosty00 the problem is that binance doesn't have `fetchCurrencies` implemented yet

**Comment by frosty00** [comment] 2019-02-03 21:53
Yeah, maybe we should change `loadCurrencies` so it adds the default limits if they are not there

**Comment by Arrmlet** [comment] 2019-02-03 22:04
My code
`import ccxt
binance = ccxt.binance()
binance.load_markets()
info =binance.currencies['XRP']`
It's returns me `{'id': 'XRP', 'numericId': None, 'code': 'XRP', 'precision': 8}`
As I understood most of exchanges is not supporting this info via API, I'm trying to find some information in their official repository on github but without results. Will hope we can find answers soon:)
thx

**Comment by kroitor** [comment] 2019-02-04 10:36
@Arrmlet we'll be happy to add it, let us know if you find anything in this regard. Thx!

**Comment by kroitor** [comment] 2019-02-11 00:03
Closing this for now, if you don't mind, until we have a followup.

**Closed by kroitor** 2019-02-11 00:03 UTC
