### ISSUE TITLE
EXMO fetchCurrencies() is missing currencies

### ISSUE THREAD

**Issue by davidonlaptop** [ccxt/ccxt#6964] opened 2020-05-18 01:28 UTC
- OS: OSX
- Programming Language version: Node.js
- CCXT version: 1.27.89

```
const ccxt = require('ccxt');

(async () => {
  const exch = new ccxt.exmo({
    enableRateLimit: true, 
    apiKey: 'K-yourKEY, 
    secret: 'S-yourSECRET'
  });

  const markets = await exch.loadMarkets(true);

  console.info("Markets found: %s", Object.keys(markets).sort().join(' '));
  console.info("Currencies found: %s", Object.keys(exch.currencies).sort().join(' '));
})();
```

```
node exmo-currency-bug.js 

Markets found: ADA/BTC ADA/ETH ADA/USD ALGO/BTC ALGO/EUR ALGO/EXM ALGO/RUB ALGO/USDT ATOM/BTC ATOM/EUR ATOM/EXM ATOM/USD BCH/BTC BCH/ETH BCH/EUR BCH/RUB BCH/UAH BCH/USD BCH/USDT BTC/EUR BTC/GBP BTC/KZT BTC/PLN BTC/RUB BTC/TRY BTC/UAH BTC/USD BTC/USDT BTG/BTC BTG/ETH BTG/USD BTT/BTC BTT/RUB BTT/UAH CRON/BTC CRON/ETH CRON/EXM CRON/USDT DAI/BTC DAI/ETH DAI/RUB DAI/USD DASH/BTC DASH/RUB DASH/UAH DASH/USD DASH/USDT DCR/BTC DCR/RUB DCR/UAH DOGE/BTC DOGE/USD EOS/BTC EOS/EUR EOS/USD ETC/BTC ETC/RUB ETC/USD ETH/BTC ETH/EUR ETH/GBP ETH/KZT ETH/LTC ETH/PLN ETH/RUB ETH/TRY ETH/UAH ETH/USD ETH/USDT ETZ/BTC ETZ/ETH ETZ/USDT EXM/BTC EXM/ETH EXM/USDT GAS/BTC GAS/USD GNT/BTC GNT/ETH GUSD/BTC GUSD/RUB GUSD/USD HB/BTC HP/BTC LSK/BTC LSK/RUB LSK/USD LTC/BTC LTC/EUR LTC/RUB LTC/UAH LTC/USD MKR/BTC MKR/DAI MNC/BTC MNC/ETH MNC/USD NEO/BTC NEO/RUB NEO/USD OMG/BTC OMG/ETH OMG/USD ONG/BTC ONG/EXM ONG/RUB ONG/UAH ONT/BTC ONT/EXM ONT/RUB ONT/UAH PTI/BTC PTI/EOS PTI/RUB PTI/USDT QTUM/BTC QTUM/ETH QTUM/USD ROOBEE/BTC SMART/BTC SMART/EUR SMART/RUB SMART/USD TRX/BTC TRX/EUR TRX/RUB TRX/UAH TRX/USD USD/RUB USDC/BTC USDC/ETH USDC/USD USDC/USDT USDT/EUR USDT/GBP USDT/KZT USDT/RUB USDT/UAH USDT/USD VLX/BTC WAVES/BTC WAVES/ETH WAVES/RUB WAVES/USD XEM/BTC XEM/EUR XEM/UAH XEM/USD XLM/BTC XLM/RUB XLM/TRY XLM/USD XMR/BTC XMR/ETH XMR/EUR XMR/RUB XMR/UAH XMR/USD XRP/BTC XRP/ETH XRP/EUR XRP/GBP XRP/RUB XRP/TRY XRP/UAH XRP/USD XRP/USDT XTZ/BTC XTZ/ETH XTZ/RUB XTZ/USD ZAG/BTC ZEC/BTC ZEC/EUR ZEC/RUB ZEC/USD ZRX/BTC ZRX/ETH ZRX/USD

Currencies found: ADA ALGO ATMCASH BCH BTC BTCZ BTG BTT CRON DAI DASH DCR DOGE DXT EOS ETC ETH ETZ EUR EXM GAS GNT GUSD HB INK KICK KZT LSK LTC MKR MNC MNX NEO OMG ONG ONT PLN PTI QTUM ROOBEE RUB SMART TRX TRY UAH USD USDC USDT VLX WAVES XEM XLM XMR XRP ZAG ZEC ZRX
```

There is currencies that we find in the markets, but which are missing in the `currencies` object: eg.: `ATOM`, `GBP`, `HP`, `XTZ`.

I've tried `fetchCurrencies()` but the result is the same.

**Comment by kroitor** [comment] 2020-05-18 01:36
I would suggest to forward this question to the exchange itself. Basically, what you see is the data from the exchange itself. If it so happens that the exchange returns more currencies from their markets endpoint than the number of currencies returned from the currencies endpoint – CCXT is not supposed to fix that, because this is a bug on the exchange side.

- https://exmo.com/en/trade/XTZ_BTC
- https://exmo.me/en/trade/XTZ_BTC

↑ This pair does not look like it is tradable.

Let me know if that does not answer the question.

**Comment by davidonlaptop** [comment] 2020-05-18 01:43
Thanks @kroitor , it's true that XTZ_BTC does not seem tradeable, but [BTC/GBP](https://exmo.com/en/trade/BTC_GBP) appears to be so.

When digging in the source of `fetchCurrencies()` it seems to rely on `fetchFundingFees()` but lost the track from there: https://github.com/ccxt/ccxt/blob/4e279314b5a9cec22e5a83e37370b9e83ea1ee21/js/exmo.js#L523

**Comment by davidonlaptop** [comment] 2020-05-18 01:47
is it fetching from an html link or using an API?

**Comment by kroitor** [comment] 2020-05-18 01:49
@davidonlaptop actually, it falls back to the currencies listed out in `describe()`, i will fix this shortly. The problem is that EXMO bans the client fetching their currency settings outside of the browser session. Therefore, we have to refresh their definitions from time to time.

**Comment by davidonlaptop** [comment] 2020-05-18 01:51
Ah great! thanks :)

**Comment by davidonlaptop** [comment] 2020-05-18 01:59
Actually, I found similar issues at other exchanges, and I wrote a script to quickly find the missing currencies, should I share it here or create another issue?

**Comment by kroitor** [comment] 2020-05-18 02:01
@davidonlaptop you can paste it here – i would add that to our tests. Thx!

**Comment by davidonlaptop** [comment] 2020-05-18 02:03
Contents of file `bug-report.js`:
```
const ccxt = require('ccxt');

// Synopsis: node bug-report.js exchange, key, secret
const args = process.argv.slice(2);
const exchangeCode = args[0];
const apiKey = args[1];
const secret = args[2];

function unique(arr) {
  return arr.filter((value, idx, theArray) => theArray.indexOf(value) === idx);
}

(async () => {
  const exch = new ccxt[exchangeCode]({
    enableRateLimit: true, 
    apiKey, 
    secret
  });

  const markets = await exch.loadMarkets(true);

  console.info("Markets found: %s", Object.keys(markets).sort().join(' '));
  console.info("Currencies found: %s", Object.keys(exch.currencies).sort().join(' '));
  
  const missingCurrencies = [];
  for (const market of Object.values(markets)) {
    if (!(market.base in exch.currencies)) {
      missingCurrencies.push(market.base);
    }

    if (!(market.quote in exch.currencies)) {
      missingCurrencies.push(market.quote);
    }
  }

  const sortedAndUnique = unique(missingCurrencies.sort());
  if (sortedAndUnique.length > 0) {
    console.warn("*** %s: Missing currencies: %s", exchangeCode, sortedAndUnique.join(' '));
  }
})();
```

It can be executed with: 
```
node bug-report.js bibox MYKEY MYSECRET
```

If it finds missing currencies it will print:
```
*** bibox: Missing currencies: 4BCH 4BTC 4EOS 4ETH 4LTC
```

**Comment by kroitor** [comment] 2020-05-18 02:14
@davidonlaptop i've uploaded an update to EXMO metainfo, that fixes ATOM and GBP. However, we can't find anything about HP or XTZ here:

- https://exmo.me/ctrl/feesAndLimits
- https://exmo.com/ctrl/feesAndLimits

So, you might really want to forward your question on HP / XTZ to EXMO.

On the script - thank you very much for it! The problem is that it false alarms, since 4BCH, 4BTC are not currencies – those are just the way for Bibox to label their stuff. You would still use the BCH, BTC currencies to withdraw and deposit, not 4BCH nor 4BTC – those are the names of perpetual contracts. Bibox uses those 4xxx symbols to differentiate spot pairs from contracts. So a general script does not help resolve this – we still have to look into each exchange and their rules in particular. If you find more bugs like EXMO – let us know. We will fix the specific exchanges, where there is a bug indeed.

Closing this for now if you don't mind. Feel free to reopen it or just ask further questions if you have more. Thx again for the feedback, we really appreciate your involvement!

**Comment by kroitor** [comment] 2020-05-18 02:14
P.S. The new build will arrive in version 1.27.90 in 15 minutes.

**Closed by kroitor** 2020-05-18 02:14 UTC
Labels: question

**Comment by davidonlaptop** [comment] 2020-05-18 14:19
Thanks for your explanations and your fast response!

Although `HP` and `XTZ` are present in the link that you shared:
```
{"pair":"HP\/BTC","min_q":"500","max_q":"100000000","min_p":"0.00000001","max_p":"0.1","min_a":"0.00001","max_a":"100","taker":"0.4","maker":"0.4"},
```

```
{"pair":"XTZ\/USD","min_q":"0.5","max_q":"100000","min_p":"0.0001","max_p":"1000","min_a":"0.1","max_a":"100000","taker":"0.4","maker":"0.4"},{"pair":"XTZ\/RUB","min_q":"0.1","max_q":"100000","min_p":"0.00001","max_p":"100000","min_a":"0.5","max_a":"500000","taker":"0.4","maker":"0.4"},{"pair":"XTZ\/BTC","min_q":"0.5","max_q":"100000","min_p":"0.00000001","max_p":"1","min_a":"0.00001","max_a":"10","taker":"0.4","maker":"0.4"},{"pair":"XTZ\/ETH","min_q":"0.5","max_q":"100000","min_p":"0.0000001","max_p":"10","min_a":"0.0001","max_a":"1000","taker":"0.4","maker":"0.4"},
```

**Comment by davidonlaptop** [comment] 2020-05-18 14:29
I see, it's not in the fees section.

Okay that works!

**Comment by davidonlaptop** [comment] 2020-05-18 14:37
Actually the latest version (1.27.91) brings ATOM and GBP, but we lost BCH and USDT. USDT is present in the fees section.

```
*** exmo: Missing currencies: BCH HP USDT XTZ
```

**Comment by kroitor** [comment] 2020-05-18 21:05
@davidonlaptop i've uploaded the fix for USDT, however, on BCH they say this: https://exmo.me/en/news_view?id=2989

**Comment by davidonlaptop** [comment] 2020-05-18 22:05
Thanks again @kroitor !
